#include <aimee/db2/vector_route.h>

#include "memory_scope_query.h"

#include <assert.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

_Static_assert(AIMEE_VECTOR_EVENT_CAPABILITIES == 0x80030001u, "DB3 capability event drift");
_Static_assert(AIMEE_VECTOR_EVENT_APPLY == 0x80030002u, "DB3 apply event drift");
_Static_assert(AIMEE_VECTOR_EVENT_APPLIED == 0x80030003u, "DB3 applied event drift");
_Static_assert(AIMEE_VECTOR_EVENT_SEARCH == 0x80030004u, "DB3 search event drift");
_Static_assert(AIMEE_VECTOR_EVENT_ROUTE == 0x80030005u, "DB3 route event drift");

typedef struct
{
   int calls;
   int mode;
   int64_t first_id;
} search_state_t;

typedef struct
{
   int calls;
   int reject_id;
   int fail;
} auth_state_t;

static int search(void *context, const aimee_vector_search_request_t *request,
                  aimee_vector_search_reply_t *reply)
{
   search_state_t *state = context;
   state->calls++;
   if (state->mode == 1)
      return -1;
   reply->request_id = request->request_id;
   reply->generation = request->required_generation;
   reply->count = 3;
   for (uint32_t i = 0; i < reply->count; ++i)
   {
      reply->candidates[i].point_id = state->first_id + (int64_t)i;
      reply->candidates[i].score = 0.9 - 0.1 * (double)i;
   }
   if (state->mode == 2)
      reply->candidates[0].point_id = 0;
   else if (state->mode == 3)
      reply->candidates[0].score = NAN;
   else if (state->mode == 4)
      reply->candidates[1].point_id = reply->candidates[0].point_id;
   else if (state->mode == 5)
      reply->generation++;
   return 0;
}

static int authorize(void *context, const char *workspace, const char *project, int64_t point_id)
{
   auth_state_t *state = context;
   state->calls++;
   assert(strcmp(workspace, "workspace-a") == 0);
   assert(strcmp(project, "project-a") == 0);
   if (state->fail)
      return -1;
   return point_id != state->reject_id;
}

/* The caller owns the vector now, so the fixture is handed the buffer it should
 * point at rather than carrying one of its own. Every real caller makes the same
 * change; the tests should not be exempt from it. */
static aimee_vector_search_request_t request(float *vector)
{
   aimee_vector_search_request_t value = {0};
   value.request_id = 91;
   value.required_generation = 7;
   strcpy(value.workspace, "workspace-a");
   strcpy(value.project, "project-a");
   strcpy(value.record_type, "memory");
   value.dimension = 3;
   value.top_k = 3;
   vector[0] = 0.25f;
   vector[1] = -0.5f;
   vector[2] = 0.75f;
   value.vector = vector;
   return value;
}

/* The exact 48 bytes server-go/vector's EncodeCapabilities produces for the
 * announcement built in capabilities_fixture(). Not hand-assembled: generated by
 * running that encoder, and pinned on the Go side too (TestCapabilitiesGoldenFrame),
 * so a layout change on either side fails on the side that changed.
 *
 * Every field carries set bits and the generation's bytes are all distinct, so a
 * swapped pair of offsets cannot yield a value that still looks plausible. */
static const uint8_t capabilities_golden[AIMEE_VECTOR_CAPABILITIES_HEADER] = {
    0x44, 0x42, 0x33, 0x43, 0x01, 0x00, 0x30, 0x00, 0x88, 0x77, 0x66, 0x55, 0x44, 0x33, 0x22, 0x11,
    0x03, 0x00, 0x00, 0x00, 0x05, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
    0x00, 0x04, 0x00, 0x00, 0x40, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

static aimee_vector_capabilities_t capabilities_fixture(void)
{
   aimee_vector_capabilities_t capabilities = {
       .generation = 0x1122334455667788ull,
       .operations = AIMEE_VECTOR_OPERATION_SEARCH | AIMEE_VECTOR_OPERATION_APPLY,
       .metrics = AIMEE_VECTOR_METRIC_COSINE | AIMEE_VECTOR_METRIC_DOT,
       .filters = AIMEE_VECTOR_FILTER_EXACT,
       .max_dimension = 1024,
       .max_batch = 64,
       .max_top_k = 128,
       .ready = 1,
   };
   return capabilities;
}

/* A ready, search-capable, cosine, exact-filter provider: the minimum that makes
 * a provider eligible to serve reads. */
static aimee_vector_capabilities_t eligible_fixture(void)
{
   aimee_vector_capabilities_t capabilities = {
       .generation = 7,
       .operations = AIMEE_VECTOR_OPERATION_SEARCH,
       .metrics = AIMEE_VECTOR_METRIC_COSINE,
       .filters = AIMEE_VECTOR_FILTER_EXACT,
       .max_dimension = 1024,
       .max_top_k = 128,
       .ready = 1,
   };
   return capabilities;
}

static void test_capabilities_codec(void)
{
   aimee_vector_capabilities_t capabilities = capabilities_fixture();
   uint8_t encoded[AIMEE_VECTOR_CAPABILITIES_HEADER];
   size_t written = 0;
   assert(aimee_vector_capabilities_encode(&capabilities, encoded, sizeof(encoded), &written) == 0);
   assert(written == AIMEE_VECTOR_CAPABILITIES_HEADER);
   /* The C encoder agrees with the Go one, byte for byte. */
   assert(memcmp(encoded, capabilities_golden, sizeof(encoded)) == 0);

   /* And the C decoder reads the Go encoder's own bytes back to the same
    * announcement -- which is what proves the offsets, not the round trip
    * through my own encoder, since a consistently wrong pair of offsets would
    * round-trip perfectly. */
   aimee_vector_capabilities_t decoded;
   assert(aimee_vector_capabilities_decode(capabilities_golden, sizeof(capabilities_golden),
                                           &decoded) == 0);
   assert(decoded.generation == capabilities.generation);
   assert(decoded.operations == capabilities.operations);
   assert(decoded.metrics == capabilities.metrics);
   assert(decoded.filters == capabilities.filters);
   assert(decoded.max_dimension == 1024 && decoded.max_batch == 64 && decoded.max_top_k == 128);
   assert(decoded.ready == 1);

   /* A buffer one byte short is refused rather than partially written. */
   assert(aimee_vector_capabilities_encode(&capabilities, encoded,
                                           AIMEE_VECTOR_CAPABILITIES_HEADER - 1, &written) == -1);
}

static void test_capabilities_refusals(void)
{
   uint8_t frame[AIMEE_VECTOR_CAPABILITIES_HEADER];
   aimee_vector_capabilities_t decoded;

   /* Truncated, and over-long: a short frame is a truncated read, a long one
    * means the sender is using a field this build does not know about. */
   memcpy(frame, capabilities_golden, sizeof(frame));
   assert(aimee_vector_capabilities_decode(frame, sizeof(frame) - 1, &decoded) == -1);
   uint8_t longer[AIMEE_VECTOR_CAPABILITIES_HEADER + 1] = {0};
   memcpy(longer, capabilities_golden, sizeof(frame));
   assert(aimee_vector_capabilities_decode(longer, sizeof(longer), &decoded) == -1);

   /* Wrong magic, wrong version, wrong declared header. */
   memcpy(frame, capabilities_golden, sizeof(frame));
   frame[0] ^= 0xff;
   assert(aimee_vector_capabilities_decode(frame, sizeof(frame), &decoded) == -1);
   memcpy(frame, capabilities_golden, sizeof(frame));
   frame[4] = 2;
   assert(aimee_vector_capabilities_decode(frame, sizeof(frame), &decoded) == -1);
   memcpy(frame, capabilities_golden, sizeof(frame));
   frame[6] = 40;
   assert(aimee_vector_capabilities_decode(frame, sizeof(frame), &decoded) == -1);

   /* A sender using the reserved word is a sender from a newer contract. */
   memcpy(frame, capabilities_golden, sizeof(frame));
   frame[44] = 1;
   assert(aimee_vector_capabilities_decode(frame, sizeof(frame), &decoded) == -1);

   /* ready is a boolean on the wire; 2 is a field being used for something. */
   memcpy(frame, capabilities_golden, sizeof(frame));
   frame[28] = 2;
   assert(aimee_vector_capabilities_decode(frame, sizeof(frame), &decoded) == -1);

   /* An unknown metric bit. Refused, not masked: reading this as "cosine and
    * dot" would rank results by a metric nobody in this build chose. */
   memcpy(frame, capabilities_golden, sizeof(frame));
   frame[23] = 0x80;
   assert(aimee_vector_capabilities_decode(frame, sizeof(frame), &decoded) == -1);

   /* An unknown operation bit, likewise. */
   memcpy(frame, capabilities_golden, sizeof(frame));
   frame[19] = 0x80;
   assert(aimee_vector_capabilities_decode(frame, sizeof(frame), &decoded) == -1);

   /* Ready against generation 0: readiness is a claim about a generation of the
    * corpus, and there is no such generation. */
   aimee_vector_capabilities_t bad = capabilities_fixture();
   bad.generation = 0;
   assert(aimee_vector_capabilities_validate(&bad) == -1);

   /* No operations at all is not a provider. */
   bad = capabilities_fixture();
   bad.operations = 0;
   assert(aimee_vector_capabilities_validate(&bad) == -1);

   /* Search without a metric, a dimension or a top_k cannot serve a search. */
   bad = eligible_fixture();
   bad.metrics = 0;
   assert(aimee_vector_capabilities_validate(&bad) == -1);
   bad = eligible_fixture();
   bad.max_top_k = 0;
   assert(aimee_vector_capabilities_validate(&bad) == -1);
}

static void test_provider_selection(void)
{
   search_state_t internal = {.first_id = 10}, external = {.first_id = 20};
   auth_state_t auth = {.reject_id = -1};
   aimee_vector_route_t route;
   assert(aimee_vector_route_init(&route, search, &internal, authorize, &auth) == 0);
   assert(aimee_vector_route_set_transport(&route, search, &external, 1) == 0);
   assert(route.selected_principal == 0);

   aimee_vector_capabilities_t eligible = eligible_fixture();

   /* An ineligible provider records evidence and selects nothing: not ready. */
   aimee_vector_capabilities_t not_ready = eligible;
   not_ready.ready = 0;
   assert(aimee_vector_route_observe_capabilities(&route, 2000, 1, 1, &not_ready) == 0);
   assert(route.selected_principal == 0);

   /* Nor does one that cannot search, or cannot do cosine, or cannot filter --
    * each of which would otherwise be selected and then fail every query. */
   aimee_vector_capabilities_t apply_only = eligible;
   apply_only.operations = AIMEE_VECTOR_OPERATION_APPLY;
   apply_only.max_batch = 8;
   assert(aimee_vector_route_observe_capabilities(&route, 2001, 1, 1, &apply_only) == 0);
   assert(route.selected_principal == 0);
   aimee_vector_capabilities_t l2_only = eligible;
   l2_only.metrics = AIMEE_VECTOR_METRIC_L2;
   assert(aimee_vector_route_observe_capabilities(&route, 2002, 1, 1, &l2_only) == 0);
   assert(route.selected_principal == 0);

   /* The first eligible one is selected. */
   assert(aimee_vector_route_observe_capabilities(&route, 1500, 1, 1, &eligible) == 0);
   assert(route.selected_principal == 1500 && route.selected_ready == 1);

   /* A lower principal wins, and a higher one does not displace it -- so the
    * result does not depend on the order announcements arrived in, which is
    * what lets this router and the Go one reach the same answer. */
   assert(aimee_vector_route_observe_capabilities(&route, 1200, 1, 1, &eligible) == 0);
   assert(route.selected_principal == 1200);
   assert(aimee_vector_route_observe_capabilities(&route, 1800, 1, 1, &eligible) == 0);
   assert(route.selected_principal == 1200);

   /* Stale within one attachment is refused; the same sequence from a NEW
    * attachment is not a replay and is accepted. */
   assert(aimee_vector_route_observe_capabilities(&route, 1200, 1, 1, &eligible) == -1);
   assert(aimee_vector_route_observe_capabilities(&route, 1200, 2, 1, &eligible) == 0);

   /* Losing the selected provider advances to the next eligible one rather than
    * stranding the deployment on a principal that is gone. */
   assert(aimee_vector_route_remove_provider(&route, 1200, 2) == 1);
   assert(route.selected_principal == 1500);
   /* A handle that does not match is somebody else's attachment. */
   assert(aimee_vector_route_remove_provider(&route, 1500, 99) == 0);
   assert(route.selected_principal == 1500);
   assert(aimee_vector_route_remove_provider(&route, 1500, 1) == 1);
   assert(route.selected_principal == 1800);
   assert(aimee_vector_route_remove_provider(&route, 1800, 1) == 1);
   /* And with none left, back to pgvector rather than to a dangling principal. */
   assert(route.selected_principal == 0 && route.selected_ready == 0);

   /* An explicit control decision pins the selection: evidence still records,
    * but it does not move, and losing that provider fails closed rather than
    * silently handing reads to a different index. */
   assert(aimee_vector_route_select(&route, 9000, 1, 0, search, &external) == 0);
   assert(aimee_vector_route_observe_capabilities(&route, 1200, 3, 5, &eligible) == 0);
   assert(route.selected_principal == 9000);
   assert(aimee_vector_route_remove_provider(&route, 1200, 3) == 1);
   assert(route.selected_principal == 9000);

   /* Clearing returns to automatic, and to whatever the live evidence implies. */
   assert(aimee_vector_route_observe_capabilities(&route, 1700, 1, 1, &eligible) == 0);
   aimee_vector_route_clear(&route);
   assert(route.selected_principal == 1700);

   /* The registry is bounded, and observing past it is refused rather than
    * overwriting somebody. */
   for (uint32_t i = 0; i < AIMEE_VECTOR_MAX_PROVIDERS; ++i)
      (void)aimee_vector_route_observe_capabilities(&route, 3000 + i, 1, 1, &eligible);
   assert(route.provider_count == AIMEE_VECTOR_MAX_PROVIDERS);
   assert(aimee_vector_route_observe_capabilities(&route, 9999, 1, 1, &eligible) == -1);
}

static void test_default_external_and_authorization(void)
{
   search_state_t internal = {.first_id = 10}, external = {.first_id = 20};
   auth_state_t auth = {.reject_id = 11};
   aimee_vector_route_t route;
   assert(aimee_vector_route_init(&route, search, &internal, authorize, &auth) == 0);
   float vec[3];
   aimee_vector_search_request_t req = request(vec);
   aimee_vector_search_outcome_t out;

   /* Internal results are NOT authorised: they came from a query that applied
    * the scope filter, so the callback would be a round trip per candidate to
    * re-derive it. Point 11 is what proves it -- the callback rejects that id,
    * and it is still here. Asserting only the count would also pass against a
    * route that had dropped authorisation entirely. */
   assert(aimee_vector_memory_candidates_search(&route, &req, &out) == AIMEE_VECTOR_OK);
   assert(out.route == AIMEE_VECTOR_ROUTE_DEFAULT_PGVECTOR && out.selected_principal == 0);
   assert(internal.calls == 1 && external.calls == 0 && out.reply.count == 3);
   assert(out.reply.candidates[0].point_id == 10 && out.reply.candidates[1].point_id == 11 &&
          out.reply.candidates[2].point_id == 12);
   assert(auth.calls == 0);

   auth.reject_id = 21;
   assert(aimee_vector_route_select(&route, 1001, 1, 0, search, &external) == 0);
   assert(aimee_vector_memory_candidates_search(&route, &req, &out) == AIMEE_VECTOR_OK);
   assert(out.route == AIMEE_VECTOR_ROUTE_EXTERNAL && out.selected_principal == 1001);
   /* A provider IS authorised: it is a separate process holding embeddings and
    * is not trusted to enforce tenancy. Point 21 is rejected and absent. */
   assert(internal.calls == 1 && external.calls == 1 && out.reply.count == 2);
   assert(out.reply.candidates[0].point_id == 20 && out.reply.candidates[1].point_id == 22);
   assert(auth.calls == 3);

   aimee_vector_route_clear(&route);
   assert(aimee_vector_memory_candidates_search(&route, &req, &out) == AIMEE_VECTOR_OK);
   assert(out.route == AIMEE_VECTOR_ROUTE_DEFAULT_PGVECTOR && internal.calls == 2);
}

static void test_fail_closed_and_explicit_fallback(void)
{
   search_state_t internal = {.first_id = 10}, external = {.first_id = 20, .mode = 1};
   auth_state_t auth = {.reject_id = -1};
   aimee_vector_route_t route;
   float vec[3];
   aimee_vector_search_request_t req = request(vec);
   aimee_vector_search_outcome_t out;
   assert(aimee_vector_route_init(&route, search, &internal, authorize, &auth) == 0);

   assert(aimee_vector_route_select(&route, 1001, 0, 0, search, &external) == 0);
   assert(aimee_vector_memory_candidates_search(&route, &req, &out) == AIMEE_VECTOR_UNAVAILABLE);
   assert(out.route == AIMEE_VECTOR_ROUTE_EXTERNAL &&
          out.external_error == AIMEE_VECTOR_UNAVAILABLE);
   assert(internal.calls == 0 && external.calls == 0);

   assert(aimee_vector_route_select(&route, 1001, 1, 0, search, &external) == 0);
   assert(aimee_vector_memory_candidates_search(&route, &req, &out) ==
          AIMEE_VECTOR_PROVIDER_FAILURE);
   assert(internal.calls == 0 && external.calls == 1);

   assert(aimee_vector_route_select(&route, 1001, 1, 1, search, &external) == 0);
   assert(aimee_vector_memory_candidates_search(&route, &req, &out) == AIMEE_VECTOR_OK);
   assert(out.route == AIMEE_VECTOR_ROUTE_EXPLICIT_FALLBACK);
   assert(out.external_error == AIMEE_VECTOR_PROVIDER_FAILURE);
   assert(internal.calls == 1 && external.calls == 2);

   external.mode = 3;
   assert(aimee_vector_memory_candidates_search(&route, &req, &out) == AIMEE_VECTOR_OK);
   assert(out.route == AIMEE_VECTOR_ROUTE_EXPLICIT_FALLBACK);
   assert(out.external_error == AIMEE_VECTOR_INVALID_RESPONSE);
   assert(internal.calls == 2 && external.calls == 3);

   route.fallback_enabled = 0;
   for (int mode = 2; mode <= 5; ++mode)
   {
      external.mode = mode;
      assert(aimee_vector_memory_candidates_search(&route, &req, &out) ==
             AIMEE_VECTOR_INVALID_RESPONSE);
      assert(out.reply.count == 3 || mode == 2);
   }

   external.mode = 0;
   auth.fail = 1;
   assert(aimee_vector_memory_candidates_search(&route, &req, &out) == AIMEE_VECTOR_INTERNAL);
}

static void test_invalid_requests(void)
{
   search_state_t internal = {.first_id = 1};
   auth_state_t auth = {0};
   aimee_vector_route_t route;
   aimee_vector_search_outcome_t out;
   assert(aimee_vector_route_init(&route, search, &internal, authorize, &auth) == 0);
   float vec[3];
   aimee_vector_search_request_t req = request(vec);

   vec[1] = INFINITY;
   assert(aimee_vector_memory_candidates_search(&route, &req, &out) ==
          AIMEE_VECTOR_INVALID_REQUEST);
   req = request(vec);
   req.top_k = 0;
   assert(aimee_vector_memory_candidates_search(&route, &req, &out) ==
          AIMEE_VECTOR_INVALID_REQUEST);
   req = request(vec);
   req.workspace[0] = '\0';
   req.project[0] = '\0';
   assert(aimee_vector_memory_candidates_search(&route, &req, &out) ==
          AIMEE_VECTOR_INVALID_REQUEST);
   req = request(vec);
   memset(req.record_type, 'x', sizeof(req.record_type));
   assert(aimee_vector_memory_candidates_search(&route, &req, &out) ==
          AIMEE_VECTOR_INVALID_REQUEST);
   assert(internal.calls == 0);
}

static void test_wire_codecs(void)
{
   uint8_t wire[512], mutated[512];
   size_t length = 0;
   float vec[3], decoded_vec[AIMEE_VECTOR_MAX_DIM];
   aimee_vector_filter_view_t decoded_filters;
   aimee_vector_search_request_t req = request(vec), decoded_req;
   assert(aimee_vector_search_request_encode(&req, wire, sizeof(wire), &length) == 0);
   assert(length == 36 + strlen(req.workspace) + strlen(req.project) + strlen(req.record_type) +
                        req.dimension * sizeof(float));
   assert(aimee_vector_search_request_decode(wire, length, &decoded_req, decoded_vec,
                                             AIMEE_VECTOR_MAX_DIM, &decoded_filters) == 0);
   assert(decoded_req.request_id == req.request_id && decoded_req.dimension == req.dimension);
   assert(memcmp(decoded_req.vector, req.vector, req.dimension * sizeof(float)) == 0);
   assert(aimee_vector_search_request_decode(wire, length - 1, &decoded_req, decoded_vec,
                                             AIMEE_VECTOR_MAX_DIM, &decoded_filters) != 0);
   memcpy(mutated, wire, length);
   mutated[34] = 1;
   assert(aimee_vector_search_request_decode(mutated, length, &decoded_req, decoded_vec,
                                             AIMEE_VECTOR_MAX_DIM, &decoded_filters) != 0);
   memcpy(mutated, wire, length);
   mutated[length - 1] = 0x7f;
   mutated[length - 2] = 0x80;
   mutated[length - 3] = 0;
   mutated[length - 4] = 0;
   assert(aimee_vector_search_request_decode(mutated, length, &decoded_req, decoded_vec,
                                             AIMEE_VECTOR_MAX_DIM, &decoded_filters) != 0);

   aimee_vector_search_reply_t reply = {.request_id = req.request_id,
                                        .generation = req.required_generation,
                                        .count = 2,
                                        .candidates = {{101, 0.9}, {102, 0.8}}};
   aimee_vector_search_reply_t decoded_reply;
   assert(aimee_vector_search_reply_encode(&reply, wire, sizeof(wire), &length) == 0);
   assert(aimee_vector_search_reply_decode(wire, length, &decoded_reply) == 0);
   assert(aimee_vector_search_reply_validate(&req, &decoded_reply) == 0);
   assert(aimee_vector_search_reply_decode(wire, length - 1, &decoded_reply) != 0);
   assert(aimee_vector_search_reply_decode(wire, length, &decoded_reply) == 0);
   decoded_reply.candidates[1].point_id = 101;
   assert(aimee_vector_search_reply_validate(&req, &decoded_reply) != 0);
   assert(aimee_vector_search_reply_encode(&decoded_reply, wire, sizeof(wire), &length) != 0);

   float apply_vec[3] = {0.1f, 0.2f, 0.3f};
   aimee_vector_apply_t apply = {.operation_id = 1001,
                                 .generation = 7,
                                 .point_id = 101,
                                 .kind = AIMEE_VECTOR_APPLY_UPSERT,
                                 .collection = "memory",
                                 .dimension = 3,
                                 .vector = apply_vec};
   aimee_vector_apply_t decoded_apply;
   assert(aimee_vector_apply_encode(&apply, wire, sizeof(wire), &length) == 0);
   assert(aimee_vector_apply_decode(wire, length, &decoded_apply, decoded_vec,
                                    AIMEE_VECTOR_MAX_DIM) == 0);
   assert(decoded_apply.operation_id == apply.operation_id && decoded_apply.dimension == 3);
   assert(aimee_vector_apply_decode(wire, length - 1, &decoded_apply, decoded_vec,
                                    AIMEE_VECTOR_MAX_DIM) != 0);
   apply_vec[0] = NAN;
   assert(aimee_vector_apply_encode(&apply, wire, sizeof(wire), &length) != 0);
   apply_vec[0] = 0.1f;
   apply.kind = AIMEE_VECTOR_APPLY_DELETE;
   assert(aimee_vector_apply_validate(&apply) != 0);
   apply.dimension = 0;
   assert(aimee_vector_apply_validate(&apply) == 0);

   apply.kind = AIMEE_VECTOR_APPLY_UPSERT;
   apply.dimension = 3;
   apply.label_count = 3;
   strcpy(apply.labels[0].key, "project");
   strcpy(apply.labels[0].value, "project with space");
   strcpy(apply.labels[1].key, "record_type");
   strcpy(apply.labels[1].value, "memory");
   strcpy(apply.labels[2].key, "workspace");
   strcpy(apply.labels[2].value, "workspace-a");
   assert(aimee_vector_apply_encode(&apply, wire, sizeof(wire), &length) == 0);
   assert(wire[4] == AIMEE_VECTOR_APPLY_V2_VERSION && wire[5] == 0);
   assert(aimee_vector_apply_decode(wire, length, &decoded_apply, decoded_vec,
                                    AIMEE_VECTOR_MAX_DIM) == 0);
   assert(decoded_apply.label_count == 3);
   assert(strcmp(decoded_apply.labels[0].value, "project with space") == 0);
   assert(strcmp(decoded_apply.labels[2].key, "workspace") == 0);
   memcpy(mutated, wire, length);
   mutated[36] = 0;
   mutated[37] = 0;
   assert(aimee_vector_apply_decode(mutated, length, &decoded_apply, decoded_vec,
                                    AIMEE_VECTOR_MAX_DIM) != 0);
   memcpy(mutated, wire, length);
   mutated[38]++;
   assert(aimee_vector_apply_decode(mutated, length, &decoded_apply, decoded_vec,
                                    AIMEE_VECTOR_MAX_DIM) != 0);
   /* Out of order by key. */
   strcpy(apply.labels[1].key, "project");
   assert(aimee_vector_apply_validate(&apply) != 0);
   strcpy(apply.labels[1].key, "record_type");
   apply.labels[1].value[0] = '\n';
   apply.labels[1].value[1] = '\0';
   assert(aimee_vector_apply_validate(&apply) != 0);
   strcpy(apply.labels[1].value, "memory");

   /* ------------------------------------------------- multi-valued labels
    *
    * One key carrying several values is the whole reason search version 2 needs
    * no OR: scope visibility is a four-way disjunction in SQL -- active project,
    * active workspace, global, shared, and the ABSENCE of any scope row meaning
    * legacy-untagged -- and it becomes ONE set-membership predicate only if a
    * point can say every scope it belongs to under one key.
    *
    * Ordering by key alone made that malformed. It is now (key, value), still
    * strict. */
   apply.kind = AIMEE_VECTOR_APPLY_UPSERT;
   apply.dimension = 3;
   apply.label_count = 4;
   strcpy(apply.labels[0].key, "record_type");
   strcpy(apply.labels[0].value, "memory");
   strcpy(apply.labels[1].key, "visibility");
   strcpy(apply.labels[1].value, "global");
   strcpy(apply.labels[2].key, "visibility");
   strcpy(apply.labels[2].value, "project:widgets");
   strcpy(apply.labels[3].key, "visibility");
   strcpy(apply.labels[3].value, "workspace:acme");
   assert(aimee_vector_apply_validate(&apply) == 0);
   assert(aimee_vector_apply_encode(&apply, wire, sizeof(wire), &length) == 0);
   assert(aimee_vector_apply_decode(wire, length, &decoded_apply, decoded_vec,
                                    AIMEE_VECTOR_MAX_DIM) == 0);
   /* Four labels, three of them one key: the repeated key survives the round
    * trip rather than the last value winning, which is what a map would do. */
   assert(decoded_apply.label_count == 4);
   assert(strcmp(decoded_apply.labels[1].key, decoded_apply.labels[3].key) == 0);
   assert(strcmp(decoded_apply.labels[1].value, "global") == 0);
   assert(strcmp(decoded_apply.labels[2].value, "project:widgets") == 0);
   assert(strcmp(decoded_apply.labels[3].value, "workspace:acme") == 0);

   /* Values under one key must ascend too. Descending is malformed... */
   strcpy(apply.labels[2].value, "zzz");
   strcpy(apply.labels[3].value, "aaa");
   assert(aimee_vector_apply_validate(&apply) != 0);
   /* ...and so is the same pair twice: a duplicate carries no information, and
    * two encodings of one point defeat comparing them. */
   strcpy(apply.labels[2].value, "project:widgets");
   strcpy(apply.labels[3].value, "project:widgets");
   assert(aimee_vector_apply_validate(&apply) != 0);
   strcpy(apply.labels[3].value, "workspace:acme");
   assert(aimee_vector_apply_validate(&apply) == 0);

   apply.label_count = 3;
   strcpy(apply.labels[0].key, "project");
   strcpy(apply.labels[0].value, "project with space");
   strcpy(apply.labels[1].key, "record_type");
   strcpy(apply.labels[1].value, "memory");
   strcpy(apply.labels[2].key, "workspace");
   strcpy(apply.labels[2].value, "workspace-a");
   apply.kind = AIMEE_VECTOR_APPLY_DELETE;
   apply.dimension = 0;
   assert(aimee_vector_apply_validate(&apply) != 0);

   /* Generated tests/baselines/modules/vector-wire-v1.json replays these exact
    * bytes in Go. Pin them here as the C side of the cross-language fixture. */
   const uint8_t expected_request[] = {
       0x44, 0x42, 0x33, 0x53, 0x01, 0x00, 0x24, 0x00, 0x4d, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
       0x00, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0b, 0x00, 0x09, 0x00, 0x06, 0x00,
       0x03, 0x00, 0x02, 0x00, 0x00, 0x00, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65,
       0x2d, 0x61, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2d, 0x61, 0x6d, 0x65, 0x6d, 0x6f,
       0x72, 0x79, 0x9a, 0x99, 0x99, 0x3e, 0xcd, 0xcc, 0x4c, 0x3e, 0xcd, 0xcc, 0xcc, 0x3d};
   const uint8_t expected_reply[] = {
       0x44, 0x42, 0x33, 0x52, 0x01, 0x00, 0x1c, 0x00, 0x4d, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
       0x00, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x29, 0x00,
       0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0xee, 0x3f, 0x2a,
       0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xe8, 0x3f};
   const uint8_t expected_apply[] = {
       0x44, 0x42, 0x33, 0x41, 0x01, 0x00, 0x01, 0x00, 0xe9, 0x03, 0x00, 0x00, 0x00, 0x00,
       0x00, 0x00, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x29, 0x00, 0x00, 0x00,
       0x00, 0x00, 0x00, 0x00, 0x06, 0x00, 0x03, 0x00, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
       0xcd, 0xcc, 0xcc, 0x3d, 0xcd, 0xcc, 0x4c, 0x3e, 0x9a, 0x99, 0x99, 0x3e};
   const uint8_t expected_apply_v2[] = {
       0x44, 0x42, 0x33, 0x41, 0x02, 0x00, 0x01, 0x00, 0xea, 0x03, 0x00, 0x00, 0x00, 0x00,
       0x00, 0x00, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x2a, 0x00, 0x00, 0x00,
       0x00, 0x00, 0x00, 0x00, 0x06, 0x00, 0x03, 0x00, 0x03, 0x00, 0x41, 0x00, 0x6d, 0x65,
       0x6d, 0x6f, 0x72, 0x79, 0x9a, 0x99, 0x99, 0x3e, 0xcd, 0xcc, 0x4c, 0x3e, 0xcd, 0xcc,
       0xcc, 0x3d, 0x07, 0x00, 0x09, 0x00, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x70,
       0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2d, 0x61, 0x0b, 0x00, 0x06, 0x00, 0x72, 0x65,
       0x63, 0x6f, 0x72, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x6d, 0x65, 0x6d, 0x6f, 0x72,
       0x79, 0x09, 0x00, 0x0b, 0x00, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65,
       0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2d, 0x61};
   float fixture_request_vec[3] = {0.3f, 0.2f, 0.1f};
   aimee_vector_search_request_t fixture_request = {.request_id = 77,
                                                    .required_generation = 7,
                                                    .workspace = "workspace-a",
                                                    .project = "project-a",
                                                    .record_type = "memory",
                                                    .dimension = 3,
                                                    .top_k = 2,
                                                    .vector = fixture_request_vec};
   assert(aimee_vector_search_request_encode(&fixture_request, wire, sizeof(wire), &length) == 0);
   assert(length == sizeof(expected_request) && memcmp(wire, expected_request, length) == 0);
   aimee_vector_search_reply_t fixture_reply = {
       .request_id = 77, .generation = 7, .count = 2, .candidates = {{41, 0.95}, {42, 0.75}}};
   assert(aimee_vector_search_reply_encode(&fixture_reply, wire, sizeof(wire), &length) == 0);
   assert(length == sizeof(expected_reply) && memcmp(wire, expected_reply, length) == 0);
   float fixture_apply_vec[3] = {0.1f, 0.2f, 0.3f};
   aimee_vector_apply_t fixture_apply = {.operation_id = 1001,
                                         .generation = 7,
                                         .point_id = 41,
                                         .kind = AIMEE_VECTOR_APPLY_UPSERT,
                                         .collection = "memory",
                                         .dimension = 3,
                                         .vector = fixture_apply_vec};
   assert(aimee_vector_apply_encode(&fixture_apply, wire, sizeof(wire), &length) == 0);
   assert(length == sizeof(expected_apply) && memcmp(wire, expected_apply, length) == 0);
   float fixture_apply_v2_vec[3] = {0.3f, 0.2f, 0.1f};
   aimee_vector_apply_t fixture_apply_v2 = {.operation_id = 1002,
                                            .generation = 7,
                                            .point_id = 42,
                                            .kind = AIMEE_VECTOR_APPLY_UPSERT,
                                            .collection = "memory",
                                            .dimension = 3,
                                            .vector = fixture_apply_v2_vec,
                                            .label_count = 3,
                                            .labels = {
                                                {.key = "project", .value = "project-a"},
                                                {.key = "record_type", .value = "memory"},
                                                {.key = "workspace", .value = "workspace-a"},
                                            }};
   assert(aimee_vector_apply_encode(&fixture_apply_v2, wire, sizeof(wire), &length) == 0);
   assert(length == sizeof(expected_apply_v2) && memcmp(wire, expected_apply_v2, length) == 0);
}

static void test_every_filter_a_search_has_is_carried(void)
{
   /* This test used to assert the opposite: that four filters and two
    * predicates were REFUSED. That was the right assertion about a wire which
    * could not carry them, and it would now pin the defect.
    *
    * The six things every DB2 vector search filters by, and where each goes:
    *
    *   labels             one EQ each -- four curator searches
    *   kinds              one IN      -- two memory searches
    *   exclude_project    one NE      -- two scoped kb searches
    *   rank_column        the collection field -- claim and code-unit search
    *   visibility         one IN over a multi-valued label -- scope membership
    *   current_generation one EQ      -- currency
    */
   float vec[3] = {0.25f, -0.5f, 0.75f};
   const char *kinds[] = {"note", "fact"};
   const char *label_keys[] = {"status"};
   const char *label_values[] = {"open"};
   const char *visibility[] = {"proj:project-a", "ws:workspace-a", "global", "untagged"};
   aimee_vector_filter_t predicates[AIMEE_VECTOR_MAX_FILTERS];
   aimee_vector_search_request_t request;

   aimee_vector_search_filters_t everything = {.workspace = "workspace-a",
                                               .project = "project-a",
                                               .record_type = "memory",
                                               .rank_column = "subj_attr",
                                               .exclude_project = "project-b",
                                               .kinds = kinds,
                                               .kind_count = 2,
                                               .label_keys = label_keys,
                                               .label_values = label_values,
                                               .label_count = 1,
                                               .visibility = visibility,
                                               .visibility_count = 4,
                                               .current_generation = "7"};
   assert(aimee_vector_search_filters_expressible(&everything) == 1);
   assert(aimee_vector_search_request_build(&everything, 91, 7, vec, 3, 3, predicates,
                                            AIMEE_VECTOR_MAX_FILTERS, &request) == 0);
   /* Five predicates: one label, kinds, exclude_project, visibility, generation.
    * rank_column is the collection field rather than a predicate. */
   assert(request.filter_count == 5);
   assert(strcmp(request.collection, "subj_attr") == 0);

   /* And they survive the wire, which is the half a struct comparison cannot
    * show. Walked with the cursor a provider would use. */
   uint8_t wire[4096];
   size_t length = 0;
   assert(aimee_vector_search_request_encode(&request, wire, sizeof(wire), &length) == 0);
   aimee_vector_search_request_t decoded;
   float decoded_vector[AIMEE_VECTOR_MAX_DIM];
   aimee_vector_filter_view_t view;
   assert(aimee_vector_search_request_decode(wire, length, &decoded, decoded_vector,
                                             AIMEE_VECTOR_MAX_DIM, &view) == 0);
   assert(strcmp(decoded.collection, "subj_attr") == 0);
   assert(decoded.filter_count == 5);

   int saw_kinds = 0, saw_exclude = 0, saw_visibility = 0, saw_generation = 0, saw_label = 0;
   aimee_vector_filter_entry_t entry;
   while (aimee_vector_filter_next(&view, &entry) == 1)
   {
      const char *value = NULL;
      size_t value_length = 0;
      if (entry.key_length == 4 && memcmp(entry.key, "kind", 4) == 0)
      {
         assert(entry.op == AIMEE_VECTOR_FILTER_IN && entry.value_count == 2);
         assert(aimee_vector_filter_value(&view, &entry, 1, &value, &value_length) == 0);
         assert(value_length == 4 && memcmp(value, "fact", 4) == 0);
         saw_kinds = 1;
      }
      else if (entry.key_length == 7 && memcmp(entry.key, "project", 7) == 0)
      {
         assert(entry.op == AIMEE_VECTOR_FILTER_NE && entry.value_count == 1);
         saw_exclude = 1;
      }
      else if (entry.key_length == 10 && memcmp(entry.key, "visibility", 10) == 0)
      {
         /* The four-way scope disjunction, as ONE set-membership predicate. */
         assert(entry.op == AIMEE_VECTOR_FILTER_IN && entry.value_count == 4);
         assert(aimee_vector_filter_value(&view, &entry, 3, &value, &value_length) == 0);
         assert(value_length == 8 && memcmp(value, "untagged", 8) == 0);
         saw_visibility = 1;
      }
      else if (entry.key_length == 10 && memcmp(entry.key, "generation", 10) == 0)
      {
         assert(entry.op == AIMEE_VECTOR_FILTER_EQ && entry.value_count == 1);
         assert(aimee_vector_filter_value(&view, &entry, 0, &value, &value_length) == 0);
         assert(value_length == 1 && value[0] == '7');
         saw_generation = 1;
      }
      else if (entry.key_length == 6 && memcmp(entry.key, "status", 6) == 0)
      {
         assert(entry.op == AIMEE_VECTOR_FILTER_EQ);
         saw_label = 1;
      }
   }
   assert(saw_kinds && saw_exclude && saw_visibility && saw_generation && saw_label);
}

static void test_a_request_with_nothing_extra_is_still_version_one(void)
{
   /* Byte for byte, so a provider that speaks only version 1 keeps receiving
    * every request it could already serve. The compatibility is a consequence
    * of the encoding rather than a promise made about it. */
   float vec[3];
   aimee_vector_filter_t predicates[AIMEE_VECTOR_MAX_FILTERS];
   aimee_vector_search_request_t plain;
   aimee_vector_search_filters_t bare = {
       .workspace = "workspace-a", .project = "project-a", .record_type = "memory"};
   vec[0] = 0.25f;
   vec[1] = -0.5f;
   vec[2] = 0.75f;
   assert(aimee_vector_search_request_build(&bare, 91, 7, vec, 3, 3, predicates,
                                            AIMEE_VECTOR_MAX_FILTERS, &plain) == 0);
   assert(plain.filter_count == 0 && plain.collection[0] == '\0');

   uint8_t wire[512];
   size_t length = 0;
   assert(aimee_vector_search_request_encode(&plain, wire, sizeof(wire), &length) == 0);
   assert(length == AIMEE_VECTOR_SEARCH_REQUEST_HEADER + strlen("workspace-a") +
                        strlen("project-a") + strlen("memory") + 3 * sizeof(float));
   uint16_t version = (uint16_t)(wire[4] | (wire[5] << 8));
   assert(version == AIMEE_VECTOR_WIRE_VERSION);
}

static void test_one_meaning_has_one_encoding(void)
{
   /* The encoder picks version 1 when there is nothing version 2 carries, so a
    * version 2 frame with neither a collection nor a filter is one nobody
    * writes. Accepting it would make two byte sequences mean one request, and a
    * provider that treats the versions differently would answer differently for
    * the same question. */
   float vec[3] = {0.25f, -0.5f, 0.75f};
   aimee_vector_filter_t predicates[AIMEE_VECTOR_MAX_FILTERS];
   aimee_vector_search_request_t request;
   aimee_vector_search_filters_t bare = {
       .workspace = "workspace-a", .project = "project-a", .record_type = "memory"};
   assert(aimee_vector_search_request_build(&bare, 91, 7, vec, 3, 3, predicates,
                                            AIMEE_VECTOR_MAX_FILTERS, &request) == 0);

   uint8_t wire[512];
   size_t length = 0;
   assert(aimee_vector_search_request_encode(&request, wire, sizeof(wire), &length) == 0);

   /* Hand-build the version 2 form of the same request: the v1 header widened,
    * the version bumped, the three new fields zero. Every byte after the header
    * is identical, which is what makes it the same request. */
   uint8_t forged[512];
   size_t header = AIMEE_VECTOR_SEARCH_REQUEST_HEADER;
   size_t v2_header = AIMEE_VECTOR_SEARCH_REQUEST_V2_HEADER;
   memset(forged, 0, v2_header);
   memcpy(forged, wire, header);
   forged[4] = (uint8_t)AIMEE_VECTOR_SEARCH_REQUEST_V2_VERSION;
   forged[5] = 0;
   forged[6] = (uint8_t)v2_header;
   forged[7] = 0;
   memcpy(forged + v2_header, wire + header, length - header);
   size_t forged_length = length - header + v2_header;

   aimee_vector_search_request_t decoded;
   float decoded_vector[AIMEE_VECTOR_MAX_DIM];
   aimee_vector_filter_view_t view;
   assert(aimee_vector_search_request_decode(forged, forged_length, &decoded, decoded_vector,
                                             AIMEE_VECTOR_MAX_DIM, &view) != 0);

   /* And the form the encoder does write still decodes. */
   assert(aimee_vector_search_request_decode(wire, length, &decoded, decoded_vector,
                                             AIMEE_VECTOR_MAX_DIM, &view) == 0);
}

static void test_what_does_not_fit_is_still_refused(void)
{
   /* The refusals that remain are arithmetic rather than vocabulary: a set over
    * the ceiling, more predicates than there are fields for, half a label pair.
    * Still refusals rather than trims -- a filter set silently narrowed is a
    * search with a predicate missing, which returns more rows than it should
    * and looks exactly like a correct answer. */
   float vec[3] = {0.25f, -0.5f, 0.75f};
   aimee_vector_filter_t predicates[AIMEE_VECTOR_MAX_FILTERS];
   aimee_vector_search_request_t request;
   const char *many[AIMEE_VECTOR_MAX_FILTER_VALUES + 1];
   for (size_t i = 0; i < sizeof(many) / sizeof(many[0]); ++i)
      many[i] = "value";

   aimee_vector_search_filters_t base = {
       .workspace = "workspace-a", .project = "project-a", .record_type = "memory"};

   aimee_vector_search_filters_t too_many_values = base;
   too_many_values.kinds = many;
   too_many_values.kind_count = AIMEE_VECTOR_MAX_FILTER_VALUES + 1;
   assert(aimee_vector_search_filters_expressible(&too_many_values) == 0);

   /* A label pair with one half missing. Guessing the other half is how a
    * search asks a question nobody wrote. */
   const char *keys[] = {"status"};
   aimee_vector_search_filters_t half_a_pair = base;
   half_a_pair.label_keys = keys;
   half_a_pair.label_count = 1;
   assert(aimee_vector_search_filters_expressible(&half_a_pair) == 0);

   /* More predicates than the caller gave room for. */
   const char *label_keys[AIMEE_VECTOR_MAX_FILTERS];
   const char *label_values[AIMEE_VECTOR_MAX_FILTERS];
   for (size_t i = 0; i < AIMEE_VECTOR_MAX_FILTERS; ++i)
   {
      label_keys[i] = "status";
      label_values[i] = "open";
   }
   aimee_vector_search_filters_t full = base;
   full.label_keys = label_keys;
   full.label_values = label_values;
   full.label_count = AIMEE_VECTOR_MAX_FILTERS;
   assert(aimee_vector_search_filters_expressible(&full) == 1);
   assert(aimee_vector_search_request_build(&full, 91, 7, vec, 3, 3, predicates, 4, &request) != 0);

   /* One more than there are filter slots. */
   aimee_vector_search_filters_t over = full;
   over.current_generation = "7";
   assert(aimee_vector_search_filters_expressible(&over) == 0);
}

/* The caller's half of the visibility vocabulary.
 *
 * memory_visibility_labels() (modules/db2/c/schema.sql) writes every scope a
 * point belongs to as separate values of one label; this builds the set a
 * caller may match, and visibility is then "do the two sets intersect" -- one
 * IN over a multi-valued label, which is why the four-way disjunction needs no
 * OR. That the two halves agree with DB2_MEMORY_SCOPE_RANK_SQL is checked
 * against a real database in scripts/db2_replay_env.sh; what is pinned here is
 * the vocabulary itself, because a value spelled differently on the two sides
 * makes every search return nothing and looks exactly like no matches.
 *
 * Asserted as exact strings on purpose. Building the expectation from the same
 * macros the implementation uses would agree with any typo in them. */
static void test_the_callers_half_of_the_visibility_vocabulary(void)
{
   db2_memory_scope_context_t ctx;
   char storage[DB2_MEMORY_VISIBILITY_MAX_VALUES][DB2_MEMORY_VISIBILITY_VALUE_MAX];
   const char *values[DB2_MEMORY_VISIBILITY_MAX_VALUES];

   /* No scope, and include_all, are both "admit everything" to the rank
    * filter -- so no predicate at all, not a predicate matching everything. */
   memset(&ctx, 0, sizeof(ctx));
   assert(db2_memory_visibility_filter_values(&ctx, storage, values,
                                              DB2_MEMORY_VISIBILITY_MAX_VALUES) == 0);
   ctx.active = 1;
   ctx.include_all = 1;
   assert(db2_memory_visibility_filter_values(&ctx, storage, values,
                                              DB2_MEMORY_VISIBILITY_MAX_VALUES) == 0);

   /* An active scope: the caller's project and workspace, then the three that
    * are always visible -- global, '_shared', and the legacy-untagged rows,
    * whose visibility is the ABSENCE of a scope row and therefore has to be a
    * value before a provider can be asked about it. */
   ctx.include_all = 0;
   snprintf(ctx.workspace, sizeof(ctx.workspace), "ws-a");
   snprintf(ctx.project, sizeof(ctx.project), "pj-a");
   assert(db2_memory_visibility_filter_values(&ctx, storage, values,
                                              DB2_MEMORY_VISIBILITY_MAX_VALUES) == 5);
   assert(strcmp(values[0], "project:pj-a") == 0);
   assert(strcmp(values[1], "workspace:ws-a") == 0);
   assert(strcmp(values[2], "global") == 0);
   assert(strcmp(values[3], "workspace:_shared") == 0);
   assert(strcmp(values[4], "untagged") == 0);

   /* An empty component is not a wildcard: it drops out rather than matching
    * every project, which is the same rule the rank applies with ?104 <> ''. */
   ctx.project[0] = '\0';
   assert(db2_memory_visibility_filter_values(&ctx, storage, values,
                                              DB2_MEMORY_VISIBILITY_MAX_VALUES) == 4);
   assert(strcmp(values[0], "workspace:ws-a") == 0);

   /* A workspace literally named '_shared' builds the constant a second time.
    * One question, one encoding. */
   snprintf(ctx.workspace, sizeof(ctx.workspace), "_shared");
   assert(db2_memory_visibility_filter_values(&ctx, storage, values,
                                              DB2_MEMORY_VISIBILITY_MAX_VALUES) == 3);
   assert(strcmp(values[0], "workspace:_shared") == 0);
   assert(strcmp(values[1], "global") == 0);
   assert(strcmp(values[2], "untagged") == 0);

   /* Refused, not truncated. A workspace cut short is a different workspace,
    * and the search it filters returns a short answer that cannot be told
    * apart from a complete one. */
   memset(ctx.workspace, 'w', sizeof(ctx.workspace) - 1);
   ctx.workspace[sizeof(ctx.workspace) - 1] = '\0';
   assert(db2_memory_visibility_filter_values(&ctx, storage, values,
                                              DB2_MEMORY_VISIBILITY_MAX_VALUES) == -1);

   /* A set that does not fit the caller's array is refused for the same
    * reason: a filter silently narrowed is a filter missing. */
   snprintf(ctx.workspace, sizeof(ctx.workspace), "ws-a");
   snprintf(ctx.project, sizeof(ctx.project), "pj-a");
   assert(db2_memory_visibility_filter_values(&ctx, storage, values, 4) == -1);
}

int main(void)
{
   test_capabilities_codec();
   test_capabilities_refusals();
   test_provider_selection();
   test_default_external_and_authorization();
   test_fail_closed_and_explicit_fallback();
   test_invalid_requests();
   test_wire_codecs();
   test_every_filter_a_search_has_is_carried();
   test_a_request_with_nothing_extra_is_still_version_one();
   test_what_does_not_fit_is_still_refused();
   test_one_meaning_has_one_encoding();
   test_the_callers_half_of_the_visibility_vocabulary();
   puts("test_vector_route: routing, fallback, revalidation, and codecs passed");
   return 0;
}
