/* test_bus_wire.c: slice 1 of the event-bus feature tree.
 *
 * Three jobs, deliberately kept separate:
 *
 *   1. Hold the codec to the committed golden vectors in
 *      src/tests/fixtures/bus/wire_vectors.tsv. Those bytes are generated by
 *      scripts/gen_bus_wire_vectors.py, which re-declares the byte layout from
 *      the spec independently of this codec — so agreement is evidence about
 *      the wire, not the codec agreeing with itself. The table is the source of
 *      truth here: this test parses its field column into a frame and checks
 *      the codec against it in both directions. It never constructs the
 *      expected bytes.
 *
 *   2. Exercise the message-pattern contract from an independently enumerated
 *      matrix, so a pattern or placement added to bus_wire.h later cannot
 *      silently go untested.
 *
 *   3. Reject every malformed frame the decoder is responsible for catching.
 *
 * Regenerating the vectors is a separate, reviewable act: run the Python
 * generator and commit the byte diff. This test has no --regen path, because a
 * test that can rewrite its own expectations is not a test.
 */
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "bus_wire.h"

/* Set by the build so the test is cwd-independent. */
#ifndef BUS_VECTOR_DIR
#define BUS_VECTOR_DIR "fixtures/bus"
#endif
#define VECTOR_PATH BUS_VECTOR_DIR "/wire_vectors.tsv"

/* ------------------------------------------------------------------ */
/* helpers                                                             */

static int hex_decode(const char *in, uint8_t *out, size_t outsz, size_t *n)
{
   size_t len = strlen(in);
   if (len % 2 != 0 || len / 2 > outsz)
      return 0;
   for (size_t i = 0; i < len; i += 2)
   {
      int hi = -1, lo = -1;
      for (int k = 0; k < 16; k++)
      {
         if ("0123456789abcdef"[k] == in[i])
            hi = k;
         if ("0123456789abcdef"[k] == in[i + 1])
            lo = k;
      }
      if (hi < 0 || lo < 0)
         return 0;
      out[i / 2] = (uint8_t)((hi << 4) | lo);
   }
   *n = len / 2;
   return 1;
}

static void hex_encode(const uint8_t *in, size_t n, char *out)
{
   static const char *h = "0123456789abcdef";
   for (size_t i = 0; i < n; i++)
   {
      out[2 * i] = h[in[i] >> 4];
      out[2 * i + 1] = h[in[i] & 0x0f];
   }
   out[2 * n] = '\0';
}

/* Parse one "k=v;k=v" field column into a frame. The table is authoritative,
 * so a field this parser does not know is a hard error rather than a default —
 * silently ignoring it would let a vector assert something never checked. */
static void parse_fields(const char *name, const char *spec, bus_frame_t *f)
{
   char buf[512];
   snprintf(buf, sizeof buf, "%s", spec);
   memset(f, 0, sizeof *f);

   int seen = 0;
   for (char *tok = strtok(buf, ";"); tok; tok = strtok(NULL, ";"))
   {
      char *eq = strchr(tok, '=');
      if (!eq)
      {
         fprintf(stderr, "vector '%s': malformed field '%s'\n", name, tok);
         exit(1);
      }
      *eq = '\0';
      const char *k = tok;
      unsigned long long v = strtoull(eq + 1, NULL, 0);

      if (!strcmp(k, "flags"))
         f->hdr_flags = (uint16_t)v;
      else if (!strcmp(k, "ver"))
         f->wire_version = (uint16_t)v;
      else if (!strcmp(k, "kind"))
         f->event_kind = (uint32_t)v;
      else if (!strcmp(k, "principal"))
         f->principal_ref = (uint32_t)v;
      else if (!strcmp(k, "corr"))
         f->correlation_id = (uint64_t)v;
      else if (!strcmp(k, "seq"))
         f->seq = (uint64_t)v;
      else if (!strcmp(k, "lts"))
         f->logical_ts = (uint64_t)v;
      else if (!strcmp(k, "pref"))
         f->payload_ref = (uint64_t)v;
      else if (!strcmp(k, "plen"))
         f->payload_len = (uint32_t)v;
      else if (!strcmp(k, "src"))
         f->src_handle = (uint32_t)v;
      else if (!strcmp(k, "dst"))
         f->dst_handle = (uint32_t)v;
      else
      {
         fprintf(stderr, "vector '%s': unknown field '%s'\n", name, k);
         exit(1);
      }
      seen++;
   }
   if (seen != 11)
   {
      fprintf(stderr, "vector '%s': expected 11 fields, saw %d\n", name, seen);
      exit(1);
   }
}

/* ------------------------------------------------------------------ */
/* 1. the committed vectors                                            */

/* Flag combinations that must appear somewhere in the table. Declared here
 * independently of the table so a pattern added to bus_wire.h without a vector
 * is caught, rather than the table quietly defining its own coverage. */
typedef struct
{
   const char *what;
   uint16_t flags;
} required_shape_t;

static const required_shape_t REQUIRED_SHAPES[] = {
   {"notification, no payload", BUS_F_NOTIFICATION},
   {"notification, inline", BUS_F_NOTIFICATION | BUS_F_INLINE},
   {"notification, arena", BUS_F_NOTIFICATION | BUS_F_ARENA},
   {"request", BUS_F_REQUEST | BUS_F_ARENA},
   {"reply", BUS_F_REPLY | BUS_F_INLINE},
   {"reply, no payload", BUS_F_REPLY},
   {"cancel", BUS_F_CANCEL},
   {"control class", BUS_F_NOTIFICATION | BUS_F_CONTROL | BUS_F_INLINE},
};
#define REQUIRED_SHAPE_COUNT (sizeof REQUIRED_SHAPES / sizeof REQUIRED_SHAPES[0])

static size_t verify_vectors(void)
{
   FILE *fp = fopen(VECTOR_PATH, "r");
   if (!fp)
   {
      fprintf(stderr, "cannot open %s\n", VECTOR_PATH);
      exit(1);
   }

   int shape_seen[REQUIRED_SHAPE_COUNT];
   memset(shape_seen, 0, sizeof shape_seen);

   size_t n = 0;
   char line[2048];
   while (fgets(line, sizeof line, fp))
   {
      if (line[0] == '#' || line[0] == '\n')
         continue;
      char *nl = strchr(line, '\n');
      if (nl)
         *nl = '\0';

      char *name = strtok(line, "\t");
      char *expect = strtok(NULL, "\t");
      char *hex = strtok(NULL, "\t");
      char *fields = strtok(NULL, "\t");
      if (!name || !expect || !hex || !fields)
      {
         fprintf(stderr, "malformed vector line %zu\n", n + 1);
         exit(1);
      }

      bus_frame_t want;
      parse_fields(name, fields, &want);

      uint8_t raw[BUS_WIRE_HDR_LEN];
      size_t rawn = 0;
      if (!hex_decode(hex, raw, sizeof raw, &rawn) || rawn != BUS_WIRE_HDR_LEN)
      {
         fprintf(stderr, "vector '%s': hex is not %d bytes\n", name, BUS_WIRE_HDR_LEN);
         exit(1);
      }

      /* Decode direction: the committed bytes must yield the committed fields.
       * Both sides come from the generator, so this checks the decoder against
       * an independent statement of the layout. */
      bus_frame_t got;
      bus_wire_result_t r = bus_wire_decode(raw, rawn, &got);
      if (strcmp(bus_wire_result_name(r), expect) != 0)
      {
         fprintf(stderr, "vector '%s': decode gave %s, table says %s\n", name,
                 bus_wire_result_name(r), expect);
         exit(1);
      }
      if (r == BUS_WIRE_OK && memcmp(&want, &got, sizeof want) != 0)
      {
         fprintf(stderr, "vector '%s': decoded fields differ from the table\n", name);
         exit(1);
      }

      /* Encode direction: the committed fields must yield the committed bytes.
       * Compared against the table's hex, never against freshly encoded bytes. */
      if (r == BUS_WIRE_OK)
      {
         uint8_t enc[BUS_WIRE_HDR_LEN];
         char enc_hex[2 * BUS_WIRE_HDR_LEN + 1];
         if (bus_wire_encode(&want, enc, sizeof enc) != BUS_WIRE_HDR_LEN)
         {
            fprintf(stderr, "vector '%s': encode refused a committed frame\n", name);
            exit(1);
         }
         hex_encode(enc, sizeof enc, enc_hex);
         if (strcmp(enc_hex, hex) != 0)
         {
            fprintf(stderr, "vector '%s' drifted:\n  committed %s\n  encoded   %s\n", name,
                    hex, enc_hex);
            exit(1);
         }

         for (size_t i = 0; i < REQUIRED_SHAPE_COUNT; i++)
            if (want.hdr_flags == REQUIRED_SHAPES[i].flags)
               shape_seen[i] = 1;
      }
      n++;
   }
   fclose(fp);

   if (n == 0)
   {
      fprintf(stderr, "vector table is empty\n");
      exit(1);
   }
   for (size_t i = 0; i < REQUIRED_SHAPE_COUNT; i++)
      if (!shape_seen[i])
      {
         fprintf(stderr, "no vector covers: %s (flags 0x%04x)\n", REQUIRED_SHAPES[i].what,
                 REQUIRED_SHAPES[i].flags);
         exit(1);
      }

   printf("  vectors: %zu rows, both directions, all %zu required shapes covered\n", n,
          REQUIRED_SHAPE_COUNT);
   return n;
}

/* ------------------------------------------------------------------ */
/* 2. the pattern matrix, enumerated independently of the table        */

static void check_roundtrip(const char *what, bus_frame_t in)
{
   uint8_t buf[BUS_WIRE_HDR_LEN];
   if (bus_wire_encode(&in, buf, sizeof buf) != BUS_WIRE_HDR_LEN)
   {
      fprintf(stderr, "encode failed: %s\n", what);
      abort();
   }
   bus_frame_t out;
   bus_wire_result_t r = bus_wire_decode(buf, BUS_WIRE_HDR_LEN, &out);
   if (r != BUS_WIRE_OK)
   {
      fprintf(stderr, "decode failed: %s -> %s\n", what, bus_wire_result_name(r));
      abort();
   }
   if (memcmp(&in, &out, sizeof in) != 0)
   {
      fprintf(stderr, "round trip changed the frame: %s\n", what);
      abort();
   }
}

static bus_frame_t base_frame(void)
{
   bus_frame_t f;
   memset(&f, 0, sizeof f);
   f.wire_version = BUS_WIRE_VERSION;
   f.event_kind = BUS_KIND_MODULE_BASE;
   f.principal_ref = 0x11223344u;
   f.src_handle = 7;
   f.logical_ts = 0x0102030405060708ull;
   return f;
}

/* Every pattern crossed with every placement, driven off the flag constants so
 * the matrix follows bus_wire.h rather than a hand-kept list. */
static void test_pattern_matrix(void)
{
   const uint16_t patterns[] = {BUS_F_NOTIFICATION, BUS_F_REQUEST, BUS_F_REPLY, BUS_F_CANCEL};
   const uint16_t placements[] = {0, BUS_F_INLINE, BUS_F_ARENA};
   int cases = 0;

   for (size_t p = 0; p < sizeof patterns / sizeof patterns[0]; p++)
      for (size_t q = 0; q < sizeof placements / sizeof placements[0]; q++)
         for (int control = 0; control <= 1; control++)
         {
            bus_frame_t f = base_frame();
            f.hdr_flags = (uint16_t)(patterns[p] | placements[q] |
                                     (control ? BUS_F_CONTROL : 0));
            if (patterns[p] != BUS_F_NOTIFICATION)
               f.correlation_id = 0xdeadbeefcafef00dull;
            if (placements[q] != 0)
            {
               f.payload_len = 128;
               f.payload_ref = placements[q] == BUS_F_INLINE ? BUS_WIRE_HDR_LEN : 0x40000;
            }

            char what[96];
            snprintf(what, sizeof what, "matrix flags=0x%04x", f.hdr_flags);
            check_roundtrip(what, f);
            cases++;
         }

   /* The payload bound from both sides: at the maximum it round-trips, and one
    * byte over is rejected by validate. An off-by-one here would otherwise only
    * surface once a real allocator was involved. */
   bus_frame_t max = base_frame();
   max.hdr_flags = BUS_F_NOTIFICATION | BUS_F_ARENA;
   max.payload_len = BUS_WIRE_MAX_PAYLOAD;
   max.payload_ref = 0x40000;
   check_roundtrip("payload.max", max);
   max.payload_len = BUS_WIRE_MAX_PAYLOAD + 1;
   assert(bus_wire_validate(&max) == BUS_WIRE_ERR_PAYLOAD_LEN);

   printf("  pattern matrix: %d cases + payload bound both sides\n", cases);
}

/* ------------------------------------------------------------------ */
/* 3. rejections                                                       */

/* Write a frame the encoder would refuse, so the decoder's own guards can be
 * reached. Offsets mirror bus_wire.c's layout comment. */
static void encode_unchecked(const bus_frame_t *f, uint8_t *out)
{
   bus_frame_t ok = base_frame();
   ok.hdr_flags = BUS_F_NOTIFICATION;
   assert(bus_wire_encode(&ok, out, BUS_WIRE_HDR_LEN) == BUS_WIRE_HDR_LEN);
   out[4] = (uint8_t)(f->hdr_flags & 0xff);
   out[5] = (uint8_t)((f->hdr_flags >> 8) & 0xff);
   out[6] = (uint8_t)(f->wire_version & 0xff);
   out[7] = (uint8_t)((f->wire_version >> 8) & 0xff);
   for (int i = 0; i < 8; i++)
      out[16 + i] = (uint8_t)((f->correlation_id >> (8 * i)) & 0xff);
   for (int i = 0; i < 8; i++)
      out[40 + i] = (uint8_t)((f->payload_ref >> (8 * i)) & 0xff);
   for (int i = 0; i < 4; i++)
      out[48 + i] = (uint8_t)((f->payload_len >> (8 * i)) & 0xff);
}

static void expect_reject(const char *what, const uint8_t *buf, size_t n,
                          bus_wire_result_t want)
{
   bus_frame_t out;
   memset(&out, 0xa5, sizeof out);
   bus_frame_t before = out;
   bus_wire_result_t r = bus_wire_decode(buf, n, &out);
   if (r != want)
   {
      fprintf(stderr, "%s: expected %s, got %s\n", what, bus_wire_result_name(want),
              bus_wire_result_name(r));
      abort();
   }
   if (memcmp(&before, &out, sizeof out) != 0)
   {
      fprintf(stderr, "%s: decoder wrote to *out on failure\n", what);
      abort();
   }
}

static void test_rejections(void)
{
   uint8_t buf[BUS_WIRE_HDR_LEN], bad[BUS_WIRE_HDR_LEN];
   bus_frame_t good = base_frame();
   good.hdr_flags = BUS_F_NOTIFICATION;
   assert(bus_wire_encode(&good, buf, sizeof buf) == BUS_WIRE_HDR_LEN);

   for (size_t n = 0; n < BUS_WIRE_HDR_LEN; n++)
      expect_reject("short", buf, n, BUS_WIRE_ERR_SHORT);

   memcpy(bad, buf, sizeof bad);
   bad[0] ^= 0xff;
   expect_reject("magic", bad, sizeof bad, BUS_WIRE_ERR_MAGIC);

   memcpy(bad, buf, sizeof bad);
   bad[60] = 1;
   expect_reject("reserved", bad, sizeof bad, BUS_WIRE_ERR_RESERVED);

   struct
   {
      const char *what;
      uint16_t flags;
      uint16_t ver;
      uint64_t corr;
      uint64_t pref;
      uint32_t plen;
      bus_wire_result_t want;
   } cases[] = {
      {"version", BUS_F_NOTIFICATION, BUS_WIRE_VERSION + 1, 0, 0, 0, BUS_WIRE_ERR_VERSION},
      {"unknown flag bit", BUS_F_NOTIFICATION | 0x8000u, BUS_WIRE_VERSION, 0, 0, 0,
       BUS_WIRE_ERR_FLAGS},
      {"no pattern", 0, BUS_WIRE_VERSION, 0, 0, 0, BUS_WIRE_ERR_FLAGS},
      {"two patterns", BUS_F_REQUEST | BUS_F_REPLY, BUS_WIRE_VERSION, 1, 0, 0,
       BUS_WIRE_ERR_FLAGS},
      {"payload without placement", BUS_F_NOTIFICATION, BUS_WIRE_VERSION, 0, 0, 32,
       BUS_WIRE_ERR_FLAGS},
      {"both placements", BUS_F_NOTIFICATION | BUS_F_INLINE | BUS_F_ARENA, BUS_WIRE_VERSION,
       0, 0, 32, BUS_WIRE_ERR_FLAGS},
      {"placement without payload", BUS_F_NOTIFICATION | BUS_F_INLINE, BUS_WIRE_VERSION, 0, 0,
       0, BUS_WIRE_ERR_FLAGS},
      {"ref without payload", BUS_F_NOTIFICATION, BUS_WIRE_VERSION, 0, 4096, 0,
       BUS_WIRE_ERR_PAYLOAD_LEN},
      {"oversize payload", BUS_F_NOTIFICATION | BUS_F_ARENA, BUS_WIRE_VERSION, 0, 0x40000,
       BUS_WIRE_MAX_PAYLOAD + 1, BUS_WIRE_ERR_PAYLOAD_LEN},
      {"notification with correlation", BUS_F_NOTIFICATION, BUS_WIRE_VERSION, 5, 0, 0,
       BUS_WIRE_ERR_CORRELATION},
      {"request without correlation", BUS_F_REQUEST, BUS_WIRE_VERSION, 0, 0, 0,
       BUS_WIRE_ERR_CORRELATION},
      {"reply without correlation", BUS_F_REPLY, BUS_WIRE_VERSION, 0, 0, 0,
       BUS_WIRE_ERR_CORRELATION},
      {"cancel without correlation", BUS_F_CANCEL, BUS_WIRE_VERSION, 0, 0, 0,
       BUS_WIRE_ERR_CORRELATION},
   };

   for (size_t i = 0; i < sizeof cases / sizeof cases[0]; i++)
   {
      bus_frame_t f = base_frame();
      f.hdr_flags = cases[i].flags;
      f.wire_version = cases[i].ver;
      f.correlation_id = cases[i].corr;
      f.payload_ref = cases[i].pref;
      f.payload_len = cases[i].plen;
      encode_unchecked(&f, bad);
      expect_reject(cases[i].what, bad, sizeof bad, cases[i].want);
      /* The encoder must refuse exactly what the decoder refuses, so a caller
       * cannot build a frame this process would then reject. */
      uint8_t scratch[BUS_WIRE_HDR_LEN];
      assert(bus_wire_encode(&f, scratch, sizeof scratch) == 0);
   }

   assert(bus_wire_encode(&good, buf, BUS_WIRE_HDR_LEN - 1) == 0);

   printf("  rejections: %zu malformed shapes + %d truncations, encoder agrees\n",
          sizeof cases / sizeof cases[0] + 2, BUS_WIRE_HDR_LEN);
}

int main(void)
{
   printf("test_bus_wire:\n");
   verify_vectors();
   test_pattern_matrix();
   test_rejections();
   printf("test_bus_wire: OK\n");
   return 0;
}
