from pathlib import Path
from html import escape
out=Path(__file__).resolve().parent
class Diagram:
 def __init__(self,w,h,title,desc):
  self.w=w;self.h=h;self.parts=[f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}" role="img" aria-labelledby="title desc"><title id="title">{escape(title)}</title><desc id="desc">{escape(desc)}</desc><defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8" fill="#52657a"/></marker></defs><rect width="100%" height="100%" fill="#ffffff"/><style>text{{font-family:DejaVu Sans,Arial,sans-serif;fill:#172b40}}.title{{font-size:23px;font-weight:700}}.label{{font-size:17px;font-weight:600}}.body{{font-size:15px}}.edge{{font-size:14px;fill:#394d62}}</style>']; self.text(w/2,32,title,'title')
 def text(self,x,y,t,cls='body',anchor='middle'):self.parts.append(f'<text class="{cls}" x="{x}" y="{y}" text-anchor="{anchor}">{escape(t)}</text>')
 def box(self,x,y,w,h,title,lines=(),color='#edf4fa',dashed=False):
  dash=' stroke-dasharray="7 5"' if dashed else ''
  self.parts.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="10" fill="{color}" stroke="#9ab0c5" stroke-width="1.5"{dash}/>');self.text(x+w/2,y+28,title,'label')
  for i,line in enumerate(lines):self.text(x+w/2,y+54+23*i,line)
 def group(self,x,y,w,h,title):
  self.parts.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="14" fill="#f8fafc" stroke="#c8d3df" stroke-width="2"/>');self.text(x+18,y+28,title,'label','start')
 def arrow(self,pts,label='',lx=None,ly=None,dashed=False):
  dash=' stroke-dasharray="6 4"' if dashed else ''
  p=' '.join(f'{x},{y}' for x,y in pts);self.parts.append(f'<polyline points="{p}" fill="none" stroke="#52657a" stroke-width="2" marker-end="url(#arrow)"{dash}/>')
  if label:self.text(lx,ly,label,'edge')
 def save(self,name): (out/name).write_text('\n'.join(self.parts+['</svg>'])+'\n')
d=Diagram(1160,630,'One personal runtime, optional shared knowledge','Enrolled tools use Server. Server owns personal runtime and memory, local PostgreSQL, embedding and optional synthesis. KB is independent. Cognee replaces retrieval through the existing governed path.')
d.box(25,170,230,130,'Your clients',['CLI · MCP · ACP','Coding tools · browser','Enrolled / scoped access'])
d.box(350,110,370,240,'Server: one runtime owner',['Sessions · private code · memory','Tools · delegates · workflows','C resource host + event bus','Supervised Go modules'])
d.arrow([(255,230),(350,230)],'TLS / local UDS',302,205)
d.box(830,90,300,100,'Server PostgreSQL',['Runtime + canonical personal data'])
d.arrow([(720,155),(830,155)],'local bus / SQL',775,140)
d.box(830,235,300,105,'Model services',['Embedding · optional synthesis','Local or configured remote roles'])
d.arrow([(720,290),(830,290)],'governed calls',775,275)
d.box(350,425,370,130,'Optional independent KB',['Shared corpus · facts · documents','Own identity, Vault, bus and store','Explicit shared requests only'],dashed=True)
d.arrow([(535,350),(535,425)],'authenticated /v1',625,395)
d.box(830,425,300,130,'Optional Cognee retrieval',['Selected by memory contract','Existing egress + Vault transport','Aimee keeps canonical ownership'],dashed=True)
d.arrow([(690,350),(775,385),(775,490),(830,490)],'selected engine',868,393,dashed=True)
d.text(580,605,'Server and KB remain separate roles. Parent-node federation is separate design work.');d.save('overview.svg')
d=Diagram(1240,765,'Processes and storage in the current composition','Server and KB each run a C resource host and bus, a Go role supervisor and module fleet. The Go PostgreSQL provider reaches a separate database. WORM evidence is separate from canonical storage.')
for x,role,host,domain,db in [(25,'Server instance','aimee-server','aimee domain · memory · tools','Runtime + personal memory'),(645,'Optional KB instance','aimee-kb','memory · knowledge modules','Shared corpus + vectors')]:
 d.group(x,60,570,660,role+' · separate home / Vault / identity')
 d.box(x+30,110,300,95,host,['C resource API and authentication','Mechanical enforcement / transport'])
 d.box(x+355,110,185,95,'Go role supervisor',[role.lower().split()[0], 'Supervises module fleet'])
 d.box(x+30,250,510,65,'C event-bus host',['Admitted principals, grants, bounded frames'])
 d.arrow([(x+180,205),(x+180,250)],'requests',x+230,234)
 d.box(x+30,365,300,95,'Go process modules',[domain,'Policy and bounded domain behavior'])
 d.arrow([(x+180,315),(x+180,365)],'typed module events',x+270,345)
 d.box(x+355,365,185,95,'Go postgres',['SQL / transactions','Migration transport'])
 d.arrow([(x+330,390),(x+355,390)])
 d.text(x+310,486,'Module SQL crosses the local bus; no native libpq pool.','edge')
 d.box(x+355,510,185,95,'PostgreSQL 18',[('Runtime + personal' if role=='Server instance' else 'Shared corpus + vectors'),'Canonical source data'])
 d.arrow([(x+447,460),(x+447,510)])
 d.box(x+30,510,300,95,'Role-specific peer',[('aimee-wfe: workflow lifecycle' if role=='Server instance' else 'aimee-kb-worm: outbox delivery'),('Workflow lifecycle writer' if role=='Server instance' else 'Evidence chain writer')])
 d.box(x+30,635,510,60,'Separate WORM evidence',['Tap observations and mutation delivery are distinct milestones'])
 if role!='Server instance':d.arrow([(x+180,605),(x+180,635)])
 else:d.arrow([(x+30,280),(x+15,280),(x+15,665),(x+30,665)],dashed=True)
d.text(620,748,'26 Go process identities in the catalog; required and optional placement determines what runs.');d.save('processes.svg')
d=Diagram(1160,650,'Replaceable memory, fixed Aimee guarantees','The existing memory owner applies admission, scope, identity and lifecycle. Native and Cognee adhere to a generic Store contract. Cognee indexes derived datasets and returns identities revalidated against Aimee canonical records.')
d.box(25,90,240,120,'Authenticated request',['Store / scope / principal','Existing C host and module bus'])
d.box(355,75,395,150,'Aimee memory owner',['Authorization · identity · versions','Audit · lifecycle · cancellation','Generic Store + optional cleanup'])
d.arrow([(265,150),(355,150)])
d.box(865,90,270,120,'Canonical Aimee records',['Existing PostgreSQL provider','Authoritative source + revisions'])
d.arrow([(750,150),(865,150)],'source reads / writes',808,130)
d.box(135,320,320,115,'Native engine (default)',['Existing storage / retrieval modules','Extended native contracts remain'])
d.box(650,320,390,115,'Cognee adapter (selected alternative)',['Generic contract, scoped revision datasets','Returned identities checked against source'])
d.arrow([(480,225),(480,272),(295,272),(295,320)],'backend factory',326,255)
d.arrow([(625,225),(625,272),(845,272),(845,320)],'backend factory',823,255)
d.box(650,490,390,115,'Existing egress + Vault → Cognee',['Bounded add / cognify / search / cleanup','Cognee is derived state; no new authority'])
d.arrow([(845,435),(845,490)])
d.text(580,633,'A replacement engine does not acquire another placement, caller authority or canonical identity.');d.save('memory-backends.svg')
d=Diagram(1240,440,'Erasure completes only after the selected memory owner is clean','The existing subject-erasure workflow records canonical erasure, completes receipt replay, invokes provider cleanup and acknowledges verified completion. Failed cleanup uses the existing journal and request ID. Startup resets restored derived state before readiness.')
d.box(20,100,230,125,'Existing erasure request',['Authenticated subject','Stable request ID / journal'])
d.parts.append('<style>.label{font-size:15px}</style>')
d.box(340,100,250,125,'Canonical erasure + replay',['Existing owners / transactions','Existing request journal','Retained other sources survive'])
d.box(680,100,240,125,'Clean derived provider state',['Native: no external state','Cognee: reset node namespace','Verify managed live absence'])
d.box(1010,100,210,125,'Completion coverage',['Acknowledge only success','Repeat is idempotent'])
for a,b in [(250,340),(590,680),(920,1010)]:d.arrow([(a,155),(b,155)])
d.arrow([(800,225),(800,280),(135,280),(135,225)],'cleanup failure: same request retries, no completed coverage',490,310,dashed=True)
d.box(270,345,710,70,'Memory startup / restore',['Canonical replay → selected provider reset → readiness'])
d.save('memory-erasure.svg')
d=Diagram(1160,590,'Deploy and recover each role independently','The standard Server project has application, PostgreSQL and embedding services; synthesis is optional. KB uses a distinct project and matched backups. Cognee is an optional independent derived store reached by governed egress.')
for x,title in [(25,'Server Compose project'),(605,'Optional separate KB project')]:
 d.group(x,65,530,390,title)
 d.box(x+25,120,480,100,'Application image · immutable role',['Local home / identity / Vault / audit','Role supervisor + native host + Go module fleet'])
 d.box(x+25,285,225,100,'PostgreSQL service',['Persistent volume','Plain default; LUKS opt-in'])
 d.box(x+280,285,225,100,'Model sidecars',['Embedding','Synthesis optional'])
 d.arrow([(x+137,220),(x+137,285)])
 d.arrow([(x+392,220),(x+392,285)])
 d.text(x+265,431,'Back up home, Vault, store and audit as a matched set.','edge')
d.arrow([(555,171),(605,171)],'/v1',580,150,dashed=True)
d.box(160,490,840,70,'Optional Cognee service / alternative retrieval engine',['Separate durable provider state and credentials; source ownership stays in Aimee'])
d.save('deployment.svg')

d=Diagram(1160,490,'Selected records become attention memory on the inference host','An enrolled vLLM plugin requests the Aimee native primitive. Aimee authorizes and selects canonical records through its memory owner. The inference host prepares model-specific banks and uses them in native attention. Storage engine selection is independent.')
d.box(30,105,300,130,'Aimee instance',['Canonical source records','Authorization + memory selection','Native primitive endpoint'])
d.box(435,105,300,130,'Enrolled plugin client',['Existing thin-client identity','TLS trust + current bearer','No separate credential copy'])
d.arrow([(435,170),(330,170)],'authenticated request',381,83)
d.box(830,105,300,130,'Inference host',['Model weights + tokenizer','Local preparation and bank cache','Model-specific native attention'])
d.arrow([(735,170),(830,170)],'selected records',783,83)
d.box(235,330,690,90,'Independent choices',['Memory backend: native or Cognee retrieval contract','Model plugin: separately staged vLLM attention integration'])
d.text(580,470,'Aimee does not download the inference model. Selected records are not added as chat messages.');d.save('native-attention.svg')
