/* cli_dispatch_defs_data.h: THE CLI dispatch rows.
 *
 * `aimee <group> <verb>` -> the method the server routes, plus the response
 * field to extract and a per-command timeout. These were compiled into the thin
 * client, which meant a command added server-side could not be INVOKED from an
 * existing client even once its route and help were served: the client had no
 * row mapping the words the user typed to a method.
 *
 * They now live with the server and ride the CLI manifest. The client keeps a
 * copy compiled from THIS FILE as a last resort so dispatch still works with no
 * server reachable, but a served row always wins.
 *
 * Kept as an include rather than inlined so the owning TUs stay under the
 * source line-count limit. Included inside an array initializer; the row type
 * lives with each includer.
 */
{"init", "", "init.run", NULL, NULL, 0}, {"doctor", "forensics", "doctor.forensics", NULL, NULL, 0},
    {"memory", "search", "memory.search", NULL, NULL, 60000},
    {"memory", "recall", "memory.recall", NULL, NULL, 60000},
    {"memory", "store", "memory.store", NULL, NULL, 60000},
    {"memory", "identity", "memory.identity", "memory.user_capture", NULL, 60000},
    {"memory", "prefer", "memory.prefer", "memory.user_capture", NULL, 60000},
    {"memory", "archive", "memory.archive", "memory.user_capture", NULL, 60000},
    {"memory", "list", "memory.list", NULL, "memories", 60000},
    {"memory", "get", "memory.get", NULL, NULL, 60000},
    {"memory", "delete", "memory.delete", NULL, NULL, 60000},
    {"memory", "supersede", "memory.supersede", NULL, NULL, 60000},
    {"memory", "show", "memory.get", NULL, NULL, 60000},
    {"memory", "read", "memory.read", NULL, NULL, 60000},
    {"memory", "embed", "memory.embed", NULL, NULL, 900000},
    {"memory", "stats", "memory.stats", NULL, NULL, 60000},
    {"economizer", "stats", "economizer.stats", NULL, NULL, 60000},
    {"memory", "benchmark", "memory.benchmark", NULL, NULL, 600000},
    {"index", "scan", "index.scan", NULL, NULL, 300000},
    {"index", "verify", "index.verify", NULL, NULL, 300000},
    {"index", "overview", "index.list", NULL, "projects", 0},
    {"index", "list", "index.list", NULL, "projects", 0},
    {"index", "find", "index.find", NULL, NULL, 0},
    {"curator", "implements", "curator.implements", NULL, NULL, 0},
    {"curator", "synthesize", "curator.synthesize", NULL, NULL, 0},
    {"curator", "contradictions", "curator.contradictions", NULL, NULL, 0},
    {"index", "blast-radius", "index.blast_radius", NULL, NULL, 0},
    /* Structural search is the same server capability exposed by MCP. Keeping
     * this as mcp.call avoids a second implementation while making CLI the
     * preferred, chainable surface. */
    {"index", "ast-grep", "index.ast_grep", "mcp.call", NULL, 60000},
    {"index", "structure", "index.structure", NULL, NULL, 0},
    {"index", "span", "index.span", NULL, NULL, 0},
    {"index", "investigate", "index.investigate", NULL, NULL, 0},
    {"index", "hybrid", "index.hybrid", NULL, NULL, 0},
    {"index", "callers", "index.find_callers", NULL, NULL, 0},
    {"index", "deps", "index.deps", NULL, NULL, 0},
    {"workspace", "add", "workspace.add", NULL, NULL, 300000},
    {"workspace", "list", "workspace.list", NULL, NULL, 0},
    {"workspace", "get", "workspace.get", NULL, NULL, 0},
    {"workspace", "remove", "workspace.remove", NULL, NULL, 0},
    {"workspace", "mirror-sync", "workspace.mirror-sync", NULL, NULL, 60000},
    {"graph", "sync-code", "graph.sync_code", NULL, NULL, 300000},
    {"graph", "explain", "graph.explain", NULL, NULL, 60000},
    {"notes", "search", "notes.search", NULL, "notes", 0},
    /* "" not NULL: notes.list takes no arguments (marshal_no_args), so a NULL
       row -- which matches ANY subcommand and then discards it -- turned every
       unrecognised word into a listing. `aimee notes add "a thing worth
       keeping"` printed the notes and added nothing, with no hint that `add`
       is not a subcommand. The empty form still matches the bare command and
       its flags, and lets anything else fall through to the "not a subcommand
       of 'notes'; try: search" that every other command already gives. */
    {"notes", "", "notes.list", NULL, "notes", 0},
    {"session", "list", "session.list", NULL, "sessions", 0},
    {"session", "show", "session.get", NULL, NULL, 0},
    {"session", "get", "session.get", NULL, NULL, 0},
    {"session", "close", "session.close", NULL, NULL, 0},
    {"session", "brief", "session.brief", NULL, NULL, 0},
    {"session", "attach", "session.attach", NULL, NULL, 0},
    {"session", "detach", "session.detach", NULL, NULL, 0},
    {"presence", NULL, "session.presence", NULL, "presences", 0},
    {"trajectory", "export", "trajectory.export", NULL, NULL, 0},
    {"trajectory", "batch", "trajectory.batch", NULL, NULL, 900000},
    {"rules", "list", "rules.list", NULL, "rules", 0},
    {"rules", "generate", "rules.generate", NULL, NULL, 0},
    {"rules", "delete", "rules.delete", NULL, NULL, 0},
    {"skill", "list", "skill.list", NULL, "skills", 0},
    {"skill", "show", "skill.show", NULL, NULL, 0}, {"skill", "lint", "skill.lint", NULL, NULL, 0},
    {"skill", "eval", "skill.eval", NULL, NULL, 0},
    {"skill", "create", "skill.create", NULL, NULL, 0},
    {"skill", "edit", "skill.edit", NULL, NULL, 0},
    {"skill", "patch", "skill.patch", NULL, NULL, 0},
    {"skill", "archive", "skill.archive", NULL, NULL, 0},
    {"skill", "lifecycle", "skill.lifecycle", NULL, NULL, 0},
    {"skill", "autostub", "skill.autostub", NULL, NULL, 60000},
    {"skill", "pin", "skill.pin", NULL, NULL, 0}, {"skill", "unpin", "skill.unpin", NULL, NULL, 0},
    {"toolset", "list", "toolset.list", NULL, "toolsets", 0},
    {"toolset", "show", "toolset.show", NULL, NULL, 0},
    {"toolset", "resolve", "toolset.resolve", NULL, "tools", 0},
    {"wm", "set", "wm.set", NULL, NULL, 0}, {"wm", "get", "wm.get", NULL, NULL, 0},
    {"wm", "list", "wm.list", NULL, "entries", 0}, {"primary", NULL, "primary.set", NULL, NULL, 0},
    {"kb", "search", "kb.search", NULL, NULL, 60000},
    {"kb", "build", "kb.build", NULL, NULL, 900000},
    {"kb", "update", "kb.update", NULL, NULL, 900000},
    {"kb", "docs push", "kb.docs.push", NULL, NULL, 900000},
    /* Grant administration. `show` maps to the same method as `list` — it is that listing
     * filtered to one subject, so there is one row shape and one route. */
    /* A DISTINCT method from `list`, resolving to the same route. Sharing the method would
     * leave the marshaller unable to require --subject, and `show` with no subject would
     * silently list everything. */
    {"kb", "ingest", "kb.ingest", NULL, NULL, 30000},
    {"kb", "ingest status", "kb.ingest.status", NULL, NULL, 0},
    {"kb", "reembed", "kb.reembed", NULL, NULL, 900000},
    {"kb", "health", "kb.health", NULL, NULL, 0}, {"kb", "status", "kb.status", NULL, NULL, 0},
    {"kb", "curator status", "kb.curator", NULL, NULL, 0},
    {"kb", "curator", "kb.curator", NULL, NULL, 0},
    {"kb", "calibrate", "calibration.readiness", NULL, NULL, 0},
    {"kb", "demote", "demotion.check", NULL, NULL, 0},
    {"kb", "ranker export-view", "ranker.export_view", NULL, NULL, 0},
    {"kb", "ranker fit", "ranker.fit", NULL, NULL, 900000},
    {"workers", "", "workers", NULL, NULL, 0},
    {"insights", NULL, "insights.overview", NULL, NULL, 0},
    {"worktree", "gc", "worktree.gc", NULL, NULL, 60000},
    {"pipeline", "start", "pipeline.start", NULL, NULL, 60000},
    {"pipeline", "status", "pipeline.status", NULL, NULL, 0},
    {"pipeline", "list", "pipeline.list", NULL, NULL, 0},
    {"pipeline", "cancel", "pipeline.cancel", NULL, NULL, 0},
    {"pipeline", "resume", "pipeline.resume", NULL, NULL, 0},
    {"pipeline", "advance", "pipeline.advance", NULL, NULL, 300000},
    {"pipeline", "gate", "pipeline.gate", NULL, NULL, 300000},
    {"delegate", "launch", "delegate.launch", NULL, NULL, 300000},
    {"delegate", "status", "delegate.status", NULL, NULL, 0},
    {"delegate", "--list-roles", "model.list", NULL, "agents", 0},
    {"delegate", "log", "delegate.log", NULL, "episodes", 0},
    {"delegate", "history", "delegate.log", NULL, "episodes", 0},
    {"delegate", "sandbox list", "delegate.sandbox_list", NULL, "images", 0},
    {"delegate", "sandbox gc", "delegate.sandbox_gc", NULL, NULL, 60000},
    /* MoA ensemble aggregate: positional[0] is the PROMPT (not a role). Async —
     * forwards to POST /v1/delegate/aggregate and polls GET /v1/runs/{id}. This
     * specific route is what makes `aimee delegate aggregate "<prompt>"` reach the
     * ensemble; without it the prompt fell through to the catch-all delegate
     * route, which maps positional[0] -> role and never ran the engine. */
    {"delegate", "aggregate", "delegate.aggregate", NULL, NULL, 600000},
    {"roundtable", "review", "roundtable.review", NULL, NULL, 900000},
    {"ensemble", "aggregate", "delegate.aggregate", NULL, NULL, 600000},
    /* Codex/openai delegate agents have agent->timeout_ms == 900000 server-side.
     * The CLI must outlast that, otherwise we report "no response" while the
     * server is still genuinely working. */
    {"delegate", NULL, "delegate", NULL, NULL, 900000},
    {"jobs", "list", "jobs.list", NULL, "jobs", 0},
    {"jobs", "status", "jobs.status", NULL, NULL, 0},
    {"jobs", "show", "jobs.status", NULL, NULL, 0}, {"jobs", "log", "jobs.logs", NULL, NULL, 0},
    {"jobs", "logs", "jobs.logs", NULL, NULL, 0}, {"jobs", "cancel", "jobs.cancel", NULL, NULL, 0},
    {"job", "start", "job.start", NULL, NULL, 0}, {"job", "list", "job.list", NULL, "jobs", 0},
    {"job", "status", "job.status", NULL, NULL, 0}, {"job", "show", "job.status", NULL, NULL, 0},
    {"job", "cancel", "job.cancel", NULL, NULL, 0},
    {"aux", "config show", "aux.config_show", NULL, NULL, 0},
    {"aux", "config", "aux.config_show", NULL, NULL, 0},
    {"aux", "test", "aux.test", NULL, NULL, 300000}, {"aux", "", "aux.config_show", NULL, NULL, 0},
    {"config", "show", "config.show", NULL, NULL, 0},
    {"config", "get", "config.get", NULL, NULL, 0},
    {"config", "deploy-env", "config.deploy_env", NULL, NULL, 0},
    {"config", "set", "config.set", NULL, NULL, 0}, {"config", "", "config.show", NULL, NULL, 0},
    {"vault", "unlock", "vault.unlock", NULL, NULL, 0},
    {"vault", "set", "vault.set", NULL, NULL, 0},
    {"vault", "set-server", "vault.set_server", NULL, NULL, 0},
    {"vault", "capability", "vault.capability", NULL, NULL, 0},
    {"vault", "list", "vault.list", NULL, "credentials", 0},
    {"vault", "delete", "vault.delete", NULL, NULL, 0},
    {"vault", "lock", "vault.lock", NULL, NULL, 0}, {"cert", "issue", "cert.issue", NULL, NULL, 0},
    {"cert", "list", "cert.list", NULL, "certs", 0},
    {"cert", "revoke", "cert.revoke", NULL, NULL, 0},
    {"episode", "list", "episode.list", NULL, "episodes", 0},
    {"trigger", "list", "trigger.list", NULL, "triggers", 0},
    {"trigger", "status", "trigger.status", NULL, NULL, 0},
    {"trigger", "cancel", "trigger.cancel", NULL, NULL, 0},
    {"trigger", "fire", "trigger.fire", NULL, NULL, 0},
    {"cron", "list", "cron.list", NULL, "jobs", 0}, {"cron", "add", "cron.add", NULL, NULL, 0},
    {"cron", "show", "cron.show", NULL, NULL, 0},
    {"cron", "history", "cron.history", NULL, "runs", 0},
    {"cron", "run", "cron.run", NULL, NULL, 60000},
    {"cron", "enable", "cron.enable", NULL, NULL, 0},
    {"cron", "disable", "cron.disable", NULL, NULL, 0},
    {"cron", "remove", "cron.remove", NULL, NULL, 0},
    {"model", "list", "model.list", NULL, "agents", 0},
    {"audit", "verify", "audit.verify", NULL, NULL, 0},
    {"audit", "checkpoint", "audit.checkpoint", NULL, NULL, 0},
    {"audit", "seal", "audit.seal", NULL, NULL, 0},
    {"audit", "snapshot", "audit.snapshot", NULL, NULL, 0},
    {"audit", "", "audit.verify", NULL, NULL, 0},
    {"model", "episodes", "model.episodes", NULL, "episodes", 0},
    {"model", "add", "model.add", NULL, NULL, 300000},
    {"model", "local", "model.local", NULL, NULL, 300000},
    {"model", "remove", "model.remove", NULL, NULL, 0},
    {"model", "enable", "model.enable", NULL, NULL, 0},
    {"model", "roles", "model.roles", NULL, NULL, 0},
    {"model", "personas", "model.personas", NULL, NULL, 0},
    {"model", "disable", "model.disable", NULL, NULL, 0},
    {"model", "probe", "model.probe", NULL, NULL, 300000},
    /* Deprecated alias: the roster tab and its ops were called "agent" before
     * they were named for what a roster entry actually is -- one model. Kept so
     * existing scripts keep working; both spellings reach the same ops. */
    {"agent", "list", "model.list", NULL, "agents", 0},
    {"agent", "episodes", "model.episodes", NULL, "episodes", 0},
    {"agent", "add", "model.add", NULL, NULL, 300000},
    {"agent", "local", "model.local", NULL, NULL, 300000},
    {"agent", "set", "model.set", NULL, NULL, 0},
    {"agent", "remove", "model.remove", NULL, NULL, 0},
    {"agent", "enable", "model.enable", NULL, NULL, 0},
    {"agent", "roles", "model.roles", NULL, NULL, 0},
    {"agent", "personas", "model.personas", NULL, NULL, 0},
    {"agent", "disable", "model.disable", NULL, NULL, 0},
    {"agent", "probe", "model.probe", NULL, NULL, 300000},
    {"mcp", "audit", "mcp.audit", NULL, "items", 0},
    {"mcp", "recheck", "mcp.recheck", NULL, "items", 300000},
    /* Universal CLI projection of the MCP dispatch table. Every MCP tool is
     * callable through this route, even before it receives an ergonomic alias. */
    {"tool", "call", "tool.call", "mcp.call", NULL, 300000},
    {"audit", "trace", "evidence.trace_retrieval_event", NULL, NULL, 0},
    {"audit", "provenance", "evidence.provenance_retrieval_event", NULL, NULL, 0},
    {"audit", "fidelity", "evidence.fidelity_retrieval_event", NULL, NULL, 0},
    {"get_help", NULL, "get_help", "help.get", NULL, 0},
    {"get-help", NULL, "get_help", "help.get", NULL, 0},
    {"verify", NULL, "git.verify", "mcp.call", NULL, 900000},
    {"git", "verify", "git.verify", "mcp.call", NULL, 900000},
    /* Every other git subcommand, wildcard so `aimee git <anything>` reaches the
     * server's git tool instead of "not a subcommand of 'git'". MUST stay after
     * the verify row: pass 2 takes the first match, and verify has its own
     * marshaler (--status, async=). Wildcard also means argv[0] is the
     * subcommand, which is what marshal_git_cli needs to pick the tool. */
    {"git", NULL, "git.cli", "mcp.call", NULL, 300000},
    {"provider", "list", "provider.list", NULL, "providers", 300000},
    {"provider", "show", "provider.show", NULL, NULL, 0},
    {"provider", "models", "provider.models", NULL, "models", 300000},
    {"provider", "test", "provider.test", NULL, NULL, 300000},
    {"provider", "quota", "provider.quota", NULL, NULL, 0},
    {"provider", "", "provider.get", NULL, NULL, 0},
    {"provider", NULL, "provider.set", NULL, NULL, 0}, {"use", NULL, "provider.set", NULL, NULL, 0},
    /* The model CAPABILITY CATALOG (what a model can do: context window,
     * pricing, flags). Distinct from the model ROSTER (`aimee model`),
     * which is the configured fleet. */
    {"catalog", "list", "catalog.list", NULL, "models", 0},
    {"catalog", "show", "catalog.show", NULL, NULL, 0},
    {"catalog", "refresh", "catalog.refresh", NULL, NULL, 300000},
    {"server", "status", "server.health", NULL, NULL, 0},
    {"server", "health", "server.health", NULL, NULL, 0},
    {"status", "", "server.health", NULL, NULL, 0}, {"api", "status", "api.status", NULL, NULL, 0},
    {"api", "enable", "api.enable", NULL, NULL, 0},
    {"api", "disable", "api.disable", NULL, NULL, 0}, {"api", "", "api.status", NULL, NULL, 0},
    {"hud", "", "hud.status", NULL, NULL, 0}, {"dogfood", "tag", "dogfood.tag", NULL, NULL, 0},
    /* Month-scale dogfood logs can take longer than the default request timeout. */
    {"dogfood", "review", "dogfood.review", NULL, NULL, 300000},
    {"dogfood", "report", "dogfood.report", NULL, NULL, 300000},
    {"eval", "run", "eval.run", NULL, NULL, 900000},
    {"eval", "results", "eval.results", NULL, NULL, 0},
    {"eval", "candidates", "eval.candidates", NULL, NULL, 0},
    {"eval", "candidates-update", "eval.candidates-update", NULL, NULL, 120000},
    {"learning", "approaches", "learning.approaches", NULL, NULL, 0},
    {"learning", "attribution", "learning.attribution", NULL, NULL, 0},
    {"learning", "resolve", "learning.resolve", NULL, NULL, 120000},
    {"learning", "fate", "learning.fate", NULL, NULL, 0},
    {"identity", "show", "identity.show", NULL, NULL, 0},
    {"identity", "snapshot", "identity.snapshot", NULL, NULL, 0},
    {"identity", "diff", "identity.diff", NULL, NULL, 0},
    {"delegate-backend", "list", "delegate.backend_list", NULL, "backends", 0},
    {"delegate-backend", "exec", "delegate.backend_exec", NULL, NULL, 90000},
    {NULL, NULL, NULL, NULL, NULL, 0},
