/* Generated by scripts/gen_db2_contract.py; do not edit. */
#ifndef AIMEE_DB2_CLIENT_H
#define AIMEE_DB2_CLIENT_H 1

#include <stdint.h>

#include <aimee/core/event_bus/module_client.h>
#include <aimee/db2/module_api.h>

#ifdef __cplusplus
extern "C"
{
#endif

   typedef aimee_module_call_result_t (*aimee_db2_call_fn)(
       void *context, uint32_t event_kind, uint32_t stage_id, uint64_t trace_id,
       uint64_t deadline_ns, const void *request_body, uint32_t request_len,
       void *response_body, uint32_t response_capacity, uint32_t *response_len,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_health_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       int *schema_ok, int *have_pg_trgm, int *kb_tables_ok,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_embedding_dimension_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *domain_result, uint32_t *dimension,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_level3_count_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_level2_count_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_orphaned_l0_count_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_total_count_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_session_l2_count_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *source_session, uint32_t *count,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_key_exists_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *key, uint32_t *exists, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_find_id_by_key_kind_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *key, const char *kind, uint32_t *found, uint64_t *id,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_key_exists_in_tier_pair_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *key, const char *tier_a, const char *tier_b, uint32_t *exists,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_effectiveness_update_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t memory_id, uint32_t has_value, double value, uint32_t *domain_result,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_retention_enforce_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *deleted_count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_effectiveness_demote_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *demoted_count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_effectiveness_stats_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       aimee_db2_effectiveness_stats_t *stats, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_l2_memory_ids_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_health_record_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t promotions, uint32_t demotions, uint32_t expirations,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_health_retention_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *snapshots_deleted, uint32_t *contradictions_deleted,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_health_counters_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       aimee_db2_health_counters_t *counters, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_stats_counts_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       aimee_db2_memory_stats_t *stats, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_expire_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *level0_deleted, uint32_t *stale_level1_deleted,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_demote_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *demoted_count, uint32_t *cascaded_count, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_promote_stable_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *promoted_count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_reclassify_directives_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t require_approval, uint32_t *reclassified_count,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_record_l4_approval_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t memory_id, const char *approver, const char *note,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_prune_orphaned_l0_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *deleted_count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_lifecycle_sweep_expired_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *archived_count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_demote_id_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t memory_id, uint32_t *demoted_count, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_has_workspace_tag_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t memory_id, uint32_t *tagged, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_delete_row_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t memory_id, uint32_t *deleted_rows, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_touch_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t memory_id, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_link_delete_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t link_id, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_valid_at_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t memory_id, const char *as_of, uint32_t *domain_result, uint32_t *in_force,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_has_scope_type_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t memory_id, const char *scope_type, uint32_t *present,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_reject_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t memory_id, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_update_content_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t memory_id, const char *content, uint32_t *updated_rows,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_decay_confidence_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t memory_id, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_workspace_tag_insert_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t memory_id, const char *workspace, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_set_cognified_kind_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t memory_id, const char *kind, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_set_source_session_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t memory_id, const char *session_id, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_negation_tokens_update_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t memory_id, const char *tokens, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_get_content_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t memory_id, uint32_t *domain_result, char *content, size_t content_capacity,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_get_source_session_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t memory_id, uint32_t *domain_result, char *session_id, size_t session_capacity,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_pick_first_temporal_ref_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t memory_id, uint32_t *domain_result, char *ref_key, size_t key_capacity,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_count_and_max_updated_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *domain_result, uint32_t *count, char *max_updated_at, size_t stamp_capacity,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   /* The scope travels with the request because the backend would otherwise
    * read it from a thread-local the caller cannot reach across a process
    * boundary. scope_flags is bit 0 active, bit 1 include-all. */
   aimee_module_call_result_t aimee_db2_top_l2_facts_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t limit, uint32_t scope_flags, const char *workspace, const char *project,
       uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_list_session_scope_priority_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t limit, uint32_t scope_flags, const char *workspace, const char *project,
       uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_collect_alias_matches_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *term, uint32_t limit, uint32_t scope_flags, const char *workspace,
       const char *project, uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_collect_entity_matches_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *term, uint32_t limit, uint32_t scope_flags, const char *workspace,
       const char *project, uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_collect_event_frame_matches_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *term, uint32_t limit, uint32_t scope_flags, const char *workspace,
       const char *project, uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_collect_relation_token_matches_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *term, uint32_t limit, uint32_t scope_flags, const char *workspace,
       const char *project, uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_collect_summary_matches_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *term, uint32_t limit, uint32_t scope_flags, const char *workspace,
       const char *project, uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_collect_temporal_matches_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *term, uint32_t limit, uint32_t scope_flags, const char *workspace,
       const char *project, uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_find_facts_like_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *term, uint32_t limit, uint32_t scope_flags, const char *workspace,
       const char *project, uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_list_session_scope_priority_like_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *term, uint32_t limit, uint32_t scope_flags, const char *workspace,
       const char *project, uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_negation_fts_search_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *term, uint32_t limit, uint32_t scope_flags, const char *workspace,
       const char *project, uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_session_neighbors_before_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *session_id, uint64_t anchor_id, uint32_t limit, uint64_t *memory_ids,
       uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_session_neighbors_after_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *session_id, uint64_t anchor_id, uint32_t limit, uint64_t *memory_ids,
       uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_row_get_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t memory_id, uint32_t *domain_result, aimee_db2_memory_row_t *row,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_row_get_by_unit_id_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t unit_id, uint32_t *domain_result, aimee_db2_memory_row_t *row,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_search_facts_patterns_by_keyword_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *term, uint32_t limit, uint32_t scope_flags, const char *workspace,
       const char *project, uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_fact_history_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *normalized_key, uint32_t limit, uint64_t *memory_ids, uint32_t capacity,
       uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_list_rows_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t limit, uint32_t scope_flags, uint32_t hide_archived, const char *tier,
       const char *kind, const char *workspace, const char *project, uint64_t *memory_ids,
       uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_aggregate_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *entity_seed, const char *keyword, uint32_t limit, uint32_t *truncated,
       uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_load_eval_corpus_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t limit, char *label, size_t label_capacity, uint64_t *memory_ids,
       uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_entity_edge_prune_orphans_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *pruned_count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_entity_edge_normalize_weights_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *normalized_count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_project_count_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *project_count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_purge_hidden_pollution_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *purged_count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_requeue_drifted_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *requeued_count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_cross_repo_rebuild_routes_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *route_count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_cross_repo_rebuild_identities_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *identities_written, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_cross_repo_rebuild_build_deps_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *build_deps_written, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_drift_candidates_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t *drift_candidates, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_rules_decay_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *rules_touched, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_curiosity_rescore_all_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *items_rescored, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_mining_seed_job_defaults_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_rel_types_ensure_seed_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_vector_rebuild_lock_try_acquire_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *acquired, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_vector_rebuild_lock_release_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_release_get_active_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t *release_id, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_proposals_archive_expired_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_trace_mining_last_id_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t *last_trace_id, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_prospective_sweep_expired_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *expired_count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_directive_sweep_expired_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *directives_expired, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_mark_revisit_due_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *marked_count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_ingest_queue_reset_running_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *reset_count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_evidence_reembed_all_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *requeued_rows, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_curator_reembed_all_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *demoted_artifacts, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_synth_reenqueue_all_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *reenqueued_ops, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_curator_reenqueue_extract_all_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *extract_jobs, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_directive_suppress_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t directive_id, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_anti_pattern_bump_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t anti_pattern_id, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_file_index_delete_project_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, uint32_t *deleted_entries, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_clear_project_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, uint32_t *deleted_documents, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_clear_current_project_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, uint32_t *deleted_documents, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_anti_pattern_delete_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t anti_pattern_id, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_doc_delete_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t doc_id, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_task_delete_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t task_id, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_directive_record_surface_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t directive_id, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_pool_status_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *domain_result, aimee_db2_pool_status_t *status,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_embedding_refusals_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *domain_result, aimee_db2_embedding_refusals_t *status,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_postgres_status_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *domain_result, aimee_db2_postgres_status_t *status,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_reembed_status_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *domain_result, aimee_db2_reembed_status_t *status,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_reembed_clear_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *domain_result, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_reembed_clear_maintenance_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t force, uint32_t *domain_result, aimee_db2_reembed_clear_maintenance_t *status,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_embedder_serving_id_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t *domain_result, char *serving_id, size_t serving_id_capacity,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_dimension_reset_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t target_dimension, uint32_t force, uint32_t dry_run, uint32_t *domain_result,
       aimee_db2_dimension_reset_t *status, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

#ifdef __cplusplus
}
#endif

   aimee_module_call_result_t aimee_db2_record_exists_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t record_id, uint32_t *exists, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_prospective_set_state_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t prospective_id, const char *new_state, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_dedupe_by_key_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t dry_run, uint32_t *merged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_scene_member_exists_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t scene_memory_id, uint64_t scene_id, uint32_t *member, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_unit_edge_exists_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t unit_id_a, uint64_t unit_id_b, uint32_t *connected, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_match_error_keys_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *error_lowered, aimee_db2_match_error_keys_row_t *rows, uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_memory_ids_by_updated_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t limit, aimee_db2_memory_ids_by_updated_row_t *rows, uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_unit_ids_for_memory_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t memory_id, aimee_db2_unit_ids_for_memory_row_t *rows, uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_entity_observation_count_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *entity_id, uint32_t *count, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_entity_profile_fresh_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *entity_id, const char *window, uint32_t *fresh,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_project_fingerprint_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, char *fingerprint, size_t fingerprint_capacity, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_visible_source_hash_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, char *source_hash, size_t source_hash_capacity, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_entity_profile_card_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *entity_id, char *card_json, size_t card_json_capacity, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_generation_abort_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t generation_id, const char *error_message, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_generation_set_source_hash_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t generation_id, const char *source_hash, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_generation_publish_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t generation_id, const char *project, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_purge_files_matching_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t project_id, const char *path_glob, uint32_t *deleted, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_file_index_delete_current_generation_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, uint32_t *deleted, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_project_delete_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, uint32_t *deleted, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_minhash_delete_current_generation_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_minhash_delete_file_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, const char *file_path, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_project_current_generation_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, uint64_t *generation, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_projection_generation_create_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, uint64_t *generation, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_projection_visible_id_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, uint64_t *generation, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_unique_file_basename_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, const char *basename, char *file_path, size_t file_path_capacity, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_entity_neighbors_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *entity, uint32_t limit, aimee_db2_entity_neighbors_row_t *rows, uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_entity_neighbors_filtered_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *entity, const char *relation_a, const char *relation_b, uint32_t order_by_weight, uint32_t limit, aimee_db2_entity_neighbors_filtered_row_t *rows, uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_entity_outbound_neighbors_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *entity, uint32_t limit, aimee_db2_entity_outbound_neighbors_row_t *rows, uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_entity_top_partners_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *entity, const char *relation, aimee_db2_entity_top_partners_row_t *rows, uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_entity_top_targets_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *entity, const char *relation, aimee_db2_entity_top_targets_row_t *rows, uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_file_definitions_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, const char *file_path, aimee_db2_file_definitions_row_t *rows, uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_trace_mining_record_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t last_trace_id, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_anti_pattern_exists_exact_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *pattern, uint32_t *exists, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_anti_pattern_exists_by_source_ref_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *source_ref, uint32_t *exists, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_artifact_citation_count_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *artifact_id, uint32_t *count, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_commits_in_last_7_days_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *sink, uint32_t *count, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_fidelity_attribution_count_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *turn_id, uint32_t *count, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_artifact_stamp_reflected_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *artifact_id, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_failed_query_bump_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *query_norm, uint32_t *count, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_artifact_set_state_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *state, const char *artifact_id, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_artifact_register_exemplar_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *artifact_id, const char *collection, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_evidence_enqueue_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *artifact_id, const char *collection, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_evidence_mark_failed_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *artifact_id, const char *last_error, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_bandit_arms_list_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *decision_point, char *arms, size_t arms_capacity, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_bandit_promotion_get_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *decision_point, char *arm_id, size_t arm_id_capacity, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_decision_log_set_outcome_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t decision_id, const char *outcome, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_decision_log_set_status_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t decision_id, const char *status, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_decision_log_set_revisit_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t decision_id, const char *revisit_when, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_collab_rule_approve_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t rule_id, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_collab_rule_reject_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t rule_id, uint32_t *changed, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_collab_rule_retire_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t rule_id, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_proposal_bump_corroboration_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t proposal_id, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_proposal_mark_committed_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t proposal_id, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_rules_delete_by_id_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t rule_row_id, uint32_t *deleted, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_calibration_surfaces_with_data_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t min_rows, uint32_t *surfaces, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_artifact_cite_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *citing_artifact_id, const char *source_kind, const char *source_id, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_artifact_link_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *from_artifact_id, const char *to_artifact_id, const char *link_kind, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_bandit_promotion_set_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *decision_point, const char *arm_id, const char *rollback_arm, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_collab_rule_propose_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *rule_text, const char *rule_reason, const char *proposed_by, uint32_t *rule_id, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_rules_delete_by_directive_type_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *directive_type, uint32_t *deleted, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_artifact_flag_review_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *artifact_id, const char *flag_reason, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_verdict_suppressed_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *verdict_tag, const char *verdict_scope, uint32_t *suppressed, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_curator_invalidate_doc_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, const char *file_path, uint32_t *invalidated, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_document_exists_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t document_id, uint32_t *exists, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_blob_referenced_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *blob_ref, uint32_t *referenced, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_fence_active_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, uint32_t *active, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_doc_exists_by_hash_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *content_hash, const char *scope, uint32_t *exists,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_pdf_quarantine_confirm_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, const char *file_path, uint32_t *confirmed,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_pdf_quarantine_reject_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, const char *file_path, uint32_t *rejected,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_ontology_eval_status_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *rel_type, char *status, size_t status_capacity, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_task_update_state_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t task_id, const char *state, uint32_t *changed, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_release_add_doc_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t release_id, uint64_t doc_id, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_ontology_approve_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *rel_type, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_ontology_reject_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *rel_type, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_doc_assets_delete_for_doc_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, const char *document_key, uint32_t *deleted, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_ontology_map_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *rel_type, const char *mapped_to, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_release_create_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *release_name, uint64_t *release_id, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_purge_fence_heartbeat_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, const char *generation, const char *purge_id, uint32_t *applied, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_purge_fence_clear_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, const char *generation, const char *purge_id, uint32_t *applied, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_document_stored_hash_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, const char *file_path, char *file_hash, size_t file_hash_capacity, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_document_hash_exists_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, const char *file_hash, uint32_t *exists, char *sample_path, size_t sample_path_capacity, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_pdf_tsr_state_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, const char *document_key, char *tsr_state, size_t tsr_state_capacity, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_document_chunk_ids_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, const char *file_path, aimee_db2_document_chunk_ids_row_t *rows, uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_enrollment_active_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *cert_issuer, const char *cert_serial_norm, uint32_t *active,
       aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_async_pending_count_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *kind, uint32_t *count, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_runtime_state_touch_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *state_key, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_synth_enqueue_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *artifact_id, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_synth_mark_done_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *artifact_id, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_reembed_mark_finished_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *finished_at, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_mining_job_try_lock_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *job_id, uint32_t *acquired, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_synth_mark_failed_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *artifact_id, const char *last_error, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_runtime_state_set_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *state_key, const char *state_value, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_set_active_embedder_version_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *version, const char *updated_at, aimee_module_cancelled_fn cancelled,
       void *cancel_context);

   aimee_module_call_result_t aimee_db2_runtime_state_get_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *state_key, char *state_value, size_t state_value_capacity, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_ingest_queue_fail_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t ingest_job_id, const char *error_message, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_reset_stuck_vector_ops_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t max_attempts, uint32_t *reset_rows, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_directive_resolve_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint64_t directive_id, uint64_t resolution_memory_id, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_css_migration_enumerate_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, uint32_t *enumerated, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_css_migration_assert_conventions_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *project, const char *now_iso, uint32_t *asserted, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_css_migration_rules_doc_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       const char *exemplar_project, char *rules_doc, size_t rules_doc_capacity, aimee_module_cancelled_fn cancelled, void *cancel_context);

   aimee_module_call_result_t aimee_db2_retryable_index_failures_call(
       aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
       uint32_t max_attempts, uint32_t limit, aimee_db2_retryable_index_failures_row_t *rows, uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context);

#endif /* AIMEE_DB2_CLIENT_H */
