FROM alpine:3.20@sha256:d9e853e87e55526f6b2917df91a2115c36dd7c696a35be12163d44e6e2a4b6bc
RUN apk add --no-cache sqlite-libs libpq openssl-libs-static
COPY aimee-proxy /usr/local/bin/
COPY aimee-proxy.yaml /etc/aimee/
EXPOSE 8400
CMD ["aimee-proxy", "--config", "/etc/aimee/aimee-proxy.yaml", "start"]
