/* Auto-generated by src/gen_config_accessors.py — do not edit directly.
 *
 * One accessor per config_t field. config_t is ~750 KB and its layout is a
 * config-module secret; callers outside the module ask for the value they
 * want and never name the type. Each reads a single field out of the live
 * snapshot under a reader pin, so a caller pays for one field rather than a
 * whole-struct copy.
 */

#include <stddef.h>
#include <stdio.h>
#include <string.h>

#include "config.h"
#include "config_accessors.h"

/* Defined in config.c: reads one field out of the pinned snapshot, falling
 * back to a heap-loaded config when no snapshot is live. */
int config_field_read(size_t offset, size_t size, void *dst);

int config_skills_stale_after_days(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, skills_stale_after_days), sizeof(v), &v);
   return v;
}

int config_skills_archive_after_days(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, skills_archive_after_days), sizeof(v), &v);
   return v;
}

int config_skills_dispatch_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, skills_dispatch_enabled), sizeof(v), &v);
   return v;
}

int config_skills_curator_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, skills_curator_enabled), sizeof(v), &v);
   return v;
}

int config_skills_curator_interval_hours(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, skills_curator_interval_hours), sizeof(v), &v);
   return v;
}

int config_skills_dispatch_max_index(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, skills_dispatch_max_index), sizeof(v), &v);
   return v;
}

int config_skills_dispatch_advisory(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, skills_dispatch_advisory), sizeof(v), &v);
   return v;
}

int config_skills_capability_autostub(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, skills_capability_autostub), sizeof(v), &v);
   return v;
}

int config_skills_eval_gate_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, skills_eval_gate_enabled), sizeof(v), &v);
   return v;
}

double config_skills_eval_threshold(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, skills_eval_threshold), sizeof(v), &v);
   return v;
}

int config_worktree_gc_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, worktree_gc_enabled), sizeof(v), &v);
   return v;
}

int config_worktree_gc_max_age_days(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, worktree_gc_max_age_days), sizeof(v), &v);
   return v;
}

int config_aux_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, aux_enabled), sizeof(v), &v);
   return v;
}

int config_aux_default_max_tokens(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, aux_default_max_tokens), sizeof(v), &v);
   return v;
}

int config_aux_task_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, aux_task_count), sizeof(v), &v);
   return v;
}

int config_prefer_local_agents(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, prefer_local_agents), sizeof(v), &v);
   return v;
}

int config_model_meta_refresh_minutes(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, model_meta_refresh_minutes), sizeof(v), &v);
   return v;
}

int config_model_meta_capability_routing(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, model_meta_capability_routing), sizeof(v), &v);
   return v;
}

int64_t config_db2_vector_corpus_diskann_threshold(void)
{
   int64_t v = 0;
   config_field_read(offsetof(config_t, db2_vector_corpus_diskann_threshold), sizeof(v), &v);
   return v;
}

int config_ensemble_reference_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, ensemble_reference_count), sizeof(v), &v);
   return v;
}

int config_ensemble_reference_persona_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, ensemble_reference_persona_count), sizeof(v), &v);
   return v;
}

int config_ensemble_min_successful(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, ensemble_min_successful), sizeof(v), &v);
   return v;
}

double config_ensemble_max_cost_usd(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, ensemble_max_cost_usd), sizeof(v), &v);
   return v;
}

int config_roundtable_max_rounds(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, roundtable_max_rounds), sizeof(v), &v);
   return v;
}

int config_roundtable_converge_threshold(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, roundtable_converge_threshold), sizeof(v), &v);
   return v;
}

int config_roundtable_deadline_ms(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, roundtable_deadline_ms), sizeof(v), &v);
   return v;
}

int config_roundtable_pipeline_max_passes(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, roundtable_pipeline_max_passes), sizeof(v), &v);
   return v;
}

int config_roundtable_pipeline_max_attempts_per_pass(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, roundtable_pipeline_max_attempts_per_pass), sizeof(v), &v);
   return v;
}

double config_roundtable_pipeline_max_cost_usd(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, roundtable_pipeline_max_cost_usd), sizeof(v), &v);
   return v;
}

double config_roundtable_pipeline_max_total_cost_usd(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, roundtable_pipeline_max_total_cost_usd), sizeof(v), &v);
   return v;
}

int config_roundtable_pipeline_gate_ttl_h(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, roundtable_pipeline_gate_ttl_h), sizeof(v), &v);
   return v;
}

int config_roundtable_pipeline_parked_releases_slot(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, roundtable_pipeline_parked_releases_slot), sizeof(v), &v);
   return v;
}

int config_roundtable_pipeline_unknown_context_tokens(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, roundtable_pipeline_unknown_context_tokens), sizeof(v), &v);
   return v;
}

const char *config_db1_path(void)
{
   static _Thread_local char buf[MAX_PATH_LEN];
   buf[0] = 0;
   config_field_read(offsetof(config_t, db1_path), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_db2_url(void)
{
   static _Thread_local char buf[CONFIG_DB2_URL_LEN];
   buf[0] = 0;
   config_field_read(offsetof(config_t, db2_url), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_provider(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, provider), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_default_persona(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, default_persona), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_claude_model(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, claude_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_codex_model(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, codex_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_model_reasoning_effort(void)
{
   static _Thread_local char buf[32];
   buf[0] = 0;
   config_field_read(offsetof(config_t, model_reasoning_effort), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_openai_endpoint(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, openai_endpoint), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_openai_model(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, openai_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_openai_key_cmd(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, openai_key_cmd), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_embedding_model(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, embedding_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_embedding_endpoint(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, embedding_endpoint), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_weight_profile(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_weight_profile), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_rerank_mode(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_rerank_mode), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_css_render_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, css_render_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_vault_custody(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, vault_custody), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_vault_tpm2_blob_path(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, vault_tpm2_blob_path), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_vault_tpm2_tcti(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, vault_tpm2_tcti), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_vault_tpm2_nv_index(void)
{
   static _Thread_local char buf[32];
   buf[0] = 0;
   config_field_read(offsetof(config_t, vault_tpm2_nv_index), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_coref_mode(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_coref_mode), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_cognify_model(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_cognify_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_cognify_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_cognify_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_delegate_sandbox_image(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, delegate_sandbox_image), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_delegate_sandbox_package_access(void)
{
   static _Thread_local char buf[32];
   buf[0] = 0;
   config_field_read(offsetof(config_t, delegate_sandbox_package_access), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_pdf_tier(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_pdf_tier), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_tsr_command(void)
{
   static _Thread_local char buf[1024];
   buf[0] = 0;
   config_field_read(offsetof(config_t, tsr_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_pdf_blob_dir(void)
{
   static _Thread_local char buf[1024];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_pdf_blob_dir), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_ocr_command(void)
{
   static _Thread_local char buf[1024];
   buf[0] = 0;
   config_field_read(offsetof(config_t, ocr_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_pagerank_relations(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_pagerank_relations), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_citations_mode(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_citations_mode), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_rewrite_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_rewrite_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_rerank_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_rerank_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_query_expansion_mode(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_query_expansion_mode), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_recall_lanes_summary_kinds(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_recall_lanes_summary_kinds), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_recall_lanes_fact_kinds(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_recall_lanes_fact_kinds), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_hard_negative_log(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_hard_negative_log), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_dogfood_log_dir(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, dogfood_log_dir), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_learning_synthesize_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, learning_synthesize_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_learning_embed_model_version(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, learning_embed_model_version), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_learning_synthesize_prompt_version(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, learning_synthesize_prompt_version), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_verify_cmd(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, verify_cmd), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_verify_role(void)
{
   static _Thread_local char buf[32];
   buf[0] = 0;
   config_field_read(offsetof(config_t, verify_role), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_verify_prompt(void)
{
   static _Thread_local char buf[2048];
   buf[0] = 0;
   config_field_read(offsetof(config_t, verify_prompt), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_search_backend(void)
{
   static _Thread_local char buf[32];
   buf[0] = 0;
   config_field_read(offsetof(config_t, search_backend), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_search_searxng_url(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, search_searxng_url), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_search_tavily_api_key(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, search_tavily_api_key), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_search_backends(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, search_backends), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_coord_closet_denylist(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, coord_closet_denylist), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_prompt_tier(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, prompt_tier), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_prompt_file(void)
{
   static _Thread_local char buf[MAX_PATH_LEN];
   buf[0] = 0;
   config_field_read(offsetof(config_t, prompt_file), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_delegate_prompt_tier(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, delegate_prompt_tier), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_otel_endpoint(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, otel_endpoint), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_otel_service_name(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, otel_service_name), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_mcp_osv_endpoint(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, mcp_osv_endpoint), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_computer_use_default_navigation(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, computer_use_default_navigation), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_proxy_url(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, proxy_url), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_proxy_token(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, proxy_token), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_ingress_trusted_proxy_secret(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, ingress_trusted_proxy_secret), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_guardrails_semantic_mode(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, guardrails_semantic_mode), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_guardrails_semantic_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, guardrails_semantic_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_api_bearer_token(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_api_bearer_token), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_telemetry_metrics_token(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, telemetry_metrics_token), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_client_url(void)
{
   static _Thread_local char buf[CONFIG_DB2_URL_LEN];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_client_url), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_client_bearer_token(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_client_bearer_token), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_mode(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_mode), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_llm_embed_backend(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, llm_embed_backend), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_llm_embed_host(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, llm_embed_host), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_llm_embed_gpu(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, llm_embed_gpu), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_llm_embed_tier(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, llm_embed_tier), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_llm_rerank_backend(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, llm_rerank_backend), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_llm_rerank_host(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, llm_rerank_host), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_llm_rerank_gpu(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, llm_rerank_gpu), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_llm_rerank_tier(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, llm_rerank_tier), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_llm_rerank_endpoint(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, llm_rerank_endpoint), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_llm_synth_backend(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, llm_synth_backend), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_llm_synth_host(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, llm_synth_host), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_llm_synth_gpu(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, llm_synth_gpu), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_llm_synth_tier(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, llm_synth_tier), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_llm_synth_endpoint(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, llm_synth_endpoint), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_llm_synth_model(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, llm_synth_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_server_api_mtls_client_ca(void)
{
   static _Thread_local char buf[MAX_PATH_LEN];
   buf[0] = 0;
   config_field_read(offsetof(config_t, server_api_mtls_client_ca), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_server_api_bearer_token(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, server_api_bearer_token), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_server_api_client_transport(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, server_api_client_transport), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_calibration_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, calibration_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_calibration_prompt_version(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, calibration_prompt_version), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_calibration_model_version(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, calibration_model_version), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_fusion_mode(void)
{
   static _Thread_local char buf[32];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_fusion_mode), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_ranker_fuse_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, ranker_fuse_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_ranker_fit_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_ranker_fit_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_ranker_fit_benchmark(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_ranker_fit_benchmark), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_ranker_fit_objective(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_ranker_fit_objective), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_reasoning_datalog_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, reasoning_datalog_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_bandit_optimize_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, bandit_optimize_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_planner_search_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, planner_search_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_constraint_solver_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, constraint_solver_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_synthesize_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_synthesize_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_trigger_auth_token(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, trigger_auth_token), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_tier(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_tier), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_extract_prompt_version(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_extract_prompt_version), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_embed_model_version(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_embed_model_version), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_invalidation_notify_socket(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_invalidation_notify_socket), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_extract_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_extract_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_stage_order(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_stage_order), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_user_presets(void)
{
   static _Thread_local char buf[4096];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_user_presets), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_custom_stages(void)
{
   static _Thread_local char buf[4096];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_custom_stages), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_provider_base_url(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_provider_base_url), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_provider_model(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_provider_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_provider_api_key(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_provider_api_key), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_tier_b_base_url(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_tier_b_base_url), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_tier_b_model(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_tier_b_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_tier_b_api_key(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_tier_b_api_key), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_judge_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_judge_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_synthesize_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_synthesize_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_aux_default_provider(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, aux_default_provider), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_aux_default_model(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, aux_default_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_db2_vector_corpus_index(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, db2_vector_corpus_index), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_ensemble_aggregator(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, ensemble_aggregator), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_roundtable_turns(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, roundtable_turns), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_roundtable_default(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, roundtable_default), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_roundtable_pipeline_done_bar(void)
{
   static _Thread_local char buf[40];
   buf[0] = 0;
   config_field_read(offsetof(config_t, roundtable_pipeline_done_bar), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_context_engine(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, context_engine), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_workspaces(int index)
{
   static _Thread_local char buf[MAX_PATH_LEN];
   buf[0] = 0;
   if (index < 0 || index >= (64))
      return buf;
   config_field_read(offsetof(config_t, workspaces) + (size_t)index * sizeof(buf), sizeof(buf),
                     buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_workspace_providers(int index)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   if (index < 0 || index >= (64))
      return buf;
   config_field_read(offsetof(config_t, workspace_providers) + (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_workspace_vcs_remote(int index)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   if (index < 0 || index >= (64))
      return buf;
   config_field_read(offsetof(config_t, workspace_vcs_remote) + (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_workspace_vcs_head(int index)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   if (index < 0 || index >= (64))
      return buf;
   config_field_read(offsetof(config_t, workspace_vcs_head) + (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_workspace_sandbox_image(int index)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   if (index < 0 || index >= (64))
      return buf;
   config_field_read(offsetof(config_t, workspace_sandbox_image) + (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_charter_safety_axioms(int index)
{
   static _Thread_local char buf[CONFIG_CHARTER_ENTRY_LEN];
   buf[0] = 0;
   if (index < 0 || index >= (CONFIG_CHARTER_MAX_ENTRIES))
      return buf;
   config_field_read(offsetof(config_t, charter_safety_axioms) + (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_charter_hard_constraints(int index)
{
   static _Thread_local char buf[CONFIG_CHARTER_ENTRY_LEN];
   buf[0] = 0;
   if (index < 0 || index >= (CONFIG_CHARTER_MAX_ENTRIES))
      return buf;
   config_field_read(offsetof(config_t, charter_hard_constraints) + (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_charter_values(int index)
{
   static _Thread_local char buf[CONFIG_CHARTER_ENTRY_LEN];
   buf[0] = 0;
   if (index < 0 || index >= (CONFIG_CHARTER_MAX_ENTRIES))
      return buf;
   config_field_read(offsetof(config_t, charter_values) + (size_t)index * sizeof(buf), sizeof(buf),
                     buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_charter_tone_boundaries(int index)
{
   static _Thread_local char buf[CONFIG_CHARTER_ENTRY_LEN];
   buf[0] = 0;
   if (index < 0 || index >= (CONFIG_CHARTER_MAX_ENTRIES))
      return buf;
   config_field_read(offsetof(config_t, charter_tone_boundaries) + (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_compact_per_tool(int index)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   if (index < 0 || index >= (CONFIG_COMPACT_MAX_PER_TOOL))
      return buf;
   config_field_read(offsetof(config_t, compact_per_tool) + (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_mcp_osv_allow(int index)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   if (index < 0 || index >= (CONFIG_MCP_OSV_MAX_ALLOW))
      return buf;
   config_field_read(offsetof(config_t, mcp_osv_allow) + (size_t)index * sizeof(buf), sizeof(buf),
                     buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_computer_use_allowed_domains(int index)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   if (index < 0 || index >= (CONFIG_COMPUTER_USE_MAX_DOMAINS))
      return buf;
   config_field_read(offsetof(config_t, computer_use_allowed_domains) + (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_ensemble_reference_models(int index)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   if (index < 0 || index >= (32))
      return buf;
   config_field_read(offsetof(config_t, ensemble_reference_models) + (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_ensemble_reference_personas(int index)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   if (index < 0 || index >= (32))
      return buf;
   config_field_read(offsetof(config_t, ensemble_reference_personas) + (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}
