#ifndef CLI_V1_ROUTES_INTERNAL_H
#define CLI_V1_ROUTES_INTERNAL_H
/* INTERNAL: cross-segment decls for the split cli_v1_routes*.c TUs. Private. */
#include "cli_client.h"
#include "aimee_home.h" /* aimee_home() — cross-platform, used outside the _WIN32 guard */
#include "cli_v1_routes.h"
#define V1_MAX_POS   16
#define V1_MAX_FLAGS 32
typedef struct
{
   const char *positional[V1_MAX_POS];
   int pos_count;
   struct
   {
      const char *raw; /* flag name from argv (after --), may include =val */
      const char *value;
   } flags[V1_MAX_FLAGS];
   int flag_count;
} rpc_opts_t;
int cli_v1_args_request_json(int argc, char **argv);
void __attribute__((unused)) cli_v1_sleep_ms(int ms);
int git_verify_response_is_failure(cJSON *resp);
double json_double(cJSON *obj, const char *key, double def);
int json_int(cJSON *obj, const char *key, int def);
const char *json_str(cJSON *obj, const char *key);
cJSON *marshal_audit_fidelity(int argc, char **argv);
cJSON *marshal_audit_provenance(int argc, char **argv);
cJSON *marshal_audit_trace(int argc, char **argv);
cJSON *marshal_config_get(int argc, char **argv);
cJSON *marshal_config_set(int argc, char **argv);
cJSON *marshal_coord_job_start(int argc, char **argv);
cJSON *marshal_coord_jobs_list(int argc, char **argv);
cJSON *marshal_curator_contradictions(int argc, char **argv);
cJSON *marshal_curator_topic(const char *method, int argc, char **argv);
cJSON *marshal_delegate(int argc, char **argv);
cJSON *marshal_delegate_aggregate(int argc, char **argv);
cJSON *marshal_delegate_backend_exec(int argc, char **argv);
cJSON *marshal_delegate_log(int argc, char **argv);
cJSON *marshal_delegate_roundtable(int argc, char **argv);
cJSON *marshal_delegate_status(int argc, char **argv);
cJSON *marshal_index_blast_radius(int argc, char **argv);
cJSON *marshal_index_deps(int argc, char **argv);
cJSON *marshal_index_find(int argc, char **argv);
cJSON *marshal_index_find_callers(int argc, char **argv);
cJSON *marshal_index_list(int argc, char **argv);
cJSON *marshal_index_scan(int argc, char **argv);
cJSON *marshal_index_structure(int argc, char **argv);
cJSON *marshal_insights_overview(int argc, char **argv);
cJSON *marshal_job_id_request(const char *method, int argc, char **argv);
cJSON *marshal_jobs_list(int argc, char **argv);
cJSON *marshal_kb_build(int argc, char **argv);
cJSON *marshal_kb_docs_push(int argc, char **argv);
cJSON *marshal_kb_ingest(int argc, char **argv);
cJSON *marshal_kb_search(int argc, char **argv);
cJSON *marshal_kb_status(int argc, char **argv);
cJSON *marshal_kb_update(int argc, char **argv);
cJSON *marshal_mcp_recheck(int argc, char **argv);
cJSON *marshal_memory_benchmark(int argc, char **argv);
cJSON *marshal_memory_get(int argc, char **argv);
cJSON *marshal_memory_list(int argc, char **argv);
cJSON *marshal_memory_read(int argc, char **argv);
cJSON *marshal_memory_recall(int argc, char **argv);
cJSON *marshal_memory_search(int argc, char **argv);
cJSON *marshal_memory_store(int argc, char **argv);
cJSON *marshal_memory_identity(int argc, char **argv);
cJSON *marshal_memory_prefer(int argc, char **argv);
cJSON *marshal_no_args(const char *method);
cJSON *marshal_notes_search(int argc, char **argv);
cJSON *marshal_primary(int argc, char **argv);
cJSON *marshal_repo_trust(int argc, char **argv);
cJSON *marshal_request(const char *method, int argc, char **argv);
cJSON *marshal_rules_delete(int argc, char **argv);
cJSON *marshal_session_attach(int argc, char **argv);
cJSON *marshal_session_brief(int argc, char **argv);
cJSON *marshal_session_close(int argc, char **argv);
cJSON *marshal_session_detach(int argc, char **argv);
cJSON *marshal_session_get(int argc, char **argv);
cJSON *marshal_session_list(int argc, char **argv);
cJSON *marshal_session_presence(int argc, char **argv);
cJSON *marshal_trajectory_batch(int argc, char **argv);
cJSON *marshal_trajectory_export(int argc, char **argv);
cJSON *marshal_wm_get(int argc, char **argv);
cJSON *marshal_wm_list(int argc, char **argv);
cJSON *marshal_wm_set(int argc, char **argv);
cJSON *marshal_work_request(const char *method, int argc, char **argv);
cJSON *marshal_worktree_gc(int argc, char **argv);
void print_aux_config(cJSON *resp);
void print_coord_job_cancel(cJSON *resp);
void print_coord_job_start(cJSON *resp);
void print_coord_job_status(cJSON *resp);
void print_coord_jobs_list(cJSON *resp);
void print_insights_overview(cJSON *resp);
void print_jobs_cancel(cJSON *resp);
void print_jobs_list(cJSON *resp);
void print_jobs_logs(cJSON *resp);
void print_jobs_status(cJSON *resp);
void print_mcp_audit(cJSON *resp);
void print_mcp_content(cJSON *resp);
void print_mcp_recheck(cJSON *resp);
void print_server_health(cJSON *resp);
void print_session_brief(cJSON *resp);
void print_session_get(cJSON *resp);
void print_session_list(cJSON *resp);
void print_toolset_list(cJSON *resp);
void print_toolset_resolve(cJSON *resp);
void print_toolset_show(cJSON *resp);
void pt_print_agent_add(const char *method, cJSON *resp);
void pt_print_agent_disable(const char *method, cJSON *resp);
void pt_print_agent_enable(const char *method, cJSON *resp);
void pt_print_agent_list(const char *method, cJSON *resp);
void pt_print_agent_local(const char *method, cJSON *resp);
void pt_print_agent_probe(const char *method, cJSON *resp);
void pt_print_agent_remove(const char *method, cJSON *resp);
void pt_print_api_status(const char *method, cJSON *resp);
void pt_print_aux_config_show(const char *method, cJSON *resp);
void pt_print_aux_test(const char *method, cJSON *resp);
void pt_print_config_get(const char *method, cJSON *resp);
void pt_print_config_set(const char *method, cJSON *resp);
void pt_print_config_show(const char *method, cJSON *resp);
void pt_print_cron_add(const char *method, cJSON *resp);
void pt_print_cron_history(const char *method, cJSON *resp);
void pt_print_cron_list(const char *method, cJSON *resp);
void pt_print_cron_run(const char *method, cJSON *resp);
void pt_print_cron_show(const char *method, cJSON *resp);
void pt_print_delegate(const char *method, cJSON *resp);
void pt_print_delegate_launch(const char *method, cJSON *resp);
void pt_print_delegate_log(const char *method, cJSON *resp);
void pt_print_delegate_roundtable(const char *method, cJSON *resp);
void pt_print_delegate_status(const char *method, cJSON *resp);
void pt_print_dogfood_report(const char *method, cJSON *resp);
void pt_print_dogfood_tag(const char *method, cJSON *resp);
void pt_print_eval_results(const char *method, cJSON *resp);
void pt_print_eval_run(const char *method, cJSON *resp);
void pt_print_get_help(const char *method, cJSON *resp);
void pt_print_git_verify(const char *method, cJSON *resp);
void pt_print_graph_sync_code(const char *method, cJSON *resp);
void pt_print_hud_status(const char *method, cJSON *resp);
void pt_print_identity_diff(const char *method, cJSON *resp);
void pt_print_identity_show(const char *method, cJSON *resp);
void pt_print_identity_snapshot(const char *method, cJSON *resp);
void pt_print_index_blast_radius(const char *method, cJSON *resp);
void pt_print_index_deps(const char *method, cJSON *resp);
void pt_print_index_find(const char *method, cJSON *resp);
void pt_print_index_find_callers(const char *method, cJSON *resp);
void pt_print_index_list(const char *method, cJSON *resp);
void pt_print_index_scan(const char *method, cJSON *resp);
void pt_print_index_structure(const char *method, cJSON *resp);
void pt_print_init_run(const char *method, cJSON *resp);
void pt_print_insights_overview(const char *method, cJSON *resp);
void pt_print_job_cancel(const char *method, cJSON *resp);
void pt_print_job_list(const char *method, cJSON *resp);
void pt_print_job_start(const char *method, cJSON *resp);
void pt_print_job_status(const char *method, cJSON *resp);
void pt_print_jobs_cancel(const char *method, cJSON *resp);
void pt_print_jobs_list(const char *method, cJSON *resp);
void pt_print_jobs_logs(const char *method, cJSON *resp);
void pt_print_jobs_status(const char *method, cJSON *resp);
void pt_print_kb_build(const char *method, cJSON *resp);
void pt_print_kb_docs_push(const char *method, cJSON *resp);
void pt_print_kb_ingest(const char *method, cJSON *resp);
void pt_print_kb_ingest_status(const char *method, cJSON *resp);
void pt_print_kb_search(const char *method, cJSON *resp);
void pt_print_kb_status(const char *method, cJSON *resp);
void pt_print_mcp_audit(const char *method, cJSON *resp);
void pt_print_mcp_recheck(const char *method, cJSON *resp);
void pt_print_memory_get(const char *method, cJSON *resp);
void pt_print_memory_list(const char *method, cJSON *resp);
void pt_print_memory_read(const char *method, cJSON *resp);
void pt_print_memory_search(const char *method, cJSON *resp);
void pt_print_memory_stats(const char *method, cJSON *resp);
void pt_print_memory_store(const char *method, cJSON *resp);
void pt_print_migrate_v2(const char *method, cJSON *resp);
void pt_print_model_list(const char *method, cJSON *resp);
void pt_print_model_refresh(const char *method, cJSON *resp);
void pt_print_model_show(const char *method, cJSON *resp);
void pt_print_primary_set(const char *method, cJSON *resp);
void pt_print_provider_get(const char *method, cJSON *resp);
void pt_print_provider_list(const char *method, cJSON *resp);
void pt_print_provider_models(const char *method, cJSON *resp);
void pt_print_provider_quota(const char *method, cJSON *resp);
void pt_print_provider_set(const char *method, cJSON *resp);
void pt_print_provider_show(const char *method, cJSON *resp);
void pt_print_provider_test(const char *method, cJSON *resp);
void pt_print_repo_trust(const char *method, cJSON *resp);
void pt_print_rules_delete(const char *method, cJSON *resp);
void pt_print_rules_generate(const char *method, cJSON *resp);
void pt_print_server_health(const char *method, cJSON *resp);
void pt_print_session_attach(const char *method, cJSON *resp);
void pt_print_session_brief(const char *method, cJSON *resp);
void pt_print_session_close(const char *method, cJSON *resp);
void pt_print_session_detach(const char *method, cJSON *resp);
void pt_print_session_get(const char *method, cJSON *resp);
void pt_print_session_list(const char *method, cJSON *resp);
void pt_print_session_presence(const char *method, cJSON *resp);
void pt_print_skill_group(const char *method, cJSON *resp);
void pt_print_skill_list(const char *method, cJSON *resp);
void pt_print_skill_show(const char *method, cJSON *resp);
void pt_print_toolset_list(const char *method, cJSON *resp);
void pt_print_toolset_resolve(const char *method, cJSON *resp);
void pt_print_toolset_show(const char *method, cJSON *resp);
void pt_print_trajectory_batch(const char *method, cJSON *resp);
void pt_print_trajectory_export(const char *method, cJSON *resp);
void pt_print_trigger_cancel(const char *method, cJSON *resp);
void pt_print_trigger_fire(const char *method, cJSON *resp);
void pt_print_trigger_list(const char *method, cJSON *resp);
void pt_print_trigger_status(const char *method, cJSON *resp);
void pt_print_wm_get(const char *method, cJSON *resp);
void pt_print_wm_list(const char *method, cJSON *resp);
void pt_print_wm_set(const char *method, cJSON *resp);
void pt_print_work_add(const char *method, cJSON *resp);
void pt_print_work_add_batch(const char *method, cJSON *resp);
void pt_print_work_board(const char *method, cJSON *resp);
void pt_print_work_cancel(const char *method, cJSON *resp);
void pt_print_work_claim(const char *method, cJSON *resp);
void pt_print_work_clear(const char *method, cJSON *resp);
void pt_print_work_complete(const char *method, cJSON *resp);
void pt_print_work_fail(const char *method, cJSON *resp);
void pt_print_work_gc(const char *method, cJSON *resp);
void pt_print_work_list(const char *method, cJSON *resp);
void pt_print_work_release(const char *method, cJSON *resp);
void pt_print_work_stats(const char *method, cJSON *resp);
void pt_print_work_sync_proposals(const char *method, cJSON *resp);
void pt_print_workers(const char *method, cJSON *resp);
void pt_print_workspace_add(const char *method, cJSON *resp);
void pt_print_workspace_get(const char *method, cJSON *resp);
void pt_print_workspace_list(const char *method, cJSON *resp);
void pt_print_workspace_mirror_sync(const char *method, cJSON *resp);
void pt_print_workspace_remove(const char *method, cJSON *resp);
void pt_print_worktree_gc(const char *method, cJSON *resp);
const char *rpc_get(const rpc_opts_t *opts, const char *name);
int rpc_get_int(const rpc_opts_t *opts, const char *name, int def);
int rpc_has_flag(const rpc_opts_t *opts, const char *name);
void rpc_parse(int argc, char **argv, const char **bool_flags, rpc_opts_t *out);
int cli_v1_args_request_json(int argc, char **argv);
void __attribute__((unused)) cli_v1_sleep_ms(int ms);
int git_verify_response_is_failure(cJSON *resp);
double json_double(cJSON *obj, const char *key, double def);
int json_int(cJSON *obj, const char *key, int def);
const char *json_str(cJSON *obj, const char *key);
cJSON *marshal_audit_fidelity(int argc, char **argv);
cJSON *marshal_audit_provenance(int argc, char **argv);
cJSON *marshal_audit_trace(int argc, char **argv);
cJSON *marshal_config_get(int argc, char **argv);
cJSON *marshal_config_set(int argc, char **argv);
cJSON *marshal_coord_job_start(int argc, char **argv);
cJSON *marshal_coord_jobs_list(int argc, char **argv);
cJSON *marshal_curator_contradictions(int argc, char **argv);
cJSON *marshal_curator_topic(const char *method, int argc, char **argv);
cJSON *marshal_delegate(int argc, char **argv);
cJSON *marshal_delegate_aggregate(int argc, char **argv);
cJSON *marshal_delegate_backend_exec(int argc, char **argv);
cJSON *marshal_delegate_log(int argc, char **argv);
cJSON *marshal_delegate_roundtable(int argc, char **argv);
cJSON *marshal_delegate_status(int argc, char **argv);
cJSON *marshal_index_blast_radius(int argc, char **argv);
cJSON *marshal_index_deps(int argc, char **argv);
cJSON *marshal_index_find(int argc, char **argv);
cJSON *marshal_index_find_callers(int argc, char **argv);
cJSON *marshal_index_list(int argc, char **argv);
cJSON *marshal_index_scan(int argc, char **argv);
cJSON *marshal_index_structure(int argc, char **argv);
cJSON *marshal_insights_overview(int argc, char **argv);
cJSON *marshal_job_id_request(const char *method, int argc, char **argv);
cJSON *marshal_jobs_list(int argc, char **argv);
cJSON *marshal_kb_build(int argc, char **argv);
cJSON *marshal_kb_docs_push(int argc, char **argv);
cJSON *marshal_kb_ingest(int argc, char **argv);
cJSON *marshal_kb_search(int argc, char **argv);
cJSON *marshal_kb_status(int argc, char **argv);
cJSON *marshal_kb_update(int argc, char **argv);
cJSON *marshal_mcp_recheck(int argc, char **argv);
cJSON *marshal_memory_benchmark(int argc, char **argv);
cJSON *marshal_memory_get(int argc, char **argv);
cJSON *marshal_memory_list(int argc, char **argv);
cJSON *marshal_memory_read(int argc, char **argv);
cJSON *marshal_memory_recall(int argc, char **argv);
cJSON *marshal_memory_search(int argc, char **argv);
cJSON *marshal_memory_store(int argc, char **argv);
cJSON *marshal_memory_identity(int argc, char **argv);
cJSON *marshal_memory_prefer(int argc, char **argv);
cJSON *marshal_no_args(const char *method);
cJSON *marshal_notes_search(int argc, char **argv);
cJSON *marshal_primary(int argc, char **argv);
cJSON *marshal_repo_trust(int argc, char **argv);
cJSON *marshal_request(const char *method, int argc, char **argv);
cJSON *marshal_rules_delete(int argc, char **argv);
cJSON *marshal_session_attach(int argc, char **argv);
cJSON *marshal_session_brief(int argc, char **argv);
cJSON *marshal_session_close(int argc, char **argv);
cJSON *marshal_session_detach(int argc, char **argv);
cJSON *marshal_session_get(int argc, char **argv);
cJSON *marshal_session_list(int argc, char **argv);
cJSON *marshal_session_presence(int argc, char **argv);
cJSON *marshal_trajectory_batch(int argc, char **argv);
cJSON *marshal_trajectory_export(int argc, char **argv);
cJSON *marshal_wm_get(int argc, char **argv);
cJSON *marshal_wm_list(int argc, char **argv);
cJSON *marshal_wm_set(int argc, char **argv);
cJSON *marshal_work_request(const char *method, int argc, char **argv);
cJSON *marshal_worktree_gc(int argc, char **argv);
void print_aux_config(cJSON *resp);
void print_coord_job_cancel(cJSON *resp);
void print_coord_job_start(cJSON *resp);
void print_coord_job_status(cJSON *resp);
void print_coord_jobs_list(cJSON *resp);
void print_insights_overview(cJSON *resp);
void print_jobs_cancel(cJSON *resp);
void print_jobs_list(cJSON *resp);
void print_jobs_logs(cJSON *resp);
void print_jobs_status(cJSON *resp);
void print_mcp_audit(cJSON *resp);
void print_mcp_content(cJSON *resp);
void print_mcp_recheck(cJSON *resp);
void print_server_health(cJSON *resp);
void print_session_brief(cJSON *resp);
void print_session_get(cJSON *resp);
void print_session_list(cJSON *resp);
void print_toolset_list(cJSON *resp);
void print_toolset_resolve(cJSON *resp);
void print_toolset_show(cJSON *resp);
void pt_print_agent_add(const char *method, cJSON *resp);
void pt_print_agent_disable(const char *method, cJSON *resp);
void pt_print_agent_enable(const char *method, cJSON *resp);
void pt_print_agent_list(const char *method, cJSON *resp);
void pt_print_agent_local(const char *method, cJSON *resp);
void pt_print_agent_probe(const char *method, cJSON *resp);
void pt_print_agent_remove(const char *method, cJSON *resp);
void pt_print_api_status(const char *method, cJSON *resp);
void pt_print_aux_config_show(const char *method, cJSON *resp);
void pt_print_aux_test(const char *method, cJSON *resp);
void pt_print_config_get(const char *method, cJSON *resp);
void pt_print_config_set(const char *method, cJSON *resp);
void pt_print_config_show(const char *method, cJSON *resp);
void pt_print_cron_add(const char *method, cJSON *resp);
void pt_print_cron_history(const char *method, cJSON *resp);
void pt_print_cron_list(const char *method, cJSON *resp);
void pt_print_cron_run(const char *method, cJSON *resp);
void pt_print_cron_show(const char *method, cJSON *resp);
void pt_print_delegate(const char *method, cJSON *resp);
void pt_print_delegate_launch(const char *method, cJSON *resp);
void pt_print_delegate_log(const char *method, cJSON *resp);
void pt_print_delegate_roundtable(const char *method, cJSON *resp);
void pt_print_delegate_status(const char *method, cJSON *resp);
void pt_print_dogfood_report(const char *method, cJSON *resp);
void pt_print_dogfood_tag(const char *method, cJSON *resp);
void pt_print_eval_results(const char *method, cJSON *resp);
void pt_print_eval_run(const char *method, cJSON *resp);
void pt_print_get_help(const char *method, cJSON *resp);
void pt_print_git_verify(const char *method, cJSON *resp);
void pt_print_graph_sync_code(const char *method, cJSON *resp);
void pt_print_hud_status(const char *method, cJSON *resp);
void pt_print_identity_diff(const char *method, cJSON *resp);
void pt_print_identity_show(const char *method, cJSON *resp);
void pt_print_identity_snapshot(const char *method, cJSON *resp);
void pt_print_index_blast_radius(const char *method, cJSON *resp);
void pt_print_index_deps(const char *method, cJSON *resp);
void pt_print_index_find(const char *method, cJSON *resp);
void pt_print_index_find_callers(const char *method, cJSON *resp);
void pt_print_index_list(const char *method, cJSON *resp);
void pt_print_index_scan(const char *method, cJSON *resp);
void pt_print_index_structure(const char *method, cJSON *resp);
void pt_print_init_run(const char *method, cJSON *resp);
void pt_print_insights_overview(const char *method, cJSON *resp);
void pt_print_job_cancel(const char *method, cJSON *resp);
void pt_print_job_list(const char *method, cJSON *resp);
void pt_print_job_start(const char *method, cJSON *resp);
void pt_print_job_status(const char *method, cJSON *resp);
void pt_print_jobs_cancel(const char *method, cJSON *resp);
void pt_print_jobs_list(const char *method, cJSON *resp);
void pt_print_jobs_logs(const char *method, cJSON *resp);
void pt_print_jobs_status(const char *method, cJSON *resp);
void pt_print_kb_build(const char *method, cJSON *resp);
void pt_print_kb_docs_push(const char *method, cJSON *resp);
void pt_print_kb_ingest(const char *method, cJSON *resp);
void pt_print_kb_ingest_status(const char *method, cJSON *resp);
void pt_print_kb_search(const char *method, cJSON *resp);
void pt_print_kb_status(const char *method, cJSON *resp);
void pt_print_mcp_audit(const char *method, cJSON *resp);
void pt_print_mcp_recheck(const char *method, cJSON *resp);
void pt_print_memory_get(const char *method, cJSON *resp);
void pt_print_memory_list(const char *method, cJSON *resp);
void pt_print_memory_read(const char *method, cJSON *resp);
void pt_print_memory_search(const char *method, cJSON *resp);
void pt_print_memory_stats(const char *method, cJSON *resp);
void pt_print_memory_store(const char *method, cJSON *resp);
void pt_print_migrate_v2(const char *method, cJSON *resp);
void pt_print_model_list(const char *method, cJSON *resp);
void pt_print_model_refresh(const char *method, cJSON *resp);
void pt_print_model_show(const char *method, cJSON *resp);
void pt_print_primary_set(const char *method, cJSON *resp);
void pt_print_provider_get(const char *method, cJSON *resp);
void pt_print_provider_list(const char *method, cJSON *resp);
void pt_print_provider_models(const char *method, cJSON *resp);
void pt_print_provider_quota(const char *method, cJSON *resp);
void pt_print_provider_set(const char *method, cJSON *resp);
void pt_print_provider_show(const char *method, cJSON *resp);
void pt_print_provider_test(const char *method, cJSON *resp);
void pt_print_repo_trust(const char *method, cJSON *resp);
void pt_print_rules_delete(const char *method, cJSON *resp);
void pt_print_rules_generate(const char *method, cJSON *resp);
void pt_print_server_health(const char *method, cJSON *resp);
void pt_print_session_attach(const char *method, cJSON *resp);
void pt_print_session_brief(const char *method, cJSON *resp);
void pt_print_session_close(const char *method, cJSON *resp);
void pt_print_session_detach(const char *method, cJSON *resp);
void pt_print_session_get(const char *method, cJSON *resp);
void pt_print_session_list(const char *method, cJSON *resp);
void pt_print_session_presence(const char *method, cJSON *resp);
void pt_print_skill_group(const char *method, cJSON *resp);
void pt_print_skill_list(const char *method, cJSON *resp);
void pt_print_skill_show(const char *method, cJSON *resp);
void pt_print_toolset_list(const char *method, cJSON *resp);
void pt_print_toolset_resolve(const char *method, cJSON *resp);
void pt_print_toolset_show(const char *method, cJSON *resp);
void pt_print_trajectory_batch(const char *method, cJSON *resp);
void pt_print_trajectory_export(const char *method, cJSON *resp);
void pt_print_trigger_cancel(const char *method, cJSON *resp);
void pt_print_trigger_fire(const char *method, cJSON *resp);
void pt_print_trigger_list(const char *method, cJSON *resp);
void pt_print_trigger_status(const char *method, cJSON *resp);
void pt_print_wm_get(const char *method, cJSON *resp);
void pt_print_wm_list(const char *method, cJSON *resp);
void pt_print_wm_set(const char *method, cJSON *resp);
void pt_print_work_add(const char *method, cJSON *resp);
void pt_print_work_add_batch(const char *method, cJSON *resp);
void pt_print_work_board(const char *method, cJSON *resp);
void pt_print_work_cancel(const char *method, cJSON *resp);
void pt_print_work_claim(const char *method, cJSON *resp);
void pt_print_work_clear(const char *method, cJSON *resp);
void pt_print_work_complete(const char *method, cJSON *resp);
void pt_print_work_fail(const char *method, cJSON *resp);
void pt_print_work_gc(const char *method, cJSON *resp);
void pt_print_work_list(const char *method, cJSON *resp);
void pt_print_work_release(const char *method, cJSON *resp);
void pt_print_work_stats(const char *method, cJSON *resp);
void pt_print_work_sync_proposals(const char *method, cJSON *resp);
void pt_print_workers(const char *method, cJSON *resp);
void pt_print_workspace_add(const char *method, cJSON *resp);
void pt_print_workspace_get(const char *method, cJSON *resp);
void pt_print_workspace_list(const char *method, cJSON *resp);
void pt_print_workspace_mirror_sync(const char *method, cJSON *resp);
void pt_print_workspace_remove(const char *method, cJSON *resp);
void pt_print_worktree_gc(const char *method, cJSON *resp);
const char *rpc_get(const rpc_opts_t *opts, const char *name);
int rpc_get_int(const rpc_opts_t *opts, const char *name, int def);
int rpc_has_flag(const rpc_opts_t *opts, const char *name);
void rpc_parse(int argc, char **argv, const char **bool_flags, rpc_opts_t *out);

void rpc_parse(int argc, char **argv, const char **bool_flags, rpc_opts_t *out);
void __attribute__((unused)) cli_v1_sleep_ms(int ms);
#endif
