"""Generate bench/evidence/RUNS.md: every prediction file, with its validity.

Written because the article will need to say which numbers survived and which
did not, and that answer must come from the artefacts rather than from memory.
A run is marked INVALID here if the scorer would now refuse it — incomplete, or
containing a row the harness truncated — so the index cannot disagree with the
scorer about what is usable.
"""
import glob
import json
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GOLD = {"tier-a": os.path.join(ROOT, "tier-a/data/gold.jsonl"),
        "tier-b": os.path.join(ROOT, "tier-b/data/topics.jsonl")}

LANE_NOTES = {
    "thinking":      "thinking ON, cap 8192 — CURRENT",
    "gpu":           "thinking OFF (disable_thinking) — SUPERSEDED",
    "llamacpp":      "thinking OFF — SUPERSEDED; device varies, see defect 15",
    "ceiling":       "thinking OFF — SUPERSEDED",
    "ablation-conf": "MF_CONF_FLOOR ablation",
    "noconf":        "confidence floor removed",
    "promptfix":     "prompt correction",
    "cpu":           "llama-bench throughput only, no extraction",
    "diagnostics":   "cap and repetition-penalty variants",
    "sub1b":         "sub-1B ladder, thinking ON",
    # INVALID DEVICE, not just an incomparable one. These runs were taken while
    # the 7900 XTX had NO DRIVER BOUND: llama.cpp enumerated only the Phoenix
    # iGPU (8GB shared out of a 14GB host), so a ~19GB Q6 model was never
    # resident on a discrete card at all. Accuracy may survive — the same GGUF
    # answers the same wherever it runs — but every speed, fit and "does this
    # architecture work" claim from this lane is void. The card was bound after a
    # reboot on 2026-08-01; anything measured before that needs re-running.
    "challenger-254": "MISMEASURED: ran on an 8GB iGPU, not the 7900 XTX — speed/fit claims void",
    "cpufit":        "declared CPU lane, model does not fit the card",
    "ple-control":   "transformers/bf16, PLE applied — compare against the GGUF lanes",
    "quant":         "Unsloth Dynamic quants, thinking ON, --no-mmproj — quality vs resident memory",
}


def audit(path, expected):
    rows = [json.loads(l) for l in open(path) if l.strip()]
    problems = []
    if len(rows) != expected:
        problems.append(f"incomplete ({len(rows)}/{expected})")
    cut = [r.get("id") for r in rows if r.get("truncated")]
    if cut:
        problems.append(f"truncated x{len(cut)}")
    err = [r.get("id") for r in rows if r.get("error")]
    if err:
        problems.append(f"errored x{len(err)}")
    return len(rows), problems


def main():
    out = ["# Run index",
           "",
           "Generated by `build_index.py`. A run is INVALID when the scorer would",
           "refuse it: incomplete, or containing a row the harness truncated or",
           "errored out. That rule is the same one `score.py` and `score_b.py`",
           "enforce, so this table cannot drift from what is scoreable.",
           ""]
    for tier in ("tier-a", "tier-b"):
        gold_path = GOLD[tier]
        expected = sum(1 for l in open(gold_path) if l.strip())
        # tier-a gold carries one excluded note; the scorer's own count is authoritative
        out += [f"## {tier}", "",
                f"| lane | model | rows | status | lane note |",
                f"| --- | --- | ---: | --- | --- |"]
        for f in sorted(glob.glob(os.path.join(ROOT, tier, "results/*/*.pred.jsonl"))):
            lane = os.path.basename(os.path.dirname(f))
            model = os.path.basename(f).replace(".pred.jsonl", "")
            n, problems = audit(f, expected)
            status = "VALID" if not problems else "INVALID: " + ", ".join(problems)
            out.append(f"| {lane} | {model} | {n} | {status} | {LANE_NOTES.get(lane,'')} |")
        out.append("")
    open(os.path.join(ROOT, "evidence/RUNS.md"), "w").write("\n".join(out) + "\n")
    print("\n".join(out[:8]))


if __name__ == "__main__":
    main()
