#ifndef AIMEE_EGRESS_MODULE_API_H
#define AIMEE_EGRESS_MODULE_API_H

#define AIMEE_EGRESS_EVENT_AUTHORIZE      12289u
#define AIMEE_EGRESS_EVENT_HTTP           12290u
#define AIMEE_EGRESS_EVENT_SSE_OPEN       12291u
#define AIMEE_EGRESS_EVENT_SSE_SEND       12292u
#define AIMEE_EGRESS_EVENT_SSE_RECV       12293u
#define AIMEE_EGRESS_EVENT_SSE_CLOSE      12294u
#define AIMEE_EGRESS_EVENT_CREDENTIAL_KEY 12295u

#define AIMEE_EGRESS_STAGE_AUTHORIZE      1u
#define AIMEE_EGRESS_STAGE_HTTP           2u
#define AIMEE_EGRESS_STAGE_SSE_OPEN       3u
#define AIMEE_EGRESS_STAGE_SSE_SEND       4u
#define AIMEE_EGRESS_STAGE_SSE_RECV       5u
#define AIMEE_EGRESS_STAGE_SSE_CLOSE      6u
#define AIMEE_EGRESS_STAGE_CREDENTIAL_KEY 7u

#define AIMEE_EGRESS_GIT_CLIENT_REF 71u

#endif
