#!/bin/bash
# Build a real certificate chain so the mTLS path can actually be exercised.
#
# TWO DIFFERENT SOURCES, deliberately.
#
# The CLIENT certificate is issued by aimee's OWN PKI (`aimee cert issue`), not
# by an openssl CA invented here. A hand-rolled client cert gets through the TLS
# handshake and is then refused by the server:
#
#     client certificate is no longer valid (revoked, expired, or unrecognized)
#
# because verification is two gates, not one: the chain is checked against
# aimee.api.mtls_client_ca, and the serial is then re-checked against the
# DURABLE ROSTER (pki_cert_check -> db1_pki_cert_check, DB1 stage 19). Only a
# cert aimee issued is in that roster. Using its PKI is also simply the real
# path -- it is how a thin client is actually enrolled.
#
# The SERVER certificate is generated by aimee's PKI too, and deliberately not
# by this script: its key is sealed into the Vault on first load, so a
# regenerated cert orphans that key and TLS stops serving.
#
# The ROGUE client certificate is openssl-made ON PURPOSE, from an unrelated CA.
# It is the negative control: without it, "the mTLS caller got user authority"
# cannot be distinguished from "the server accepts any certificate", which would
# be a far worse bug than the one under test.
#
# aimee's client CA lands at $AIMEE_HOME/tls/client-ca.crt (pki.c:67) and the
# server identity at $AIMEE_HOME/tls/server.crt, so these paths are not free
# choices.
#
# CN: vault_principal_name_sanitize() refuses a CN it cannot sanitize (embedded
# ':', newline, traversal, or a "uid:0" shape); a refused CN yields NO principal
# while still classifying as mTLS -- fail-closed. "thin-client-a" is clean.
# Run AS ROOT in the container.
set -u
export LC_ALL=C
TLS=/root/.config/aimee-tls
HOME_TLS=/root/tls
CN="${1:-thin-client-a}"
mkdir -p "$TLS" "$HOME_TLS"
cd "$TLS" || exit 1

gen_ca() { # $1 = name, $2 = CN
  openssl req -x509 -newkey rsa:2048 -nodes -days 3650 \
    -keyout "$1-ca.key" -out "$1-ca.crt" -subj "/CN=$2" 2>/dev/null
}

# --- server identity: aimee's PKI owns it, we must NOT ------------------------
# An existing $AIMEE_HOME/tls/server.crt is AUTHORITATIVE (pki.c:472), and its
# private key is SEALED INTO THE VAULT on first load, with the on-disk copy
# erased. So minting a server cert here works exactly once: regenerate it and
# the new cert no longer matches the vaulted key --
#
#     ERROR pki: Vault-held server TLS key does not match /root/tls/server.crt
#     WARN  server.tls: no private key assigned
#
# and TLS silently stops serving. Removing the cert lets pki generate its own
# identity, key and all, which is the real path and cannot desynchronise.
rm -f "$HOME_TLS/server.crt" "$HOME_TLS/server.key"
echo "server identity: removed; aimee's PKI will generate and vault its own"

# --- rogue client (openssl, unrelated CA): the negative control ---------------
gen_ca rogue "unrelated CA"
cat > client-ext.cnf <<'EOF'
extendedKeyUsage = clientAuth
EOF
openssl req -newkey rsa:2048 -nodes -keyout rogue.key -out rogue.csr \
  -subj "/CN=thin-client-b" 2>/dev/null
openssl x509 -req -in rogue.csr -CA rogue-ca.crt -CAkey rogue-ca.key \
  -CAcreateserial -out rogue.crt -days 3650 -extfile client-ext.cnf 2>/dev/null
rm -f rogue.csr

# --- real client: issued by aimee, so its serial is in the durable roster -----
export AIMEE_HOME=/root AIMEE_API_ENDPOINT=unix:/root/aimee-http.sock
issued="$(/usr/local/bin/aimee cert issue "$CN" --days 365 2>&1)"
case "$issued" in
  *'"status":"ok"'*) ;;
  *) echo "FAIL: aimee cert issue refused: $(printf '%s' "$issued" | head -c 200)" >&2; exit 1 ;;
esac
printf '%s' "$issued" | python3 -c '
import json,sys
d = json.load(sys.stdin)
open("/root/.config/aimee-tls/client.crt","w").write(d["cert"])
open("/root/.config/aimee-tls/client.key","w").write(d["key"])
open("/root/.config/aimee-tls/client.serial","w").write(d["serial"])
print("issued serial", d["serial"])
' || { echo "FAIL: could not unpack the issued certificate" >&2; exit 1; }
chmod 600 client.key

echo
echo "server cert:  $HOME_TLS/server.crt        (generated by aimee PKI on next start)"
echo "client cert:  $TLS/client.crt              CN=$CN (ISSUED BY AIMEE, in the roster)"
echo "rogue  cert:  $TLS/rogue.crt               CN=thin-client-b (untrusted CA, negative control)"
echo "aimee client CA (verify store): $HOME_TLS/client-ca.crt"
ls -la "$HOME_TLS/client-ca.crt" 2>&1 | tail -1
