#!/bin/bash
# Build a real certificate chain so the mTLS path can actually be exercised.
#
# This script sets up only what surrounds the client identity: the server's own
# TLS identity and a deliberately-untrusted rogue certificate. The real client
# certificate is produced by enroll-first-user.sh.
#
# A hand-rolled client cert would get through the TLS handshake and then be
# refused by the server:
#
#     client certificate is no longer valid (revoked, expired, or unrecognized)
#
# because verification is two gates, not one: the chain is checked against
# aimee.api.mtls_client_ca, and the serial is then re-checked against the
# DURABLE ROSTER (pki_cert_check then db1_pki_cert_check, DB1 stage 19).
#
# The SERVER certificate is generated by aimee's PKI too, and deliberately not
# by this script: its key is sealed into the Vault on first load, so a
# regenerated cert orphans that key and TLS stops serving.
#
# The ROGUE client certificate is openssl-made ON PURPOSE, from an unrelated CA.
# It is the negative control: without it, "the mTLS caller got user authority"
# cannot be distinguished from "the server accepts any certificate", which would
# be a far worse bug than the one under test.
#
# aimee's client CA lands at $AIMEE_HOME/tls/client-ca.crt (pki.c:67) and the
# server identity at $AIMEE_HOME/tls/server.crt, so these paths are not free
# choices.
#
# CN: vault_principal_name_sanitize() refuses a CN it cannot sanitize (embedded
# ':', newline, traversal, or a "uid:0" shape); a refused CN yields NO principal
# while still classifying as mTLS -- fail-closed. "thin-client-a" is clean.
# Run AS ROOT in the container.
set -u
export LC_ALL=C
TLS=/root/.config/aimee-tls
HOME_TLS=/root/tls
CN="${1:-thin-client-a}"
mkdir -p "$TLS" "$HOME_TLS"
cd "$TLS" || exit 1

gen_ca() { # $1 = name, $2 = CN
  openssl req -x509 -newkey rsa:2048 -nodes -days 3650 \
    -keyout "$1-ca.key" -out "$1-ca.crt" -subj "/CN=$2" 2>/dev/null
}

# --- server identity: aimee's PKI owns it, we must NOT ------------------------
# An existing $AIMEE_HOME/tls/server.crt is AUTHORITATIVE (pki.c:472), and its
# private key is SEALED INTO THE VAULT on first load, with the on-disk copy
# erased. So minting a server cert here works exactly once: regenerate it and
# the new cert no longer matches the vaulted key --
#
#     ERROR pki: Vault-held server TLS key does not match /root/tls/server.crt
#     WARN  server.tls: no private key assigned
#
# and TLS silently stops serving. Removing the cert lets pki generate its own
# identity, key and all, which is the real path and cannot desynchronise.
rm -f "$HOME_TLS/server.crt" "$HOME_TLS/server.key"
echo "server identity: removed; aimee's PKI will generate and vault its own"

# --- rogue client (openssl, unrelated CA): the negative control ---------------
gen_ca rogue "unrelated CA"
cat > client-ext.cnf <<'EOF'
extendedKeyUsage = clientAuth
EOF
openssl req -newkey rsa:2048 -nodes -keyout rogue.key -out rogue.csr \
  -subj "/CN=thin-client-b" 2>/dev/null
openssl x509 -req -in rogue.csr -CA rogue-ca.crt -CAkey rogue-ca.key \
  -CAcreateserial -out rogue.crt -days 3650 -extfile client-ext.cnf 2>/dev/null
rm -f rogue.csr

# --- real client: NOT minted here ---------------------------------------------
# The client certificate comes from enroll-first-user.sh, which drives the
# actual enrollment: /v1/deploy/apply claims the first user and returns an
# enrollment-only bearer, and /v1/cert/sign then issues the certificate AND
# binds its serial to the standing grant. Issuing one here with `aimee cert
# issue` produced a certificate in the PKI roster but with NO grant, which stops
# at the write-tier wall -- and writing the grant row by hand skipped the very
# step that makes enrollment mean anything (possession of the client-generated
# private key, proved by the CSR).

echo
echo "server cert:  $HOME_TLS/server.crt        (generated by aimee PKI on next start)"
echo "client cert:  from enroll-first-user.sh (real enrollment, not minted here)"
echo "rogue  cert:  $TLS/rogue.crt               CN=thin-client-b (untrusted CA, negative control)"
echo "aimee client CA (verify store): $HOME_TLS/client-ca.crt"
# ABSENT HERE IS NORMAL ON A FRESH BOX, and saying so matters because the bare
# `ls` error this used to print reads as a failure during setup.
#
# The client CA is created by aimee's OWN PKI the first time the server signs a
# certificate, which happens during enroll-first-user.sh -- a LATER step. On a
# container that had enrolled before, the file was already there and this always
# printed a reassuring line; the first genuinely fresh container printed
# "No such file or directory" in the middle of a successful setup.
#
# The ordering is not a mistake and cannot be reversed: enrollment itself
# requires config_server_api_mtls() > 0, so mTLS has to be configured -- pointing
# at this not-yet-existing path -- before the enrollment that creates it. The
# server tolerates the dangling path at startup, which is what makes the sequence
# work at all.
if [ -s "$HOME_TLS/client-ca.crt" ]; then
  ls -la "$HOME_TLS/client-ca.crt" | tail -1
else
  echo "  not present yet -- aimee PKI writes it when it signs the first client"
  echo "  certificate, in enroll-first-user.sh. Expected on a fresh container."
fi
