-- Native PostgreSQL schema for the management challenge store (kind 11794).
--
-- Two tables that travel together: the outstanding challenges, and the
-- revocation high-water mark that a successful consume advances.
--
-- Same singleton fix as the JWKS cache: the SQLite-derived version declared
-- `singleton BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK
-- (singleton = 1)`, an identity sequence on a column that may only ever hold 1.

CREATE TABLE IF NOT EXISTS server_mgmt_nonce (
  nonce            BYTEA PRIMARY KEY CHECK (length(nonce) = 32),
  peer_issuer      TEXT   NOT NULL,
  peer_serial_norm TEXT   NOT NULL,
  peer_fingerprint TEXT   NOT NULL,
  channel_binding  TEXT   NOT NULL,
  target_server_id TEXT   NOT NULL,
  purpose          TEXT   NOT NULL,
  expires_at       BIGINT NOT NULL
);

-- Issue sweeps expired challenges before counting, so this is on the sweep's
-- predicate rather than a covering index: the sweep deletes by expiry alone.
CREATE INDEX IF NOT EXISTS idx_server_mgmt_nonce_expiry
  ON server_mgmt_nonce (expires_at);

CREATE TABLE IF NOT EXISTS server_mgmt_status_hwm (
  singleton  BOOLEAN PRIMARY KEY DEFAULT true CHECK (singleton),
  generation BIGINT NOT NULL CHECK (generation >= 0)
);

-- The row must EXIST, not merely be permitted: hwm_read reports a failure when
-- there is no row, and both hwm_set and the consume path require their UPDATE
-- to affect exactly one row. Seeding it here is what makes the store usable
-- from cold, and ON CONFLICT keeps re-applying the schema idempotent.
INSERT INTO server_mgmt_status_hwm (singleton, generation)
     VALUES (true, 0)
ON CONFLICT (singleton) DO NOTHING;
