-- Native PostgreSQL schema for the delegation family (event kind 11781).
--
-- Seven tables from five sources: the spawn tree and its message log, the
-- agent-job queue and its completion log, the replay reservation, the retry
-- checkpoint, and the learning store.
--
-- The timestamps become TIMESTAMPTZ, and the ones that mean "has not happened
-- yet" become NULLABLE rather than defaulting to ''. That is what let the C's
-- staleness queries be built with snprintf: a TEXT column has no interval
-- arithmetic, so the threshold had to be spliced into the statement text. With
-- a real timestamp every one of them is a bound parameter.

CREATE TABLE IF NOT EXISTS delegation_messages (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  delegation_id TEXT NOT NULL DEFAULT '',
  direction     TEXT NOT NULL DEFAULT '',
  content       TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_delegation_messages_delegation
  ON delegation_messages (delegation_id, id);

CREATE TABLE IF NOT EXISTS delegation_spawns (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  delegation_id        TEXT   NOT NULL DEFAULT '',
  parent_delegation_id TEXT   NOT NULL DEFAULT '',
  session_id           TEXT   NOT NULL DEFAULT '',
  depth                BIGINT NOT NULL DEFAULT 0 CHECK (depth >= 0),
  role                 TEXT   NOT NULL DEFAULT '',
  status               TEXT   NOT NULL DEFAULT 'active',
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- NULL until the spawn reaches a terminal status.
  completed_at         TIMESTAMPTZ,
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Every status read and every cancel is by delegation_id.
CREATE INDEX IF NOT EXISTS idx_delegation_spawns_delegation
  ON delegation_spawns (delegation_id);

-- The tree walks climb by parent and descend by parent, so this serves both
-- recursive queries.
CREATE INDEX IF NOT EXISTS idx_delegation_spawns_parent
  ON delegation_spawns (parent_delegation_id);

CREATE INDEX IF NOT EXISTS idx_delegation_spawns_session
  ON delegation_spawns (session_id);

-- The stale sweep and the active list both filter on status.
CREATE INDEX IF NOT EXISTS idx_delegation_spawns_status
  ON delegation_spawns (status, created_at);

CREATE TABLE IF NOT EXISTS delegation_checkpoint (
  delegation_id   TEXT PRIMARY KEY,
  job_id          TEXT   NOT NULL DEFAULT '',
  steps_completed TEXT   NOT NULL DEFAULT '[]',
  last_output     TEXT   NOT NULL DEFAULT '',
  error           TEXT   NOT NULL DEFAULT '',
  attempt         BIGINT NOT NULL DEFAULT 0 CHECK (attempt >= 0),
  -- These two are caller-supplied epochs rather than the store's own clock, so
  -- they stay BIGINT for the same reason the token epochs elsewhere do.
  failed_at       BIGINT NOT NULL DEFAULT 0,
  created_at      BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS agent_jobs (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role              TEXT   NOT NULL DEFAULT '',
  prompt            TEXT   NOT NULL DEFAULT '',
  agent_name        TEXT   NOT NULL DEFAULT '',
  participant_token TEXT   NOT NULL DEFAULT '',
  status            TEXT   NOT NULL DEFAULT 'pending',
  result            TEXT   NOT NULL DEFAULT '',
  cursor            TEXT   NOT NULL DEFAULT '',
  lease_owner       TEXT   NOT NULL DEFAULT '',
  current_tool      TEXT   NOT NULL DEFAULT '',
  api_call_count    BIGINT NOT NULL DEFAULT 0 CHECK (api_call_count >= 0),
  cost_usd          DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (cost_usd >= 0),
  cost_known        BIGINT NOT NULL DEFAULT 0 CHECK (cost_known IN (0, 1)),
  cancel_reason     TEXT   NOT NULL DEFAULT '',
  -- NULL until it happens. The C used '' in a TEXT column and then had to write
  -- COALESCE(NULLIF(heartbeat_at, ''), created_at) at the one place it mattered.
  heartbeat_at      TIMESTAMPTZ,
  cancelled_at      TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- A participant token identifies at most one job. The partial index is what
-- lets the many jobs with no token coexist.
CREATE UNIQUE INDEX IF NOT EXISTS idx_agent_jobs_participant_token
  ON agent_jobs (participant_token) WHERE participant_token <> '';

-- The running list, the stale sweep and the restart cancel all filter on status.
CREATE INDEX IF NOT EXISTS idx_agent_jobs_status
  ON agent_jobs (status, created_at);

-- The recent list orders newest-first; id breaks the tie.
CREATE INDEX IF NOT EXISTS idx_agent_jobs_recent
  ON agent_jobs (created_at DESC, id DESC);

-- agent_log is NOT declared here. The agent_work family owns it: that family
-- inserts, and eleven of its operations read. This family only reads it,
-- through agent_log_entry_list.
--
-- It used to be declared in both files, with different types for `success` and
-- a different constraint on `confidence`. Both said IF NOT EXISTS, so the
-- winner was whichever file applied first and the loser vanished without a
-- word -- and the per-family suites could not see it, because each applies only
-- its own schema and so only ever meets its own definition.



CREATE TABLE IF NOT EXISTS lifecycle_delegate_job (
  execution_key     TEXT PRIMARY KEY,
  -- NULL means "a seat is reserved but no job has been launched into it yet".
  -- The WIRE spells that 0, and the module maps between the two at the edge --
  -- the same split conv_tool_events.chain_id makes, for the same reason: a
  -- foreign key must hold for every non-null value, and no agent job has id 0,
  -- so storing the sentinel literally would reject exactly the empty seats it
  -- exists to represent.
  --
  -- Without the reference a seat could name a job that had been deleted, and
  -- the terminal sweep's JOIN would quietly skip it forever -- a seat that can
  -- never be cancelled and never be reused. ON DELETE SET NULL returns it to
  -- empty instead, which is what it actually is.
  job_id            BIGINT REFERENCES agent_jobs (id) ON DELETE SET NULL,
  work_item_id      TEXT   NOT NULL DEFAULT '',
  participant_token TEXT   NOT NULL DEFAULT '',
  cancel_attempts   BIGINT NOT NULL DEFAULT 0 CHECK (cancel_attempts >= 0),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The legacy adoption looks a work item's seats up by prefix.
CREATE INDEX IF NOT EXISTS idx_lifecycle_delegate_job_work_item
  ON lifecycle_delegate_job (work_item_id);

CREATE TABLE IF NOT EXISTS delegate_learnings (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id    TEXT   NOT NULL DEFAULT '',
  role          TEXT   NOT NULL DEFAULT '',
  failure_mode  TEXT   NOT NULL DEFAULT 'success',
  lesson        TEXT   NOT NULL DEFAULT '',
  evidence_json TEXT   NOT NULL DEFAULT '{}',
  confidence    DOUBLE PRECISION NOT NULL DEFAULT 0.5
                  CHECK (confidence >= 0 AND confidence <= 1),
  auto_applied  BIGINT NOT NULL DEFAULT 1 CHECK (auto_applied IN (0, 1)),
  review_status TEXT   NOT NULL DEFAULT 'pending'
                  CHECK (review_status IN ('pending', 'reviewed', 'rejected')),
  reviewed_at   TIMESTAMPTZ,
  reviewer_notes TEXT  NOT NULL DEFAULT '',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The eviction takes the oldest of a review status; the prompt injection takes
-- the highest-confidence for a role.
CREATE INDEX IF NOT EXISTS idx_delegate_learnings_evict
  ON delegate_learnings (review_status, created_at);

CREATE INDEX IF NOT EXISTS idx_delegate_learnings_role
  ON delegate_learnings (role, confidence DESC, created_at DESC)
  WHERE auto_applied = 1;
