-- Workflow family: execution plans and their steps, execution traces,
-- pipelines, roadmap dispatches, and the workflow-engine session binding.

-- --------------------------------------------------------------------------
-- Execution plans
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS execution_plans (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_name    TEXT NOT NULL DEFAULT '',
  task          TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'pending',
  confidence    DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  cancelled_at  TIMESTAMPTZ,
  cancel_reason TEXT NOT NULL DEFAULT '',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT execution_plans_status
    CHECK (status IN ('pending', 'running', 'done', 'failed', 'cancelled')),
  -- A cancelled plan says when and why; a plan that is not cancelled carries
  -- neither. The C left both set on plans it moved on from.
  CONSTRAINT execution_plans_cancelled_together
    CHECK ((status = 'cancelled') = (cancelled_at IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS execution_plans_running
  ON execution_plans (id) WHERE status = 'running';

CREATE INDEX IF NOT EXISTS execution_plans_recent ON execution_plans (id DESC);

CREATE TABLE IF NOT EXISTS plan_steps (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id           BIGINT NOT NULL REFERENCES execution_plans (id) ON DELETE CASCADE,
  seq               BIGINT NOT NULL CHECK (seq >= 0),
  action            TEXT NOT NULL,
  precondition      TEXT NOT NULL DEFAULT '',
  success_predicate TEXT NOT NULL DEFAULT '',
  rollback          TEXT NOT NULL DEFAULT '',
  -- The C accepted BOTH names and stringified integers here -- its queries read
  -- "status IN ('pending','running') OR status IN ('0','1')" -- because an
  -- older writer had put numbers in the column and nothing had ever cleaned
  -- them out. A store that admits two spellings for one state has two states,
  -- and every query has to know both. This one admits the names.
  status            TEXT NOT NULL DEFAULT 'pending',
  output            TEXT NOT NULL DEFAULT '',
  checkpoint        TEXT NOT NULL DEFAULT '',
  deps              TEXT NOT NULL DEFAULT '[]',
  started_at        TIMESTAMPTZ,
  finished_at       TIMESTAMPTZ,

  CONSTRAINT plan_steps_status
    CHECK (status IN ('pending', 'running', 'done', 'failed', 'skipped')),
  -- A step's position within its plan is unique, so "step 3" names one step.
  UNIQUE (plan_id, seq)
);

CREATE INDEX IF NOT EXISTS plan_steps_plan ON plan_steps (plan_id, seq);
CREATE INDEX IF NOT EXISTS plan_steps_active
  ON plan_steps (plan_id) WHERE status IN ('pending', 'running');

CREATE TABLE IF NOT EXISTS step_evidence (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- The C carried these as bare integers with no reference, so evidence could
  -- name a plan or a step that had been deleted and the latest-evidence read
  -- would keep returning it.
  plan_id    BIGINT NOT NULL REFERENCES execution_plans (id) ON DELETE CASCADE,
  step_id    BIGINT NOT NULL REFERENCES plan_steps (id) ON DELETE CASCADE,
  kind       TEXT   NOT NULL,
  content    TEXT   NOT NULL,
  passed     BOOLEAN NOT NULL DEFAULT false,
  strength   TEXT   NOT NULL DEFAULT 'weak',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT step_evidence_strength
    CHECK (strength IN ('weak', 'moderate', 'strong'))
);

-- get_latest reads exactly this: one step's newest evidence.
CREATE INDEX IF NOT EXISTS step_evidence_latest ON step_evidence (step_id, id DESC);

-- --------------------------------------------------------------------------
-- Execution traces
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS execution_trace (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- NULL means "not part of a plan"; the wire spells that 0. A trace outlives
  -- the plan it belonged to -- the whole point of a trace is to still be there
  -- afterwards -- so the reference nulls rather than cascades.
  plan_id      BIGINT REFERENCES execution_plans (id) ON DELETE SET NULL,
  session_id   TEXT   NOT NULL DEFAULT '',
  turn         BIGINT NOT NULL DEFAULT 0 CHECK (turn >= 0),
  direction    TEXT   NOT NULL DEFAULT 'call',
  content      TEXT   NOT NULL DEFAULT '',
  tool_name    TEXT   NOT NULL DEFAULT '',
  tool_args    TEXT   NOT NULL DEFAULT '',
  tool_result  TEXT   NOT NULL DEFAULT '',
  context_hash TEXT   NOT NULL DEFAULT '',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS execution_trace_session ON execution_trace (session_id, id);
CREATE INDEX IF NOT EXISTS execution_trace_recent ON execution_trace (id DESC);

-- list_after_id reads only the rows that named a tool.
CREATE INDEX IF NOT EXISTS execution_trace_tool_calls
  ON execution_trace (plan_id, turn, id) WHERE tool_name <> '';

-- --------------------------------------------------------------------------
-- Pipelines
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS pipelines (
  id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task                   TEXT NOT NULL,
  status                 TEXT NOT NULL DEFAULT 'active',
  current_phase          TEXT NOT NULL DEFAULT 'plan',
  phase_attempts         BIGINT NOT NULL DEFAULT 0 CHECK (phase_attempts >= 0),
  -- NULL means "no plan linked yet"; the wire spells that 0.
  plan_id                BIGINT REFERENCES execution_plans (id) ON DELETE SET NULL,
  -- job_id and clarify_session_id name rows in OTHER families' tables
  -- (agent_jobs, clarify_sessions). They carry no reference here on purpose:
  -- each family's schema loads on its own, and a cross-file foreign key would
  -- make that order matter. They keep the wire's 0 sentinel for the same
  -- reason -- there is nothing for a null to mean without a reference.
  job_id                 BIGINT NOT NULL DEFAULT 0,
  clarify_session_id     BIGINT NOT NULL DEFAULT 0,
  request_classification TEXT NOT NULL DEFAULT 'simple',
  plan_depth             TEXT NOT NULL DEFAULT 'simple',
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pipelines_status
    CHECK (status IN ('active', 'paused', 'done', 'failed', 'cancelled'))
);

-- list_active reads exactly this slice.
CREATE INDEX IF NOT EXISTS pipelines_active
  ON pipelines (updated_at DESC) WHERE status IN ('active', 'paused');

-- --------------------------------------------------------------------------
-- Roadmap dispatch
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS roadmap_dispatch (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  roadmap_id               TEXT NOT NULL UNIQUE,
  status                   TEXT NOT NULL DEFAULT 'running',
  phase                    TEXT NOT NULL DEFAULT 'plan',
  token_profile            TEXT NOT NULL DEFAULT 'balanced',
  require_slice_discussion BOOLEAN NOT NULL DEFAULT true,
  budget_ceiling_tokens    BIGINT NOT NULL DEFAULT 0 CHECK (budget_ceiling_tokens >= 0),
  exit_reason              TEXT NOT NULL DEFAULT '',
  created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS roadmap_unit_dispatch (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  roadmap_id        TEXT NOT NULL,
  unit_id           TEXT NOT NULL,
  level             TEXT NOT NULL DEFAULT 'task',
  state             TEXT NOT NULL DEFAULT 'pending',
  tool_policy_mode  TEXT NOT NULL DEFAULT 'execution',
  -- '' means unclaimed, which is what makes a unit selectable AND what makes
  -- the claim itself the thing that decides between two claimants.
  claimed_by        TEXT NOT NULL DEFAULT '',
  claimed_at        TIMESTAMPTZ,
  heartbeat_at      TIMESTAMPTZ,
  verify_attempts   BIGINT NOT NULL DEFAULT 0 CHECK (verify_attempts >= 0),
  dispatch_attempts BIGINT NOT NULL DEFAULT 0 CHECK (dispatch_attempts >= 0),
  worktree_path     TEXT NOT NULL DEFAULT '',
  -- Names an agent_jobs row in another family; see the note on pipelines.job_id.
  coord_job_id      BIGINT NOT NULL DEFAULT 0,
  result            TEXT NOT NULL DEFAULT '',
  error             TEXT NOT NULL DEFAULT '',
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (roadmap_id, unit_id),
  CONSTRAINT roadmap_unit_state
    CHECK (state IN ('pending', 'active', 'done', 'failed', 'skipped')),
  -- A claimed unit says who holds it and since when; an unclaimed one says
  -- neither. Without this a unit could read as owned by nobody since a
  -- timestamp, which the selector would then hand to a second worker.
  CONSTRAINT roadmap_unit_claim_together
    CHECK ((claimed_by <> '') = (claimed_at IS NOT NULL))
);

-- select_next reads exactly this slice, lowest id first.
CREATE INDEX IF NOT EXISTS roadmap_unit_selectable
  ON roadmap_unit_dispatch (roadmap_id, id)
  WHERE level = 'task' AND state = 'pending' AND claimed_by = '';

-- --------------------------------------------------------------------------
-- Workflow-engine session binding
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS workflow_binding (
  aimee_session_id TEXT PRIMARY KEY,
  work_item_id     TEXT NOT NULL,
  enforce_stage    TEXT NOT NULL DEFAULT 'off',
  -- NULL means "no lease", which is what the C spelled as an empty string and
  -- then compared lexically against a formatted timestamp. A real timestamp
  -- compares as a time, and the absence is representable rather than being a
  -- value that happens to sort before every date.
  lease_expiry     TIMESTAMPTZ,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS workflow_binding_work_item
  ON workflow_binding (work_item_id);

-- reclaim_stale reads exactly this: the leases that have run out.
CREATE INDEX IF NOT EXISTS workflow_binding_stale
  ON workflow_binding (lease_expiry) WHERE lease_expiry IS NOT NULL;
