-- Native PostgreSQL schema for session checkpoints (event kind 11790).
--
-- This table used to hold two unrelated things: these checkpoints, which are
-- rows, and the economizer's reducer state, which is one opaque document per
-- session stored under a magic label. That split is finished -- the reducer
-- state has its own table now (see server-go/modules/db1state) -- so this holds
-- only what its name says.
--
-- created_at becomes TIMESTAMPTZ. The C wrote SQLite's datetime('now') into a
-- TEXT column, which sorts correctly only because that format happens to sort
-- lexicographically, cannot be compared against an interval, and drops the
-- zone. The wire still carries the same 'YYYY-MM-DD HH24:MI:SS' UTC spelling --
-- the module formats it at the boundary rather than storing it that way.

CREATE TABLE IF NOT EXISTS checkpoints (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id    BIGINT NOT NULL DEFAULT 0,
  session_id TEXT   NOT NULL DEFAULT '',
  label      TEXT   NOT NULL,
  snapshot   TEXT   NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The list reads newest-first. id is in the index as a tiebreaker because
-- created_at alone is not unique: two checkpoints taken in the same instant
-- ordered arbitrarily before, so a LIMIT could return either one and a caller
-- paging through them could see the same row twice or miss one.
CREATE INDEX IF NOT EXISTS idx_checkpoints_recent
  ON checkpoints (created_at DESC, id DESC);
