-- Conversation family: working memory, payload rewrite state, tool-event
-- chains, context windows, user memories, and clarification sessions.
--
-- Two things in here are not translations of the C's schema but replacements
-- for SQLite features that PostgreSQL deliberately does not have. Both are
-- called out where they appear: the implicit rowid, and the FTS5 index.

-- --------------------------------------------------------------------------
-- Working memory
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS working_memory (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id  TEXT NOT NULL,
  key         TEXT NOT NULL,
  value       TEXT NOT NULL DEFAULT '',
  category    TEXT NOT NULL DEFAULT 'general',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at  TIMESTAMPTZ DEFAULT NULL,
  UNIQUE (session_id, key)
);

-- wm_gc deletes every expired entry in one statement. The index is what keeps
-- that from being a full scan once the table is large.
CREATE INDEX IF NOT EXISTS working_memory_expires_at
  ON working_memory (expires_at) WHERE expires_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS working_memory_session
  ON working_memory (session_id, category);

-- --------------------------------------------------------------------------
-- Payload rewrite state
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS payload_rewrite_state (
  session_id                 TEXT PRIMARY KEY,
  payload_epoch              BIGINT NOT NULL DEFAULT 0,
  compaction_epoch           BIGINT NOT NULL DEFAULT 0,
  last_prefix_hash           TEXT   NOT NULL DEFAULT '',
  last_payload_tokens        BIGINT NOT NULL DEFAULT 0,
  last_rewrite_at            TEXT   NOT NULL DEFAULT '',
  deferred_rewrite_count     BIGINT NOT NULL DEFAULT 0,
  consecutive_deferred_count BIGINT NOT NULL DEFAULT 0,
  bytes_saved_pending        BIGINT NOT NULL DEFAULT 0,
  rewrite_reason             TEXT   NOT NULL DEFAULT '',
  updated_at                 TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- --------------------------------------------------------------------------
-- Tool events and the chains that summarise them
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS conv_tool_chains (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id     TEXT   NOT NULL,
  event_id_first BIGINT NOT NULL DEFAULT 0,
  event_id_last  BIGINT NOT NULL DEFAULT 0,
  tools          TEXT   NOT NULL DEFAULT '',
  stub           TEXT   NOT NULL DEFAULT '',
  raw_bytes      BIGINT NOT NULL DEFAULT 0,
  stub_bytes     BIGINT NOT NULL DEFAULT 0,
  state          TEXT   NOT NULL DEFAULT 'active',
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS conv_tool_chains_session
  ON conv_tool_chains (session_id, id);

CREATE TABLE IF NOT EXISTS conv_tool_events (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id   TEXT   NOT NULL,
  tool_name    TEXT   NOT NULL,
  tool_input   TEXT   NOT NULL DEFAULT '{}',
  tool_result  TEXT   NOT NULL DEFAULT '',
  result_bytes BIGINT NOT NULL DEFAULT 0,
  -- NULL means "not yet assigned to a chain", which is what conv_pending_events
  -- looks for.
  --
  -- The WIRE spells that as 0, because it carries an int64 with no null. The
  -- two are not the same thing and the difference is what makes the reference
  -- below possible: a foreign key must hold for every non-null value, and no
  -- chain has id 0, so storing the sentinel literally would reject exactly the
  -- unassigned events it exists to represent. The module maps between them --
  -- 0 in becomes NULL here, NULL here becomes 0 out -- so the wire is unchanged
  -- and the column can say what it means.
  --
  -- ON DELETE SET NULL: deleting a chain returns its events to unassigned,
  -- which is true and is what the next chain-building pass will find. Without
  -- the reference they kept pointing at a chain that no longer existed.
  chain_id     BIGINT REFERENCES conv_tool_chains (id) ON DELETE SET NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS conv_tool_events_session
  ON conv_tool_events (session_id, id);

-- conv_pending_events reads exactly this slice, so it gets its own index.
CREATE INDEX IF NOT EXISTS conv_tool_events_pending
  ON conv_tool_events (session_id, id) WHERE chain_id IS NULL;

CREATE TABLE IF NOT EXISTS conv_context_state (
  session_id    TEXT PRIMARY KEY,
  last_event_id BIGINT NOT NULL DEFAULT 0,
  chain_count   BIGINT NOT NULL DEFAULT 0,
  event_count   BIGINT NOT NULL DEFAULT 0,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- --------------------------------------------------------------------------
-- Context windows
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS windows (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT   NOT NULL,
  seq        BIGINT NOT NULL,
  summary    TEXT   NOT NULL DEFAULT '',
  tier       TEXT   NOT NULL DEFAULT 'raw',
  thread_id  BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS windows_session_seq ON windows (session_id, seq);
CREATE INDEX IF NOT EXISTS windows_session_tier ON windows (session_id, tier);

-- The FTS5 replacement.
--
-- SQLite carried a separate `window_fts` virtual table that the module wrote to
-- by hand, one INSERT per indexed summary. Two stores of the same text, kept in
-- step by remembering to call window_index_summary -- and nothing enforced it,
-- so a summary updated without that call stayed searchable under its old text.
--
-- Here the index is DERIVED from windows.summary, so it cannot disagree with
-- the row it indexes and there is nothing to keep in step. window_index_summary
-- accordingly has no index to write; see the note on that operation.
CREATE INDEX IF NOT EXISTS windows_summary_fts
  ON windows USING GIN (to_tsvector('english', summary));

CREATE TABLE IF NOT EXISTS window_terms (
  -- The C pruned this table by SQLite's implicit rowid, which PostgreSQL has
  -- no equivalent of. An explicit identity column makes the insertion order
  -- the prune depends on a real, declared column instead of an artefact of the
  -- storage engine.
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  window_id BIGINT NOT NULL REFERENCES windows (id) ON DELETE CASCADE,
  term      TEXT   NOT NULL
);

CREATE INDEX IF NOT EXISTS window_terms_window ON window_terms (window_id);
CREATE INDEX IF NOT EXISTS window_terms_term ON window_terms (term);

CREATE TABLE IF NOT EXISTS window_files (
  -- Same rowid replacement as window_terms above; this table's prune keeps the
  -- OLDEST rows, so its ordering column matters even more.
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  window_id BIGINT NOT NULL REFERENCES windows (id) ON DELETE CASCADE,
  file_path TEXT   NOT NULL
);

CREATE INDEX IF NOT EXISTS window_files_window ON window_files (window_id);

-- --------------------------------------------------------------------------
-- User memories
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS user_memories (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind            TEXT NOT NULL DEFAULT 'fact',
  tier            TEXT NOT NULL DEFAULT 'L2',
  key             TEXT NOT NULL,
  content         TEXT NOT NULL DEFAULT '',
  confidence      DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  use_count       BIGINT NOT NULL DEFAULT 0,
  last_used_at    TIMESTAMPTZ DEFAULT NULL,
  lifecycle_state TEXT NOT NULL DEFAULT 'active',
  valid_until     TIMESTAMPTZ DEFAULT NULL,
  source_session  TEXT NOT NULL DEFAULT '',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (kind, key)
);

CREATE INDEX IF NOT EXISTS user_memories_recall
  ON user_memories (kind, lifecycle_state);

-- --------------------------------------------------------------------------
-- Clarification sessions
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS clarify_sessions (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description TEXT NOT NULL,
  status      TEXT NOT NULL DEFAULT 'open',
  score       DOUBLE PRECISION NOT NULL DEFAULT 0,
  spec        TEXT NOT NULL DEFAULT '',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT clarify_sessions_status
    CHECK (status IN ('open', 'ready', 'cancelled'))
);

CREATE TABLE IF NOT EXISTS clarify_qa (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES clarify_sessions (id) ON DELETE CASCADE,
  dimension  TEXT   NOT NULL DEFAULT '',
  question   TEXT   NOT NULL,
  answer     TEXT   NOT NULL DEFAULT '',
  answered   BIGINT NOT NULL DEFAULT 0,
  seq        BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS clarify_qa_session ON clarify_qa (session_id, seq);
