-- Native PostgreSQL schema for the lifecycle family (event kind 11792).
--
-- The work-item tree and everything hanging off it: the audit events, the
-- per-stage attempt counters, the convergence record, and the frozen-create
-- ledger.
--
-- parent_id gets a CHECK that a work item cannot be its own parent.
--
-- That is not cosmetic. Seven recursive walks climb or descend this column, and
-- db1_work_item_set_parent accepted a self-parent -- one such call made every
-- one of those walks spin forever. The walks are bounded now, but a bound turns
-- a hang into a wrong answer; refusing the write is what stops the bad state
-- existing. A CHECK cannot see a longer cycle (A -> B -> A needs to look at
-- another row), so the walks stay bounded as well: the constraint removes the
-- reachable case, the bound contains the rest.

CREATE TABLE IF NOT EXISTS lifecycle_work_item (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_item_id            TEXT NOT NULL UNIQUE,
  repo                    TEXT NOT NULL DEFAULT '',
  proposal_path           TEXT NOT NULL DEFAULT '',
  workflow_name           TEXT NOT NULL DEFAULT 'build',
  workflow_version        TEXT NOT NULL DEFAULT '',
  current_stage           TEXT NOT NULL DEFAULT '',
  state                   TEXT NOT NULL DEFAULT 'active',
  mode                    TEXT NOT NULL DEFAULT 'interactive',
  pause_reason            TEXT NOT NULL DEFAULT '',
  paused_state            TEXT NOT NULL DEFAULT '',
  content_hash            TEXT NOT NULL DEFAULT '',
  pr_ref                  TEXT NOT NULL DEFAULT '',
  worktree                TEXT NOT NULL DEFAULT '',
  submitter               TEXT NOT NULL DEFAULT '',
  cum_cost_usd            DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (cum_cost_usd >= 0),
  reserved_cost_usd       DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (reserved_cost_usd >= 0),
  reservation_state       TEXT NOT NULL DEFAULT '',
  reservation_owner       TEXT NOT NULL DEFAULT '',
  -- NULL until a reservation is held.
  reservation_lease_until TIMESTAMPTZ,
  work_item_max_cost_usd  DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (work_item_max_cost_usd >= 0),
  override_count          BIGINT NOT NULL DEFAULT 0 CHECK (override_count >= 0),
  parent_id               TEXT NOT NULL DEFAULT '',
  source_path             TEXT NOT NULL DEFAULT '',
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (repo, proposal_path),
  CONSTRAINT lifecycle_work_item_not_own_parent CHECK (parent_id <> work_item_id)
);

-- Every tree walk reads by parent_id, and the child counts group by it.
CREATE INDEX IF NOT EXISTS idx_lifecycle_work_item_parent
  ON lifecycle_work_item (parent_id);

-- The admission counts filter by submitter and state; the LRU list orders by
-- updated_at.
CREATE INDEX IF NOT EXISTS idx_lifecycle_work_item_submitter
  ON lifecycle_work_item (submitter, state, created_at);

CREATE INDEX IF NOT EXISTS idx_lifecycle_work_item_lru
  ON lifecycle_work_item (updated_at, work_item_id);

CREATE INDEX IF NOT EXISTS idx_lifecycle_work_item_state
  ON lifecycle_work_item (state);

CREATE INDEX IF NOT EXISTS idx_lifecycle_work_item_pr_ref
  ON lifecycle_work_item (pr_ref) WHERE pr_ref <> '';

CREATE TABLE IF NOT EXISTS lifecycle_event (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_item_id TEXT NOT NULL,
  stage        TEXT NOT NULL DEFAULT '',
  kind         TEXT NOT NULL DEFAULT '',
  actor        TEXT NOT NULL DEFAULT '',
  detail       TEXT NOT NULL DEFAULT '',
  content_hash TEXT NOT NULL DEFAULT '',
  cost_usd     DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The event list is newest-first per work item; id breaks the tie.
CREATE INDEX IF NOT EXISTS idx_lifecycle_event_wi
  ON lifecycle_event (work_item_id, id DESC);

CREATE TABLE IF NOT EXISTS lifecycle_stage_attempt (
  work_item_id TEXT   NOT NULL,
  stage        TEXT   NOT NULL,
  attempts     BIGINT NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  PRIMARY KEY (work_item_id, stage)
);

CREATE TABLE IF NOT EXISTS wfe_convergence (
  work_item_id      TEXT   NOT NULL,
  gate              TEXT   NOT NULL,
  artifact_hash     TEXT   NOT NULL,
  feedback_hash     TEXT   NOT NULL,
  identical_repeats BIGINT NOT NULL CHECK (identical_repeats >= 0),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (work_item_id, gate)
);

CREATE TABLE IF NOT EXISTS wfe_frozen_create (
  parent_id    TEXT NOT NULL,
  path         TEXT NOT NULL,
  work_item_id TEXT NOT NULL,
  content_hash TEXT NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (parent_id, path, work_item_id)
);

CREATE INDEX IF NOT EXISTS idx_wfe_frozen_create_item
  ON wfe_frozen_create (work_item_id);
