-- Native PostgreSQL schema for the roundtable pipeline (event kind 11788).
--
-- Four tables in one hierarchy: a run has passes, a pass has attempts, a run
-- has gates. Every child cascades, so deleting a run does not strand anything.
--
-- The 0/1 integer flags stay BIGINT rather than becoming BOOLEAN, which is a
-- deliberate exception to preferring the native type. These rows are opaque
-- pass-through: the wire carries 36, 33 and 22 fields as text, the module does
-- not interpret most of them, and converting fifteen columns in both directions
-- on every read and write of a wide row would buy nothing but a nicer column
-- type -- while adding a class of column-mapping bug that does not exist today.
-- What the columns DID lack is a statement of what they may hold, so each one
-- now carries a CHECK. That is the part that was actually missing.
--
-- The timestamps become TIMESTAMPTZ. terminal_at and resolved_at are NULLABLE
-- because "not yet" is what they mean when unset; the C spelled that as an
-- empty string in a TEXT column, and the wire still carries '' for a NULL.

CREATE TABLE IF NOT EXISTS roundtable_pipeline_runs (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idea                    TEXT   NOT NULL,
  state                   TEXT   NOT NULL DEFAULT 'drafting',
  phase                   TEXT   NOT NULL DEFAULT 'proposal',
  admission_class         TEXT   NOT NULL DEFAULT 'active',
  schema_version          BIGINT NOT NULL DEFAULT 1,
  done_bar                TEXT   NOT NULL DEFAULT 'zero_blocking',
  brief                   TEXT   NOT NULL DEFAULT '',
  gate_digest             TEXT   NOT NULL DEFAULT '',
  proposal_ref            TEXT   NOT NULL DEFAULT '',
  proposal_origin_hash    TEXT   NOT NULL DEFAULT '',
  diff_ref                TEXT   NOT NULL DEFAULT '',
  diff_origin_hash        TEXT   NOT NULL DEFAULT '',
  chunk_index_ref         TEXT   NOT NULL DEFAULT '',
  repo_root               TEXT   NOT NULL DEFAULT '',
  remote                  TEXT   NOT NULL DEFAULT '',
  base_branch             TEXT   NOT NULL DEFAULT 'testing',
  head_branch             TEXT   NOT NULL DEFAULT '',
  workspace_id            TEXT   NOT NULL DEFAULT '',
  workspace_provider      TEXT   NOT NULL DEFAULT 'shared',
  worktree_path           TEXT   NOT NULL DEFAULT '',
  head_sha                TEXT   NOT NULL DEFAULT '',
  base_sha                TEXT   NOT NULL DEFAULT '',
  proposal_pr_number      BIGINT NOT NULL DEFAULT 0 CHECK (proposal_pr_number >= 0),
  proposal_pr_url         TEXT   NOT NULL DEFAULT '',
  impl_pr_number          BIGINT NOT NULL DEFAULT 0 CHECK (impl_pr_number >= 0),
  impl_pr_url             TEXT   NOT NULL DEFAULT '',
  cost_scope              TEXT   NOT NULL DEFAULT 'roundtable_only',
  cost_source             TEXT   NOT NULL DEFAULT 'roundtable_result',
  cost_version            BIGINT NOT NULL DEFAULT 1,
  proposal_phase_cost_usd DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (proposal_phase_cost_usd >= 0),
  impl_phase_cost_usd     DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (impl_phase_cost_usd >= 0),
  total_cost_usd          DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (total_cost_usd >= 0),
  accepted_question_count BIGINT NOT NULL DEFAULT 0 CHECK (accepted_question_count >= 0),
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The list filters by state and the active count filters by both.
CREATE INDEX IF NOT EXISTS idx_rt_pipeline_runs_state
  ON roundtable_pipeline_runs (state, admission_class);

-- The list orders newest-first; id breaks the tie so a LIMIT is a stable page.
CREATE INDEX IF NOT EXISTS idx_rt_pipeline_runs_updated
  ON roundtable_pipeline_runs (updated_at DESC, id DESC);

-- The branch-owner check asks whether a non-terminal run already holds a head
-- branch, which is the guard against two runs racing on one branch.
CREATE INDEX IF NOT EXISTS idx_rt_pipeline_runs_head_branch
  ON roundtable_pipeline_runs (head_branch);

CREATE TABLE IF NOT EXISTS roundtable_pipeline_passes (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pipeline_id       BIGINT NOT NULL REFERENCES roundtable_pipeline_runs(id) ON DELETE CASCADE,
  phase             TEXT   NOT NULL,
  mode              TEXT   NOT NULL,
  pass_no           BIGINT NOT NULL CHECK (pass_no >= 0),
  status            TEXT   NOT NULL DEFAULT 'open',
  artifact_hash     TEXT   NOT NULL DEFAULT '',
  converged         BIGINT NOT NULL DEFAULT 0 CHECK (converged IN (0, 1)),
  envelope_valid    BIGINT NOT NULL DEFAULT 0 CHECK (envelope_valid IN (0, 1)),
  blocking_count    BIGINT NOT NULL DEFAULT 0 CHECK (blocking_count >= 0),
  suggestion_count  BIGINT NOT NULL DEFAULT 0 CHECK (suggestion_count >= 0),
  nit_count         BIGINT NOT NULL DEFAULT 0 CHECK (nit_count >= 0),
  open_questions    BIGINT NOT NULL DEFAULT 0 CHECK (open_questions >= 0),
  coverage_gaps     BIGINT NOT NULL DEFAULT 0 CHECK (coverage_gaps >= 0),
  items_round       BIGINT NOT NULL DEFAULT 0,
  artifact_round    BIGINT NOT NULL DEFAULT 0,
  best_round        BIGINT NOT NULL DEFAULT 0,
  rounds_run        BIGINT NOT NULL DEFAULT 0 CHECK (rounds_run >= 0),
  cost_usd          DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (cost_usd >= 0),
  result_hash       TEXT   NOT NULL DEFAULT '',
  is_chunked        BIGINT NOT NULL DEFAULT 0 CHECK (is_chunked IN (0, 1)),
  chunk_total       BIGINT NOT NULL DEFAULT 0 CHECK (chunk_total >= 0),
  chunk_done        BIGINT NOT NULL DEFAULT 0 CHECK (chunk_done >= 0),
  synthesis_done    BIGINT NOT NULL DEFAULT 0 CHECK (synthesis_done IN (0, 1)),
  chunk_group       BIGINT NOT NULL DEFAULT 0 CHECK (chunk_group >= 0),
  -- chunk_index is negative for the synthesis member, which is how the group
  -- aggregate tells a whole-artifact check from a chunk.
  chunk_index       BIGINT NOT NULL DEFAULT 0,
  answered_count    BIGINT NOT NULL DEFAULT 0 CHECK (answered_count >= 0),
  chunk_offset      BIGINT NOT NULL DEFAULT 0 CHECK (chunk_offset >= 0),
  chunk_len         BIGINT NOT NULL DEFAULT 0 CHECK (chunk_len >= 0),
  chunk_omitted     BIGINT NOT NULL DEFAULT 0 CHECK (chunk_omitted >= 0),
  chunk_over_budget BIGINT NOT NULL DEFAULT 0 CHECK (chunk_over_budget IN (0, 1)),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (pipeline_id, phase, pass_no)
);

CREATE INDEX IF NOT EXISTS idx_rt_pipeline_passes_pipeline
  ON roundtable_pipeline_passes (pipeline_id, id);

-- The group aggregate reads every member of one chunk group.
CREATE INDEX IF NOT EXISTS idx_rt_pipeline_passes_group
  ON roundtable_pipeline_passes (pipeline_id, phase, chunk_group);

CREATE TABLE IF NOT EXISTS roundtable_pipeline_attempts (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pass_id         BIGINT NOT NULL REFERENCES roundtable_pipeline_passes(id) ON DELETE CASCADE,
  attempt_no      BIGINT NOT NULL CHECK (attempt_no >= 0),
  run_id          TEXT   NOT NULL DEFAULT '',
  is_current      BIGINT NOT NULL DEFAULT 1 CHECK (is_current IN (0, 1)),
  capture_status  TEXT   NOT NULL DEFAULT 'pending',
  terminal_status TEXT   NOT NULL DEFAULT '',
  parse_status    TEXT   NOT NULL DEFAULT '',
  envelope_valid  BIGINT NOT NULL DEFAULT 0 CHECK (envelope_valid IN (0, 1)),
  items_truncated BIGINT NOT NULL DEFAULT 0 CHECK (items_truncated IN (0, 1)),
  truncated       BIGINT NOT NULL DEFAULT 0 CHECK (truncated IN (0, 1)),
  degraded        BIGINT NOT NULL DEFAULT 0 CHECK (degraded IN (0, 1)),
  cost_capped     BIGINT NOT NULL DEFAULT 0 CHECK (cost_capped IN (0, 1)),
  deadline_hit    BIGINT NOT NULL DEFAULT 0 CHECK (deadline_hit IN (0, 1)),
  cancelled       BIGINT NOT NULL DEFAULT 0 CHECK (cancelled IN (0, 1)),
  lost_result     BIGINT NOT NULL DEFAULT 0 CHECK (lost_result IN (0, 1)),
  result_hash     TEXT   NOT NULL DEFAULT '',
  result_snapshot TEXT   NOT NULL DEFAULT '',
  cost_usd        DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (cost_usd >= 0),
  cost_known      BIGINT NOT NULL DEFAULT 0 CHECK (cost_known IN (0, 1)),
  submitted_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- NULL until the attempt reaches a terminal state. The C spelled that as an
  -- empty string in a TEXT column; the wire still carries '' for a NULL.
  terminal_at     TIMESTAMPTZ,
  UNIQUE (pass_id, attempt_no)
);

CREATE INDEX IF NOT EXISTS idx_rt_pipeline_attempts_run
  ON roundtable_pipeline_attempts (run_id);

-- The current-attempt lookup and the supersede both read by pass.
CREATE INDEX IF NOT EXISTS idx_rt_pipeline_attempts_pass
  ON roundtable_pipeline_attempts (pass_id, is_current);

CREATE TABLE IF NOT EXISTS roundtable_pipeline_gates (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pipeline_id       BIGINT NOT NULL REFERENCES roundtable_pipeline_runs(id) ON DELETE CASCADE,
  gate_no           BIGINT NOT NULL CHECK (gate_no >= 0),
  verdict           TEXT   NOT NULL DEFAULT '',
  reason            TEXT   NOT NULL DEFAULT '',
  actor             TEXT   NOT NULL DEFAULT '',
  pr_number         BIGINT NOT NULL DEFAULT 0 CHECK (pr_number >= 0),
  expected_head_sha TEXT   NOT NULL DEFAULT '',
  merge_sha         TEXT   NOT NULL DEFAULT '',
  merge_executor    TEXT   NOT NULL DEFAULT '',
  merge_command     TEXT   NOT NULL DEFAULT '',
  merge_output      TEXT   NOT NULL DEFAULT '',
  merge_exit_code   BIGINT NOT NULL DEFAULT 0,
  resolved_at       TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Gate reads take the newest gate for a (pipeline, gate_no), so id is part of
-- the index rather than an afterthought.
CREATE INDEX IF NOT EXISTS idx_rt_pipeline_gates_pipeline
  ON roundtable_pipeline_gates (pipeline_id, gate_no, id DESC);
