-- Telemetry family: token accounting, cost folding, interaction events,
-- guardrail events, evaluation results, and diagnoses.

-- --------------------------------------------------------------------------
-- Token audit
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS token_audit (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id         TEXT   NOT NULL DEFAULT '',
  delegation_id      TEXT   NOT NULL DEFAULT '',
  project_name       TEXT   NOT NULL DEFAULT '',
  tool_name          TEXT   NOT NULL DEFAULT '',
  role               TEXT   NOT NULL DEFAULT '',
  model              TEXT   NOT NULL DEFAULT '',
  source             TEXT   NOT NULL DEFAULT '',
  requested_model    TEXT   NOT NULL DEFAULT '',
  stop_reason        TEXT   NOT NULL DEFAULT '',
  usage_kind         TEXT   NOT NULL DEFAULT 'realized',
  agent_log_id       BIGINT NOT NULL DEFAULT 0,
  request_id         TEXT   NOT NULL DEFAULT '',
  idempotency_key    TEXT   NOT NULL DEFAULT '',
  attempt            BIGINT NOT NULL DEFAULT 0,
  principal          TEXT   NOT NULL DEFAULT '',
  served_model       TEXT   NOT NULL DEFAULT '',
  duration_ms        BIGINT NOT NULL DEFAULT 0 CHECK (duration_ms >= 0),
  metadata           TEXT   NOT NULL DEFAULT '',
  prompt_tokens      BIGINT NOT NULL DEFAULT 0 CHECK (prompt_tokens >= 0),
  completion_tokens  BIGINT NOT NULL DEFAULT 0 CHECK (completion_tokens >= 0),
  cache_write_tokens BIGINT NOT NULL DEFAULT 0 CHECK (cache_write_tokens >= 0),
  cache_read_tokens  BIGINT NOT NULL DEFAULT 0 CHECK (cache_read_tokens >= 0),
  -- Money. NUMERIC rather than the C's double, because a spend total summed
  -- from a few thousand binary floats does not add up to what the individual
  -- charges say it should, and this column is what a bill is reconciled
  -- against.
  estimated_cost_usd NUMERIC(20, 10) NOT NULL DEFAULT 0 CHECK (estimated_cost_usd >= 0),
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The idempotency guard. The C created this index from a separate operation
-- the caller had to remember to call (token_audit_ensure_idem_index), so a
-- store that had never been asked accepted duplicate charges silently. Here it
-- is part of the schema, which is the only way a uniqueness rule is actually a
-- rule.
CREATE UNIQUE INDEX IF NOT EXISTS token_audit_idempotency
  ON token_audit (source, principal, idempotency_key, attempt)
  WHERE idempotency_key <> '';

CREATE INDEX IF NOT EXISTS token_audit_delegation ON token_audit (delegation_id);
CREATE INDEX IF NOT EXISTS token_audit_session ON token_audit (session_id);
CREATE INDEX IF NOT EXISTS token_audit_recent ON token_audit (created_at DESC);
CREATE INDEX IF NOT EXISTS token_audit_usage_kind ON token_audit (usage_kind, created_at DESC);

-- --------------------------------------------------------------------------
-- Cost folding
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS cost_fold_log (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_session_id TEXT NOT NULL,
  child_session_id  TEXT NOT NULL,
  cost_usd          NUMERIC(20, 10) NOT NULL DEFAULT 0 CHECK (cost_usd >= 0),
  cost_source       TEXT NOT NULL DEFAULT '',
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- A child's cost folds into its parent exactly once. This is what makes the
  -- record idempotent: a repeated fold updates rather than double-counting.
  UNIQUE (parent_session_id, child_session_id),
  -- A session cannot be its own parent, which would fold its cost into itself
  -- and double every total that reads it.
  CONSTRAINT cost_fold_not_self CHECK (parent_session_id <> child_session_id)
);

CREATE INDEX IF NOT EXISTS cost_fold_parent ON cost_fold_log (parent_session_id);

-- --------------------------------------------------------------------------
-- Interaction events
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS interaction_events (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  session_id   TEXT NOT NULL DEFAULT '',
  event_type   TEXT NOT NULL,
  actor        TEXT NOT NULL DEFAULT 'agent',
  payload      TEXT NOT NULL DEFAULT '{}',
  outcome      TEXT NOT NULL DEFAULT 'ok',
  -- NULL means "not yet". These are the columns the unreflected and promotion
  -- feeds select on, so the absence has to be representable.
  reflected_at TIMESTAMPTZ,
  promoted_at  TIMESTAMPTZ,
  -- Promotion follows reflection: an event cannot be promoted out of a feed it
  -- was never reflected into.
  CONSTRAINT interaction_events_promotion_follows_reflection
    CHECK (promoted_at IS NULL OR reflected_at IS NOT NULL)
);

-- The two feeds read exactly these slices.
CREATE INDEX IF NOT EXISTS interaction_events_unreflected
  ON interaction_events (id) WHERE reflected_at IS NULL;

CREATE INDEX IF NOT EXISTS interaction_events_promotion_feed
  ON interaction_events (id) WHERE reflected_at IS NOT NULL AND promoted_at IS NULL;

CREATE INDEX IF NOT EXISTS interaction_events_session
  ON interaction_events (session_id, id DESC);

-- --------------------------------------------------------------------------
-- Guardrail events
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS guardrail_events (
  id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id             TEXT NOT NULL DEFAULT '',
  recorded_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  tool_name              TEXT NOT NULL DEFAULT '',
  overall_risk           DOUBLE PRECISION NOT NULL DEFAULT 0,
  action_risk            DOUBLE PRECISION NOT NULL DEFAULT 0,
  diff_risk              DOUBLE PRECISION NOT NULL DEFAULT 0,
  drift_risk             DOUBLE PRECISION NOT NULL DEFAULT 0,
  antipattern_similarity DOUBLE PRECISION NOT NULL DEFAULT 0,
  recommendation         TEXT NOT NULL DEFAULT '',
  labels                 TEXT NOT NULL DEFAULT '',
  final_action           TEXT NOT NULL DEFAULT '',
  explanation            TEXT NOT NULL DEFAULT '',
  -- A guardrail that only observed is not a guardrail that acted. This stays a
  -- boolean rather than the C's 0/1 integer so a reader cannot mistake 2 for
  -- some third mode.
  dry_run                BOOLEAN NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS guardrail_events_recent ON guardrail_events (recorded_at DESC);
CREATE INDEX IF NOT EXISTS guardrail_events_session
  ON guardrail_events (session_id, recorded_at DESC);

-- --------------------------------------------------------------------------
-- Evaluation results
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS eval_results (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  suite              TEXT   NOT NULL,
  task_name          TEXT   NOT NULL DEFAULT '',
  agent_name         TEXT   NOT NULL DEFAULT '',
  ablation           TEXT   NOT NULL DEFAULT 'full',
  success            BOOLEAN NOT NULL DEFAULT false,
  turns              BIGINT NOT NULL DEFAULT 0 CHECK (turns >= 0),
  tool_calls         BIGINT NOT NULL DEFAULT 0 CHECK (tool_calls >= 0),
  tool_call_failures BIGINT NOT NULL DEFAULT 0 CHECK (tool_call_failures >= 0),
  rescue_recoveries  BIGINT NOT NULL DEFAULT 0 CHECK (rescue_recoveries >= 0),
  prompt_tokens      BIGINT NOT NULL DEFAULT 0 CHECK (prompt_tokens >= 0),
  completion_tokens  BIGINT NOT NULL DEFAULT 0 CHECK (completion_tokens >= 0),
  latency_ms         BIGINT NOT NULL DEFAULT 0 CHECK (latency_ms >= 0),
  response           TEXT   NOT NULL DEFAULT '',
  -- '' rather than NULL: the wire carries text with no null, and a reader
  -- asking "did this fail" reads success, not whether this is set.
  error              TEXT   NOT NULL DEFAULT '',
  dataset_hash       TEXT   NOT NULL DEFAULT '',
  target_hash        TEXT   NOT NULL DEFAULT '',
  harness_version    TEXT   NOT NULL DEFAULT '1',
  hardware_profile   TEXT   NOT NULL DEFAULT '',
  seed               BIGINT NOT NULL DEFAULT 0,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- A run cannot have failed more tool calls than it made.
  CONSTRAINT eval_results_failures_within_calls
    CHECK (tool_call_failures <= tool_calls)
);

CREATE INDEX IF NOT EXISTS eval_results_suite ON eval_results (suite, created_at DESC);
CREATE INDEX IF NOT EXISTS eval_results_outcome ON eval_results (success, created_at DESC);

-- --------------------------------------------------------------------------
-- Diagnoses
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS diagnoses (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symptom    TEXT NOT NULL,
  status     TEXT NOT NULL DEFAULT 'active',
  conclusion TEXT NOT NULL DEFAULT '',
  confidence DOUBLE PRECISION NOT NULL DEFAULT 0
               CHECK (confidence >= 0 AND confidence <= 1),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT diagnoses_status
    CHECK (status IN ('active', 'concluded', 'abandoned')),
  -- A concluded diagnosis says what it concluded. Concluding with nothing is
  -- indistinguishable from never having concluded, and the caller cannot tell
  -- which happened.
  CONSTRAINT diagnoses_conclusion_when_concluded
    CHECK (status <> 'concluded' OR conclusion <> '')
);

CREATE INDEX IF NOT EXISTS diagnoses_recent ON diagnoses (updated_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS diagnosis_items (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  diagnosis_id  BIGINT NOT NULL REFERENCES diagnoses (id) ON DELETE CASCADE,
  kind          TEXT   NOT NULL,
  -- NULL means "this item hangs off nothing" -- an observation, or a
  -- hypothesis. Evidence names the hypothesis it bears on.
  --
  -- The WIRE spells that 0, and the module maps between them, which is what
  -- lets this carry a reference: a foreign key holds for every non-null value,
  -- and no item has id 0. Without it, evidence could name a hypothesis that
  -- had been deleted, and the ranking would count it toward nothing while
  -- still reading it out of the table.
  parent_id     BIGINT REFERENCES diagnosis_items (id) ON DELETE CASCADE,
  content       TEXT   NOT NULL,
  source        TEXT   NOT NULL DEFAULT '',
  evidence_rank BIGINT NOT NULL DEFAULT 4 CHECK (evidence_rank BETWEEN 1 AND 4),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT diagnosis_items_kind
    CHECK (kind IN ('observation', 'hypothesis', 'evidence_for',
                    'evidence_against', 'probe')),
  -- Evidence bears on a hypothesis; nothing else does. An evidence row with no
  -- parent is counted toward no hypothesis and is invisible to the ranking,
  -- which is the same as not having been recorded.
  CONSTRAINT diagnosis_items_evidence_has_a_parent
    CHECK ((kind IN ('evidence_for', 'evidence_against')) = (parent_id IS NOT NULL)),
  -- An item cannot bear on itself.
  CONSTRAINT diagnosis_items_not_own_parent CHECK (parent_id <> id)
);

CREATE INDEX IF NOT EXISTS diagnosis_items_diagnosis
  ON diagnosis_items (diagnosis_id, id);

CREATE INDEX IF NOT EXISTS diagnosis_items_parent
  ON diagnosis_items (parent_id) WHERE parent_id IS NOT NULL;
