-- Agent-work family: the agent log, coordination jobs and their tasks, cron
-- jobs and their runs, trigger runs, and the cognify queue.

-- --------------------------------------------------------------------------
-- Agent log
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS agent_log (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_name        TEXT   NOT NULL DEFAULT '',
  role              TEXT   NOT NULL,
  input             TEXT   NOT NULL DEFAULT '',
  output            TEXT   NOT NULL DEFAULT '',
  prompt_tokens     BIGINT NOT NULL DEFAULT 0 CHECK (prompt_tokens >= 0),
  completion_tokens BIGINT NOT NULL DEFAULT 0 CHECK (completion_tokens >= 0),
  latency_ms        BIGINT NOT NULL DEFAULT 0 CHECK (latency_ms >= 0),
  success           BOOLEAN NOT NULL DEFAULT false,
  -- '' rather than NULL: the wire carries text with no null, and every reader
  -- asks `success`, not whether this is set.
  error             TEXT   NOT NULL DEFAULT '',
  -- -1 means "not scored". A confidence of 0 is a real answer and a very
  -- different one, which is why the absence needs its own value.
  confidence        BIGINT NOT NULL DEFAULT -1 CHECK (confidence BETWEEN -1 AND 100),
  turns             BIGINT NOT NULL DEFAULT 0 CHECK (turns >= 0),
  tool_calls        BIGINT NOT NULL DEFAULT 0 CHECK (tool_calls >= 0),
  session_id        TEXT   NOT NULL DEFAULT '',
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The recent-first reads: agent_log is written once per delegate turn and read
-- newest-first, by everything and by agent.
CREATE INDEX IF NOT EXISTS idx_agent_log_recent ON agent_log (id DESC);
CREATE INDEX IF NOT EXISTS idx_agent_log_agent ON agent_log (agent_name, id DESC);

CREATE INDEX IF NOT EXISTS agent_log_recent ON agent_log (id DESC);
CREATE INDEX IF NOT EXISTS agent_log_session ON agent_log (session_id, id DESC)
  WHERE session_id <> '';
CREATE INDEX IF NOT EXISTS agent_log_role ON agent_log (role, created_at DESC);
CREATE INDEX IF NOT EXISTS agent_log_failures
  ON agent_log (created_at DESC) WHERE NOT success;

-- --------------------------------------------------------------------------
-- Coordination jobs and tasks
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS coord_jobs (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Names an execution_plans row in the workflow family. No reference: each
  -- family's schema loads on its own and a cross-file key would make the order
  -- matter. 0 means "no plan".
  plan_id        BIGINT NOT NULL DEFAULT 0,
  status         TEXT   NOT NULL DEFAULT 'pending',
  max_concurrent BIGINT NOT NULL DEFAULT 3 CHECK (max_concurrent > 0),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT coord_jobs_status
    CHECK (status IN ('pending', 'running', 'done', 'failed', 'cancelled'))
);

CREATE TABLE IF NOT EXISTS coord_job_tasks (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id           BIGINT NOT NULL REFERENCES coord_jobs (id) ON DELETE CASCADE,
  step_id          BIGINT,
  status           TEXT   NOT NULL DEFAULT 'pending',
  claimed_by       TEXT   NOT NULL DEFAULT '',
  claimed_at       TIMESTAMPTZ,
  -- A JSON array of the paths this task will touch. Stored as JSONB so the
  -- conflict check is a set operation the database can do, rather than a
  -- parse-and-compare loop in the module against a fixed-size array of the
  -- tasks it happened to read.
  files            JSONB  NOT NULL DEFAULT '[]'::jsonb,
  role             TEXT   NOT NULL DEFAULT 'execute',
  persona          TEXT   NOT NULL DEFAULT 'engineer',
  prompt           TEXT   NOT NULL DEFAULT '',
  cwd              TEXT   NOT NULL DEFAULT '',
  result           TEXT   NOT NULL DEFAULT '',
  error            TEXT   NOT NULL DEFAULT '',
  preempt_requeues BIGINT NOT NULL DEFAULT 0 CHECK (preempt_requeues >= 0),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT coord_task_status
    CHECK (status IN ('pending', 'claimed', 'running', 'done', 'failed')),
  -- files is an ARRAY of paths. A task whose files are an object or a bare
  -- string would silently conflict with nothing -- the C's overlap check
  -- returned "no conflict" whenever either document failed to parse, so a
  -- malformed task was handed out alongside anything.
  CONSTRAINT coord_task_files_is_array
    CHECK (jsonb_typeof(files) = 'array'),
  -- A claimed task says who holds it and since when.
  CONSTRAINT coord_task_claim_together
    CHECK ((claimed_by <> '') = (claimed_at IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS coord_task_job ON coord_job_tasks (job_id, id);

-- claim_next reads exactly this slice.
CREATE INDEX IF NOT EXISTS coord_task_pending
  ON coord_job_tasks (job_id, id) WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS coord_task_holding
  ON coord_job_tasks (job_id) WHERE status IN ('claimed', 'running');

-- The conflict check asks whether any held task shares a path.
CREATE INDEX IF NOT EXISTS coord_task_files ON coord_job_tasks USING GIN (files);

-- --------------------------------------------------------------------------
-- Cron jobs and runs
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS cron_jobs (
  id                       TEXT PRIMARY KEY,
  schedule                 TEXT NOT NULL,
  mode                     TEXT NOT NULL CHECK (mode IN ('script', 'llm', 'hybrid')),
  script                   TEXT NOT NULL DEFAULT '',
  prompt                   TEXT NOT NULL DEFAULT '',
  skills_csv               TEXT NOT NULL DEFAULT '',
  workdir                  TEXT NOT NULL DEFAULT '',
  deliver_target           TEXT NOT NULL DEFAULT '',
  deliver_only_if_changed  BOOLEAN NOT NULL DEFAULT false,
  deliver_first_run_silent BOOLEAN NOT NULL DEFAULT false,
  context_from             TEXT NOT NULL DEFAULT '',
  when_context_contains    TEXT NOT NULL DEFAULT '',
  pre_wake_gate            BOOLEAN NOT NULL DEFAULT false,
  enabled                  BOOLEAN NOT NULL DEFAULT true,
  -- These stay epoch seconds: they are the caller's clock, compared against
  -- the scheduler's, and converting them here would put this store's idea of
  -- now between the two.
  next_run_at              BIGINT NOT NULL DEFAULT 0,
  last_run_at              BIGINT NOT NULL DEFAULT 0,
  last_run_status          TEXT NOT NULL DEFAULT '',
  last_run_output_hash     TEXT NOT NULL DEFAULT '',
  created_at               BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM now())::bigint,

  -- A job must have something to run. A script-mode job with no script, or an
  -- llm-mode job with no prompt, fires forever and does nothing.
  CONSTRAINT cron_jobs_has_work
    CHECK ((mode = 'script' AND script <> '')
        OR (mode = 'llm'    AND prompt <> '')
        OR (mode = 'hybrid' AND script <> '' AND prompt <> ''))
);

CREATE INDEX IF NOT EXISTS cron_jobs_due
  ON cron_jobs (next_run_at) WHERE enabled;

CREATE TABLE IF NOT EXISTS cron_job_runs (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id       TEXT   NOT NULL REFERENCES cron_jobs (id) ON DELETE CASCADE,
  started_at   BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM now())::bigint,
  completed_at BIGINT NOT NULL DEFAULT 0,
  status       TEXT   NOT NULL DEFAULT '',
  silent       BOOLEAN NOT NULL DEFAULT false,
  delivered    BOOLEAN NOT NULL DEFAULT false,
  output       TEXT   NOT NULL DEFAULT '',
  error        TEXT   NOT NULL DEFAULT '',
  output_hash  TEXT   NOT NULL DEFAULT ''
);

-- ON DELETE CASCADE, where the C had a plain reference: deleting a job left its
-- run history behind pointing at a job that no longer existed, and the history
-- read would keep returning it.
CREATE INDEX IF NOT EXISTS cron_job_runs_job ON cron_job_runs (job_id, id DESC);

-- --------------------------------------------------------------------------
-- Trigger runs
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS trigger_runs (
  id          TEXT PRIMARY KEY,
  source      TEXT NOT NULL,
  event       TEXT NOT NULL DEFAULT '',
  task        TEXT NOT NULL,
  workspace   TEXT NOT NULL DEFAULT '',
  metadata    TEXT NOT NULL DEFAULT '{}',
  pipeline_id TEXT NOT NULL DEFAULT '',
  status      TEXT NOT NULL DEFAULT 'queued',
  queued_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  started_at  TIMESTAMPTZ,
  finished_at TIMESTAMPTZ,
  error       TEXT NOT NULL DEFAULT '',

  CONSTRAINT trigger_runs_status
    CHECK (status IN ('queued', 'running', 'done', 'failed', 'cancelled')),
  -- A run that finished started first. The C set the two from separate
  -- statements and nothing tied them together, so a run could read as finished
  -- without ever having started.
  CONSTRAINT trigger_runs_finish_after_start
    CHECK (finished_at IS NULL OR started_at IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS trigger_runs_recent ON trigger_runs (queued_at DESC);

-- --------------------------------------------------------------------------
-- The cognify queue
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS memory_cognify_jobs (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind         TEXT   NOT NULL DEFAULT 'cognify_unit',
  memory_id    BIGINT NOT NULL,
  status       TEXT   NOT NULL DEFAULT 'pending',
  attempts     BIGINT NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  max_attempts BIGINT NOT NULL DEFAULT 3 CHECK (max_attempts > 0),
  last_error   TEXT   NOT NULL DEFAULT '',
  claimed_by   TEXT   NOT NULL DEFAULT '',
  claimed_at   TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (kind, memory_id),
  CONSTRAINT cognify_status
    CHECK (status IN ('pending', 'running', 'done', 'failed')),
  CONSTRAINT cognify_claim_together
    CHECK ((claimed_by <> '') = (claimed_at IS NOT NULL))
);

-- claim_next reads exactly this slice, oldest first.
CREATE INDEX IF NOT EXISTS cognify_pending
  ON memory_cognify_jobs (id) WHERE status = 'pending';
