package providers

// Built-in discovery profiles migrated from the native registry. Saved account
// connections are separate records; these entries are suggestions for setup.
var profiles = []object{
	{"name": "openai", "display_name": "OpenAI", "description": "OpenAI API (GPT-4o, o1, o3, ...)", "base_url": "https://api.openai.com/v1", "models_url": "https://api.openai.com/v1/models", "signup_url": "https://platform.openai.com/api-keys", "auth_type": "api_key", "default_model": "gpt-4o", "default_aux_model": "gpt-4o-mini", "env_vars": []string{"OPENAI_API_KEY"}, "routable_models": []string{"gpt-5.6-sol", "gpt-5.6-terra", "gpt-5.6-luna"}, "fallback_models": []string{}, "default_headers": []string{}, "fixed_temperature": -1, "default_max_tokens": 8192, "api_mode": 0},
	{"name": "anthropic", "display_name": "Anthropic", "description": "Anthropic Claude API (claude-sonnet, claude-opus, claude-haiku)", "base_url": "https://api.anthropic.com/v1", "models_url": "https://api.anthropic.com/v1/models", "signup_url": "https://console.anthropic.com/account/keys", "auth_type": "x-api-key", "default_model": "claude-sonnet-4-6", "default_aux_model": "claude-haiku-4-5-20251001", "env_vars": []string{"ANTHROPIC_API_KEY"}, "routable_models": []string{"claude-opus-4-8", "claude-sonnet-5", "claude-haiku-4-5"}, "fallback_models": []string{}, "default_headers": []string{"anthropic-version", "2023-06-01"}, "fixed_temperature": -1, "default_max_tokens": 8192, "api_mode": 2},
	{"name": "ollama", "display_name": "Ollama (local)", "description": "Ollama local model server (OpenAI-compatible /v1 API)", "base_url": "http://localhost:11434/v1", "models_url": "http://localhost:11434/api/tags", "signup_url": "https://ollama.com", "auth_type": "none", "default_model": "qwen3:1.7b", "default_aux_model": "qwen3:0.6b", "env_vars": []string{}, "fallback_models": []string{}, "default_headers": []string{}, "fixed_temperature": -1, "default_max_tokens": 4096, "api_mode": 0},
	{"name": "llama_native", "display_name": "llama.cpp (local)", "description": "llama.cpp server \u2014 native or OpenAI-compatible API", "base_url": "http://localhost:8080/v1", "models_url": "http://localhost:8080/v1/models", "signup_url": "https://github.com/ggerganov/llama.cpp", "auth_type": "none", "default_model": "local", "default_aux_model": "local", "env_vars": []string{}, "fallback_models": []string{}, "default_headers": []string{}, "fixed_temperature": -1, "default_max_tokens": 4096, "api_mode": 3},
	{"name": "openrouter", "display_name": "OpenRouter", "description": "OpenAI-compatible routing layer for 200+ models", "base_url": "https://openrouter.ai/api/v1", "models_url": "https://openrouter.ai/api/v1/models", "signup_url": "https://openrouter.ai/keys", "auth_type": "api_key", "default_model": "anthropic/claude-opus-4.7", "default_aux_model": "google/gemini-2.5-flash", "env_vars": []string{"OPENROUTER_API_KEY"}, "fallback_models": []string{"anthropic/claude-opus-4.7", "google/gemini-2.5-flash", "mistralai/mistral-large-2512"}, "default_headers": []string{"HTTP-Referer", "https://github.com/JBailes/aimee", "X-Title", "aimee"}, "fixed_temperature": -1, "default_max_tokens": 8192, "api_mode": 0},
	{"name": "mistral", "display_name": "Mistral AI", "description": "Mistral API (Codestral, Mistral Large, Mistral Small)", "base_url": "https://api.mistral.ai/v1", "models_url": "https://api.mistral.ai/v1/models", "signup_url": "https://console.mistral.ai/api-keys", "auth_type": "api_key", "default_model": "mistral-large-latest", "default_aux_model": "mistral-small-latest", "env_vars": []string{"MISTRAL_API_KEY"}, "fallback_models": []string{"mistral-large-latest", "mistral-small-latest"}, "default_headers": []string{}, "fixed_temperature": -1, "default_max_tokens": 8192, "api_mode": 0},
	{"name": "minimax", "display_name": "MiniMax", "description": "MiniMax API (MiniMax-M3)", "base_url": "https://api.minimax.io/v1", "models_url": "https://api.minimax.io/v1/models", "signup_url": "https://platform.minimax.io", "auth_type": "api_key", "default_model": "MiniMax-M3", "default_aux_model": "MiniMax-M3", "env_vars": []string{"MINIMAX_API_KEY"}, "routable_models": []string{"MiniMax-M3"}, "fallback_models": []string{"MiniMax-M2.7"}, "default_headers": []string{}, "fixed_temperature": -1, "default_max_tokens": 8192, "api_mode": 0},
}

func profile(name string) object { return find(profiles, name) }
