package db2

// Code generated by scripts/gen_db2_live_probes.py. DO NOT EDIT.
//
// One probe per catalogued operation that has no hand-written one. Each
// sends the contract's minimum-valid request and asserts only that the
// operation ran and its reply decodes -- which is what proves the statement
// parses and binds against a real schema.
//
// The parity run is what checks the ANSWERS: it replays the C's own requests
// and compares them byte for byte. These exist so no operation can be added
// without something having run it against Postgres.

import (
	"testing"

	db2contract "github.com/JBailes/aimee/server-go/db2"
)

func liveGeneratedProbes() []liveRequest {
	return []liveRequest{
		{
			name:      "lifecycle.health",
			stage:     db2contract.StageHealth,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeHealthRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "lifecycle.embedding_dimension",
			stage:     db2contract.StageEmbeddingDimension,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeEmbeddingDimensionRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, _, err := db2contract.DecodeEmbeddingDimensionReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "lifecycle.pool_status",
			stage:     db2contract.StagePoolStatus,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodePoolStatusRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, _, err := db2contract.DecodePoolStatusReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "lifecycle.embedding_refusals",
			stage:     db2contract.StageEmbeddingRefusals,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeEmbeddingRefusalsRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, _, err := db2contract.DecodeEmbeddingRefusalsReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "lifecycle.postgres_status",
			stage:     db2contract.StagePostgresStatus,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodePostgresStatusRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, _, err := db2contract.DecodePostgresStatusReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "lifecycle.reembed_status",
			stage:     db2contract.StageReembedStatus,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeReembedStatusRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, _, err := db2contract.DecodeReembedStatusReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "lifecycle.reembed_clear",
			stage:     db2contract.StageReembedClear,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeReembedClearRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeReembedClearReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "lifecycle.reembed_clear_maintenance",
			stage:     db2contract.StageReembedClearMaintenance,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeReembedClearMaintenanceRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				if _, _, err := db2contract.DecodeReembedClearMaintenanceReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "lifecycle.embedder_serving_id",
			stage:     db2contract.StageEmbedderServingID,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeEmbedderServingIDRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, _, err := db2contract.DecodeEmbedderServingIDReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "lifecycle.dimension_reset",
			stage:     db2contract.StageDimensionReset,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeDimensionResetRequest(1, 1, 1)
			},
			decoded: func(t *testing.T, body []byte) {
				if _, _, err := db2contract.DecodeDimensionResetReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.level3_count",
			stage:     db2contract.StageLevel3Count,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeLevel3CountRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeLevel3CountReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.level2_count",
			stage:     db2contract.StageLevel2Count,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeLevel2CountRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeLevel2CountReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.orphaned_l0_count",
			stage:     db2contract.StageOrphanedL0Count,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeOrphanedL0CountRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeOrphanedL0CountReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.total_count",
			stage:     db2contract.StageTotalCount,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeTotalCountRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeTotalCountReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.session_l2_count",
			stage:     db2contract.StageSessionL2Count,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeSessionL2CountRequest("a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeSessionL2CountReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.key_exists",
			stage:     db2contract.StageKeyExists,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeKeyExistsRequest("a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeKeyExistsReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.find_id_by_key_kind",
			stage:     db2contract.StageFindIDByKeyKind,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeFindIDByKeyKindRequest("a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, _, err := db2contract.DecodeFindIDByKeyKindReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.key_exists_in_tier_pair",
			stage:     db2contract.StageKeyExistsInTierPair,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeKeyExistsInTierPairRequest("a", "a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeKeyExistsInTierPairReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.effectiveness_update",
			stage:     db2contract.StageEffectivenessUpdate,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeEffectivenessUpdateRequest(1, 1, 1)
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeEffectivenessUpdateReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.retention_enforce",
			stage:     db2contract.StageRetentionEnforce,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeRetentionEnforceRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeRetentionEnforceReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.effectiveness_demote",
			stage:     db2contract.StageEffectivenessDemote,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeEffectivenessDemoteRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeEffectivenessDemoteReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.effectiveness_stats",
			stage:     db2contract.StageEffectivenessStats,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeEffectivenessStatsRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeEffectivenessStatsReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.l2_memory_ids",
			stage:     db2contract.StageL2MemoryIDs,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeL2MemoryIDsRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeL2MemoryIDsReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.health_record",
			stage:     db2contract.StageHealthRecord,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeHealthRecordRequest(1, 1, 1)
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "memory.health_retention",
			stage:     db2contract.StageHealthRetention,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeHealthRetentionRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, _, err := db2contract.DecodeHealthRetentionReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.health_counters",
			stage:     db2contract.StageHealthCounters,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeHealthCountersRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeHealthCountersReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.stats_counts",
			stage:     db2contract.StageStatsCounts,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeStatsCountsRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeStatsCountsReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.expire",
			stage:     db2contract.StageExpire,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeExpireRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, _, err := db2contract.DecodeExpireReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.demote",
			stage:     db2contract.StageDemote,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeDemoteRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, _, err := db2contract.DecodeDemoteReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.promote_stable",
			stage:     db2contract.StagePromoteStable,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodePromoteStableRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodePromoteStableReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.reclassify_directives",
			stage:     db2contract.StageReclassifyDirectives,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeReclassifyDirectivesRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeReclassifyDirectivesReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.record_l4_approval",
			stage:     db2contract.StageRecordL4Approval,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeRecordL4ApprovalRequest(1, "a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "memory.prune_orphaned_l0",
			stage:     db2contract.StagePruneOrphanedL0,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodePruneOrphanedL0Request(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodePruneOrphanedL0Reply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.lifecycle_sweep_expired",
			stage:     db2contract.StageLifecycleSweepExpired,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeLifecycleSweepExpiredRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeLifecycleSweepExpiredReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.demote_id",
			stage:     db2contract.StageDemoteID,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeDemoteIDRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeDemoteIDReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.has_workspace_tag",
			stage:     db2contract.StageHasWorkspaceTag,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeHasWorkspaceTagRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeHasWorkspaceTagReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.delete_row",
			stage:     db2contract.StageDeleteRow,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeDeleteRowRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeDeleteRowReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.touch",
			stage:     db2contract.StageTouch,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeTouchRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "memory.link_delete",
			stage:     db2contract.StageLinkDelete,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeLinkDeleteRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "memory.valid_at",
			stage:     db2contract.StageValidAt,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeValidAtRequest(1, "a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, _, err := db2contract.DecodeValidAtReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.has_scope_type",
			stage:     db2contract.StageHasScopeType,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeHasScopeTypeRequest(1, "a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeHasScopeTypeReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.reject",
			stage:     db2contract.StageReject,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeRejectRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "memory.update_content",
			stage:     db2contract.StageUpdateContent,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeUpdateContentRequest(1, "a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeUpdateContentReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.decay_confidence",
			stage:     db2contract.StageDecayConfidence,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeDecayConfidenceRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "memory.workspace_tag_insert",
			stage:     db2contract.StageWorkspaceTagInsert,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeWorkspaceTagInsertRequest(1, "a")
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "memory.set_cognified_kind",
			stage:     db2contract.StageSetCognifiedKind,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeSetCognifiedKindRequest(1, "a")
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "memory.set_source_session",
			stage:     db2contract.StageSetSourceSession,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeSetSourceSessionRequest(1, "a")
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "memory.negation_tokens_update",
			stage:     db2contract.StageNegationTokensUpdate,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeNegationTokensUpdateRequest(1, "a")
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "memory.get_content",
			stage:     db2contract.StageGetContent,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeGetContentRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				if _, _, err := db2contract.DecodeGetContentReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.get_source_session",
			stage:     db2contract.StageGetSourceSession,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeGetSourceSessionRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				if _, _, err := db2contract.DecodeGetSourceSessionReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.pick_first_temporal_ref",
			stage:     db2contract.StagePickFirstTemporalRef,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodePickFirstTemporalRefRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				if _, _, err := db2contract.DecodePickFirstTemporalRefReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.count_and_max_updated",
			stage:     db2contract.StageCountAndMaxUpdated,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeCountAndMaxUpdatedRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, _, _, err := db2contract.DecodeCountAndMaxUpdatedReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.top_l2_facts",
			stage:     db2contract.StageTopL2Facts,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeTopL2FactsRequest(1, 1, "a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeTopL2FactsReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.list_session_scope_priority",
			stage:     db2contract.StageListSessionScopePriority,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeListSessionScopePriorityRequest(1, 1, "a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeListSessionScopePriorityReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.collect_alias_matches",
			stage:     db2contract.StageCollectAliasMatches,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeCollectAliasMatchesRequest("a", 1, 1, "a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeCollectAliasMatchesReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.collect_entity_matches",
			stage:     db2contract.StageCollectEntityMatches,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeCollectEntityMatchesRequest("a", 1, 1, "a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeCollectEntityMatchesReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.collect_event_frame_matches",
			stage:     db2contract.StageCollectEventFrameMatches,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeCollectEventFrameMatchesRequest("a", 1, 1, "a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeCollectEventFrameMatchesReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.collect_relation_token_matches",
			stage:     db2contract.StageCollectRelationTokenMatches,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeCollectRelationTokenMatchesRequest("a", 1, 1, "a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeCollectRelationTokenMatchesReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.collect_summary_matches",
			stage:     db2contract.StageCollectSummaryMatches,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeCollectSummaryMatchesRequest("a", 1, 1, "a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeCollectSummaryMatchesReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.collect_temporal_matches",
			stage:     db2contract.StageCollectTemporalMatches,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeCollectTemporalMatchesRequest("a", 1, 1, "a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeCollectTemporalMatchesReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.find_facts_like",
			stage:     db2contract.StageFindFactsLike,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeFindFactsLikeRequest("a", 1, 1, "a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeFindFactsLikeReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.list_session_scope_priority_like",
			stage:     db2contract.StageListSessionScopePriorityLike,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeListSessionScopePriorityLikeRequest("a", 1, 1, "a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeListSessionScopePriorityLikeReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.negation_fts_search",
			stage:     db2contract.StageNegationFtsSearch,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeNegationFtsSearchRequest("a", 1, 1, "a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeNegationFtsSearchReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.session_neighbors_before",
			stage:     db2contract.StageSessionNeighborsBefore,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeSessionNeighborsBeforeRequest("a", 1, 1)
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeSessionNeighborsBeforeReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.session_neighbors_after",
			stage:     db2contract.StageSessionNeighborsAfter,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeSessionNeighborsAfterRequest("a", 1, 1)
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeSessionNeighborsAfterReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.row_get",
			stage:     db2contract.StageRowGet,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeRowGetRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				if _, _, err := db2contract.DecodeRowGetReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.row_get_by_unit_id",
			stage:     db2contract.StageRowGetByUnitID,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeRowGetByUnitIDRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				if _, _, err := db2contract.DecodeRowGetByUnitIDReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.search_facts_patterns_by_keyword",
			stage:     db2contract.StageSearchFactsPatternsByKeyword,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeSearchFactsPatternsByKeywordRequest("a", 1, 1, "a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeSearchFactsPatternsByKeywordReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.fact_history",
			stage:     db2contract.StageFactHistory,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeFactHistoryRequest("a", 1)
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeFactHistoryReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.list_rows",
			stage:     db2contract.StageListRows,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeListRowsRequest(1, 1, 1, "a", "a", "a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeListRowsReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.aggregate",
			stage:     db2contract.StageAggregate,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeAggregateRequest("a", "a", 1)
			},
			decoded: func(t *testing.T, body []byte) {
				if _, _, err := db2contract.DecodeAggregateReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.load_eval_corpus",
			stage:     db2contract.StageLoadEvalCorpus,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeLoadEvalCorpusRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				if _, _, err := db2contract.DecodeLoadEvalCorpusReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "memory.record_exists",
			stage:     db2contract.StageRecordExists,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeRecordExistsRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeRecordExistsReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "index.entity_edge_prune_orphans",
			stage:     db2contract.StageEntityEdgePruneOrphans,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeEntityEdgePruneOrphansRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeEntityEdgePruneOrphansReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "index.entity_edge_normalize_weights",
			stage:     db2contract.StageEntityEdgeNormalizeWeights,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeEntityEdgeNormalizeWeightsRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeEntityEdgeNormalizeWeightsReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "index.project_count",
			stage:     db2contract.StageProjectCount,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeProjectCountRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeProjectCountReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "index.purge_hidden_pollution",
			stage:     db2contract.StagePurgeHiddenPollution,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodePurgeHiddenPollutionRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodePurgeHiddenPollutionReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "index.requeue_drifted",
			stage:     db2contract.StageRequeueDrifted,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeRequeueDriftedRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeRequeueDriftedReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "index.cross_repo_rebuild_routes",
			stage:     db2contract.StageCrossRepoRebuildRoutes,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeCrossRepoRebuildRoutesRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeCrossRepoRebuildRoutesReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "index.cross_repo_rebuild_identities",
			stage:     db2contract.StageCrossRepoRebuildIdentities,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeCrossRepoRebuildIdentitiesRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeCrossRepoRebuildIdentitiesReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "index.cross_repo_rebuild_build_deps",
			stage:     db2contract.StageCrossRepoRebuildBuildDeps,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeCrossRepoRebuildBuildDepsRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeCrossRepoRebuildBuildDepsReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "index.drift_candidates",
			stage:     db2contract.StageDriftCandidates,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeDriftCandidatesRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeDriftCandidatesReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "index.file_index_delete_project",
			stage:     db2contract.StageFileIndexDeleteProject,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeFileIndexDeleteProjectRequest("a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeFileIndexDeleteProjectReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "index.entity_observation_count",
			stage:     db2contract.StageEntityObservationCount,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeEntityObservationCountRequest("a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeEntityObservationCountReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "index.entity_profile_fresh",
			stage:     db2contract.StageEntityProfileFresh,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeEntityProfileFreshRequest("a", "-1 days")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeEntityProfileFreshReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "learning.rules_decay",
			stage:     db2contract.StageRulesDecay,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeRulesDecayRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeRulesDecayReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "learning.curiosity_rescore_all",
			stage:     db2contract.StageCuriosityRescoreAll,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeCuriosityRescoreAllRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeCuriosityRescoreAllReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "learning.mining_seed_job_defaults",
			stage:     db2contract.StageMiningSeedJobDefaults,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeMiningSeedJobDefaultsRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "learning.proposals_archive_expired",
			stage:     db2contract.StageProposalsArchiveExpired,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeProposalsArchiveExpiredRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "learning.trace_mining_last_id",
			stage:     db2contract.StageTraceMiningLastID,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeTraceMiningLastIDRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeTraceMiningLastIDReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "learning.anti_pattern_bump",
			stage:     db2contract.StageAntiPatternBump,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeAntiPatternBumpRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "learning.anti_pattern_delete",
			stage:     db2contract.StageAntiPatternDelete,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeAntiPatternDeleteRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "learning.trace_mining_record",
			stage:     db2contract.StageTraceMiningRecord,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeTraceMiningRecordRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "learning.anti_pattern_exists_exact",
			stage:     db2contract.StageAntiPatternExistsExact,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeAntiPatternExistsExactRequest("a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeAntiPatternExistsExactReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "learning.anti_pattern_exists_by_source_ref",
			stage:     db2contract.StageAntiPatternExistsBySourceRef,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeAntiPatternExistsBySourceRefRequest("a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeAntiPatternExistsBySourceRefReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "learning.artifact_citation_count",
			stage:     db2contract.StageArtifactCitationCount,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeArtifactCitationCountRequest("a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeArtifactCitationCountReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "learning.commits_in_last_7_days",
			stage:     db2contract.StageCommitsInLast7Days,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeCommitsInLast7DaysRequest("a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeCommitsInLast7DaysReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "learning.fidelity_attribution_count",
			stage:     db2contract.StageFidelityAttributionCount,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeFidelityAttributionCountRequest("a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeFidelityAttributionCountReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "learning.artifact_stamp_reflected",
			stage:     db2contract.StageArtifactStampReflected,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeArtifactStampReflectedRequest("a")
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "learning.failed_query_bump",
			stage:     db2contract.StageFailedQueryBump,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeFailedQueryBumpRequest("a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeFailedQueryBumpReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "learning.artifact_set_state",
			stage:     db2contract.StageArtifactSetState,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeArtifactSetStateRequest("a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "learning.artifact_register_exemplar",
			stage:     db2contract.StageArtifactRegisterExemplar,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeArtifactRegisterExemplarRequest("a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "learning.evidence_enqueue",
			stage:     db2contract.StageEvidenceEnqueue,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeEvidenceEnqueueRequest("a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "learning.evidence_mark_failed",
			stage:     db2contract.StageEvidenceMarkFailed,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeEvidenceMarkFailedRequest("a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "organization.rel_types_ensure_seed",
			stage:     db2contract.StageRelTypesEnsureSeed,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeRelTypesEnsureSeedRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "organization.doc_delete",
			stage:     db2contract.StageDocDelete,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeDocDeleteRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "organization.task_delete",
			stage:     db2contract.StageTaskDelete,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeTaskDeleteRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "organization.clear_project",
			stage:     db2contract.StageClearProject,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeClearProjectRequest("a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeClearProjectReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "organization.clear_current_project",
			stage:     db2contract.StageClearCurrentProject,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeClearCurrentProjectRequest("a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeClearCurrentProjectReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "organization.document_exists",
			stage:     db2contract.StageDocumentExists,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeDocumentExistsRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeDocumentExistsReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "organization.blob_referenced",
			stage:     db2contract.StageBlobReferenced,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeBlobReferencedRequest("a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeBlobReferencedReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "organization.fence_active",
			stage:     db2contract.StageFenceActive,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeFenceActiveRequest("a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeFenceActiveReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "organization.doc_exists_by_hash",
			stage:     db2contract.StageDocExistsByHash,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeDocExistsByHashRequest("a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeDocExistsByHashReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "organization.pdf_quarantine_confirm",
			stage:     db2contract.StagePdfQuarantineConfirm,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodePdfQuarantineConfirmRequest("a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodePdfQuarantineConfirmReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "organization.pdf_quarantine_reject",
			stage:     db2contract.StagePdfQuarantineReject,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodePdfQuarantineRejectRequest("a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodePdfQuarantineRejectReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "custody.vector_rebuild_lock_try_acquire",
			stage:     db2contract.StageVectorRebuildLockTryAcquire,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeVectorRebuildLockTryAcquireRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeVectorRebuildLockTryAcquireReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "custody.vector_rebuild_lock_release",
			stage:     db2contract.StageVectorRebuildLockRelease,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeVectorRebuildLockReleaseRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "custody.release_get_active",
			stage:     db2contract.StageReleaseGetActive,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeReleaseGetActiveRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeReleaseGetActiveReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "custody.enrollment_active",
			stage:     db2contract.StageEnrollmentActive,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeEnrollmentActiveRequest("a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeEnrollmentActiveReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "maintenance.prospective_sweep_expired",
			stage:     db2contract.StageProspectiveSweepExpired,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeProspectiveSweepExpiredRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeProspectiveSweepExpiredReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "maintenance.directive_sweep_expired",
			stage:     db2contract.StageDirectiveSweepExpired,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeDirectiveSweepExpiredRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeDirectiveSweepExpiredReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "maintenance.mark_revisit_due",
			stage:     db2contract.StageMarkRevisitDue,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeMarkRevisitDueRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeMarkRevisitDueReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "maintenance.ingest_queue_reset_running",
			stage:     db2contract.StageIngestQueueResetRunning,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeIngestQueueResetRunningRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeIngestQueueResetRunningReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "maintenance.evidence_reembed_all",
			stage:     db2contract.StageEvidenceReembedAll,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeEvidenceReembedAllRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeEvidenceReembedAllReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "maintenance.curator_reembed_all",
			stage:     db2contract.StageCuratorReembedAll,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeCuratorReembedAllRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeCuratorReembedAllReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "maintenance.synth_reenqueue_all",
			stage:     db2contract.StageSynthReenqueueAll,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeSynthReenqueueAllRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeSynthReenqueueAllReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "maintenance.curator_reenqueue_extract_all",
			stage:     db2contract.StageCuratorReenqueueExtractAll,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeCuratorReenqueueExtractAllRequest(), nil
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeCuratorReenqueueExtractAllReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "maintenance.directive_suppress",
			stage:     db2contract.StageDirectiveSuppress,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeDirectiveSuppressRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "maintenance.directive_record_surface",
			stage:     db2contract.StageDirectiveRecordSurface,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeDirectiveRecordSurfaceRequest(1)
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "maintenance.async_pending_count",
			stage:     db2contract.StageAsyncPendingCount,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeAsyncPendingCountRequest("a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeAsyncPendingCountReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "maintenance.runtime_state_touch",
			stage:     db2contract.StageRuntimeStateTouch,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeRuntimeStateTouchRequest("a")
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "maintenance.synth_enqueue",
			stage:     db2contract.StageSynthEnqueue,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeSynthEnqueueRequest("a")
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "maintenance.synth_mark_done",
			stage:     db2contract.StageSynthMarkDone,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeSynthMarkDoneRequest("a")
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "maintenance.reembed_mark_finished",
			stage:     db2contract.StageReembedMarkFinished,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeReembedMarkFinishedRequest("a")
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "maintenance.mining_job_try_lock",
			stage:     db2contract.StageMiningJobTryLock,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeMiningJobTryLockRequest("a")
			},
			decoded: func(t *testing.T, body []byte) {
				if _, err := db2contract.DecodeMiningJobTryLockReply(body); err != nil {
					t.Fatalf("decode reply: %v", err)
				}
			},
		},
		{
			name:      "maintenance.synth_mark_failed",
			stage:     db2contract.StageSynthMarkFailed,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeSynthMarkFailedRequest("a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "maintenance.runtime_state_set",
			stage:     db2contract.StageRuntimeStateSet,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeRuntimeStateSetRequest("a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
		{
			name:      "maintenance.set_active_embedder_version",
			stage:     db2contract.StageSetActiveEmbedderVersion,
			generated: true,
			encode: func() ([]byte, error) {
				return db2contract.EncodeSetActiveEmbedderVersionRequest("a", "a")
			},
			decoded: func(t *testing.T, body []byte) {
				_ = body
			},
		},
	}
}
