package db2

import (
	"context"
	"errors"
	"time"
)

const DefaultDeadline = 5 * time.Second

var ErrConfig = errors.New("db2: bus client is not configured")

// StageCaller is the only transport capability the DB2 contract needs. The
// production bus caller and deterministic conformance fakes both satisfy it.
type StageCaller interface {
	Call(context.Context, uint32, uint32, uint64, time.Duration, []byte) ([]byte, error)
}

// Client calls the currently selected DB2 module implementation. During the C
// boundary migration that implementation is C; the later Go provider serves
// the same generated bytes without changing callers.
type Client struct {
	caller   StageCaller
	deadline time.Duration
}

func NewClient(caller StageCaller, deadline time.Duration) (*Client, error) {
	if caller == nil {
		return nil, ErrConfig
	}
	if deadline <= 0 {
		deadline = DefaultDeadline
	}
	return &Client{caller: caller, deadline: deadline}, nil
}

// Health returns DB2-owned PostgreSQL readiness evidence. Module status and
// transport failures are returned unchanged so callers can use the bus's typed
// cancellation, deadline, capability, and status errors.
func (client *Client) Health(ctx context.Context, traceID uint64) (HealthEvidence, error) {
	if client == nil || client.caller == nil {
		return HealthEvidence{}, ErrConfig
	}
	if ctx == nil {
		ctx = context.Background()
	}
	response, err := client.caller.Call(
		ctx, EventHealth, StageHealth, traceID, client.deadline, EncodeHealthRequest(),
	)
	if err != nil {
		return HealthEvidence{}, err
	}
	return DecodeHealthResponse(response)
}
