// Code generated by scripts/gen_db2_contract.py; DO NOT EDIT.

// Package db2 is the shared Go caller-side contract for the DB2 module.
package db2

import (
	"encoding/binary"
	"errors"
)

const ContractSHA256 = "96b5f2e19c00c02bacf73244163dbd26e18e8fb44f50387fb79afbcdef3464eb"
const WireVersion uint32 = 1

const FamilyLifecycle uint32 = 1
const FamilyTenancy uint32 = 2
const FamilyMemory uint32 = 3
const FamilyIndex uint32 = 4
const FamilyLearning uint32 = 5
const FamilyOrganization uint32 = 6
const FamilyCustody uint32 = 7
const FamilyMaintenance uint32 = 8

const EventLifecycle uint32 = 11521
const EventTenancy uint32 = 11522
const EventMemory uint32 = 11523
const EventIndex uint32 = 11524
const EventLearning uint32 = 11525
const EventOrganization uint32 = 11526
const EventCustody uint32 = 11527
const EventMaintenance uint32 = 11528

const ResultOK uint32 = 0
const ResultNotFound uint32 = 1
const ResultConflict uint32 = 2
const ResultDenied uint32 = 3
const ResultRetryable uint32 = 4
const ResultInvalidState uint32 = 5

const EventHealth = EventLifecycle
const StageHealth = FamilyLifecycle
const OperationHealth uint32 = 1
const EventEmbeddingDimension = EventLifecycle
const StageEmbeddingDimension = FamilyLifecycle
const OperationEmbeddingDimension uint32 = 2
const EmbeddingDimensionMin uint32 = 1
const EmbeddingDimensionMax uint32 = 4000
const EventPoolStatus = EventLifecycle
const StagePoolStatus = FamilyLifecycle
const OperationPoolStatus uint32 = 3
const PoolSizeMax uint32 = 256
const EventEmbeddingRefusals = EventLifecycle
const StageEmbeddingRefusals = FamilyLifecycle
const OperationEmbeddingRefusals uint32 = 4
const EmbeddingOfferedMax uint32 = 2147483647
const EventPostgresStatus = EventLifecycle
const StagePostgresStatus = FamilyLifecycle
const OperationPostgresStatus uint32 = 5
const PostgresAvailableActive uint32 = 1 << 0
const PostgresAvailableMax uint32 = 1 << 1
const PostgresAvailableRole uint32 = 1 << 2
const PostgresAvailableLag uint32 = 1 << 3
const PostgresAvailableAll uint32 = 0xf
const PostgresCountMax uint32 = 2147483647
const EventReembedStatus = EventLifecycle
const StageReembedStatus = FamilyLifecycle
const OperationReembedStatus uint32 = 6
const ReembedDimensionMin uint32 = 1
const ReembedDimensionMax uint32 = 4000

const EnvelopeHeaderLen = 24
const envelopeRequestMagic uint32 = 0x51523244
const envelopeReplyMagic uint32 = 0x52523244

const healthRequestMagic uint32 = 0x51483244
const healthResponseMagic uint32 = 0x52483244
const healthRequestLen = 8
const healthResponseLen = 16

const HealthFlagSchema uint32 = 1 << 0
const HealthFlagPGTrgm uint32 = 1 << 1
const HealthFlagKBTables uint32 = 1 << 2
const healthFlagAll uint32 = 0x7

var ErrMalformedHealth = errors.New("db2: malformed lifecycle health frame")
var ErrMalformedEnvelope = errors.New("db2: malformed operation envelope")

// RequestHeader is the fixed-width prefix for every post-bootstrap DB2
// operation request. Payload contains the exact declared operation body.
type RequestHeader struct {
	Operation  uint32
	Flags      uint32
	PayloadLen uint32
}

// ReplyHeader is the fixed-width prefix for every post-bootstrap DB2 operation
// reply. Result is one of the closed Result* values above.
type ReplyHeader struct {
	Operation  uint32
	Result     uint32
	PayloadLen uint32
}

func encodeEnvelopeHeader(magic, operation, code, payloadLen uint32) ([]byte, error) {
	if operation == 0 || magic == envelopeReplyMagic && code > ResultInvalidState {
		return nil, ErrMalformedEnvelope
	}
	header := make([]byte, EnvelopeHeaderLen)
	binary.LittleEndian.PutUint32(header[0:4], magic)
	binary.LittleEndian.PutUint16(header[4:6], uint16(WireVersion))
	binary.LittleEndian.PutUint16(header[6:8], uint16(EnvelopeHeaderLen))
	binary.LittleEndian.PutUint32(header[8:12], operation)
	binary.LittleEndian.PutUint32(header[12:16], code)
	binary.LittleEndian.PutUint32(header[16:20], payloadLen)
	return header, nil
}

func decodeEnvelopeHeader(frame []byte, magic uint32, reply bool) (uint32, uint32, uint32, error) {
	if len(frame) < EnvelopeHeaderLen ||
		binary.LittleEndian.Uint32(frame[0:4]) != magic ||
		binary.LittleEndian.Uint16(frame[4:6]) != uint16(WireVersion) ||
		binary.LittleEndian.Uint16(frame[6:8]) != uint16(EnvelopeHeaderLen) ||
		binary.LittleEndian.Uint32(frame[8:12]) == 0 ||
		binary.LittleEndian.Uint32(frame[20:24]) != 0 {
		return 0, 0, 0, ErrMalformedEnvelope
	}
	operation := binary.LittleEndian.Uint32(frame[8:12])
	code := binary.LittleEndian.Uint32(frame[12:16])
	payloadLen := binary.LittleEndian.Uint32(frame[16:20])
	if uint64(payloadLen) != uint64(len(frame)-EnvelopeHeaderLen) ||
		reply && code > ResultInvalidState {
		return 0, 0, 0, ErrMalformedEnvelope
	}
	return operation, code, payloadLen, nil
}

// EncodeRequestHeader emits the header to which the caller appends payloadLen
// canonical payload bytes.
func EncodeRequestHeader(operation, flags, payloadLen uint32) ([]byte, error) {
	return encodeEnvelopeHeader(envelopeRequestMagic, operation, flags, payloadLen)
}

// DecodeRequestHeader validates a complete header-plus-payload frame.
func DecodeRequestHeader(frame []byte) (RequestHeader, error) {
	operation, flags, payloadLen, err := decodeEnvelopeHeader(frame, envelopeRequestMagic, false)
	if err != nil {
		return RequestHeader{}, err
	}
	return RequestHeader{Operation: operation, Flags: flags, PayloadLen: payloadLen}, nil
}

// EncodeReplyHeader emits the header to which the provider appends payloadLen
// canonical payload bytes.
func EncodeReplyHeader(operation, result, payloadLen uint32) ([]byte, error) {
	return encodeEnvelopeHeader(envelopeReplyMagic, operation, result, payloadLen)
}

// DecodeReplyHeader validates a complete header-plus-payload frame and the
// closed result-code domain.
func DecodeReplyHeader(frame []byte) (ReplyHeader, error) {
	operation, result, payloadLen, err := decodeEnvelopeHeader(frame, envelopeReplyMagic, true)
	if err != nil {
		return ReplyHeader{}, err
	}
	return ReplyHeader{Operation: operation, Result: result, PayloadLen: payloadLen}, nil
}

// EncodeEmbeddingDimensionRequest emits the empty request envelope for the
// effective DB2 pgvector schema width.
func EncodeEmbeddingDimensionRequest() []byte {
	header, err := EncodeRequestHeader(OperationEmbeddingDimension, 0, 0)
	if err != nil {
		panic(err)
	}
	return header
}

// DecodeEmbeddingDimensionRequest validates the exact operation envelope.
func DecodeEmbeddingDimensionRequest(request []byte) error {
	header, err := DecodeRequestHeader(request)
	if err != nil || header.Operation != OperationEmbeddingDimension ||
		header.Flags != 0 || header.PayloadLen != 0 {
		return ErrMalformedEnvelope
	}
	return nil
}

// EncodeEmbeddingDimensionReply emits either a bounded u32 success payload or
// an empty invalid-state result.
func EncodeEmbeddingDimensionReply(result, dimension uint32) ([]byte, error) {
	var payloadLen uint32
	if result == ResultOK {
		if dimension < EmbeddingDimensionMin || dimension > EmbeddingDimensionMax {
			return nil, ErrMalformedEnvelope
		}
		payloadLen = 4
	} else if result != ResultInvalidState || dimension != 0 {
		return nil, ErrMalformedEnvelope
	}
	header, err := EncodeReplyHeader(OperationEmbeddingDimension, result, payloadLen)
	if err != nil {
		return nil, ErrMalformedEnvelope
	}
	if payloadLen == 0 {
		return header, nil
	}
	reply := append(header, make([]byte, 4)...)
	binary.LittleEndian.PutUint32(reply[EnvelopeHeaderLen:], dimension)
	return reply, nil
}

// DecodeEmbeddingDimensionReply validates the operation, closed result subset,
// payload shape, and dimension domain before exposing either field.
func DecodeEmbeddingDimensionReply(reply []byte) (uint32, uint32, error) {
	header, err := DecodeReplyHeader(reply)
	if err != nil || header.Operation != OperationEmbeddingDimension {
		return 0, 0, ErrMalformedEnvelope
	}
	if header.Result == ResultInvalidState && header.PayloadLen == 0 {
		return header.Result, 0, nil
	}
	if header.Result != ResultOK || header.PayloadLen != 4 {
		return 0, 0, ErrMalformedEnvelope
	}
	dimension := binary.LittleEndian.Uint32(reply[EnvelopeHeaderLen:])
	if dimension < EmbeddingDimensionMin || dimension > EmbeddingDimensionMax {
		return 0, 0, ErrMalformedEnvelope
	}
	return header.Result, dimension, nil
}

// PoolStatus is a bounded snapshot of the DB2 PostgreSQL connection pool.
type PoolStatus struct {
	Size          uint32
	InUse         uint32
	Waiters       uint32
	LeaseGrants   uint64
	LeaseTimeouts uint64
	Stuck         uint64
	Poisoned      uint64
}

func EncodePoolStatusRequest() []byte {
	header, err := EncodeRequestHeader(OperationPoolStatus, 0, 0)
	if err != nil {
		panic(err)
	}
	return header
}

func DecodePoolStatusRequest(request []byte) error {
	header, err := DecodeRequestHeader(request)
	if err != nil || header.Operation != OperationPoolStatus || header.Flags != 0 ||
		header.PayloadLen != 0 {
		return ErrMalformedEnvelope
	}
	return nil
}

func EncodePoolStatusReply(result uint32, status PoolStatus) ([]byte, error) {
	var payloadLen uint32
	if result == ResultOK {
		if status.Size == 0 || status.Size > PoolSizeMax || status.InUse > status.Size {
			return nil, ErrMalformedEnvelope
		}
		payloadLen = 44
	} else if result != ResultInvalidState || status != (PoolStatus{}) {
		return nil, ErrMalformedEnvelope
	}
	header, err := EncodeReplyHeader(OperationPoolStatus, result, payloadLen)
	if err != nil {
		return nil, ErrMalformedEnvelope
	}
	if payloadLen == 0 {
		return header, nil
	}
	reply := append(header, make([]byte, payloadLen)...)
	payload := reply[EnvelopeHeaderLen:]
	binary.LittleEndian.PutUint32(payload[0:4], status.Size)
	binary.LittleEndian.PutUint32(payload[4:8], status.InUse)
	binary.LittleEndian.PutUint32(payload[8:12], status.Waiters)
	binary.LittleEndian.PutUint64(payload[12:20], status.LeaseGrants)
	binary.LittleEndian.PutUint64(payload[20:28], status.LeaseTimeouts)
	binary.LittleEndian.PutUint64(payload[28:36], status.Stuck)
	binary.LittleEndian.PutUint64(payload[36:44], status.Poisoned)
	return reply, nil
}

func DecodePoolStatusReply(reply []byte) (uint32, PoolStatus, error) {
	header, err := DecodeReplyHeader(reply)
	if err != nil || header.Operation != OperationPoolStatus {
		return 0, PoolStatus{}, ErrMalformedEnvelope
	}
	if header.Result == ResultInvalidState && header.PayloadLen == 0 {
		return header.Result, PoolStatus{}, nil
	}
	if header.Result != ResultOK || header.PayloadLen != 44 {
		return 0, PoolStatus{}, ErrMalformedEnvelope
	}
	payload := reply[EnvelopeHeaderLen:]
	status := PoolStatus{
		Size:          binary.LittleEndian.Uint32(payload[0:4]),
		InUse:         binary.LittleEndian.Uint32(payload[4:8]),
		Waiters:       binary.LittleEndian.Uint32(payload[8:12]),
		LeaseGrants:   binary.LittleEndian.Uint64(payload[12:20]),
		LeaseTimeouts: binary.LittleEndian.Uint64(payload[20:28]),
		Stuck:         binary.LittleEndian.Uint64(payload[28:36]),
		Poisoned:      binary.LittleEndian.Uint64(payload[36:44]),
	}
	if status.Size == 0 || status.Size > PoolSizeMax || status.InUse > status.Size {
		return 0, PoolStatus{}, ErrMalformedEnvelope
	}
	return header.Result, status, nil
}

type EmbeddingRefusals struct {
	RefusedCount uint64
	LastOffered  uint32
}

func EncodeEmbeddingRefusalsRequest() []byte {
	header, err := EncodeRequestHeader(OperationEmbeddingRefusals, 0, 0)
	if err != nil {
		panic(err)
	}
	return header
}

func DecodeEmbeddingRefusalsRequest(request []byte) error {
	header, err := DecodeRequestHeader(request)
	if err != nil || header.Operation != OperationEmbeddingRefusals || header.Flags != 0 ||
		header.PayloadLen != 0 {
		return ErrMalformedEnvelope
	}
	return nil
}

func EncodeEmbeddingRefusalsReply(result uint32, status EmbeddingRefusals) ([]byte, error) {
	var payloadLen uint32
	if result == ResultOK {
		if status.LastOffered > EmbeddingOfferedMax ||
			(status.RefusedCount == 0) != (status.LastOffered == 0) {
			return nil, ErrMalformedEnvelope
		}
		payloadLen = 12
	} else if result != ResultInvalidState || status != (EmbeddingRefusals{}) {
		return nil, ErrMalformedEnvelope
	}
	header, err := EncodeReplyHeader(OperationEmbeddingRefusals, result, payloadLen)
	if err != nil {
		return nil, ErrMalformedEnvelope
	}
	if payloadLen == 0 {
		return header, nil
	}
	reply := append(header, make([]byte, payloadLen)...)
	binary.LittleEndian.PutUint64(reply[EnvelopeHeaderLen:EnvelopeHeaderLen+8], status.RefusedCount)
	binary.LittleEndian.PutUint32(reply[EnvelopeHeaderLen+8:], status.LastOffered)
	return reply, nil
}

func DecodeEmbeddingRefusalsReply(reply []byte) (uint32, EmbeddingRefusals, error) {
	header, err := DecodeReplyHeader(reply)
	if err != nil || header.Operation != OperationEmbeddingRefusals {
		return 0, EmbeddingRefusals{}, ErrMalformedEnvelope
	}
	if header.Result == ResultInvalidState && header.PayloadLen == 0 {
		return header.Result, EmbeddingRefusals{}, nil
	}
	if header.Result != ResultOK || header.PayloadLen != 12 {
		return 0, EmbeddingRefusals{}, ErrMalformedEnvelope
	}
	status := EmbeddingRefusals{
		RefusedCount: binary.LittleEndian.Uint64(reply[EnvelopeHeaderLen : EnvelopeHeaderLen+8]),
		LastOffered:  binary.LittleEndian.Uint32(reply[EnvelopeHeaderLen+8:]),
	}
	if status.LastOffered > EmbeddingOfferedMax ||
		(status.RefusedCount == 0) != (status.LastOffered == 0) {
		return 0, EmbeddingRefusals{}, ErrMalformedEnvelope
	}
	return header.Result, status, nil
}

type PostgresStatus struct {
	Available         uint32
	ActiveConnections uint32
	MaxConnections    uint32
	IsReplica         uint32
	ReplicaLagBytes   uint64
}

func validPostgresStatus(status PostgresStatus) bool {
	if status.Available & ^PostgresAvailableAll != 0 || status.ActiveConnections > PostgresCountMax ||
		status.MaxConnections > PostgresCountMax {
		return false
	}
	if status.Available&PostgresAvailableActive == 0 && status.ActiveConnections != 0 {
		return false
	}
	if status.Available&PostgresAvailableMax == 0 && status.MaxConnections != 0 {
		return false
	}
	if status.Available&PostgresAvailableRole == 0 {
		if status.IsReplica != 0 {
			return false
		}
	} else if status.IsReplica > 1 {
		return false
	}
	if status.Available&PostgresAvailableLag == 0 {
		return status.ReplicaLagBytes == 0
	}
	return status.Available&PostgresAvailableRole != 0 && status.IsReplica == 1
}

func EncodePostgresStatusRequest() []byte {
	header, err := EncodeRequestHeader(OperationPostgresStatus, 0, 0)
	if err != nil {
		panic(err)
	}
	return header
}

func DecodePostgresStatusRequest(request []byte) error {
	header, err := DecodeRequestHeader(request)
	if err != nil || header.Operation != OperationPostgresStatus || header.Flags != 0 ||
		header.PayloadLen != 0 {
		return ErrMalformedEnvelope
	}
	return nil
}

func EncodePostgresStatusReply(result uint32, status PostgresStatus) ([]byte, error) {
	var payloadLen uint32
	if result == ResultOK {
		if !validPostgresStatus(status) {
			return nil, ErrMalformedEnvelope
		}
		payloadLen = 24
	} else if result != ResultInvalidState || status != (PostgresStatus{}) {
		return nil, ErrMalformedEnvelope
	}
	header, err := EncodeReplyHeader(OperationPostgresStatus, result, payloadLen)
	if err != nil {
		return nil, ErrMalformedEnvelope
	}
	if payloadLen == 0 {
		return header, nil
	}
	reply := append(header, make([]byte, payloadLen)...)
	payload := reply[EnvelopeHeaderLen:]
	binary.LittleEndian.PutUint32(payload[0:4], status.Available)
	binary.LittleEndian.PutUint32(payload[4:8], status.ActiveConnections)
	binary.LittleEndian.PutUint32(payload[8:12], status.MaxConnections)
	binary.LittleEndian.PutUint32(payload[12:16], status.IsReplica)
	binary.LittleEndian.PutUint64(payload[16:24], status.ReplicaLagBytes)
	return reply, nil
}

func DecodePostgresStatusReply(reply []byte) (uint32, PostgresStatus, error) {
	header, err := DecodeReplyHeader(reply)
	if err != nil || header.Operation != OperationPostgresStatus {
		return 0, PostgresStatus{}, ErrMalformedEnvelope
	}
	if header.Result == ResultInvalidState && header.PayloadLen == 0 {
		return header.Result, PostgresStatus{}, nil
	}
	if header.Result != ResultOK || header.PayloadLen != 24 {
		return 0, PostgresStatus{}, ErrMalformedEnvelope
	}
	payload := reply[EnvelopeHeaderLen:]
	status := PostgresStatus{
		Available:         binary.LittleEndian.Uint32(payload[0:4]),
		ActiveConnections: binary.LittleEndian.Uint32(payload[4:8]),
		MaxConnections:    binary.LittleEndian.Uint32(payload[8:12]),
		IsReplica:         binary.LittleEndian.Uint32(payload[12:16]),
		ReplicaLagBytes:   binary.LittleEndian.Uint64(payload[16:24]),
	}
	if !validPostgresStatus(status) {
		return 0, PostgresStatus{}, ErrMalformedEnvelope
	}
	return header.Result, status, nil
}

type ReembedStatus struct {
	TargetDimension uint32
	StartedEpoch    uint64
}

func validReembedStatus(status ReembedStatus) bool {
	return status.TargetDimension >= ReembedDimensionMin &&
		status.TargetDimension <= ReembedDimensionMax && status.StartedEpoch > 0
}

func EncodeReembedStatusRequest() []byte {
	header, err := EncodeRequestHeader(OperationReembedStatus, 0, 0)
	if err != nil {
		panic(err)
	}
	return header
}

func DecodeReembedStatusRequest(request []byte) error {
	header, err := DecodeRequestHeader(request)
	if err != nil || header.Operation != OperationReembedStatus || header.Flags != 0 ||
		header.PayloadLen != 0 {
		return ErrMalformedEnvelope
	}
	return nil
}

func EncodeReembedStatusReply(result uint32, status ReembedStatus) ([]byte, error) {
	var payloadLen uint32
	if result == ResultOK {
		if !validReembedStatus(status) {
			return nil, ErrMalformedEnvelope
		}
		payloadLen = 12
	} else if (result != ResultNotFound && result != ResultInvalidState) ||
		status != (ReembedStatus{}) {
		return nil, ErrMalformedEnvelope
	}
	header, err := EncodeReplyHeader(OperationReembedStatus, result, payloadLen)
	if err != nil {
		return nil, ErrMalformedEnvelope
	}
	if payloadLen == 0 {
		return header, nil
	}
	reply := append(header, make([]byte, payloadLen)...)
	binary.LittleEndian.PutUint32(reply[EnvelopeHeaderLen:EnvelopeHeaderLen+4], status.TargetDimension)
	binary.LittleEndian.PutUint64(reply[EnvelopeHeaderLen+4:], status.StartedEpoch)
	return reply, nil
}

func DecodeReembedStatusReply(reply []byte) (uint32, ReembedStatus, error) {
	header, err := DecodeReplyHeader(reply)
	if err != nil || header.Operation != OperationReembedStatus {
		return 0, ReembedStatus{}, ErrMalformedEnvelope
	}
	if (header.Result == ResultNotFound || header.Result == ResultInvalidState) &&
		header.PayloadLen == 0 {
		return header.Result, ReembedStatus{}, nil
	}
	if header.Result != ResultOK || header.PayloadLen != 12 {
		return 0, ReembedStatus{}, ErrMalformedEnvelope
	}
	status := ReembedStatus{
		TargetDimension: binary.LittleEndian.Uint32(reply[EnvelopeHeaderLen : EnvelopeHeaderLen+4]),
		StartedEpoch:    binary.LittleEndian.Uint64(reply[EnvelopeHeaderLen+4:]),
	}
	if !validReembedStatus(status) {
		return 0, ReembedStatus{}, ErrMalformedEnvelope
	}
	return header.Result, status, nil
}

// HealthEvidence is DB2-owned PostgreSQL readiness evidence. It intentionally
// contains no DSN, SQL, provider identity, or implementation-specific detail.
type HealthEvidence struct {
	SchemaOK   bool
	HavePGTrgm bool
	KBTablesOK bool
}

// EncodeHealthRequest emits the exact fixed-width request served by the C DB2
// module and, later, by the Go provider.
func EncodeHealthRequest() []byte {
	request := make([]byte, healthRequestLen)
	binary.LittleEndian.PutUint32(request[0:4], healthRequestMagic)
	binary.LittleEndian.PutUint32(request[4:8], WireVersion)
	return request
}

// DecodeHealthRequest validates the complete frame, including exact length.
func DecodeHealthRequest(request []byte) error {
	if len(request) != healthRequestLen ||
		binary.LittleEndian.Uint32(request[0:4]) != healthRequestMagic ||
		binary.LittleEndian.Uint32(request[4:8]) != WireVersion {
		return ErrMalformedHealth
	}
	return nil
}

// EncodeHealthResponse emits the exact fixed-width response used by the C
// implementation. Boolean fields make unknown flag bits unrepresentable.
func EncodeHealthResponse(evidence HealthEvidence) []byte {
	response := make([]byte, healthResponseLen)
	binary.LittleEndian.PutUint32(response[0:4], healthResponseMagic)
	binary.LittleEndian.PutUint32(response[4:8], WireVersion)
	var flags uint32
	if evidence.SchemaOK {
		flags |= HealthFlagSchema
	}
	if evidence.HavePGTrgm {
		flags |= HealthFlagPGTrgm
	}
	if evidence.KBTablesOK {
		flags |= HealthFlagKBTables
	}
	binary.LittleEndian.PutUint32(response[8:12], flags)
	return response
}

// DecodeHealthResponse rejects unknown flags, nonzero reserved bytes, and any
// short or trailing data before exposing readiness evidence.
func DecodeHealthResponse(response []byte) (HealthEvidence, error) {
	if len(response) != healthResponseLen ||
		binary.LittleEndian.Uint32(response[0:4]) != healthResponseMagic ||
		binary.LittleEndian.Uint32(response[4:8]) != WireVersion ||
		binary.LittleEndian.Uint32(response[12:16]) != 0 {
		return HealthEvidence{}, ErrMalformedHealth
	}
	flags := binary.LittleEndian.Uint32(response[8:12])
	if flags & ^healthFlagAll != 0 {
		return HealthEvidence{}, ErrMalformedHealth
	}
	evidence := HealthEvidence{}
	evidence.SchemaOK = flags&HealthFlagSchema != 0
	evidence.HavePGTrgm = flags&HealthFlagPGTrgm != 0
	evidence.KBTablesOK = flags&HealthFlagKBTables != 0
	return evidence, nil
}
