/* Generated by scripts/gen_db2_contract.py; do not edit. */
#include <aimee/db2/client.h>
#include <aimee/db2/module_api.h>

aimee_module_call_result_t aimee_db2_level3_count_call(aimee_db2_call_fn call, void *call_context,
                                                       uint64_t trace_id, uint64_t deadline_ns,
                                                       uint32_t *count,
                                                       aimee_module_cancelled_fn cancelled,
                                                       void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_LEVEL3_COUNT_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_LEVEL3_COUNT_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_level3_count_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INTERNAL;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_LEVEL3_COUNT, AIMEE_DB2_STAGE_LEVEL3_COUNT, trace_id,
            deadline_ns, request, sizeof(request), response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_level3_count_reply_decode(response, response_len, count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_level2_count_call(aimee_db2_call_fn call, void *call_context,
                                                       uint64_t trace_id, uint64_t deadline_ns,
                                                       uint32_t *count,
                                                       aimee_module_cancelled_fn cancelled,
                                                       void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_LEVEL2_COUNT_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_LEVEL2_COUNT_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_level2_count_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INTERNAL;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_LEVEL2_COUNT, AIMEE_DB2_STAGE_LEVEL2_COUNT, trace_id,
            deadline_ns, request, sizeof(request), response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_level2_count_reply_decode(response, response_len, count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_orphaned_l0_count_call(aimee_db2_call_fn call,
                                                            void *call_context, uint64_t trace_id,
                                                            uint64_t deadline_ns, uint32_t *count,
                                                            aimee_module_cancelled_fn cancelled,
                                                            void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_ORPHANED_L0_COUNT_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_ORPHANED_L0_COUNT_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_orphaned_l0_count_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INTERNAL;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_ORPHANED_L0_COUNT, AIMEE_DB2_STAGE_ORPHANED_L0_COUNT,
            trace_id, deadline_ns, request, sizeof(request), response, sizeof(response),
            &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_orphaned_l0_count_reply_decode(response, response_len, count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_total_count_call(aimee_db2_call_fn call, void *call_context,
                                                      uint64_t trace_id, uint64_t deadline_ns,
                                                      uint64_t *count,
                                                      aimee_module_cancelled_fn cancelled,
                                                      void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_TOTAL_COUNT_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_TOTAL_COUNT_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_total_count_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INTERNAL;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_TOTAL_COUNT, AIMEE_DB2_STAGE_TOTAL_COUNT, trace_id,
            deadline_ns, request, sizeof(request), response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_total_count_reply_decode(response, response_len, count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_session_l2_count_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                uint64_t deadline_ns, const char *source_session, uint32_t *count,
                                aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !source_session || !count)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_SESSION_L2_COUNT_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_SESSION_L2_COUNT_RESPONSE_LEN];
   uint32_t request_len = 0u, response_len = 0u;
   if (aimee_db2_session_l2_count_request_encode(source_session, request, sizeof(request),
                                                 &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_SESSION_L2_COUNT, AIMEE_DB2_STAGE_SESSION_L2_COUNT,
            trace_id, deadline_ns, request, request_len, response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_session_l2_count_reply_decode(response, response_len, count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_key_exists_call(aimee_db2_call_fn call, void *call_context,
                                                     uint64_t trace_id, uint64_t deadline_ns,
                                                     const char *key, uint32_t *exists,
                                                     aimee_module_cancelled_fn cancelled,
                                                     void *cancel_context)
{
   if (exists)
      *exists = 0u;
   if (!call || !key || !exists)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_KEY_EXISTS_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_KEY_EXISTS_RESPONSE_LEN];
   uint32_t request_len = 0u, response_len = 0u;
   if (aimee_db2_key_exists_request_encode(key, request, sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport = call(
       call_context, AIMEE_DB2_EVENT_KEY_EXISTS, AIMEE_DB2_STAGE_KEY_EXISTS, trace_id, deadline_ns,
       request, request_len, response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_key_exists_reply_decode(response, response_len, exists) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_find_id_by_key_kind_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                   uint64_t deadline_ns, const char *key, const char *kind,
                                   uint32_t *found, uint64_t *id,
                                   aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (found)
      *found = 0u;
   if (id)
      *id = 0u;
   if (!call || !key || !kind || !found || !id)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_FIND_ID_BY_KEY_KIND_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_FIND_ID_BY_KEY_KIND_RESPONSE_LEN];
   uint32_t request_len = 0u, response_len = 0u;
   if (aimee_db2_find_id_by_key_kind_request_encode(key, kind, request, sizeof(request),
                                                    &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_FIND_ID_BY_KEY_KIND, AIMEE_DB2_STAGE_FIND_ID_BY_KEY_KIND,
            trace_id, deadline_ns, request, request_len, response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_find_id_by_key_kind_reply_decode(response, response_len, found, id) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_key_exists_in_tier_pair_call(aimee_db2_call_fn call, void *call_context,
                                       uint64_t trace_id, uint64_t deadline_ns, const char *key,
                                       const char *tier_a, const char *tier_b, uint32_t *exists,
                                       aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (exists)
      *exists = 0u;
   if (!call || !key || !tier_a || !tier_b || !exists)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_KEY_EXISTS_IN_TIER_PAIR_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_KEY_EXISTS_IN_TIER_PAIR_RESPONSE_LEN];
   uint32_t request_len = 0u, response_len = 0u;
   if (aimee_db2_key_exists_in_tier_pair_request_encode(key, tier_a, tier_b, request,
                                                        sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_KEY_EXISTS_IN_TIER_PAIR,
            AIMEE_DB2_STAGE_KEY_EXISTS_IN_TIER_PAIR, trace_id, deadline_ns, request, request_len,
            response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_key_exists_in_tier_pair_reply_decode(response, response_len, exists) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_effectiveness_update_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                    uint64_t deadline_ns, uint64_t memory_id, uint32_t has_value,
                                    double value, uint32_t *domain_result,
                                    aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (domain_result)
      *domain_result = 0u;
   if (!call || !domain_result)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_EFFECTIVENESS_UPDATE_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_EFFECTIVENESS_UPDATE_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_effectiveness_update_request_encode(memory_id, has_value, value, request,
                                                     sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_EFFECTIVENESS_UPDATE,
            AIMEE_DB2_STAGE_EFFECTIVENESS_UPDATE, trace_id, deadline_ns, request, sizeof(request),
            response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_effectiveness_update_reply_decode(response, response_len, domain_result) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_retention_enforce_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                 uint64_t deadline_ns, uint32_t *deleted_count,
                                 aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (deleted_count)
      *deleted_count = 0u;
   if (!call || !deleted_count)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_RETENTION_ENFORCE_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_RETENTION_ENFORCE_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_retention_enforce_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INTERNAL;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_RETENTION_ENFORCE, AIMEE_DB2_STAGE_RETENTION_ENFORCE,
            trace_id, deadline_ns, request, sizeof(request), response, sizeof(response),
            &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_retention_enforce_reply_decode(response, response_len, deleted_count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_effectiveness_demote_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                    uint64_t deadline_ns, uint32_t *demoted_count,
                                    aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (demoted_count)
      *demoted_count = 0u;
   if (!call || !demoted_count)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_EFFECTIVENESS_DEMOTE_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_EFFECTIVENESS_DEMOTE_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_effectiveness_demote_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INTERNAL;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_EFFECTIVENESS_DEMOTE,
            AIMEE_DB2_STAGE_EFFECTIVENESS_DEMOTE, trace_id, deadline_ns, request, sizeof(request),
            response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_effectiveness_demote_reply_decode(response, response_len, demoted_count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_effectiveness_stats_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                   uint64_t deadline_ns, aimee_db2_effectiveness_stats_t *stats,
                                   aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (stats)
      memset(stats, 0, sizeof(*stats));
   if (!call || !stats)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_EFFECTIVENESS_STATS_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_EFFECTIVENESS_STATS_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_effectiveness_stats_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INTERNAL;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_EFFECTIVENESS_STATS, AIMEE_DB2_STAGE_EFFECTIVENESS_STATS,
            trace_id, deadline_ns, request, sizeof(request), response, sizeof(response),
            &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_effectiveness_stats_reply_decode(response, response_len, stats) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_l2_memory_ids_call(aimee_db2_call_fn call, void *call_context,
                                                        uint64_t trace_id, uint64_t deadline_ns,
                                                        uint64_t *memory_ids, uint32_t capacity,
                                                        uint32_t *count,
                                                        aimee_module_cancelled_fn cancelled,
                                                        void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || (capacity > 0u && !memory_ids))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_L2_MEMORY_IDS_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_L2_MEMORY_IDS_RESPONSE_MAX_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_l2_memory_ids_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INTERNAL;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_L2_MEMORY_IDS, AIMEE_DB2_STAGE_L2_MEMORY_IDS, trace_id,
            deadline_ns, request, sizeof(request), response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_l2_memory_ids_reply_decode(response, response_len, memory_ids, capacity, count) !=
       0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_health_record_call(aimee_db2_call_fn call, void *call_context,
                                                        uint64_t trace_id, uint64_t deadline_ns,
                                                        uint32_t promotions, uint32_t demotions,
                                                        uint32_t expirations,
                                                        aimee_module_cancelled_fn cancelled,
                                                        void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_HEALTH_RECORD_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_HEALTH_RECORD_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_health_record_request_encode(promotions, demotions, expirations, request,
                                              sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_HEALTH_RECORD, AIMEE_DB2_STAGE_HEALTH_RECORD, trace_id,
            deadline_ns, request, sizeof(request), response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_health_record_reply_decode(response, response_len) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_health_retention_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                uint64_t deadline_ns, uint32_t *snapshots_deleted,
                                uint32_t *contradictions_deleted,
                                aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (snapshots_deleted)
      *snapshots_deleted = 0u;
   if (contradictions_deleted)
      *contradictions_deleted = 0u;
   if (!call || !snapshots_deleted || !contradictions_deleted)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_HEALTH_RETENTION_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_HEALTH_RETENTION_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_health_retention_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INTERNAL;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_HEALTH_RETENTION, AIMEE_DB2_STAGE_HEALTH_RETENTION,
            trace_id, deadline_ns, request, sizeof(request), response, sizeof(response),
            &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_health_retention_reply_decode(response, response_len, snapshots_deleted,
                                               contradictions_deleted) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_health_counters_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                               uint64_t deadline_ns, aimee_db2_health_counters_t *counters,
                               aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (counters)
      memset(counters, 0, sizeof(*counters));
   if (!call || !counters)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_HEALTH_COUNTERS_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_HEALTH_COUNTERS_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_health_counters_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INTERNAL;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_HEALTH_COUNTERS, AIMEE_DB2_STAGE_HEALTH_COUNTERS,
            trace_id, deadline_ns, request, sizeof(request), response, sizeof(response),
            &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_health_counters_reply_decode(response, response_len, counters) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_stats_counts_call(aimee_db2_call_fn call, void *call_context,
                                                       uint64_t trace_id, uint64_t deadline_ns,
                                                       aimee_db2_memory_stats_t *stats,
                                                       aimee_module_cancelled_fn cancelled,
                                                       void *cancel_context)
{
   if (stats)
      memset(stats, 0, sizeof(*stats));
   if (!call || !stats)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_STATS_COUNTS_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_STATS_COUNTS_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_stats_counts_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INTERNAL;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_STATS_COUNTS, AIMEE_DB2_STAGE_STATS_COUNTS, trace_id,
            deadline_ns, request, sizeof(request), response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_stats_counts_reply_decode(response, response_len, stats) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_expire_call(aimee_db2_call_fn call, void *call_context,
                                                 uint64_t trace_id, uint64_t deadline_ns,
                                                 uint32_t *level0_deleted,
                                                 uint32_t *stale_level1_deleted,
                                                 aimee_module_cancelled_fn cancelled,
                                                 void *cancel_context)
{
   if (level0_deleted)
      *level0_deleted = 0u;
   if (stale_level1_deleted)
      *stale_level1_deleted = 0u;
   if (!call || !level0_deleted || !stale_level1_deleted)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_EXPIRE_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_EXPIRE_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_expire_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INTERNAL;
   aimee_module_call_result_t transport = call(
       call_context, AIMEE_DB2_EVENT_EXPIRE, AIMEE_DB2_STAGE_EXPIRE, trace_id, deadline_ns, request,
       sizeof(request), response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_expire_reply_decode(response, response_len, level0_deleted,
                                     stale_level1_deleted) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_demote_call(aimee_db2_call_fn call, void *call_context,
                                                 uint64_t trace_id, uint64_t deadline_ns,
                                                 uint32_t *demoted_count, uint32_t *cascaded_count,
                                                 aimee_module_cancelled_fn cancelled,
                                                 void *cancel_context)
{
   if (demoted_count)
      *demoted_count = 0u;
   if (cascaded_count)
      *cascaded_count = 0u;
   if (!call || !demoted_count || !cascaded_count)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_DEMOTE_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_DEMOTE_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_demote_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INTERNAL;
   aimee_module_call_result_t transport = call(
       call_context, AIMEE_DB2_EVENT_DEMOTE, AIMEE_DB2_STAGE_DEMOTE, trace_id, deadline_ns, request,
       sizeof(request), response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_demote_reply_decode(response, response_len, demoted_count, cascaded_count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_promote_stable_call(aimee_db2_call_fn call, void *call_context,
                                                         uint64_t trace_id, uint64_t deadline_ns,
                                                         uint32_t *promoted_count,
                                                         aimee_module_cancelled_fn cancelled,
                                                         void *cancel_context)
{
   if (promoted_count)
      *promoted_count = 0u;
   if (!call || !promoted_count)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_PROMOTE_STABLE_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_PROMOTE_STABLE_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_promote_stable_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INTERNAL;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_PROMOTE_STABLE, AIMEE_DB2_STAGE_PROMOTE_STABLE, trace_id,
            deadline_ns, request, sizeof(request), response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_promote_stable_reply_decode(response, response_len, promoted_count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_reclassify_directives_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                     uint64_t deadline_ns, uint32_t require_approval,
                                     uint32_t *reclassified_count,
                                     aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (reclassified_count)
      *reclassified_count = 0u;
   if (!call || !reclassified_count)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_RECLASSIFY_DIRECTIVES_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_RECLASSIFY_DIRECTIVES_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_reclassify_directives_request_encode(require_approval, request, sizeof(request)) !=
       0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_RECLASSIFY_DIRECTIVES,
            AIMEE_DB2_STAGE_RECLASSIFY_DIRECTIVES, trace_id, deadline_ns, request, sizeof(request),
            response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_reclassify_directives_reply_decode(response, response_len, reclassified_count) !=
       0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_record_l4_approval_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                  uint64_t deadline_ns, uint64_t memory_id, const char *approver,
                                  const char *note, aimee_module_cancelled_fn cancelled,
                                  void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_RECORD_L4_APPROVAL_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_RECORD_L4_APPROVAL_RESPONSE_LEN];
   uint32_t request_len = 0u, response_len = 0u;
   if (aimee_db2_record_l4_approval_request_encode(memory_id, approver, note, request,
                                                   sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_RECORD_L4_APPROVAL, AIMEE_DB2_STAGE_RECORD_L4_APPROVAL,
            trace_id, deadline_ns, request, request_len, response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_record_l4_approval_reply_decode(response, response_len) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_prune_orphaned_l0_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                 uint64_t deadline_ns, uint32_t *deleted_count,
                                 aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call || !deleted_count)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   *deleted_count = 0u;
   uint8_t request[AIMEE_DB2_PRUNE_ORPHANED_L0_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_PRUNE_ORPHANED_L0_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_prune_orphaned_l0_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_PRUNE_ORPHANED_L0, AIMEE_DB2_STAGE_PRUNE_ORPHANED_L0,
            trace_id, deadline_ns, request, sizeof(request), response, sizeof(response),
            &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_prune_orphaned_l0_reply_decode(response, response_len, deleted_count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_lifecycle_sweep_expired_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    uint32_t *archived_count, aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call || !archived_count)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   *archived_count = 0u;
   uint8_t request[AIMEE_DB2_LIFECYCLE_SWEEP_EXPIRED_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_LIFECYCLE_SWEEP_EXPIRED_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_lifecycle_sweep_expired_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_LIFECYCLE_SWEEP_EXPIRED,
            AIMEE_DB2_STAGE_LIFECYCLE_SWEEP_EXPIRED, trace_id, deadline_ns, request,
            sizeof(request), response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_lifecycle_sweep_expired_reply_decode(response, response_len, archived_count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_demote_id_call(aimee_db2_call_fn call, void *call_context,
                                                    uint64_t trace_id, uint64_t deadline_ns,
                                                    uint64_t memory_id, uint32_t *demoted_count,
                                                    aimee_module_cancelled_fn cancelled,
                                                    void *cancel_context)
{
   if (!call || !demoted_count)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   *demoted_count = 0u;
   uint8_t request[AIMEE_DB2_DEMOTE_ID_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_DEMOTE_ID_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_demote_id_request_encode(memory_id, request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_DEMOTE_ID, AIMEE_DB2_STAGE_DEMOTE_ID, trace_id,
            deadline_ns, request, sizeof(request), response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_demote_id_reply_decode(response, response_len, demoted_count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_has_workspace_tag_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                 uint64_t deadline_ns, uint64_t memory_id, uint32_t *tagged,
                                 aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call || !tagged)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   *tagged = 0u;
   uint8_t request[AIMEE_DB2_HAS_WORKSPACE_TAG_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_HAS_WORKSPACE_TAG_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_has_workspace_tag_request_encode(memory_id, request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_HAS_WORKSPACE_TAG, AIMEE_DB2_STAGE_HAS_WORKSPACE_TAG,
            trace_id, deadline_ns, request, sizeof(request), response, sizeof(response),
            &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_has_workspace_tag_reply_decode(response, response_len, tagged) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_delete_row_call(aimee_db2_call_fn call, void *call_context,
                                                     uint64_t trace_id, uint64_t deadline_ns,
                                                     uint64_t memory_id, uint32_t *deleted_rows,
                                                     aimee_module_cancelled_fn cancelled,
                                                     void *cancel_context)
{
   if (!call || !deleted_rows)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   *deleted_rows = 0u;
   uint8_t request[AIMEE_DB2_DELETE_ROW_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_DELETE_ROW_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_delete_row_request_encode(memory_id, request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_DELETE_ROW, AIMEE_DB2_STAGE_DELETE_ROW, trace_id,
            deadline_ns, request, sizeof(request), response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_delete_row_reply_decode(response, response_len, deleted_rows) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_touch_call(aimee_db2_call_fn call, void *call_context,
                                                uint64_t trace_id, uint64_t deadline_ns,
                                                uint64_t memory_id,
                                                aimee_module_cancelled_fn cancelled,
                                                void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_TOUCH_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_TOUCH_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_touch_request_encode(memory_id, request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport = call(
       call_context, AIMEE_DB2_EVENT_TOUCH, AIMEE_DB2_STAGE_TOUCH, trace_id, deadline_ns, request,
       sizeof(request), response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_touch_reply_decode(response, response_len) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_link_delete_call(aimee_db2_call_fn call, void *call_context,
                                                      uint64_t trace_id, uint64_t deadline_ns,
                                                      uint64_t link_id,
                                                      aimee_module_cancelled_fn cancelled,
                                                      void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_LINK_DELETE_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_LINK_DELETE_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_link_delete_request_encode(link_id, request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_LINK_DELETE, AIMEE_DB2_STAGE_LINK_DELETE, trace_id,
            deadline_ns, request, sizeof(request), response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_link_delete_reply_decode(response, response_len) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_valid_at_call(aimee_db2_call_fn call, void *call_context,
                                                   uint64_t trace_id, uint64_t deadline_ns,
                                                   uint64_t memory_id, const char *as_of,
                                                   uint32_t *domain_result, uint32_t *in_force,
                                                   aimee_module_cancelled_fn cancelled,
                                                   void *cancel_context)
{
   if (!call || !domain_result || !in_force)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   *domain_result = 0u;
   *in_force = 0u;
   uint8_t request[AIMEE_DB2_VALID_AT_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_VALID_AT_RESPONSE_LEN];
   uint32_t request_len = 0u, response_len = 0u;
   if (aimee_db2_valid_at_request_encode(memory_id, as_of, request, sizeof(request),
                                         &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport = call(
       call_context, AIMEE_DB2_EVENT_VALID_AT, AIMEE_DB2_STAGE_VALID_AT, trace_id, deadline_ns,
       request, request_len, response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_valid_at_reply_decode(response, response_len, domain_result, in_force) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_has_scope_type_call(aimee_db2_call_fn call, void *call_context,
                                                         uint64_t trace_id, uint64_t deadline_ns,
                                                         uint64_t memory_id, const char *scope_type,
                                                         uint32_t *present,
                                                         aimee_module_cancelled_fn cancelled,
                                                         void *cancel_context)
{
   if (!call || !present)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   *present = 0u;
   uint8_t request[AIMEE_DB2_HAS_SCOPE_TYPE_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_HAS_SCOPE_TYPE_RESPONSE_LEN];
   uint32_t request_len = 0u, response_len = 0u;
   if (aimee_db2_has_scope_type_request_encode(memory_id, scope_type, request, sizeof(request),
                                               &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_HAS_SCOPE_TYPE, AIMEE_DB2_STAGE_HAS_SCOPE_TYPE, trace_id,
            deadline_ns, request, request_len, response, sizeof(response), &response_len, cancelled,
            cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_has_scope_type_reply_decode(response, response_len, present) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_reject_call(aimee_db2_call_fn call, void *call_context,
                                                 uint64_t trace_id, uint64_t deadline_ns,
                                                 uint64_t memory_id,
                                                 aimee_module_cancelled_fn cancelled,
                                                 void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_REJECT_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_REJECT_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_reject_request_encode(memory_id, request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport = call(
       call_context, AIMEE_DB2_EVENT_REJECT, AIMEE_DB2_STAGE_REJECT, trace_id, deadline_ns, request,
       sizeof(request), response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_reject_reply_decode(response, response_len) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_update_content_call(aimee_db2_call_fn call, void *call_context,
                                                         uint64_t trace_id, uint64_t deadline_ns,
                                                         uint64_t memory_id, const char *content,
                                                         uint32_t *updated_rows,
                                                         aimee_module_cancelled_fn cancelled,
                                                         void *cancel_context)
{
   if (!call || !updated_rows)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   *updated_rows = 0u;
   static _Thread_local uint8_t request[AIMEE_DB2_UPDATE_CONTENT_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_UPDATE_CONTENT_RESPONSE_LEN];
   uint32_t request_len = 0u, response_len = 0u;
   if (aimee_db2_update_content_request_encode(memory_id, content, request, sizeof(request),
                                               &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_UPDATE_CONTENT, AIMEE_DB2_STAGE_UPDATE_CONTENT, trace_id,
            deadline_ns, request, request_len, response, sizeof(response), &response_len, cancelled,
            cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_update_content_reply_decode(response, response_len, updated_rows) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_decay_confidence_call(aimee_db2_call_fn call,
                                                           void *call_context, uint64_t trace_id,
                                                           uint64_t deadline_ns, uint64_t memory_id,
                                                           aimee_module_cancelled_fn cancelled,
                                                           void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_DECAY_CONFIDENCE_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_DECAY_CONFIDENCE_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_decay_confidence_request_encode(memory_id, request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_DECAY_CONFIDENCE, AIMEE_DB2_STAGE_DECAY_CONFIDENCE,
            trace_id, deadline_ns, request, sizeof(request), response, sizeof(response),
            &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_decay_confidence_reply_decode(response, response_len) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_workspace_tag_insert_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                    uint64_t deadline_ns, uint64_t memory_id, const char *workspace,
                                    aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_WORKSPACE_TAG_INSERT_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_WORKSPACE_TAG_INSERT_RESPONSE_LEN];
   uint32_t request_len = 0u, response_len = 0u;
   if (aimee_db2_workspace_tag_insert_request_encode(memory_id, workspace, request, sizeof(request),
                                                     &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_WORKSPACE_TAG_INSERT,
            AIMEE_DB2_STAGE_WORKSPACE_TAG_INSERT, trace_id, deadline_ns, request, request_len,
            response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_workspace_tag_insert_reply_decode(response, response_len) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_set_cognified_kind_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                  uint64_t deadline_ns, uint64_t memory_id, const char *kind,
                                  aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_SET_COGNIFIED_KIND_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_SET_COGNIFIED_KIND_RESPONSE_LEN];
   uint32_t request_len = 0u, response_len = 0u;
   if (aimee_db2_set_cognified_kind_request_encode(memory_id, kind, request, sizeof(request),
                                                   &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_SET_COGNIFIED_KIND, AIMEE_DB2_STAGE_SET_COGNIFIED_KIND,
            trace_id, deadline_ns, request, request_len, response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_set_cognified_kind_reply_decode(response, response_len) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_set_source_session_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                  uint64_t deadline_ns, uint64_t memory_id, const char *session_id,
                                  aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_SET_SOURCE_SESSION_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_SET_SOURCE_SESSION_RESPONSE_LEN];
   uint32_t request_len = 0u, response_len = 0u;
   if (aimee_db2_set_source_session_request_encode(memory_id, session_id, request, sizeof(request),
                                                   &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_SET_SOURCE_SESSION, AIMEE_DB2_STAGE_SET_SOURCE_SESSION,
            trace_id, deadline_ns, request, request_len, response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_set_source_session_reply_decode(response, response_len) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_negation_tokens_update_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                      uint64_t deadline_ns, uint64_t memory_id, const char *tokens,
                                      aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   static _Thread_local uint8_t request[AIMEE_DB2_NEGATION_TOKENS_UPDATE_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_NEGATION_TOKENS_UPDATE_RESPONSE_LEN];
   uint32_t request_len = 0u, response_len = 0u;
   if (aimee_db2_negation_tokens_update_request_encode(memory_id, tokens, request, sizeof(request),
                                                       &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_NEGATION_TOKENS_UPDATE,
            AIMEE_DB2_STAGE_NEGATION_TOKENS_UPDATE, trace_id, deadline_ns, request, request_len,
            response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_negation_tokens_update_reply_decode(response, response_len) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_get_content_call(aimee_db2_call_fn call, void *call_context,
                                                      uint64_t trace_id, uint64_t deadline_ns,
                                                      uint64_t memory_id, uint32_t *domain_result,
                                                      char *content, size_t content_capacity,
                                                      aimee_module_cancelled_fn cancelled,
                                                      void *cancel_context)
{
   if (!call || !domain_result || !content ||
       content_capacity < (size_t)AIMEE_DB2_GET_CONTENT_CONTENT_MAX + 1u)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   *domain_result = 0u;
   content[0] = '\0';
   uint8_t request[AIMEE_DB2_GET_CONTENT_REQUEST_LEN];
   static _Thread_local uint8_t response[AIMEE_DB2_GET_CONTENT_RESPONSE_MAX_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_get_content_request_encode(memory_id, request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_GET_CONTENT, AIMEE_DB2_STAGE_GET_CONTENT, trace_id,
            deadline_ns, request, sizeof(request), response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_get_content_reply_decode(response, response_len, domain_result, content,
                                          content_capacity) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_get_source_session_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                  uint64_t deadline_ns, uint64_t memory_id, uint32_t *domain_result,
                                  char *session_id, size_t session_capacity,
                                  aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call || !domain_result || !session_id ||
       session_capacity < (size_t)AIMEE_DB2_GET_SOURCE_SESSION_SESSION_MAX + 1u)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   *domain_result = 0u;
   session_id[0] = '\0';
   uint8_t request[AIMEE_DB2_GET_SOURCE_SESSION_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_GET_SOURCE_SESSION_RESPONSE_MAX_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_get_source_session_request_encode(memory_id, request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_GET_SOURCE_SESSION, AIMEE_DB2_STAGE_GET_SOURCE_SESSION,
            trace_id, deadline_ns, request, sizeof(request), response, sizeof(response),
            &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_get_source_session_reply_decode(response, response_len, domain_result, session_id,
                                                 session_capacity) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_pick_first_temporal_ref_call(aimee_db2_call_fn call, void *call_context,
                                       uint64_t trace_id, uint64_t deadline_ns, uint64_t memory_id,
                                       uint32_t *domain_result, char *ref_key, size_t key_capacity,
                                       aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call || !domain_result || !ref_key ||
       key_capacity < (size_t)AIMEE_DB2_PICK_FIRST_TEMPORAL_REF_KEY_MAX + 1u)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   *domain_result = 0u;
   ref_key[0] = '\0';
   uint8_t request[AIMEE_DB2_PICK_FIRST_TEMPORAL_REF_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_PICK_FIRST_TEMPORAL_REF_RESPONSE_MAX_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_pick_first_temporal_ref_request_encode(memory_id, request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_PICK_FIRST_TEMPORAL_REF,
            AIMEE_DB2_STAGE_PICK_FIRST_TEMPORAL_REF, trace_id, deadline_ns, request,
            sizeof(request), response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_pick_first_temporal_ref_reply_decode(response, response_len, domain_result,
                                                      ref_key, key_capacity) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_count_and_max_updated_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                     uint64_t deadline_ns, uint32_t *domain_result, uint32_t *count,
                                     char *max_updated_at, size_t stamp_capacity,
                                     aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call || !domain_result || !count || !max_updated_at ||
       stamp_capacity < (size_t)AIMEE_DB2_COUNT_AND_MAX_UPDATED_STAMP_MAX + 1u)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   *domain_result = 0u;
   *count = 0u;
   max_updated_at[0] = '\0';
   uint8_t request[AIMEE_DB2_COUNT_AND_MAX_UPDATED_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_COUNT_AND_MAX_UPDATED_RESPONSE_MAX_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_count_and_max_updated_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_COUNT_AND_MAX_UPDATED,
            AIMEE_DB2_STAGE_COUNT_AND_MAX_UPDATED, trace_id, deadline_ns, request, sizeof(request),
            response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_count_and_max_updated_reply_decode(response, response_len, domain_result, count,
                                                    max_updated_at, stamp_capacity) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_top_l2_facts_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                            uint64_t deadline_ns, uint32_t limit, uint32_t scope_flags,
                            const char *workspace, const char *project, uint64_t *memory_ids,
                            uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled,
                            void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || !workspace || !project || (capacity > 0u && !memory_ids))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_TOP_L2_FACTS_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_TOP_L2_FACTS_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_top_l2_facts_request_encode(limit, scope_flags, workspace, project, request,
                                             sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_TOP_L2_FACTS, AIMEE_DB2_STAGE_TOP_L2_FACTS, trace_id,
            deadline_ns, request, request_len, response, sizeof(response), &response_len, cancelled,
            cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_top_l2_facts_reply_decode(response, response_len, memory_ids, capacity, count) !=
       0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_list_session_scope_priority_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    uint32_t limit, uint32_t scope_flags, const char *workspace, const char *project,
    uint64_t *memory_ids, uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled,
    void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || !workspace || !project || (capacity > 0u && !memory_ids))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_LIST_SESSION_SCOPE_PRIORITY_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_LIST_SESSION_SCOPE_PRIORITY_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_list_session_scope_priority_request_encode(
           limit, scope_flags, workspace, project, request, sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_LIST_SESSION_SCOPE_PRIORITY,
            AIMEE_DB2_STAGE_LIST_SESSION_SCOPE_PRIORITY, trace_id, deadline_ns, request,
            request_len, response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_list_session_scope_priority_reply_decode(response, response_len, memory_ids,
                                                          capacity, count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_collect_alias_matches_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    const char *term, uint32_t limit, uint32_t scope_flags, const char *workspace,
    const char *project, uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
    aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || !term || !workspace || !project || (capacity > 0u && !memory_ids))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_COLLECT_ALIAS_MATCHES_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_COLLECT_ALIAS_MATCHES_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_collect_alias_matches_request_encode(term, limit, scope_flags, workspace, project,
                                                      request, sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_COLLECT_ALIAS_MATCHES,
            AIMEE_DB2_STAGE_COLLECT_ALIAS_MATCHES, trace_id, deadline_ns, request, request_len,
            response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_collect_alias_matches_reply_decode(response, response_len, memory_ids, capacity,
                                                    count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_collect_entity_matches_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    const char *term, uint32_t limit, uint32_t scope_flags, const char *workspace,
    const char *project, uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
    aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || !term || !workspace || !project || (capacity > 0u && !memory_ids))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_COLLECT_ENTITY_MATCHES_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_COLLECT_ENTITY_MATCHES_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_collect_entity_matches_request_encode(term, limit, scope_flags, workspace, project,
                                                       request, sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_COLLECT_ENTITY_MATCHES,
            AIMEE_DB2_STAGE_COLLECT_ENTITY_MATCHES, trace_id, deadline_ns, request, request_len,
            response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_collect_entity_matches_reply_decode(response, response_len, memory_ids, capacity,
                                                     count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_collect_event_frame_matches_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    const char *term, uint32_t limit, uint32_t scope_flags, const char *workspace,
    const char *project, uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
    aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || !term || !workspace || !project || (capacity > 0u && !memory_ids))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_COLLECT_EVENT_FRAME_MATCHES_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_COLLECT_EVENT_FRAME_MATCHES_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_collect_event_frame_matches_request_encode(term, limit, scope_flags, workspace,
                                                            project, request, sizeof(request),
                                                            &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_COLLECT_EVENT_FRAME_MATCHES,
            AIMEE_DB2_STAGE_COLLECT_EVENT_FRAME_MATCHES, trace_id, deadline_ns, request,
            request_len, response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_collect_event_frame_matches_reply_decode(response, response_len, memory_ids,
                                                          capacity, count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_collect_relation_token_matches_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    const char *term, uint32_t limit, uint32_t scope_flags, const char *workspace,
    const char *project, uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
    aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || !term || !workspace || !project || (capacity > 0u && !memory_ids))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_COLLECT_RELATION_TOKEN_MATCHES_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_COLLECT_RELATION_TOKEN_MATCHES_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_collect_relation_token_matches_request_encode(term, limit, scope_flags, workspace,
                                                               project, request, sizeof(request),
                                                               &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_COLLECT_RELATION_TOKEN_MATCHES,
            AIMEE_DB2_STAGE_COLLECT_RELATION_TOKEN_MATCHES, trace_id, deadline_ns, request,
            request_len, response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_collect_relation_token_matches_reply_decode(response, response_len, memory_ids,
                                                             capacity, count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_collect_summary_matches_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    const char *term, uint32_t limit, uint32_t scope_flags, const char *workspace,
    const char *project, uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
    aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || !term || !workspace || !project || (capacity > 0u && !memory_ids))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_COLLECT_SUMMARY_MATCHES_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_COLLECT_SUMMARY_MATCHES_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_collect_summary_matches_request_encode(term, limit, scope_flags, workspace,
                                                        project, request, sizeof(request),
                                                        &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_COLLECT_SUMMARY_MATCHES,
            AIMEE_DB2_STAGE_COLLECT_SUMMARY_MATCHES, trace_id, deadline_ns, request, request_len,
            response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_collect_summary_matches_reply_decode(response, response_len, memory_ids, capacity,
                                                      count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_collect_temporal_matches_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    const char *term, uint32_t limit, uint32_t scope_flags, const char *workspace,
    const char *project, uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
    aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || !term || !workspace || !project || (capacity > 0u && !memory_ids))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_COLLECT_TEMPORAL_MATCHES_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_COLLECT_TEMPORAL_MATCHES_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_collect_temporal_matches_request_encode(term, limit, scope_flags, workspace,
                                                         project, request, sizeof(request),
                                                         &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_COLLECT_TEMPORAL_MATCHES,
            AIMEE_DB2_STAGE_COLLECT_TEMPORAL_MATCHES, trace_id, deadline_ns, request, request_len,
            response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_collect_temporal_matches_reply_decode(response, response_len, memory_ids, capacity,
                                                       count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_find_facts_like_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                               uint64_t deadline_ns, const char *term, uint32_t limit,
                               uint32_t scope_flags, const char *workspace, const char *project,
                               uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
                               aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || !term || !workspace || !project || (capacity > 0u && !memory_ids))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_FIND_FACTS_LIKE_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_FIND_FACTS_LIKE_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_find_facts_like_request_encode(term, limit, scope_flags, workspace, project,
                                                request, sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_FIND_FACTS_LIKE, AIMEE_DB2_STAGE_FIND_FACTS_LIKE,
            trace_id, deadline_ns, request, request_len, response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_find_facts_like_reply_decode(response, response_len, memory_ids, capacity,
                                              count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_list_session_scope_priority_like_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    const char *term, uint32_t limit, uint32_t scope_flags, const char *workspace,
    const char *project, uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
    aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || !term || !workspace || !project || (capacity > 0u && !memory_ids))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_LIST_SESSION_SCOPE_PRIORITY_LIKE_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_LIST_SESSION_SCOPE_PRIORITY_LIKE_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_list_session_scope_priority_like_request_encode(
           term, limit, scope_flags, workspace, project, request, sizeof(request), &request_len) !=
       0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_LIST_SESSION_SCOPE_PRIORITY_LIKE,
            AIMEE_DB2_STAGE_LIST_SESSION_SCOPE_PRIORITY_LIKE, trace_id, deadline_ns, request,
            request_len, response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_list_session_scope_priority_like_reply_decode(response, response_len, memory_ids,
                                                               capacity, count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_negation_fts_search_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                   uint64_t deadline_ns, const char *term, uint32_t limit,
                                   uint32_t scope_flags, const char *workspace, const char *project,
                                   uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
                                   aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || !term || !workspace || !project || (capacity > 0u && !memory_ids))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_NEGATION_FTS_SEARCH_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_NEGATION_FTS_SEARCH_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_negation_fts_search_request_encode(term, limit, scope_flags, workspace, project,
                                                    request, sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_NEGATION_FTS_SEARCH, AIMEE_DB2_STAGE_NEGATION_FTS_SEARCH,
            trace_id, deadline_ns, request, request_len, response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_negation_fts_search_reply_decode(response, response_len, memory_ids, capacity,
                                                  count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_session_neighbors_before_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    const char *session_id, uint64_t anchor_id, uint32_t limit, uint64_t *memory_ids,
    uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || !session_id || (capacity > 0u && !memory_ids))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_SESSION_NEIGHBORS_BEFORE_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_SESSION_NEIGHBORS_BEFORE_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_session_neighbors_before_request_encode(session_id, anchor_id, limit, request,
                                                         sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_SESSION_NEIGHBORS_BEFORE,
            AIMEE_DB2_STAGE_SESSION_NEIGHBORS_BEFORE, trace_id, deadline_ns, request, request_len,
            response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_session_neighbors_before_reply_decode(response, response_len, memory_ids, capacity,
                                                       count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_session_neighbors_after_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    const char *session_id, uint64_t anchor_id, uint32_t limit, uint64_t *memory_ids,
    uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || !session_id || (capacity > 0u && !memory_ids))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_SESSION_NEIGHBORS_AFTER_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_SESSION_NEIGHBORS_AFTER_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_session_neighbors_after_request_encode(session_id, anchor_id, limit, request,
                                                        sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_SESSION_NEIGHBORS_AFTER,
            AIMEE_DB2_STAGE_SESSION_NEIGHBORS_AFTER, trace_id, deadline_ns, request, request_len,
            response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_session_neighbors_after_reply_decode(response, response_len, memory_ids, capacity,
                                                      count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_row_get_call(aimee_db2_call_fn call, void *call_context,
                                                  uint64_t trace_id, uint64_t deadline_ns,
                                                  uint64_t memory_id, uint32_t *domain_result,
                                                  aimee_db2_memory_row_t *row,
                                                  aimee_module_cancelled_fn cancelled,
                                                  void *cancel_context)
{
   if (domain_result)
      *domain_result = 0u;
   if (row)
      memset(row, 0, sizeof(*row));
   if (!call || !domain_result || !row)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_ROW_GET_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_ROW_GET_RESPONSE_MAX_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_row_get_request_encode(memory_id, request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_ROW_GET, AIMEE_DB2_STAGE_ROW_GET, trace_id, deadline_ns,
            request, sizeof(request), response, sizeof(response), &response_len, cancelled,
            cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_row_get_reply_decode(response, response_len, domain_result, row) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_row_get_by_unit_id_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                  uint64_t deadline_ns, uint64_t unit_id, uint32_t *domain_result,
                                  aimee_db2_memory_row_t *row, aimee_module_cancelled_fn cancelled,
                                  void *cancel_context)
{
   if (domain_result)
      *domain_result = 0u;
   if (row)
      memset(row, 0, sizeof(*row));
   if (!call || !domain_result || !row)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_ROW_GET_BY_UNIT_ID_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_ROW_GET_BY_UNIT_ID_RESPONSE_MAX_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_row_get_by_unit_id_request_encode(unit_id, request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_ROW_GET_BY_UNIT_ID, AIMEE_DB2_STAGE_ROW_GET_BY_UNIT_ID,
            trace_id, deadline_ns, request, sizeof(request), response, sizeof(response),
            &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_row_get_by_unit_id_reply_decode(response, response_len, domain_result, row) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_search_facts_patterns_by_keyword_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    const char *term, uint32_t limit, uint32_t scope_flags, const char *workspace,
    const char *project, uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
    aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || !term || !workspace || !project || (capacity > 0u && !memory_ids))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_SEARCH_FACTS_PATTERNS_BY_KEYWORD_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_SEARCH_FACTS_PATTERNS_BY_KEYWORD_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_search_facts_patterns_by_keyword_request_encode(
           term, limit, scope_flags, workspace, project, request, sizeof(request), &request_len) !=
       0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_SEARCH_FACTS_PATTERNS_BY_KEYWORD,
            AIMEE_DB2_STAGE_SEARCH_FACTS_PATTERNS_BY_KEYWORD, trace_id, deadline_ns, request,
            request_len, response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_search_facts_patterns_by_keyword_reply_decode(response, response_len, memory_ids,
                                                               capacity, count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_fact_history_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                            uint64_t deadline_ns, const char *normalized_key, uint32_t limit,
                            uint64_t *memory_ids, uint32_t capacity, uint32_t *count,
                            aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || !normalized_key || (capacity > 0u && !memory_ids))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_FACT_HISTORY_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_FACT_HISTORY_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_fact_history_request_encode(normalized_key, limit, request, sizeof(request),
                                             &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_FACT_HISTORY, AIMEE_DB2_STAGE_FACT_HISTORY, trace_id,
            deadline_ns, request, request_len, response, sizeof(response), &response_len, cancelled,
            cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_fact_history_reply_decode(response, response_len, memory_ids, capacity, count) !=
       0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_list_rows_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    uint32_t limit, uint32_t scope_flags, uint32_t hide_archived, const char *tier,
    const char *kind, const char *workspace, const char *project, uint64_t *memory_ids,
    uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || !tier || !kind || !workspace || !project ||
       (capacity > 0u && !memory_ids))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_LIST_ROWS_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_LIST_ROWS_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_list_rows_request_encode(limit, scope_flags, hide_archived, tier, kind, workspace,
                                          project, request, sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport = call(
       call_context, AIMEE_DB2_EVENT_LIST_ROWS, AIMEE_DB2_STAGE_LIST_ROWS, trace_id, deadline_ns,
       request, request_len, response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_list_rows_reply_decode(response, response_len, memory_ids, capacity, count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_aggregate_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                         uint64_t deadline_ns, const char *entity_seed, const char *keyword,
                         uint32_t limit, uint32_t *truncated, uint64_t *memory_ids,
                         uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled,
                         void *cancel_context)
{
   if (truncated)
      *truncated = 0u;
   if (count)
      *count = 0u;
   if (!call || !count || !truncated || !entity_seed || !keyword || (capacity > 0u && !memory_ids))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_AGGREGATE_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_AGGREGATE_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_aggregate_request_encode(entity_seed, keyword, limit, request, sizeof(request),
                                          &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport = call(
       call_context, AIMEE_DB2_EVENT_AGGREGATE, AIMEE_DB2_STAGE_AGGREGATE, trace_id, deadline_ns,
       request, request_len, response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_aggregate_reply_decode(response, response_len, truncated, memory_ids, capacity,
                                        count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_load_eval_corpus_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    uint32_t limit, char *label, size_t label_capacity, uint64_t *memory_ids, uint32_t capacity,
    uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (label && label_capacity)
      label[0] = '\0';
   if (count)
      *count = 0u;
   if (!call || !count || !label ||
       label_capacity < (size_t)AIMEE_DB2_LOAD_EVAL_CORPUS_LABEL_MAX + 1u ||
       (capacity > 0u && !memory_ids))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_LOAD_EVAL_CORPUS_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_LOAD_EVAL_CORPUS_RESPONSE_MAX_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_load_eval_corpus_request_encode(limit, request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_LOAD_EVAL_CORPUS, AIMEE_DB2_STAGE_LOAD_EVAL_CORPUS,
            trace_id, deadline_ns, request, sizeof(request), response, sizeof(response),
            &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_load_eval_corpus_reply_decode(response, response_len, label, label_capacity,
                                               memory_ids, capacity, count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_record_exists_call(aimee_db2_call_fn call, void *call_context,
                                                        uint64_t trace_id, uint64_t deadline_ns,
                                                        uint64_t record_id, uint32_t *exists,
                                                        aimee_module_cancelled_fn cancelled,
                                                        void *cancel_context)
{
   if (exists)
      *exists = 0u;
   if (!call || !exists)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_RECORD_EXISTS_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_RECORD_EXISTS_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_record_exists_request_encode(record_id, request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_RECORD_EXISTS, AIMEE_DB2_STAGE_RECORD_EXISTS, trace_id,
            deadline_ns, request, sizeof(request), response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_record_exists_reply_decode(response, response_len, exists) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}
