/* Generated by scripts/gen_db2_contract.py; do not edit. */
#include <aimee/db2/client.h>
#include <aimee/db2/module_api.h>
#include <stdlib.h>

aimee_module_call_result_t aimee_db2_evidence_pending_list_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    aimee_db2_evidence_pending_list_row_t *rows, uint32_t capacity, uint32_t *count,
    aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || (capacity > 0u && !rows))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_EVIDENCE_PENDING_LIST_REQUEST_MAX_LEN];
   uint8_t *response = malloc(AIMEE_DB2_EVIDENCE_PENDING_LIST_RESPONSE_MAX_LEN);
   if (!response)
      return AIMEE_MODULE_CALL_INTERNAL;
   const size_t response_capacity = AIMEE_DB2_EVIDENCE_PENDING_LIST_RESPONSE_MAX_LEN;
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_evidence_pending_list_request_encode(request, sizeof(request), &request_len) != 0)
   {
      free(response);
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   }
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_EVIDENCE_PENDING_LIST,
            AIMEE_DB2_STAGE_EVIDENCE_PENDING_LIST, trace_id, deadline_ns, request, request_len,
            response, response_capacity, &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
   {
      free(response);
      return transport;
   }
   if (aimee_db2_evidence_pending_list_reply_decode(response, response_len, rows, capacity,
                                                    count) != 0)
   {
      free(response);
      return AIMEE_MODULE_CALL_PROTOCOL;
   }
   free(response);

   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_evidence_store_vector_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    const char *artifact_id, const char *collection, const char *embedding_text,
    uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_EVIDENCE_STORE_VECTOR_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_EVIDENCE_STORE_VECTOR_RESPONSE_MAX_LEN];
   const size_t response_capacity = sizeof(response);
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_evidence_store_vector_request_encode(artifact_id, collection, embedding_text,
                                                      request, sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_EVIDENCE_STORE_VECTOR,
            AIMEE_DB2_STAGE_EVIDENCE_STORE_VECTOR, trace_id, deadline_ns, request, request_len,
            response, response_capacity, &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_evidence_store_vector_reply_decode(response, response_len, acknowledged) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;

   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_learning_proposal_get_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    uint32_t proposal_id, uint32_t *proposal_found, uint32_t *signal_id, char *proposal_sink,
    size_t proposal_sink_capacity, char *proposal_state, size_t proposal_state_capacity,
    char *target_key, size_t target_key_capacity, uint64_t *target_memory_id, char *action_json,
    size_t action_json_capacity, char *evidence_refs, size_t evidence_refs_capacity,
    uint32_t *corroboration_count, char *expires_at, size_t expires_at_capacity, char *committed_at,
    size_t committed_at_capacity, char *archive_reason, size_t archive_reason_capacity,
    char *proposal_created_at, size_t proposal_created_at_capacity, char *proposal_updated_at,
    size_t proposal_updated_at_capacity, aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_LEARNING_PROPOSAL_GET_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_LEARNING_PROPOSAL_GET_RESPONSE_MAX_LEN];
   const size_t response_capacity = sizeof(response);
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_learning_proposal_get_request_encode(proposal_id, request, sizeof(request),
                                                      &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_LEARNING_PROPOSAL_GET,
            AIMEE_DB2_STAGE_LEARNING_PROPOSAL_GET, trace_id, deadline_ns, request, request_len,
            response, response_capacity, &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_learning_proposal_get_reply_decode(
           response, response_len, proposal_found, signal_id, proposal_sink, proposal_sink_capacity,
           proposal_state, proposal_state_capacity, target_key, target_key_capacity,
           target_memory_id, action_json, action_json_capacity, evidence_refs,
           evidence_refs_capacity, corroboration_count, expires_at, expires_at_capacity,
           committed_at, committed_at_capacity, archive_reason, archive_reason_capacity,
           proposal_created_at, proposal_created_at_capacity, proposal_updated_at,
           proposal_updated_at_capacity) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;

   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_learning_proposal_find_pending_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    const char *proposal_sink, const char *target_key, uint64_t target_memory_id,
    uint32_t *proposal_id, aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_LEARNING_PROPOSAL_FIND_PENDING_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_LEARNING_PROPOSAL_FIND_PENDING_RESPONSE_MAX_LEN];
   const size_t response_capacity = sizeof(response);
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_learning_proposal_find_pending_request_encode(proposal_sink, target_key,
                                                               target_memory_id, request,
                                                               sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_LEARNING_PROPOSAL_FIND_PENDING,
            AIMEE_DB2_STAGE_LEARNING_PROPOSAL_FIND_PENDING, trace_id, deadline_ns, request,
            request_len, response, response_capacity, &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_learning_proposal_find_pending_reply_decode(response, response_len, proposal_id) !=
       0)
      return AIMEE_MODULE_CALL_PROTOCOL;

   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_learning_proposal_insert_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    uint32_t signal_id, const char *proposal_sink, const char *target_key,
    uint64_t target_memory_id, const char *action_json, const char *evidence_refs,
    const char *expires_at, uint32_t *proposal_id, aimee_module_cancelled_fn cancelled,
    void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_LEARNING_PROPOSAL_INSERT_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_LEARNING_PROPOSAL_INSERT_RESPONSE_MAX_LEN];
   const size_t response_capacity = sizeof(response);
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_learning_proposal_insert_request_encode(
           signal_id, proposal_sink, target_key, target_memory_id, action_json, evidence_refs,
           expires_at, request, sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_LEARNING_PROPOSAL_INSERT,
            AIMEE_DB2_STAGE_LEARNING_PROPOSAL_INSERT, trace_id, deadline_ns, request, request_len,
            response, response_capacity, &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_learning_proposal_insert_reply_decode(response, response_len, proposal_id) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;

   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_decision_log_insert_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    uint64_t task_id, const char *decision_options, const char *decision_chosen,
    const char *decision_rationale, const char *decision_assumptions,
    const char *decision_created_at, uint32_t *acknowledged, uint64_t *logged_decision_id,
    uint64_t *logged_task_id, char *logged_decision_options,
    size_t logged_decision_options_capacity, char *logged_decision_chosen,
    size_t logged_decision_chosen_capacity, char *logged_decision_rationale,
    size_t logged_decision_rationale_capacity, char *logged_decision_assumptions,
    size_t logged_decision_assumptions_capacity, char *logged_decision_outcome,
    size_t logged_decision_outcome_capacity, char *logged_decision_created_at,
    size_t logged_decision_created_at_capacity, char *logged_decision_status,
    size_t logged_decision_status_capacity, char *logged_revisit_when,
    size_t logged_revisit_when_capacity, uint64_t *logged_supersedes_id,
    char *logged_decision_subject, size_t logged_decision_subject_capacity,
    char *logged_decision_author, size_t logged_decision_author_capacity,
    uint64_t *logged_linked_policy_id, aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_DECISION_LOG_INSERT_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_DECISION_LOG_INSERT_RESPONSE_MAX_LEN];
   const size_t response_capacity = sizeof(response);
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_decision_log_insert_request_encode(
           task_id, decision_options, decision_chosen, decision_rationale, decision_assumptions,
           decision_created_at, request, sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_DECISION_LOG_INSERT, AIMEE_DB2_STAGE_DECISION_LOG_INSERT,
            trace_id, deadline_ns, request, request_len, response, response_capacity, &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_decision_log_insert_reply_decode(
           response, response_len, acknowledged, logged_decision_id, logged_task_id,
           logged_decision_options, logged_decision_options_capacity, logged_decision_chosen,
           logged_decision_chosen_capacity, logged_decision_rationale,
           logged_decision_rationale_capacity, logged_decision_assumptions,
           logged_decision_assumptions_capacity, logged_decision_outcome,
           logged_decision_outcome_capacity, logged_decision_created_at,
           logged_decision_created_at_capacity, logged_decision_status,
           logged_decision_status_capacity, logged_revisit_when, logged_revisit_when_capacity,
           logged_supersedes_id, logged_decision_subject, logged_decision_subject_capacity,
           logged_decision_author, logged_decision_author_capacity, logged_linked_policy_id) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;

   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_decision_log_record_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    const char *decision_subject, const char *decision_options, const char *decision_chosen,
    const char *decision_rationale, const char *decision_author, uint64_t linked_policy_id,
    const char *revisit_when, uint64_t supersedes_id, uint32_t *acknowledged,
    uint64_t *logged_decision_id, uint64_t *logged_task_id, char *logged_decision_options,
    size_t logged_decision_options_capacity, char *logged_decision_chosen,
    size_t logged_decision_chosen_capacity, char *logged_decision_rationale,
    size_t logged_decision_rationale_capacity, char *logged_decision_assumptions,
    size_t logged_decision_assumptions_capacity, char *logged_decision_outcome,
    size_t logged_decision_outcome_capacity, char *logged_decision_created_at,
    size_t logged_decision_created_at_capacity, char *logged_decision_status,
    size_t logged_decision_status_capacity, char *logged_revisit_when,
    size_t logged_revisit_when_capacity, uint64_t *logged_supersedes_id,
    char *logged_decision_subject, size_t logged_decision_subject_capacity,
    char *logged_decision_author, size_t logged_decision_author_capacity,
    uint64_t *logged_linked_policy_id, aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_DECISION_LOG_RECORD_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_DECISION_LOG_RECORD_RESPONSE_MAX_LEN];
   const size_t response_capacity = sizeof(response);
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_decision_log_record_request_encode(
           decision_subject, decision_options, decision_chosen, decision_rationale, decision_author,
           linked_policy_id, revisit_when, supersedes_id, request, sizeof(request),
           &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_DECISION_LOG_RECORD, AIMEE_DB2_STAGE_DECISION_LOG_RECORD,
            trace_id, deadline_ns, request, request_len, response, response_capacity, &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_decision_log_record_reply_decode(
           response, response_len, acknowledged, logged_decision_id, logged_task_id,
           logged_decision_options, logged_decision_options_capacity, logged_decision_chosen,
           logged_decision_chosen_capacity, logged_decision_rationale,
           logged_decision_rationale_capacity, logged_decision_assumptions,
           logged_decision_assumptions_capacity, logged_decision_outcome,
           logged_decision_outcome_capacity, logged_decision_created_at,
           logged_decision_created_at_capacity, logged_decision_status,
           logged_decision_status_capacity, logged_revisit_when, logged_revisit_when_capacity,
           logged_supersedes_id, logged_decision_subject, logged_decision_subject_capacity,
           logged_decision_author, logged_decision_author_capacity, logged_linked_policy_id) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;

   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_artifact_list_proposed_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    const char *target_surface, uint32_t list_limit, aimee_db2_artifact_list_proposed_row_t *rows,
    uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || (capacity > 0u && !rows))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_ARTIFACT_LIST_PROPOSED_REQUEST_MAX_LEN];
   uint8_t *response = malloc(AIMEE_DB2_ARTIFACT_LIST_PROPOSED_RESPONSE_MAX_LEN);
   if (!response)
      return AIMEE_MODULE_CALL_INTERNAL;
   const size_t response_capacity = AIMEE_DB2_ARTIFACT_LIST_PROPOSED_RESPONSE_MAX_LEN;
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_artifact_list_proposed_request_encode(target_surface, list_limit, request,
                                                       sizeof(request), &request_len) != 0)
   {
      free(response);
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   }
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_ARTIFACT_LIST_PROPOSED,
            AIMEE_DB2_STAGE_ARTIFACT_LIST_PROPOSED, trace_id, deadline_ns, request, request_len,
            response, response_capacity, &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
   {
      free(response);
      return transport;
   }
   if (aimee_db2_artifact_list_proposed_reply_decode(response, response_len, rows, capacity,
                                                     count) != 0)
   {
      free(response);
      return AIMEE_MODULE_CALL_PROTOCOL;
   }
   free(response);

   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_audit_event_list_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    const char *since_at, const char *until_at, const char *scope_kind, uint32_t list_limit,
    aimee_db2_audit_event_list_row_t *rows, uint32_t capacity, uint32_t *count,
    aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || (capacity > 0u && !rows))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_AUDIT_EVENT_LIST_REQUEST_MAX_LEN];
   uint8_t *response = malloc(AIMEE_DB2_AUDIT_EVENT_LIST_RESPONSE_MAX_LEN);
   if (!response)
      return AIMEE_MODULE_CALL_INTERNAL;
   const size_t response_capacity = AIMEE_DB2_AUDIT_EVENT_LIST_RESPONSE_MAX_LEN;
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_audit_event_list_request_encode(since_at, until_at, scope_kind, list_limit,
                                                 request, sizeof(request), &request_len) != 0)
   {
      free(response);
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   }
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_AUDIT_EVENT_LIST, AIMEE_DB2_STAGE_AUDIT_EVENT_LIST,
            trace_id, deadline_ns, request, request_len, response, response_capacity, &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
   {
      free(response);
      return transport;
   }
   if (aimee_db2_audit_event_list_reply_decode(response, response_len, rows, capacity, count) != 0)
   {
      free(response);
      return AIMEE_MODULE_CALL_PROTOCOL;
   }
   free(response);

   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_demotion_candidates_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    uint32_t minimum_attributions, aimee_db2_demotion_candidates_row_t *rows, uint32_t capacity,
    uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || (capacity > 0u && !rows))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_DEMOTION_CANDIDATES_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_DEMOTION_CANDIDATES_RESPONSE_MAX_LEN];
   const size_t response_capacity = sizeof(response);
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_demotion_candidates_request_encode(minimum_attributions, request, sizeof(request),
                                                    &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_DEMOTION_CANDIDATES, AIMEE_DB2_STAGE_DEMOTION_CANDIDATES,
            trace_id, deadline_ns, request, request_len, response, response_capacity, &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_demotion_candidates_reply_decode(response, response_len, rows, capacity, count) !=
       0)
      return AIMEE_MODULE_CALL_PROTOCOL;

   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_calibration_conformal_window_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    const char *target_surface, const char *artifact_kind, const char *scope_kind,
    const char *scope_id, uint32_t window_rows, aimee_db2_calibration_conformal_window_row_t *rows,
    uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || (capacity > 0u && !rows))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_CALIBRATION_CONFORMAL_WINDOW_REQUEST_MAX_LEN];
   uint8_t *response = malloc(AIMEE_DB2_CALIBRATION_CONFORMAL_WINDOW_RESPONSE_MAX_LEN);
   if (!response)
      return AIMEE_MODULE_CALL_INTERNAL;
   const size_t response_capacity = AIMEE_DB2_CALIBRATION_CONFORMAL_WINDOW_RESPONSE_MAX_LEN;
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_calibration_conformal_window_request_encode(
           target_surface, artifact_kind, scope_kind, scope_id, window_rows, request,
           sizeof(request), &request_len) != 0)
   {
      free(response);
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   }
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_CALIBRATION_CONFORMAL_WINDOW,
            AIMEE_DB2_STAGE_CALIBRATION_CONFORMAL_WINDOW, trace_id, deadline_ns, request,
            request_len, response, response_capacity, &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
   {
      free(response);
      return transport;
   }
   if (aimee_db2_calibration_conformal_window_reply_decode(response, response_len, rows, capacity,
                                                           count) != 0)
   {
      free(response);
      return AIMEE_MODULE_CALL_PROTOCOL;
   }
   free(response);

   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_calibration_audit_stats_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    const char *target_surface, const char *artifact_kind, const char *scope_kind,
    const char *scope_id, uint32_t window_rows, aimee_db2_calibration_audit_stats_row_t *rows,
    uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || (capacity > 0u && !rows))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_CALIBRATION_AUDIT_STATS_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_CALIBRATION_AUDIT_STATS_RESPONSE_MAX_LEN];
   const size_t response_capacity = sizeof(response);
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_calibration_audit_stats_request_encode(target_surface, artifact_kind, scope_kind,
                                                        scope_id, window_rows, request,
                                                        sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_CALIBRATION_AUDIT_STATS,
            AIMEE_DB2_STAGE_CALIBRATION_AUDIT_STATS, trace_id, deadline_ns, request, request_len,
            response, response_capacity, &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_calibration_audit_stats_reply_decode(response, response_len, rows, capacity,
                                                      count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;

   return AIMEE_MODULE_CALL_OK;
}
