/* Generated by scripts/gen_db2_contract.py; do not edit. */
#include <aimee/db2/client.h>
#include <aimee/db2/module_api.h>
#include <stdlib.h>

aimee_module_call_result_t
aimee_db2_async_enqueue_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                             uint64_t deadline_ns, const char *job_kind, uint64_t document_id,
                             const char *job_project, uint32_t *acknowledged,
                             aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_ASYNC_ENQUEUE_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_ASYNC_ENQUEUE_RESPONSE_MAX_LEN];
   const size_t response_capacity = sizeof(response);
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_async_enqueue_request_encode(job_kind, document_id, job_project, request,
                                              sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_ASYNC_ENQUEUE, AIMEE_DB2_STAGE_ASYNC_ENQUEUE, trace_id,
            deadline_ns, request, request_len, response, response_capacity, &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_async_enqueue_reply_decode(response, response_len, acknowledged) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;

   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_corpus_pipeline_status_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    uint32_t *corpus_total, uint32_t *corpus_pending, uint32_t *corpus_running,
    uint32_t *corpus_failed, uint32_t *corpus_complete, uint32_t *corpus_processed,
    uint32_t *corpus_skipped, aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_CORPUS_PIPELINE_STATUS_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_CORPUS_PIPELINE_STATUS_RESPONSE_MAX_LEN];
   const size_t response_capacity = sizeof(response);
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_corpus_pipeline_status_request_encode(request, sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_CORPUS_PIPELINE_STATUS,
            AIMEE_DB2_STAGE_CORPUS_PIPELINE_STATUS, trace_id, deadline_ns, request, request_len,
            response, response_capacity, &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_corpus_pipeline_status_reply_decode(
           response, response_len, corpus_total, corpus_pending, corpus_running, corpus_failed,
           corpus_complete, corpus_processed, corpus_skipped) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;

   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_corpus_pipeline_drain_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    uint32_t drain_limit, uint32_t *drained, uint32_t *corpus_total, uint32_t *corpus_pending,
    uint32_t *corpus_running, uint32_t *corpus_failed, uint32_t *corpus_complete,
    uint32_t *corpus_processed, uint32_t *corpus_skipped, aimee_module_cancelled_fn cancelled,
    void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_CORPUS_PIPELINE_DRAIN_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_CORPUS_PIPELINE_DRAIN_RESPONSE_MAX_LEN];
   const size_t response_capacity = sizeof(response);
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_corpus_pipeline_drain_request_encode(drain_limit, request, sizeof(request),
                                                      &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_CORPUS_PIPELINE_DRAIN,
            AIMEE_DB2_STAGE_CORPUS_PIPELINE_DRAIN, trace_id, deadline_ns, request, request_len,
            response, response_capacity, &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_corpus_pipeline_drain_reply_decode(
           response, response_len, drained, corpus_total, corpus_pending, corpus_running,
           corpus_failed, corpus_complete, corpus_processed, corpus_skipped) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;

   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_kb_doc_read_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    uint64_t doc_id, uint32_t *doc_found, char *content_hash, size_t content_hash_capacity,
    char *doc_filename, size_t doc_filename_capacity, char *doc_scope, size_t doc_scope_capacity,
    char *converter, size_t converter_capacity, char *converter_version,
    size_t converter_version_capacity, char *doc_state, size_t doc_state_capacity,
    uint32_t *review_needed, char *review_reason, size_t review_reason_capacity,
    char *doc_created_at, size_t doc_created_at_capacity, char *doc_updated_at,
    size_t doc_updated_at_capacity, aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_KB_DOC_READ_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_KB_DOC_READ_RESPONSE_MAX_LEN];
   const size_t response_capacity = sizeof(response);
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_kb_doc_read_request_encode(doc_id, request, sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_KB_DOC_READ, AIMEE_DB2_STAGE_KB_DOC_READ, trace_id,
            deadline_ns, request, request_len, response, response_capacity, &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_kb_doc_read_reply_decode(
           response, response_len, doc_found, content_hash, content_hash_capacity, doc_filename,
           doc_filename_capacity, doc_scope, doc_scope_capacity, converter, converter_capacity,
           converter_version, converter_version_capacity, doc_state, doc_state_capacity,
           review_needed, review_reason, review_reason_capacity, doc_created_at,
           doc_created_at_capacity, doc_updated_at, doc_updated_at_capacity) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;

   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_kb_doc_set_state_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    uint64_t doc_id, const char *doc_state, uint32_t clear_review_needed, const char *review_reason,
    uint32_t *acknowledged, aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_KB_DOC_SET_STATE_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_KB_DOC_SET_STATE_RESPONSE_MAX_LEN];
   const size_t response_capacity = sizeof(response);
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_kb_doc_set_state_request_encode(doc_id, doc_state, clear_review_needed,
                                                 review_reason, request, sizeof(request),
                                                 &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_KB_DOC_SET_STATE, AIMEE_DB2_STAGE_KB_DOC_SET_STATE,
            trace_id, deadline_ns, request, request_len, response, response_capacity, &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_kb_doc_set_state_reply_decode(response, response_len, acknowledged) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;

   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_kb_file_index_get_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    const char *project_name, const char *file_path, uint32_t *file_found, char *file_hash,
    size_t file_hash_capacity, char *ingested_at, size_t ingested_at_capacity,
    aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_KB_FILE_INDEX_GET_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_KB_FILE_INDEX_GET_RESPONSE_MAX_LEN];
   const size_t response_capacity = sizeof(response);
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_kb_file_index_get_request_encode(project_name, file_path, request, sizeof(request),
                                                  &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_KB_FILE_INDEX_GET, AIMEE_DB2_STAGE_KB_FILE_INDEX_GET,
            trace_id, deadline_ns, request, request_len, response, response_capacity, &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_kb_file_index_get_reply_decode(response, response_len, file_found, file_hash,
                                                file_hash_capacity, ingested_at,
                                                ingested_at_capacity) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;

   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_kb_ingest_queue_complete_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    uint64_t ingest_job_id, uint32_t files_indexed, uint32_t chunks_added,
    uint32_t embeddings_added, uint32_t *acknowledged, aimee_module_cancelled_fn cancelled,
    void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_KB_INGEST_QUEUE_COMPLETE_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_KB_INGEST_QUEUE_COMPLETE_RESPONSE_MAX_LEN];
   const size_t response_capacity = sizeof(response);
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_kb_ingest_queue_complete_request_encode(ingest_job_id, files_indexed, chunks_added,
                                                         embeddings_added, request, sizeof(request),
                                                         &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_KB_INGEST_QUEUE_COMPLETE,
            AIMEE_DB2_STAGE_KB_INGEST_QUEUE_COMPLETE, trace_id, deadline_ns, request, request_len,
            response, response_capacity, &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_kb_ingest_queue_complete_reply_decode(response, response_len, acknowledged) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;

   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_count_embeddings_for_version_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    const char *embedding_version, uint32_t *embedding_count, aimee_module_cancelled_fn cancelled,
    void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_COUNT_EMBEDDINGS_FOR_VERSION_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_COUNT_EMBEDDINGS_FOR_VERSION_RESPONSE_MAX_LEN];
   const size_t response_capacity = sizeof(response);
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_count_embeddings_for_version_request_encode(embedding_version, request,
                                                             sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_COUNT_EMBEDDINGS_FOR_VERSION,
            AIMEE_DB2_STAGE_COUNT_EMBEDDINGS_FOR_VERSION, trace_id, deadline_ns, request,
            request_len, response, response_capacity, &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_count_embeddings_for_version_reply_decode(response, response_len,
                                                           embedding_count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;

   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_kb_release_read_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    uint64_t release_id, uint32_t *release_found, char *release_name, size_t release_name_capacity,
    char *release_state, size_t release_state_capacity, char *promoted_at,
    size_t promoted_at_capacity, char *retired_at, size_t retired_at_capacity,
    char *release_created_at, size_t release_created_at_capacity,
    aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_KB_RELEASE_READ_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_KB_RELEASE_READ_RESPONSE_MAX_LEN];
   const size_t response_capacity = sizeof(response);
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_kb_release_read_request_encode(release_id, request, sizeof(request),
                                                &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_KB_RELEASE_READ, AIMEE_DB2_STAGE_KB_RELEASE_READ,
            trace_id, deadline_ns, request, request_len, response, response_capacity, &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_kb_release_read_reply_decode(
           response, response_len, release_found, release_name, release_name_capacity,
           release_state, release_state_capacity, promoted_at, promoted_at_capacity, retired_at,
           retired_at_capacity, release_created_at, release_created_at_capacity) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;

   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_kb_release_promote_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                  uint64_t deadline_ns, uint64_t release_id, uint32_t *acknowledged,
                                  aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_KB_RELEASE_PROMOTE_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_KB_RELEASE_PROMOTE_RESPONSE_MAX_LEN];
   const size_t response_capacity = sizeof(response);
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_kb_release_promote_request_encode(release_id, request, sizeof(request),
                                                   &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_KB_RELEASE_PROMOTE, AIMEE_DB2_STAGE_KB_RELEASE_PROMOTE,
            trace_id, deadline_ns, request, request_len, response, response_capacity, &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_kb_release_promote_reply_decode(response, response_len, acknowledged) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;

   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_kb_release_rollback_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                   uint64_t deadline_ns, uint64_t target_release_id,
                                   uint32_t *acknowledged, aimee_module_cancelled_fn cancelled,
                                   void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_KB_RELEASE_ROLLBACK_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_KB_RELEASE_ROLLBACK_RESPONSE_MAX_LEN];
   const size_t response_capacity = sizeof(response);
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_kb_release_rollback_request_encode(target_release_id, request, sizeof(request),
                                                    &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_KB_RELEASE_ROLLBACK, AIMEE_DB2_STAGE_KB_RELEASE_ROLLBACK,
            trace_id, deadline_ns, request, request_len, response, response_capacity, &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_kb_release_rollback_reply_decode(response, response_len, acknowledged) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;

   return AIMEE_MODULE_CALL_OK;
}
