/* Generated by scripts/gen_db2_contract.py; do not edit. */
#include <aimee/db2/client.h>
#include <aimee/db2/module_api.h>

aimee_module_call_result_t aimee_db2_prospective_sweep_expired_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    uint32_t *expired_count, aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call || !expired_count)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   *expired_count = 0u;
   uint8_t request[AIMEE_DB2_PROSPECTIVE_SWEEP_EXPIRED_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_PROSPECTIVE_SWEEP_EXPIRED_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_prospective_sweep_expired_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_PROSPECTIVE_SWEEP_EXPIRED,
            AIMEE_DB2_STAGE_PROSPECTIVE_SWEEP_EXPIRED, trace_id, deadline_ns, request,
            sizeof(request), response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_prospective_sweep_expired_reply_decode(response, response_len, expired_count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_directive_sweep_expired_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    uint32_t *directives_expired, aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call || !directives_expired)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   *directives_expired = 0u;
   uint8_t request[AIMEE_DB2_DIRECTIVE_SWEEP_EXPIRED_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_DIRECTIVE_SWEEP_EXPIRED_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_directive_sweep_expired_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_DIRECTIVE_SWEEP_EXPIRED,
            AIMEE_DB2_STAGE_DIRECTIVE_SWEEP_EXPIRED, trace_id, deadline_ns, request,
            sizeof(request), response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_directive_sweep_expired_reply_decode(response, response_len, directives_expired) !=
       0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_mark_revisit_due_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                uint64_t deadline_ns, uint32_t *marked_count,
                                aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call || !marked_count)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   *marked_count = 0u;
   uint8_t request[AIMEE_DB2_MARK_REVISIT_DUE_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_MARK_REVISIT_DUE_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_mark_revisit_due_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_MARK_REVISIT_DUE, AIMEE_DB2_STAGE_MARK_REVISIT_DUE,
            trace_id, deadline_ns, request, sizeof(request), response, sizeof(response),
            &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_mark_revisit_due_reply_decode(response, response_len, marked_count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_ingest_queue_reset_running_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    uint32_t *reset_count, aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call || !reset_count)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   *reset_count = 0u;
   uint8_t request[AIMEE_DB2_INGEST_QUEUE_RESET_RUNNING_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_INGEST_QUEUE_RESET_RUNNING_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_ingest_queue_reset_running_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_INGEST_QUEUE_RESET_RUNNING,
            AIMEE_DB2_STAGE_INGEST_QUEUE_RESET_RUNNING, trace_id, deadline_ns, request,
            sizeof(request), response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_ingest_queue_reset_running_reply_decode(response, response_len, reset_count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_evidence_reembed_all_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                    uint64_t deadline_ns, uint32_t *requeued_rows,
                                    aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call || !requeued_rows)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   *requeued_rows = 0u;
   uint8_t request[AIMEE_DB2_EVIDENCE_REEMBED_ALL_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_EVIDENCE_REEMBED_ALL_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_evidence_reembed_all_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_EVIDENCE_REEMBED_ALL,
            AIMEE_DB2_STAGE_EVIDENCE_REEMBED_ALL, trace_id, deadline_ns, request, sizeof(request),
            response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_evidence_reembed_all_reply_decode(response, response_len, requeued_rows) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_curator_reembed_all_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                   uint64_t deadline_ns, uint32_t *demoted_artifacts,
                                   aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call || !demoted_artifacts)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   *demoted_artifacts = 0u;
   uint8_t request[AIMEE_DB2_CURATOR_REEMBED_ALL_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_CURATOR_REEMBED_ALL_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_curator_reembed_all_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_CURATOR_REEMBED_ALL, AIMEE_DB2_STAGE_CURATOR_REEMBED_ALL,
            trace_id, deadline_ns, request, sizeof(request), response, sizeof(response),
            &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_curator_reembed_all_reply_decode(response, response_len, demoted_artifacts) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_synth_reenqueue_all_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                   uint64_t deadline_ns, uint32_t *reenqueued_ops,
                                   aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call || !reenqueued_ops)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   *reenqueued_ops = 0u;
   uint8_t request[AIMEE_DB2_SYNTH_REENQUEUE_ALL_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_SYNTH_REENQUEUE_ALL_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_synth_reenqueue_all_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_SYNTH_REENQUEUE_ALL, AIMEE_DB2_STAGE_SYNTH_REENQUEUE_ALL,
            trace_id, deadline_ns, request, sizeof(request), response, sizeof(response),
            &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_synth_reenqueue_all_reply_decode(response, response_len, reenqueued_ops) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_curator_reenqueue_extract_all_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    uint32_t *extract_jobs, aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call || !extract_jobs)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   *extract_jobs = 0u;
   uint8_t request[AIMEE_DB2_CURATOR_REENQUEUE_EXTRACT_ALL_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_CURATOR_REENQUEUE_EXTRACT_ALL_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_curator_reenqueue_extract_all_request_encode(request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_CURATOR_REENQUEUE_EXTRACT_ALL,
            AIMEE_DB2_STAGE_CURATOR_REENQUEUE_EXTRACT_ALL, trace_id, deadline_ns, request,
            sizeof(request), response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_curator_reenqueue_extract_all_reply_decode(response, response_len, extract_jobs) !=
       0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_directive_suppress_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                  uint64_t deadline_ns, uint64_t directive_id,
                                  aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_DIRECTIVE_SUPPRESS_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_DIRECTIVE_SUPPRESS_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_directive_suppress_request_encode(directive_id, request, sizeof(request)) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_DIRECTIVE_SUPPRESS, AIMEE_DB2_STAGE_DIRECTIVE_SUPPRESS,
            trace_id, deadline_ns, request, sizeof(request), response, sizeof(response),
            &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_directive_suppress_reply_decode(response, response_len) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_directive_record_surface_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    uint64_t directive_id, aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_DIRECTIVE_RECORD_SURFACE_REQUEST_LEN];
   uint8_t response[AIMEE_DB2_DIRECTIVE_RECORD_SURFACE_RESPONSE_LEN];
   uint32_t response_len = 0u;
   if (aimee_db2_directive_record_surface_request_encode(directive_id, request, sizeof(request)) !=
       0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_DIRECTIVE_RECORD_SURFACE,
            AIMEE_DB2_STAGE_DIRECTIVE_RECORD_SURFACE, trace_id, deadline_ns, request,
            sizeof(request), response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_directive_record_surface_reply_decode(response, response_len) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_async_pending_count_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                   uint64_t deadline_ns, const char *kind, uint32_t *count,
                                   aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || !kind)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_ASYNC_PENDING_COUNT_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_ASYNC_PENDING_COUNT_RESPONSE_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_async_pending_count_request_encode(kind, request, sizeof(request), &request_len) !=
       0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_ASYNC_PENDING_COUNT, AIMEE_DB2_STAGE_ASYNC_PENDING_COUNT,
            trace_id, deadline_ns, request, request_len, response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_async_pending_count_reply_decode(response, response_len, count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_runtime_state_touch_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                   uint64_t deadline_ns, const char *state_key,
                                   aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call || !state_key)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_RUNTIME_STATE_TOUCH_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_RUNTIME_STATE_TOUCH_RESPONSE_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_runtime_state_touch_request_encode(state_key, request, sizeof(request),
                                                    &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_RUNTIME_STATE_TOUCH, AIMEE_DB2_STAGE_RUNTIME_STATE_TOUCH,
            trace_id, deadline_ns, request, request_len, response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_runtime_state_touch_reply_decode(response, response_len) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_synth_enqueue_call(aimee_db2_call_fn call, void *call_context,
                                                        uint64_t trace_id, uint64_t deadline_ns,
                                                        const char *artifact_id,
                                                        aimee_module_cancelled_fn cancelled,
                                                        void *cancel_context)
{
   if (!call || !artifact_id)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_SYNTH_ENQUEUE_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_SYNTH_ENQUEUE_RESPONSE_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_synth_enqueue_request_encode(artifact_id, request, sizeof(request),
                                              &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_SYNTH_ENQUEUE, AIMEE_DB2_STAGE_SYNTH_ENQUEUE, trace_id,
            deadline_ns, request, request_len, response, sizeof(response), &response_len, cancelled,
            cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_synth_enqueue_reply_decode(response, response_len) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_synth_mark_done_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                               uint64_t deadline_ns, const char *artifact_id,
                               aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call || !artifact_id)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_SYNTH_MARK_DONE_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_SYNTH_MARK_DONE_RESPONSE_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_synth_mark_done_request_encode(artifact_id, request, sizeof(request),
                                                &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_SYNTH_MARK_DONE, AIMEE_DB2_STAGE_SYNTH_MARK_DONE,
            trace_id, deadline_ns, request, request_len, response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_synth_mark_done_reply_decode(response, response_len) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_reembed_mark_finished_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                     uint64_t deadline_ns, const char *finished_at,
                                     aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call || !finished_at)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_REEMBED_MARK_FINISHED_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_REEMBED_MARK_FINISHED_RESPONSE_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_reembed_mark_finished_request_encode(finished_at, request, sizeof(request),
                                                      &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_REEMBED_MARK_FINISHED,
            AIMEE_DB2_STAGE_REEMBED_MARK_FINISHED, trace_id, deadline_ns, request, request_len,
            response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_reembed_mark_finished_reply_decode(response, response_len) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_mining_job_try_lock_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                   uint64_t deadline_ns, const char *job_id, uint32_t *acquired,
                                   aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (acquired)
      *acquired = 0u;
   if (!call || !acquired || !job_id)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_MINING_JOB_TRY_LOCK_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_MINING_JOB_TRY_LOCK_RESPONSE_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_mining_job_try_lock_request_encode(job_id, request, sizeof(request),
                                                    &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_MINING_JOB_TRY_LOCK, AIMEE_DB2_STAGE_MINING_JOB_TRY_LOCK,
            trace_id, deadline_ns, request, request_len, response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_mining_job_try_lock_reply_decode(response, response_len, acquired) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_synth_mark_failed_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                 uint64_t deadline_ns, const char *artifact_id,
                                 const char *last_error, aimee_module_cancelled_fn cancelled,
                                 void *cancel_context)
{
   if (!call || !artifact_id || !last_error)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_SYNTH_MARK_FAILED_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_SYNTH_MARK_FAILED_RESPONSE_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_synth_mark_failed_request_encode(artifact_id, last_error, request, sizeof(request),
                                                  &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_SYNTH_MARK_FAILED, AIMEE_DB2_STAGE_SYNTH_MARK_FAILED,
            trace_id, deadline_ns, request, request_len, response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_synth_mark_failed_reply_decode(response, response_len) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_runtime_state_set_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                 uint64_t deadline_ns, const char *state_key,
                                 const char *state_value, aimee_module_cancelled_fn cancelled,
                                 void *cancel_context)
{
   if (!call || !state_key || !state_value)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_RUNTIME_STATE_SET_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_RUNTIME_STATE_SET_RESPONSE_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_runtime_state_set_request_encode(state_key, state_value, request, sizeof(request),
                                                  &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_RUNTIME_STATE_SET, AIMEE_DB2_STAGE_RUNTIME_STATE_SET,
            trace_id, deadline_ns, request, request_len, response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_runtime_state_set_reply_decode(response, response_len) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_set_active_embedder_version_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    const char *version, const char *updated_at, aimee_module_cancelled_fn cancelled,
    void *cancel_context)
{
   if (!call || !version || !updated_at)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_SET_ACTIVE_EMBEDDER_VERSION_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_SET_ACTIVE_EMBEDDER_VERSION_RESPONSE_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_set_active_embedder_version_request_encode(version, updated_at, request,
                                                            sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_SET_ACTIVE_EMBEDDER_VERSION,
            AIMEE_DB2_STAGE_SET_ACTIVE_EMBEDDER_VERSION, trace_id, deadline_ns, request,
            request_len, response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_set_active_embedder_version_reply_decode(response, response_len) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_runtime_state_get_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                 uint64_t deadline_ns, const char *state_key, char *state_value,
                                 size_t state_value_capacity, aimee_module_cancelled_fn cancelled,
                                 void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_RUNTIME_STATE_GET_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_RUNTIME_STATE_GET_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_runtime_state_get_request_encode(state_key, request, sizeof(request),
                                                  &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_RUNTIME_STATE_GET, AIMEE_DB2_STAGE_RUNTIME_STATE_GET,
            trace_id, deadline_ns, request, request_len, response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_runtime_state_get_reply_decode(response, response_len, state_value,
                                                state_value_capacity) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_ingest_queue_fail_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                 uint64_t deadline_ns, uint64_t ingest_job_id,
                                 const char *error_message, uint32_t *acknowledged,
                                 aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_INGEST_QUEUE_FAIL_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_INGEST_QUEUE_FAIL_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_ingest_queue_fail_request_encode(ingest_job_id, error_message, request,
                                                  sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_INGEST_QUEUE_FAIL, AIMEE_DB2_STAGE_INGEST_QUEUE_FAIL,
            trace_id, deadline_ns, request, request_len, response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_ingest_queue_fail_reply_decode(response, response_len, acknowledged) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_reset_stuck_vector_ops_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                      uint64_t deadline_ns, uint32_t max_attempts,
                                      uint32_t *reset_rows, aimee_module_cancelled_fn cancelled,
                                      void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_RESET_STUCK_VECTOR_OPS_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_RESET_STUCK_VECTOR_OPS_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_reset_stuck_vector_ops_request_encode(max_attempts, request, sizeof(request),
                                                       &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_RESET_STUCK_VECTOR_OPS,
            AIMEE_DB2_STAGE_RESET_STUCK_VECTOR_OPS, trace_id, deadline_ns, request, request_len,
            response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_reset_stuck_vector_ops_reply_decode(response, response_len, reset_rows) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_directive_resolve_call(aimee_db2_call_fn call, void *call_context, uint64_t trace_id,
                                 uint64_t deadline_ns, uint64_t directive_id,
                                 uint64_t resolution_memory_id, uint32_t *acknowledged,
                                 aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_DIRECTIVE_RESOLVE_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_DIRECTIVE_RESOLVE_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_directive_resolve_request_encode(directive_id, resolution_memory_id, request,
                                                  sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_DIRECTIVE_RESOLVE, AIMEE_DB2_STAGE_DIRECTIVE_RESOLVE,
            trace_id, deadline_ns, request, request_len, response, sizeof(response), &response_len,
            cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_directive_resolve_reply_decode(response, response_len, acknowledged) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t
aimee_db2_css_migration_enumerate_call(aimee_db2_call_fn call, void *call_context,
                                       uint64_t trace_id, uint64_t deadline_ns, const char *project,
                                       uint32_t *enumerated, aimee_module_cancelled_fn cancelled,
                                       void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_CSS_MIGRATION_ENUMERATE_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_CSS_MIGRATION_ENUMERATE_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_css_migration_enumerate_request_encode(project, request, sizeof(request),
                                                        &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_CSS_MIGRATION_ENUMERATE,
            AIMEE_DB2_STAGE_CSS_MIGRATION_ENUMERATE, trace_id, deadline_ns, request, request_len,
            response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_css_migration_enumerate_reply_decode(response, response_len, enumerated) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_css_migration_assert_conventions_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    const char *project, const char *now_iso, uint32_t *asserted,
    aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_CSS_MIGRATION_ASSERT_CONVENTIONS_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_CSS_MIGRATION_ASSERT_CONVENTIONS_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_css_migration_assert_conventions_request_encode(
           project, now_iso, request, sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_CSS_MIGRATION_ASSERT_CONVENTIONS,
            AIMEE_DB2_STAGE_CSS_MIGRATION_ASSERT_CONVENTIONS, trace_id, deadline_ns, request,
            request_len, response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_css_migration_assert_conventions_reply_decode(response, response_len, asserted) !=
       0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_css_migration_rules_doc_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    const char *exemplar_project, char *rules_doc, size_t rules_doc_capacity,
    aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (!call)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_CSS_MIGRATION_RULES_DOC_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_CSS_MIGRATION_RULES_DOC_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_css_migration_rules_doc_request_encode(exemplar_project, request, sizeof(request),
                                                        &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_CSS_MIGRATION_RULES_DOC,
            AIMEE_DB2_STAGE_CSS_MIGRATION_RULES_DOC, trace_id, deadline_ns, request, request_len,
            response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_css_migration_rules_doc_reply_decode(response, response_len, rules_doc,
                                                      rules_doc_capacity) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}

aimee_module_call_result_t aimee_db2_retryable_index_failures_call(
    aimee_db2_call_fn call, void *call_context, uint64_t trace_id, uint64_t deadline_ns,
    uint32_t max_attempts, uint32_t limit, aimee_db2_retryable_index_failures_row_t *rows,
    uint32_t capacity, uint32_t *count, aimee_module_cancelled_fn cancelled, void *cancel_context)
{
   if (count)
      *count = 0u;
   if (!call || !count || (capacity > 0u && !rows))
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;

   uint8_t request[AIMEE_DB2_RETRYABLE_INDEX_FAILURES_REQUEST_MAX_LEN];
   uint8_t response[AIMEE_DB2_RETRYABLE_INDEX_FAILURES_RESPONSE_MAX_LEN];
   uint32_t request_len = 0u;
   uint32_t response_len = 0u;
   if (aimee_db2_retryable_index_failures_request_encode(max_attempts, limit, request,
                                                         sizeof(request), &request_len) != 0)
      return AIMEE_MODULE_CALL_INVALID_ARGUMENT;
   aimee_module_call_result_t transport =
       call(call_context, AIMEE_DB2_EVENT_RETRYABLE_INDEX_FAILURES,
            AIMEE_DB2_STAGE_RETRYABLE_INDEX_FAILURES, trace_id, deadline_ns, request, request_len,
            response, sizeof(response), &response_len, cancelled, cancel_context);
   if (transport != AIMEE_MODULE_CALL_OK)
      return transport;
   if (aimee_db2_retryable_index_failures_reply_decode(response, response_len, rows, capacity,
                                                       count) != 0)
      return AIMEE_MODULE_CALL_PROTOCOL;
   return AIMEE_MODULE_CALL_OK;
}
