#!/usr/bin/env python3
"""Guard that the thin client's method -> /v1 route map is in sync with the
server registry.

The map is generated from src/server/server_http_routes.c by
scripts/gen-cli-v1-routes.py and lives inline in the thin-client TU
(src/cli_v1_routes*.c) between the @@GEN-CLI-V1-ROUTES BEGIN/END markers. This
check regenerates the block and diffs it against what's committed in the file, so
a registry change that isn't reflected in the committed map fails `make lint`
instead of silently leaving the client without its first-class /v1 route.
"""
import glob
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GEN = ROOT / "scripts" / "gen-cli-v1-routes.py"
TARGET_GLOB = str(ROOT / "src" / "cli_v1_routes*.c")
MARK_BEGIN = "/* @@GEN-CLI-V1-ROUTES BEGIN — generated by scripts/gen-cli-v1-routes.py; DO NOT EDIT @@ */"
MARK_END = "/* @@GEN-CLI-V1-ROUTES END @@ */"


def committed_block():
    for f in sorted(glob.glob(TARGET_GLOB)):
        text = Path(f).read_text(encoding="utf-8")
        if MARK_BEGIN in text:
            return f, text.split(MARK_BEGIN, 1)[1].split(MARK_END, 1)[0].strip("\n")
    return None, None


def main() -> int:
    fname, committed = committed_block()
    if committed is None:
        print("check-cli-v1-routes: FAIL — @@GEN-CLI-V1-ROUTES markers not found in "
              "src/cli_v1_routes*.c; run scripts/gen-cli-v1-routes.py")
        return 1
    fresh = subprocess.run([sys.executable, str(GEN), "--stdout"],
                           check=True, capture_output=True, text=True).stdout.strip("\n")
    if committed != fresh:
        print("check-cli-v1-routes: FAIL — the generated /v1 route map is stale vs "
              "server_http_routes.c; run scripts/gen-cli-v1-routes.py and commit.")
        return 1
    n = sum(1 for ln in fresh.splitlines() if ln.lstrip().startswith('{"'))

    orphans = unreachable_methods()
    if orphans:
        print("check-cli-v1-routes: FAIL — these /v1 methods have a route and a "
              "marshaller but no `aimee <cmd> <sub>` row in the dispatch table in "
              "src/cli_v1_routes.c, so no thin client can invoke them:")
        for m in orphans:
            print(f"  {m}")
        return 1

    print(f"check-cli-v1-routes: ok ({n} client /v1 routes in sync, all reachable)")
    return 0


# The generated block above keeps method -> /v1 path in sync with the server, but
# the CLI subcommand -> method table is hand-written, so a method could be fully
# plumbed (path + marshaller + printer) and still be unreachable from the CLI.
# That is how `aimee kb build` shipped answering "command 'kb' has no /v1 route"
# while POST /v1/kb/build worked -- every piece existed except the dispatch row.
ROUTE_RE = re.compile(r'\{"([a-z0-9_.]+)",\s*"(?:GET|POST|PUT|DELETE)",\s*"/v1/[^"]+"\}')
MARSHAL_RE = re.compile(r'\{"([a-z0-9_.]+)",\s*marshal_[a-z0-9_]+\}')
DISPATCH_RE = re.compile(r'\{"[a-z0-9_-]+",\s*(?:NULL|"[a-z0-9 _-]*")\s*,\s*"([a-z0-9_.]+)"')


def unreachable_methods():
    routed, marshalled = set(), set()
    for f in sorted(glob.glob(TARGET_GLOB)):
        text = Path(f).read_text(encoding="utf-8")
        routed |= set(ROUTE_RE.findall(text))
        marshalled |= set(MARSHAL_RE.findall(text))
    dispatch = set(DISPATCH_RE.findall(
        Path(ROOT / "src" / "cli_v1_routes.c").read_text(encoding="utf-8")))
    return sorted((routed & marshalled) - dispatch)


if __name__ == "__main__":
    sys.exit(main())
