#!/usr/bin/env python3
"""Generate the thin client's method -> first-class /v1 route map from the server
registry, so the client calls dedicated REST endpoints instead of tunnelling
through the retired generic dispatch endpoint.

Single source of truth: src/server/server_http_routes.inc. We emit one row per
*synchronous* rh_dispatch_op route (RM_EXACT) — those dispatch the NDJSON method
twin verbatim and echo the raw dispatch response, so the HTTP reply is
byte-identical to the socket path and the client's existing response handling is
unchanged. Excluded on purpose:
  - rh_dispatch_op_async  : returns a queued run handle, not the direct result —
                            a different client contract (polled via /v1/runs/{id}).
  - bespoke handlers      : request/response may not match the NDJSON method.
  - RM_PREFIX ({id}) rows : handled by cli_v1_pathid_route_for_method.

Output: src/cli_v1_routes_gen.inc (committed). Re-run after changing the registry;
scripts/check-cli-v1-routes.py (in `make lint`) regenerates and diffs to prevent
drift. Usage: scripts/gen-cli-v1-routes.py [OUT]
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "src" / "server" / "server_http_routes.inc"
OUT = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "src" / "cli_v1_routes_gen.inc"

# {"VERB", "/v1/path", <suffix>, RM_EXACT, "op", <caps>, <handler>},
# The trailing handler distinguishes sync (rh_dispatch_op) from async
# (rh_dispatch_op_async); `\b` keeps `rh_dispatch_op` from matching the async one.
def _row(handler):
    return re.compile(
        r'\{\s*"(GET|POST|PUT|DELETE)"\s*,\s*'
        r'"(/v1/[^"]+)"\s*,\s*'
        r'(?:NULL|"[^"]*")\s*,\s*'
        r'RM_EXACT\s*,\s*'
        r'"([^"]+)"\s*,\s*'
        r'[^,]+,\s*' + handler + r'\s*\}'
    )


SYNC_ROW = _row(r'rh_dispatch_op')
ASYNC_ROW = _row(r'rh_dispatch_op_async')


def _routes(rx):
    text = REGISTRY.read_text(encoding="utf-8")
    seen = {}
    for verb, path, op in rx.findall(text):
        seen.setdefault(op, (verb, path))  # first row wins; op is unique
    return sorted((op, v, p) for op, (v, p) in seen.items())


def _emit(name, rows):
    out = ["static const struct",
           "{",
           "   const char *method;",
           "   const char *verb;",
           "   const char *path;",
           "} %s[] = {" % name]
    for op, verb, path in rows:
        out.append('    {"%s", "%s", "%s"},' % (op, verb, path))
    out.append("};")
    return out


def main():
    # ASYNC rows would also match the SYNC regex's prefix, so subtract them.
    async_rows = _routes(ASYNC_ROW)
    async_ops = {op for op, _, _ in async_rows}
    sync_rows = [r for r in _routes(SYNC_ROW) if r[0] not in async_ops]
    lines = [
        "/* Auto-generated by scripts/gen-cli-v1-routes.py from",
        " * src/server/server_http_routes.inc — DO NOT EDIT.",
        " *",
        " * method (op) -> first-class /v1 route for the thin client.",
        " *  - CLI_V1_GEN_ROUTES   : synchronous rh_dispatch_op routes; the HTTP",
        " *                          response is byte-identical to the NDJSON socket.",
        " *  - CLI_V1_ASYNC_ROUTES : rh_dispatch_op_async routes; POSTing returns a",
        " *                          run handle ({id}) the client polls at",
        " *                          GET /v1/runs/{id} until it completes.",
        " * Regenerate after changing the registry; scripts/check-cli-v1-routes.py",
        " * (make lint) guards against drift. */",
    ]
    lines += _emit("CLI_V1_GEN_ROUTES", sync_rows)
    lines.append("")
    lines += _emit("CLI_V1_ASYNC_ROUTES", async_rows)
    lines.append("")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"gen-cli-v1-routes: wrote {OUT} "
          f"({len(sync_rows)} sync + {len(async_rows)} async routes)")


if __name__ == "__main__":
    main()
