#!/usr/bin/env python3
"""Generate a faithful, machine-readable descriptor of the /v1 HTTP route table.

Single source of truth: the `g_v1_routes[]` array in
`src/server/server_http_routes.c` (the server's authoritative verb+path -> method
-> handler registry). This script extracts every row into
`docs/gen/v1-route-descriptor.json`, a canonical JSON artifact.

This is Step 1 of the "/v1 route single source of truth" proposal
(docs/proposals/done/route-descriptor-single-source-of-truth.md): stand up a
descriptor that is a *faithful, drift-guarded* extract of the authoritative
table, proving the descriptor holds every route fact, with ZERO behaviour change.
Later steps invert the flow so the other route/dispatch tables are generated FROM
this descriptor instead of hand-synced. For now it only mirrors the table; the
`docs-gen-check` gate (make lint) regenerates it and fails if it drifts.

Regenerate + commit:  make docs-gen
Print to stdout:      scripts/gen-v1-route-descriptor.py --stdout
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "src" / "server" / "server_http_routes.c"
OUT = ROOT / "docs" / "gen" / "v1-route-descriptor.json"

# http_route_t row:
#   {"VERB", "path", <suffix>, RM_EXACT|RM_PREFIX, <op>, <caps>, <handler>}
# suffix/op are NULL or a quoted string; caps is a bare token/expression with no
# comma (e.g. 0, CAP_X, CAP_A | CAP_B); handler is NULL or an rh_* identifier.
ROW_RE = re.compile(
    r'\{\s*'
    r'"(GET|POST|PUT|DELETE)"\s*,\s*'      # 1 verb
    r'"([^"]+)"\s*,\s*'                    # 2 path
    r'(NULL|"[^"]*")\s*,\s*'               # 3 suffix
    r'(RM_EXACT|RM_PREFIX)\s*,\s*'         # 4 match kind
    r'(NULL|"[^"]*")\s*,\s*'               # 5 op (NDJSON method twin)
    r'([^,}]+?)\s*,\s*'                    # 6 caps
    r'(NULL|rh_\w+)\s*\}'                  # 7 handler
)


def _array_body(text):
    """Return the source text between `g_v1_routes[] = {` and its closing `};`."""
    start = text.index("g_v1_routes[] = {")
    open_brace = text.index("{", start)
    depth = 0
    for i in range(open_brace, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[open_brace + 1:i]
    raise SystemExit("gen-v1-route-descriptor: unterminated g_v1_routes[] array")


def _unquote(tok):
    """NULL -> None; \"str\" -> str."""
    tok = tok.strip()
    if tok == "NULL":
        return None
    return tok[1:-1] if tok.startswith('"') and tok.endswith('"') else tok


def build_descriptor():
    text = REGISTRY.read_text(encoding="utf-8")
    body = _array_body(text)
    # Count candidate rows ({"...) so a parser miss surfaces loudly rather than
    # silently dropping a route.
    candidate = len(re.findall(r'\{\s*"(?:GET|POST|PUT|DELETE)"', body))
    routes = []
    for m in ROW_RE.finditer(body):
        verb, path, suffix, match, op, caps, handler = m.groups()
        routes.append({
            "verb": verb,
            "path": path,
            "suffix": _unquote(suffix),
            "match": "prefix" if match == "RM_PREFIX" else "exact",
            "op": _unquote(op),
            "caps": caps.strip(),
            "handler": None if handler == "NULL" else handler,
        })
    if len(routes) != candidate:
        raise SystemExit(
            f"gen-v1-route-descriptor: parsed {len(routes)} of {candidate} rows in "
            f"g_v1_routes[]: a row shape changed; update ROW_RE.")
    routes.sort(key=lambda r: (r["path"], r["verb"], r["suffix"] or ""))
    return {
        "_note": ("GENERATED by scripts/gen-v1-route-descriptor.py from "
                  "src/server/server_http_routes.c g_v1_routes[]. DO NOT EDIT. "
                  "Step 1 of the /v1 route SoT proposal: a faithful, "
                  "drift-guarded extract of the authoritative route table. "
                  "Regenerate: make docs-gen."),
        "source": "src/server/server_http_routes.c",
        "route_count": len(routes),
        "routes": routes,
    }


def main():
    doc = build_descriptor()
    out = json.dumps(doc, indent=2, ensure_ascii=False) + "\n"
    if "--stdout" in sys.argv[1:]:
        sys.stdout.write(out)
        return
    OUT.write_text(out, encoding="utf-8")
    print(f"gen-v1-route-descriptor: wrote {doc['route_count']} routes -> "
          f"{OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
