#!/usr/bin/env python3
"""Generate the SQL half of the subject-grammar cross-check.

The subject grammar is encoded three times (see src/tests/subject_corpus.h): a
Postgres CHECK regex and two C validators. The C ones are compared against the
corpus by src/tests/test_subject_grammar.c. This emits the same corpus as SQL so
the regex is held to it too, rather than to a separately hand-maintained list
that can quietly diverge from the C one.

Writes scripts/gen/subject-corpus.sql. Run via `make docs-gen`; verified by
`make subject-corpus-check`, which fails if the committed file is stale.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORPUS_H = ROOT / "src" / "tests" / "subject_corpus.h"
OUT = ROOT / "scripts" / "gen" / "subject-corpus.sql"

# {"subject", accept, "why"},  — tolerant of wrapped lines.
ENTRY = re.compile(r'\{\s*"((?:[^"\\]|\\.)*)"\s*,\s*([01])\s*,\s*"((?:[^"\\]|\\.)*)"\s*\}')


def sql_literal(raw: str) -> str:
    """A C string literal from the corpus -> a Postgres literal.

    Escape-bearing values become E'' strings so a tab stays a tab rather than
    becoming a literal backslash-t, which would test the wrong thing.
    """
    escaped = raw.replace("'", "''")
    if "\\" in raw:
        return "E'" + escaped + "'"
    return "'" + escaped + "'"


def main() -> int:
    text = CORPUS_H.read_text()
    entries = ENTRY.findall(text)
    if len(entries) < 20:
        print(f"gen-subject-corpus-sql: only {len(entries)} entries parsed from "
              f"{CORPUS_H} — the corpus format probably changed", file=sys.stderr)
        return 1

    accepted = [(s, w) for s, a, w in entries if a == "1"]
    refused = [(s, w) for s, a, w in entries if a == "0"]
    if not accepted or not refused:
        print("gen-subject-corpus-sql: corpus must contain both accepted and "
              "refused cases", file=sys.stderr)
        return 1

    lines = [
        "-- GENERATED by scripts/gen-subject-corpus-sql.py from",
        "-- src/tests/subject_corpus.h. Do not edit: edit the corpus and regenerate.",
        "--",
        "-- Holds the `subject` CHECK regex to the same corpus the two C validators",
        "-- are held to by src/tests/test_subject_grammar.c. Three copies of one rule",
        "-- drift silently — whichever is stricter just wins — so they are all tested",
        "-- against one list rather than against their own authors' assumptions.",
        "--",
        "-- SELF-CONTAINED: it builds its own team + registry fixture and rolls back, so",
        "-- it does not depend on another test file's fixture surviving. It previously did,",
        "-- and the gate caught it — the identity-authority test ends with ROLLBACK, so its",
        "-- fixture was already gone by the time this ran.",
        "",
        "\\set ON_ERROR_STOP on",
        "BEGIN;",
        "",
        "INSERT INTO kb_team(id, name) VALUES (930901, 'subject_corpus_team');",
        "INSERT INTO kb_server_registry(server_id, cert_cn, mgmt_cert_cn, team_id, endpoint, status)",
        "  VALUES ('corpussrv', 'corpus-cn', 'corpus-mgmt-cn', 930901, 'https://corpussrv', 'active');",
        "",
        "DO $CORPUS$",
        "DECLARE ok BOOLEAN; s TEXT; why TEXT;",
        "BEGIN",
    ]

    for subject, why in accepted:
        lines += [
            f"  s := {sql_literal(subject)}; why := {sql_literal(why)};",
            "  BEGIN",
            "    INSERT INTO kb_write_tier_grant(server_id, team_id, subject, tier, granted_by)",
            "      VALUES ('corpussrv', 930901, s, 'data', 'owner');",
            "    DELETE FROM kb_write_tier_grant WHERE server_id='corpussrv' AND subject=s;",
            "  EXCEPTION WHEN check_violation THEN",
            "    RAISE EXCEPTION 'FAIL: subject CHECK refused a valid subject [%] (%)', s, why;",
            "  END;",
        ]

    for subject, why in refused:
        lines += [
            f"  s := {sql_literal(subject)}; why := {sql_literal(why)};",
            "  ok := false;",
            "  BEGIN",
            "    INSERT INTO kb_write_tier_grant(server_id, team_id, subject, tier, granted_by)",
            "      VALUES ('corpussrv', 930901, s, 'data', 'owner');",
            "  EXCEPTION WHEN check_violation THEN ok := true;",
            "  END;",
            "  IF NOT ok THEN",
            "    DELETE FROM kb_write_tier_grant WHERE server_id='corpussrv' AND subject=s;",
            "    RAISE EXCEPTION 'FAIL: subject CHECK admitted a non-subject [%] (%)', s, why;",
            "  END IF;",
        ]

    lines += [
        "END $CORPUS$;",
        "",
        "ROLLBACK;",
        "",
        f"\\echo '== subject grammar: {len(accepted)} accepted / {len(refused)} refused, "
        "CHECK agrees with the C validators =='",
        "",
    ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"gen-subject-corpus-sql: wrote {OUT.relative_to(ROOT)} "
          f"({len(accepted)} accepted, {len(refused)} refused)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
