#!/usr/bin/env python3
"""Generate the compact NFKC-then-casefold table used by fact_identity.c."""

from pathlib import Path
import unicodedata


OUT_DIR = Path(__file__).resolve().parents[1] / "src/modules/db2/c"
OUT_C = OUT_DIR / "fact_identity_unicode.c"
OUT_H = OUT_DIR / "fact_identity_unicode.h"


def append_rows(lines: list[str], rows: list[str], per_line: int) -> None:
    """Pack generated initializers so the ordinary C TU stays below line-check."""
    for i in range(0, len(rows), per_line):
        lines.append("   " + " ".join(rows[i : i + per_line]))


def main() -> None:
    decompositions: list[tuple[int, int, int]] = []
    decomp_pool: list[int] = []
    folds: list[tuple[int, int, int]] = []
    fold_pool: list[int] = []
    combining: list[tuple[int, int]] = []
    compositions: list[tuple[int, int, int]] = []
    spaces: list[int] = []
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        ch = chr(cp)
        decomp = unicodedata.normalize("NFKD", ch)
        # Hangul syllables are decomposed algorithmically in C; omitting their
        # 11,172 rows keeps the checked-in table compact.
        if decomp != ch and not 0xAC00 <= cp <= 0xD7A3:
            offset = len(decomp_pool)
            decomp_pool.extend(ord(c) for c in decomp)
            decompositions.append((cp, offset, len(decomp)))
        folded = ch.casefold()
        if folded != ch:
            offset = len(fold_pool)
            fold_pool.extend(ord(c) for c in folded)
            folds.append((cp, offset, len(folded)))
        ccc = unicodedata.combining(ch)
        if ccc:
            combining.append((cp, ccc))
        nfd = unicodedata.normalize("NFD", ch)
        if len(nfd) == 2 and unicodedata.normalize("NFC", nfd) == ch:
            compositions.append((ord(nfd[0]), ord(nfd[1]), cp))
        if ch.isspace():
            spaces.append(cp)

    header = [
        "/* Generated by scripts/gen_fact_identity_unicode.py; do not edit.",
        f" * Unicode database: {unicodedata.unidata_version}. */",
        "#ifndef AIMEE_FACT_IDENTITY_UNICODE_H",
        "#define AIMEE_FACT_IDENTITY_UNICODE_H",
        "#include <stdint.h>",
        "typedef struct { uint32_t cp, offset; uint16_t len; } fi_unicode_map_t;",
        "typedef struct { uint32_t cp; uint8_t ccc; } fi_unicode_ccc_t;",
        "typedef struct { uint32_t first, second, composed; } fi_unicode_compose_t;",
        f"#define FI_NFKD_POOL_COUNT {len(decomp_pool)}u",
        f"#define FI_NFKD_MAP_COUNT {len(decompositions)}u",
        f"#define FI_CASEFOLD_POOL_COUNT {len(fold_pool)}u",
        f"#define FI_CASEFOLD_MAP_COUNT {len(folds)}u",
        f"#define FI_UNICODE_CCC_COUNT {len(combining)}u",
        f"#define FI_UNICODE_COMPOSE_COUNT {len(compositions)}u",
        f"#define FI_UNICODE_SPACES_COUNT {len(spaces)}u",
        "extern const uint32_t FI_NFKD_POOL[FI_NFKD_POOL_COUNT];",
        "extern const fi_unicode_map_t FI_NFKD_MAP[FI_NFKD_MAP_COUNT];",
        "extern const uint32_t FI_CASEFOLD_POOL[FI_CASEFOLD_POOL_COUNT];",
        "extern const fi_unicode_map_t FI_CASEFOLD_MAP[FI_CASEFOLD_MAP_COUNT];",
        "extern const fi_unicode_ccc_t FI_UNICODE_CCC[FI_UNICODE_CCC_COUNT];",
        "extern const fi_unicode_compose_t FI_UNICODE_COMPOSE[FI_UNICODE_COMPOSE_COUNT];",
        "extern const uint32_t FI_UNICODE_SPACES[FI_UNICODE_SPACES_COUNT];",
        "#endif",
        "",
    ]
    lines = [
        "/* Generated by scripts/gen_fact_identity_unicode.py; do not edit.",
        f" * Unicode database: {unicodedata.unidata_version}. */",
        '#include "fact_identity_unicode.h"',
        "// clang-format off",
        "const uint32_t FI_NFKD_POOL[FI_NFKD_POOL_COUNT] = {",
    ]
    for i in range(0, len(decomp_pool), 24):
        lines.append("   " + ", ".join(f"0x{x:X}u" for x in decomp_pool[i : i + 24]) + ",")
    lines.extend(["};", "const fi_unicode_map_t FI_NFKD_MAP[FI_NFKD_MAP_COUNT] = {"])
    append_rows(lines, [f"{{0x{cp:X}u, {offset}u, {length}u}}," for cp, offset, length in decompositions], 24)
    lines.extend(["};", "const uint32_t FI_CASEFOLD_POOL[FI_CASEFOLD_POOL_COUNT] = {"])
    for i in range(0, len(fold_pool), 24):
        lines.append("   " + ", ".join(f"0x{x:X}u" for x in fold_pool[i : i + 24]) + ",")
    lines.extend(["};", "const fi_unicode_map_t FI_CASEFOLD_MAP[FI_CASEFOLD_MAP_COUNT] = {"])
    append_rows(lines, [f"{{0x{cp:X}u, {offset}u, {length}u}}," for cp, offset, length in folds], 24)
    lines.extend([
        "};",
        "const fi_unicode_ccc_t FI_UNICODE_CCC[FI_UNICODE_CCC_COUNT] = {",
    ])
    append_rows(lines, [f"{{0x{cp:X}u, {ccc}u}}," for cp, ccc in combining], 24)
    lines.extend([
        "};",
        "const fi_unicode_compose_t FI_UNICODE_COMPOSE[FI_UNICODE_COMPOSE_COUNT] = {",
    ])
    append_rows(lines, [f"{{0x{first:X}u, 0x{second:X}u, 0x{composed:X}u}}," for first, second, composed in sorted(compositions)], 12)
    lines.extend(["};", "const uint32_t FI_UNICODE_SPACES[FI_UNICODE_SPACES_COUNT] = {"])
    for i in range(0, len(spaces), 12):
        lines.append("   " + ", ".join(f"0x{x:X}u" for x in spaces[i : i + 12]) + ",")
    lines.extend(["};", "// clang-format on", ""])
    OUT_H.write_text("\n".join(header), encoding="utf-8")
    OUT_C.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
