#!/usr/bin/env python3
"""Generate the event-bus wire conformance vectors.

These bytes are the cross-language authority (D8 of docs/dev/EVENT_BUS_DECISIONS.md):
the C codec, the Go reference client (slice 9), and any third-language client are
all held to them.

This generator exists so that authority is *independent*. If the vectors were
produced by the C encoder and then verified by re-running the C encoder, a bug
in that encoder would be baked into the table and pass its own check — the
vectors would be a copy of the implementation rather than a statement about the
wire. So the layout is re-declared here from the spec, byte offset by byte
offset, using struct.pack. Two implementations built from the same prose, in
different languages, agreeing byte-for-byte is evidence; one implementation
agreeing with itself is not.

Regeneration is a deliberate, reviewable act: run this, commit the diff, and the
diff shows exactly which bytes moved.

    scripts/gen_bus_wire_vectors.py > src/tests/fixtures/bus/wire_vectors.tsv
"""

import struct
import sys

HDR_LEN = 64
MAGIC = 0x30535542  # "BUS0" little-endian
WIRE_VERSION = 1

# hdr_flags
F_INLINE = 0x0001
F_ARENA = 0x0002
F_NOTIFICATION = 0x0004
F_REQUEST = 0x0008
F_REPLY = 0x0010
F_CANCEL = 0x0020
F_CONTROL = 0x0040

# reserved event kinds
K_CAPABILITY_ABSENT = 4
K_OVERFLOW = 5
K_MODULE_BASE = 256

FIELD_ORDER = [
    "flags", "ver", "kind", "principal", "corr",
    "seq", "lts", "pref", "plen", "src", "dst",
]


def encode(f):
    """Pack a frame from the spec's byte layout.

    Declared here as one format string rather than field-by-field writes, so the
    offsets are visible as a whole and a reordering cannot hide in a diff:

        <   little-endian, no padding
        I   0  magic          H  4  hdr_flags     H  6  wire_version
        I   8  event_kind     I 12  principal_ref
        Q  16  correlation_id Q 24  seq           Q 32  logical_ts
        Q  40  payload_ref    I 48  payload_len
        I  52  src_handle     I 56  dst_handle    I 60  reserved
    """
    blob = struct.pack(
        "<IHHIIQQQQIIII",
        MAGIC,
        f["flags"], f["ver"],
        f["kind"], f["principal"],
        f["corr"], f["seq"], f["lts"], f["pref"],
        f["plen"], f["src"], f["dst"], 0,
    )
    assert len(blob) == HDR_LEN, f"layout drifted: {len(blob)} != {HDR_LEN}"
    return blob


def frame(**kw):
    f = {
        "flags": 0, "ver": WIRE_VERSION, "kind": K_MODULE_BASE,
        "principal": 0x11223344, "corr": 0, "seq": 0,
        "lts": 0x0102030405060708, "pref": 0, "plen": 0, "src": 7, "dst": 0,
    }
    f.update(kw)
    return f


CORR = 0xDEADBEEFCAFEF00D
INLINE_AT = HDR_LEN  # in-slot payloads start just past the header

VECTORS = [
    # Every message pattern, so the table covers the routing contract and not
    # just the happy path.
    ("notification.empty", frame(flags=F_NOTIFICATION)),
    ("notification.inline.32",
     frame(flags=F_NOTIFICATION | F_INLINE, plen=32, pref=INLINE_AT)),
    ("notification.arena.65536",
     frame(flags=F_NOTIFICATION | F_ARENA, plen=65536, pref=0x40000)),
    ("request.arena",
     frame(flags=F_REQUEST | F_ARENA, corr=CORR, plen=4096, pref=0x80000)),
    ("reply.inline",
     frame(flags=F_REPLY | F_INLINE, corr=CORR, plen=16, pref=INLINE_AT,
           seq=4242, dst=7)),
    ("cancel", frame(flags=F_CANCEL, corr=CORR)),
    ("capability_absent",
     frame(flags=F_REPLY, kind=K_CAPABILITY_ABSENT, corr=CORR, seq=99, dst=7)),

    # An overflow notice is an ordinary seq-stamped frame carrying the control
    # flag (D6), not a side channel with a shape of its own.
    ("control.overflow",
     frame(flags=F_NOTIFICATION | F_CONTROL | F_INLINE, kind=K_OVERFLOW,
           plen=16, pref=INLINE_AT, seq=5000, dst=7)),

    # D4's independence proof: identical frames but for the placement flag, at
    # the provisional 192-byte inline budget. Nothing in the frame encodes the
    # threshold that chose the placement, so re-tuning inline_budget in slice 12
    # cannot invalidate a committed vector.
    ("budget.inline.192",
     frame(flags=F_NOTIFICATION | F_INLINE, plen=192, pref=INLINE_AT)),
    ("budget.arena.192",
     frame(flags=F_NOTIFICATION | F_ARENA, plen=192, pref=0x40000)),
]


def fields_str(f):
    return ("flags=0x%04x;ver=%u;kind=%u;principal=%u;corr=0x%016x;seq=%u;"
            "lts=0x%016x;pref=0x%016x;plen=%u;src=%u;dst=%u") % (
        f["flags"], f["ver"], f["kind"], f["principal"], f["corr"],
        f["seq"], f["lts"], f["pref"], f["plen"], f["src"], f["dst"])


def main():
    out = sys.stdout
    out.write("# event-bus wire vectors v%d — generated by scripts/gen_bus_wire_vectors.py.\n"
              % WIRE_VERSION)
    out.write("# Independent of any client implementation: the layout is re-declared\n")
    out.write("# from the spec here, so agreement between this table and a codec is\n")
    out.write("# evidence about the wire rather than a codec agreeing with itself.\n")
    out.write("# Regenerate deliberately; review the byte diff.\n")
    out.write("# name\texpect\thex\tfields\n")

    seen = set()
    for name, f in VECTORS:
        assert name not in seen, f"duplicate vector name {name}"
        seen.add(name)
        out.write("%s\tOK\t%s\t%s\n" % (name, encode(f).hex(), fields_str(f)))


if __name__ == "__main__":
    main()
