#!/usr/bin/env python3
"""Generate DB2's host-free fallback language extractor support unit."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src/modules/db2/support/extractor_primitives.c"


def read(relative: str) -> str:
    return (ROOT / relative).read_text(encoding="utf-8")


def after(text: str, marker: str, label: str) -> str:
    try:
        return text[text.index(marker):]
    except ValueError as exc:
        raise ValueError(f"{label}: missing marker {marker!r}") from exc


def generate() -> str:
    main = after(read("src/extractors.c"), "/* --- Extension mapping --- */", "extractors.c")
    extra = after(read("src/extractors_extra.c"), "/* --- C# --- */", "extractors_extra.c")
    new = after(read("src/extractors_new_langs.c"), "/* --- Java --- */",
                "extractors_new_langs.c")

    identity_start = "static void slash_normalize"
    identity_end = "static void py_export_line"
    if main.count(identity_start) != 1 or main.count(identity_end) != 1:
        raise ValueError("extractors.c: import-identity span markers must occur exactly once")
    start = main.index(identity_start)
    end = main.index(identity_end)
    if start >= end:
        raise ValueError("extractors.c: invalid import-identity span")
    main = main[:start] + main[end:]

    strdup_line = "   out[count] = strdup(s);"
    if main.count(strdup_line) != 1:
        raise ValueError("extractors.c: add_str strdup marker must occur exactly once")
    main = main.replace(
        strdup_line,
        "   size_t len = strlen(s) + 1;\n"
        "   out[count] = malloc(len);\n"
        "   if (out[count])\n"
        "      memcpy(out[count], s, len);",
    )

    system = read("src/headers/c_system_headers.h")
    system_start = "static const char *const AIMEE_C_SYSTEM_HEADERS[]"
    system_end = "#endif /* AIMEE_C_SYSTEM_HEADERS_H */"
    if system.count(system_start) != 1 or system.count(system_end) != 1:
        raise ValueError("c_system_headers.h: body markers must occur exactly once")
    system = system[system.index(system_start):system.index(system_end)].rstrip()

    bodies = (system, main.rstrip(), extra.rstrip(), new.rstrip())
    bodies = tuple(body.replace("definition_t", "db2_definition_t")
                   .replace("call_ref_t", "db2_call_ref_t") for body in bodies)

    prelude = """/* Generated by scripts/gen_db2_extractor_support.py; DO NOT EDIT.
 *
 * This is the default, host-free extractor path used by the standalone C DB2
 * owner. Optional tree-sitter grammars remain a later module artifact. */
#include "db2_extractors.h"

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int code_treesitter_available(const char *ext)
{
   (void)ext;
   return 0;
}

static int code_treesitter_definitions(const char *ext, const char *content,
                                       db2_definition_t *out, int max)
{
   (void)ext;
   (void)content;
   (void)out;
   (void)max;
   return -1;
}

static int code_treesitter_calls(const char *ext, const char *content, db2_call_ref_t *out,
                                 int max)
{
   (void)ext;
   (void)content;
   (void)out;
   (void)max;
   return -1;
}

"""
    return prelude + "\n\n".join(bodies) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the generated file differs")
    args = parser.parse_args()
    try:
        expected = generate()
        if args.check:
            actual = OUTPUT.read_text(encoding="utf-8")
            if actual != expected:
                raise ValueError(f"{OUTPUT.relative_to(ROOT)} is stale; regenerate it")
            print("gen_db2_extractor_support: ok")
            return 0
        OUTPUT.write_text(expected, encoding="utf-8")
        print(f"gen_db2_extractor_support: wrote {OUTPUT.relative_to(ROOT)}")
        return 0
    except (OSError, UnicodeError, ValueError) as exc:
        print(f"gen_db2_extractor_support: error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
