#!/usr/bin/env python3
"""Validate descriptor-v1 envelopes against the canonical module taxonomy."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import sys
import unicodedata
from typing import NoReturn


REPO_ROOT = Path(__file__).resolve().parent.parent
INVENTORY_PATH = Path("tests/baselines/modules/canonical-inventory.yaml")
SCHEMA_PATH = Path("src/modules/module.schema.json")
VERSION = 1
MAX_BYTES = 1_048_576
MAX_DEPTH = 32
MAX_ARRAY = 256
ID_RE = re.compile(r"^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$")
BASE_KEYS = {"descriptor_version", "id", "dependencies", "runtime_toggle"}
DEFAULT_ON = {"runtime-web", "control-web"}


class DescriptorError(ValueError):
    """A descriptor failure with a stable rule and JSON pointer."""


def fail(rule: str, message: str, pointer: str = "") -> NoReturn:
    location = pointer or "/"
    raise DescriptorError(f"rule={rule} pointer={location}: {message}")


def _duplicates(pairs: list[tuple[str, object]]) -> dict[str, object]:
    value: dict[str, object] = {}
    for key, item in pairs:
        if key in value:
            fail("json-duplicate-key", f"duplicate key {key!r}")
        value[key] = item
    return value


def _reject_number(value: str) -> NoReturn:
    fail("json-number-domain", f"forbidden number {value!r}")


def _check_domain(value: object, pointer: str = "", depth: int = 0) -> None:
    if depth > MAX_DEPTH:
        fail("json-depth", f"nesting exceeds {MAX_DEPTH}", pointer)
    if isinstance(value, str):
        if any(0xD800 <= ord(char) <= 0xDFFF for char in value):
            fail("json-surrogate", "surrogate code point is forbidden", pointer)
    elif isinstance(value, list):
        if len(value) > MAX_ARRAY:
            fail("json-array-size", f"array exceeds {MAX_ARRAY} items", pointer)
        for index, item in enumerate(value):
            _check_domain(item, f"{pointer}/{index}", depth + 1)
    elif isinstance(value, dict):
        for key, item in value.items():
            _check_domain(key, pointer, depth + 1)
            _check_domain(item, f"{pointer}/{key}", depth + 1)


def load_json(path: Path) -> object:
    try:
        raw = path.read_bytes()
    except OSError as exc:
        fail("input", f"cannot read {path}: {exc}")
    if len(raw) > MAX_BYTES:
        fail("input-size", f"{path} exceeds {MAX_BYTES} bytes")
    if raw.startswith(b"\xef\xbb\xbf"):
        fail("json-bom", f"{path} begins with a UTF-8 BOM")
    try:
        text = raw.decode("utf-8", "strict")
    except UnicodeDecodeError as exc:
        fail("json-encoding", f"{path} is not strict UTF-8: {exc}")
    try:
        value = json.loads(
            text,
            object_pairs_hook=_duplicates,
            parse_float=_reject_number,
            parse_constant=_reject_number,
        )
    except json.JSONDecodeError as exc:
        fail("json-parse", f"{path}: {exc.msg} at {exc.lineno}:{exc.colno}")
    _check_domain(value)
    return value


def module_id(value: object, pointer: str) -> str:
    if not isinstance(value, str):
        fail("module-id", "module ID must be a string", pointer)
    if len(value.encode("utf-8")) > 64:
        fail("module-id", "module ID exceeds 64 UTF-8 bytes", pointer)
    if unicodedata.normalize("NFC", value) != value or not ID_RE.fullmatch(value):
        fail("module-id", f"invalid normalized module ID {value!r}", pointer)
    return value


def load_inventory(repo: Path) -> tuple[set[str], set[str]]:
    value = load_json(repo / INVENTORY_PATH)
    if not isinstance(value, dict) or set(value) != {"schema_version", "required", "optional"}:
        fail("inventory-shape", "canonical inventory keys differ from v1")
    if type(value["schema_version"]) is not int or value["schema_version"] != 1:
        fail("inventory-version", "canonical inventory schema_version must be 1")
    groups: list[set[str]] = []
    for label in ("required", "optional"):
        entries = value[label]
        if not isinstance(entries, list) or not entries:
            fail("inventory-shape", f"inventory {label} must be a nonempty array")
        normalized = [module_id(item, f"/{label}/{index}") for index, item in enumerate(entries)]
        if len(normalized) != len(set(normalized)):
            fail("inventory-duplicate", f"inventory {label} contains duplicates")
        groups.append(set(normalized))
    if groups[0] & groups[1]:
        fail("inventory-overlap", "required and optional inventories overlap")
    return groups[0], groups[1]


def schema() -> dict[str, object]:
    module_pattern = ID_RE.pattern
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://aimee.local/schemas/module-descriptor-v1.json",
        "$comment": (
            "Generated by validate_module_descriptors.py; "
            "semantic policy is authoritative there."
        ),
        "type": "object",
        "additionalProperties": False,
        "required": sorted(BASE_KEYS),
        "properties": {
            "descriptor_version": {"const": VERSION},
            "id": {"type": "string", "pattern": module_pattern},
            "dependencies": {
                "type": "array",
                "items": {"type": "string", "pattern": module_pattern},
                "uniqueItems": True,
            },
            "enabled_by_default": {"type": "boolean"},
            "runtime_toggle": {
                "type": "object",
                "additionalProperties": False,
                "required": ["supported"],
                "properties": {"supported": {"type": "boolean"}},
            },
        },
    }


def schema_bytes() -> bytes:
    return (json.dumps(schema(), indent=2, sort_keys=True, ensure_ascii=False) + "\n").encode()


def check_schema(repo: Path) -> None:
    try:
        actual = (repo / SCHEMA_PATH).read_bytes()
    except OSError as exc:
        fail("schema-input", f"cannot read generated schema: {exc}")
    if actual != schema_bytes():
        fail("schema-drift", f"{SCHEMA_PATH} differs from the authoritative model")


def validate_descriptor(value: object, required: set[str], optional: set[str]) -> str:
    if not isinstance(value, dict):
        fail("descriptor-shape", "descriptor must be an object")
    raw_id = value.get("id")
    identifier = module_id(raw_id, "/id")
    if identifier not in required | optional:
        fail("module-unknown", f"unknown module ID {identifier!r}", "/id")
    expected_keys = BASE_KEYS | ({"enabled_by_default"} if identifier in optional else set())
    if set(value) != expected_keys:
        fail(
            "descriptor-keys",
            f"keys mismatch; missing={sorted(expected_keys-set(value))}, "
            f"unknown={sorted(set(value)-expected_keys)}",
        )
    if type(value["descriptor_version"]) is not int or value["descriptor_version"] != VERSION:
        fail(
            "descriptor-version",
            f"descriptor_version must equal {VERSION}",
            "/descriptor_version",
        )
    dependencies = value["dependencies"]
    if not isinstance(dependencies, list):
        fail("dependencies-type", "dependencies must be an array", "/dependencies")
    parsed = [module_id(item, f"/dependencies/{index}") for index, item in enumerate(dependencies)]
    if len(parsed) > MAX_ARRAY:
        fail("dependencies-size", f"dependencies exceeds {MAX_ARRAY} items", "/dependencies")
    for index in range(1, len(parsed)):
        if parsed[index - 1] >= parsed[index]:
            rule = (
                "dependency-duplicate"
                if parsed[index - 1] == parsed[index]
                else "dependency-order"
            )
            fail(rule, "dependencies must be sorted and unique", f"/dependencies/{index}")
    for index, dependency in enumerate(parsed):
        if dependency == identifier:
            fail("dependency-self", "module cannot depend on itself", f"/dependencies/{index}")
        if dependency not in required | optional:
            fail(
                "dependency-unknown",
                f"unknown dependency {dependency!r}",
                f"/dependencies/{index}",
            )
    runtime = value["runtime_toggle"]
    if not isinstance(runtime, dict) or set(runtime) != {"supported"}:
        fail(
            "runtime-toggle-shape",
            "runtime_toggle must contain only supported",
            "/runtime_toggle",
        )
    if type(runtime["supported"]) is not bool:
        fail(
            "runtime-toggle-type",
            "runtime_toggle.supported must be boolean",
            "/runtime_toggle/supported",
        )
    if identifier in required and runtime["supported"]:
        fail(
            "required-runtime-toggle",
            "required modules cannot support runtime disablement",
            "/runtime_toggle/supported",
        )
    if identifier in optional and type(value["enabled_by_default"]) is not bool:
        fail("default-type", "enabled_by_default must be boolean", "/enabled_by_default")
    return identifier


def discover(root: Path) -> list[Path]:
    if not root.is_dir():
        fail("root", f"descriptor root is not a directory: {root}")
    return sorted(root.rglob("module.yaml"))


def _normalized_cycle(cycle: list[str]) -> list[str]:
    open_cycle = cycle[:-1]
    rotations = [open_cycle[index:] + open_cycle[:index] for index in range(len(open_cycle))]
    result = min(rotations)
    return result + [result[0]]


def validate_graph(descriptors: dict[str, tuple[Path, list[str]]],
                   required: set[str], optional: set[str]) -> None:
    for identifier, (path, dependencies) in sorted(descriptors.items()):
        if identifier in required:
            for index, dependency in enumerate(dependencies):
                if dependency in optional:
                    fail("core-to-optional", f"required module {identifier!r} depends on optional "
                         f"module {dependency!r} in {path}", f"/dependencies/{index}")

    state: dict[str, int] = {identifier: 0 for identifier in descriptors}
    stack: list[str] = []

    def visit(identifier: str) -> None:
        state[identifier] = 1
        stack.append(identifier)
        for dependency in descriptors[identifier][1]:
            if dependency not in descriptors:
                continue
            if state[dependency] == 0:
                visit(dependency)
            elif state[dependency] == 1:
                start = stack.index(dependency)
                cycle = _normalized_cycle(stack[start:] + [dependency])
                fail("dependency-cycle", " -> ".join(cycle), "/dependencies")
        stack.pop()
        state[identifier] = 2

    for identifier in sorted(descriptors):
        if state[identifier] == 0:
            visit(identifier)


def validate_roots(repo: Path, roots: list[Path]) -> int:
    required, optional = load_inventory(repo)
    production_root = (repo / "src/modules").resolve()
    unresolved_roots = [root if root.is_absolute() else repo / root for root in roots]
    resolved_roots = [root.resolve() for root in unresolved_roots]
    seen: dict[str, Path] = {}
    graph: dict[str, tuple[Path, list[str]]] = {}
    count = 0
    for root, resolved in zip(roots, resolved_roots, strict=True):
        files = discover(resolved)
        if not files:
            fail("no-descriptors-found", f"no module.yaml files under {root}")
        for path in files:
            value = load_json(path)
            try:
                identifier = validate_descriptor(value, required, optional)
            except DescriptorError as exc:
                raise DescriptorError(f"{path}: {exc}") from exc
            if identifier in seen:
                fail(
                    "module-duplicate",
                    f"module {identifier!r} also declared by {seen[identifier]}",
                )
            seen[identifier] = path
            graph[identifier] = (path, list(value["dependencies"]))
            count += 1
    if resolved_roots == [production_root]:
        expected = required | optional
        actual = set(seen)
        if actual != expected:
            fail("production-coverage", f"missing={sorted(expected-actual)}, "
                 f"extra={sorted(actual-expected)}")
        casefold_paths: dict[str, Path] = {}
        for identifier, path in sorted(seen.items()):
            relative = path.relative_to(production_root)
            expected_relative = Path(identifier) / "module.yaml"
            if relative != expected_relative:
                fail("production-path", f"{path} must be {production_root / expected_relative}")
            folded = relative.as_posix().casefold()
            if folded in casefold_paths and casefold_paths[folded] != path:
                fail("production-case-collision", f"{path} collides with {casefold_paths[folded]}")
            casefold_paths[folded] = path
            value = load_json(path)
            runtime_supported = value["runtime_toggle"]["supported"]
            if identifier in required:
                expected_default = None
                expected_toggle = False
            else:
                expected_default = identifier in DEFAULT_ON
                expected_toggle = identifier in DEFAULT_ON
            if identifier in optional and value["enabled_by_default"] is not expected_default:
                fail("production-default", f"{identifier} enabled_by_default must be "
                     f"{str(expected_default).lower()}", "/enabled_by_default")
            if runtime_supported is not expected_toggle:
                fail("production-runtime-toggle", f"{identifier} runtime_toggle.supported must be "
                     f"{str(expected_toggle).lower()}", "/runtime_toggle/supported")
        validate_graph(graph, required, optional)
    return count


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("roots", nargs="*", type=Path)
    parser.add_argument("--config-root", type=Path)
    parser.add_argument("--check-schema", action="store_true")
    parser.add_argument("--emit-schema", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    if args.emit_schema:
        sys.stdout.buffer.write(schema_bytes())
        return 0
    repo = Path(os.path.realpath(args.config_root or REPO_ROOT))
    try:
        if args.check_schema:
            check_schema(repo)
        if not args.roots:
            fail("root", "at least one descriptor root is required")
        count = validate_roots(repo, args.roots)
    except (DescriptorError, OSError, UnicodeError, ValueError) as exc:
        print(f"validate_module_descriptors: error: {exc}", file=sys.stderr)
        return 1
    print(f"validate_module_descriptors: ok ({count} descriptor(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
