-- DB2 temporal helpers (postgres-native). DB2 stores wall-clock timestamps
-- as TEXT in canonical UTC format 'YYYY-MM-DD HH24:MI:SS'. pg_now_text()
-- returns "now" in that format; the modifier overload returns "now + interval"
-- where the modifier is a postgres interval string ('+7 days', '-30 days',
-- '-1800 seconds', etc.). julianday() / datetime() sqlite-compat shims that
-- previously sat here have been retired — application SQL now emits native
-- pg_now_text() and EXTRACT(EPOCH FROM x::timestamp)/86400.0 directly.
CREATE OR REPLACE FUNCTION pg_now_text() RETURNS TEXT AS $$
  SELECT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');
$$ LANGUAGE SQL STABLE;
CREATE OR REPLACE FUNCTION pg_now_text(modifier TEXT) RETURNS TEXT AS $$
  SELECT to_char((now() AT TIME ZONE 'UTC') + (modifier)::interval,
                 'YYYY-MM-DD HH24:MI:SS');
$$ LANGUAGE SQL STABLE;
CREATE TABLE IF NOT EXISTS rules (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  polarity TEXT NOT NULL,  title TEXT NOT NULL,  description TEXT NOT NULL DEFAULT '',  weight BIGINT NOT NULL DEFAULT 5,  domain TEXT NOT NULL DEFAULT '',  directive_type TEXT NOT NULL DEFAULT 'soft',  expires_at TEXT DEFAULT NULL,  last_reinforced_at TEXT DEFAULT NULL,  created_at TEXT NOT NULL,  updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS projects (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  name TEXT NOT NULL UNIQUE,  root TEXT NOT NULL,  workspace TEXT NOT NULL DEFAULT '',  scanned_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS files (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,  path TEXT NOT NULL,  purpose TEXT NOT NULL DEFAULT '',  hash TEXT NOT NULL DEFAULT '',  scanned_at TEXT NOT NULL,  UNIQUE(project_id, path));
CREATE TABLE IF NOT EXISTS file_exports (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,  name TEXT NOT NULL,  kind TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS file_imports (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,  name TEXT NOT NULL,  kind TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS terms (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,  name TEXT NOT NULL,  kind TEXT NOT NULL DEFAULT '',  line BIGINT NOT NULL DEFAULT 0,  line_end BIGINT NOT NULL DEFAULT 0);
ALTER TABLE terms ADD COLUMN IF NOT EXISTS line_end BIGINT NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS stopwords (  word TEXT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS entity_edges (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  source TEXT NOT NULL,  relation TEXT NOT NULL,  target TEXT NOT NULL,  weight BIGINT NOT NULL DEFAULT 1,  window_id BIGINT, utility_score DOUBLE PRECISION NOT NULL DEFAULT 0.0, valid_from TEXT NOT NULL DEFAULT '', valid_until TEXT NOT NULL DEFAULT '', relation_id BIGINT, subject_kind BIGINT, object_kind BIGINT);
CREATE TABLE IF NOT EXISTS memories (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  tier TEXT NOT NULL DEFAULT 'L0',  kind TEXT NOT NULL DEFAULT 'fact',  key TEXT NOT NULL,  content TEXT NOT NULL DEFAULT '',  confidence DOUBLE PRECISION NOT NULL DEFAULT 1.0,  use_count BIGINT NOT NULL DEFAULT 0,  last_used_at TEXT,  source_session TEXT,  valid_from TEXT,  valid_until TEXT,  artifact_type TEXT,  artifact_ref TEXT,  artifact_hash TEXT,  effectiveness DOUBLE PRECISION DEFAULT NULL,  sensitivity TEXT NOT NULL DEFAULT 'normal',  evidence_strength DOUBLE PRECISION NOT NULL DEFAULT 0.5,  observation_count BIGINT NOT NULL DEFAULT 1,  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),  updated_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')), salience DOUBLE PRECISION NOT NULL DEFAULT 0.5, surprise DOUBLE PRECISION NOT NULL DEFAULT 0.5, contradiction_group TEXT NOT NULL DEFAULT '', merged_into BIGINT NOT NULL DEFAULT 0, negation_tokens TEXT NOT NULL DEFAULT '', lifecycle_state TEXT NOT NULL DEFAULT 'active', archive_reason TEXT NOT NULL DEFAULT '', ttl_at TEXT NOT NULL DEFAULT '', cognified_memory_kind TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS memory_provenance (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  memory_id BIGINT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,  session_id TEXT NOT NULL,  action TEXT NOT NULL,  details TEXT,  created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS memory_conflicts (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  memory_a BIGINT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,  memory_b BIGINT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,  detected_at TEXT NOT NULL,  resolved BIGINT NOT NULL DEFAULT 0,  resolution TEXT);
CREATE TABLE IF NOT EXISTS tasks (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  parent_id BIGINT DEFAULT 0,  title TEXT NOT NULL,  state TEXT NOT NULL DEFAULT 'todo',  confidence DOUBLE PRECISION NOT NULL DEFAULT 1.0,  session_id TEXT,  success_criteria TEXT DEFAULT '',  description TEXT DEFAULT '',  acceptance_json TEXT DEFAULT '',  assignee TEXT DEFAULT '',  estimate_minutes BIGINT DEFAULT 0,  created_at TEXT NOT NULL,  updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS task_edges (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  source_id BIGINT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,  target_id BIGINT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,  relation TEXT NOT NULL DEFAULT 'depends_on');
CREATE TABLE IF NOT EXISTS decision_log (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  task_id BIGINT DEFAULT 0,  options TEXT NOT NULL,  chosen TEXT NOT NULL,  rationale TEXT NOT NULL DEFAULT '',  assumptions TEXT NOT NULL DEFAULT '',  outcome TEXT,  created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS anti_patterns (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  pattern TEXT NOT NULL,  description TEXT NOT NULL DEFAULT '',  source TEXT NOT NULL DEFAULT '',  source_ref TEXT NOT NULL DEFAULT '',  hit_count BIGINT NOT NULL DEFAULT 0,  confidence DOUBLE PRECISION NOT NULL DEFAULT 1.0);
-- workflow_patterns: durable store for promoted `workflow` learning candidates
-- (the cross-source-learning-pipeline promotion target surface). Written by
-- learning_promote; read by future workflow-suggestion consumers.
CREATE TABLE IF NOT EXISTS workflow_patterns (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  pattern TEXT NOT NULL,  description TEXT NOT NULL DEFAULT '',  source TEXT NOT NULL DEFAULT '',  source_ref TEXT NOT NULL DEFAULT '',  confidence DOUBLE PRECISION NOT NULL DEFAULT 1.0,  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE TABLE IF NOT EXISTS tool_registry (  name TEXT PRIMARY KEY,  description TEXT NOT NULL,  input_schema TEXT NOT NULL,  output_schema TEXT DEFAULT '',  side_effect TEXT NOT NULL DEFAULT 'read',  idempotent BIGINT NOT NULL DEFAULT 0,  enabled BIGINT NOT NULL DEFAULT 1,  tool_prompt TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS memory_health (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  cycle_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),  total_memories BIGINT NOT NULL DEFAULT 0,  contradictions_detected BIGINT NOT NULL DEFAULT 0,  promotions BIGINT NOT NULL DEFAULT 0,  demotions BIGINT NOT NULL DEFAULT 0,  expirations BIGINT NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS contradiction_log (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  detected_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),  memory_a_id BIGINT REFERENCES memories(id) ON DELETE CASCADE,  memory_b_id BIGINT REFERENCES memories(id) ON DELETE CASCADE,  resolution TEXT NOT NULL DEFAULT 'pending',  details TEXT DEFAULT NULL);
CREATE TABLE IF NOT EXISTS memory_workspaces (  memory_id BIGINT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,  workspace TEXT NOT NULL,  PRIMARY KEY(memory_id, workspace));
CREATE TABLE IF NOT EXISTS kind_lifecycle (  kind TEXT PRIMARY KEY,  promote_use_count BIGINT NOT NULL,  promote_confidence DOUBLE PRECISION NOT NULL,  demote_days BIGINT NOT NULL,  demote_confidence DOUBLE PRECISION NOT NULL,  expire_days BIGINT NOT NULL,  demotion_resistance DOUBLE PRECISION NOT NULL);
-- Keep agent_outcomes aligned with what agent_runtime.c:record_outcome writes.
-- Drop and recreate because older greenfield snapshots had a mismatched shape.
DROP TABLE IF EXISTS agent_outcomes;
CREATE TABLE IF NOT EXISTS agent_outcomes (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  agent_name TEXT NOT NULL DEFAULT '',  role TEXT NOT NULL DEFAULT '',  outcome TEXT NOT NULL,  reason TEXT DEFAULT '',  turns_used BIGINT NOT NULL DEFAULT 0,  tools_called BIGINT NOT NULL DEFAULT 0,  tokens_used BIGINT NOT NULL DEFAULT 0,  tool_error_pattern TEXT DEFAULT '',  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE TABLE IF NOT EXISTS memory_links (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  source_id BIGINT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,  target_id BIGINT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,  relation TEXT NOT NULL DEFAULT 'related',  weight DOUBLE PRECISION NOT NULL DEFAULT 1.0,  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE TABLE IF NOT EXISTS trace_mining_log (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  last_trace_id BIGINT NOT NULL DEFAULT 0,  mined_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE TABLE IF NOT EXISTS mining_jobs (  id TEXT PRIMARY KEY,  last_run_at TEXT,  hwm BIGINT NOT NULL DEFAULT 0,  interval_s INTEGER NOT NULL DEFAULT 300,  enabled BOOLEAN NOT NULL DEFAULT TRUE,  last_error TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS interaction_event_embeddings (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  source_event_id BIGINT NOT NULL UNIQUE,  session_id TEXT NOT NULL DEFAULT '',  event_type TEXT NOT NULL,  role TEXT NOT NULL DEFAULT '',  failure_mode TEXT NOT NULL DEFAULT '',  payload_json JSONB NOT NULL DEFAULT '{}',  embedding TEXT NOT NULL DEFAULT '[]',  cluster_key TEXT NOT NULL DEFAULT '',  created_at TEXT NOT NULL DEFAULT (pg_now_text()));
CREATE INDEX IF NOT EXISTS idx_interaction_event_embeddings_type_id ON interaction_event_embeddings (event_type, source_event_id);
CREATE INDEX IF NOT EXISTS idx_interaction_event_embeddings_failure ON interaction_event_embeddings (role, failure_mode);
CREATE TABLE IF NOT EXISTS code_calls (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,  caller TEXT NOT NULL DEFAULT '',  callee TEXT NOT NULL DEFAULT '',  line BIGINT NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS file_contents (  file_id BIGINT PRIMARY KEY REFERENCES files(id) ON DELETE CASCADE,  content TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS kb_runtime_state (  state_key TEXT PRIMARY KEY,  state_value TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS notes (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  title TEXT NOT NULL,  slug TEXT NOT NULL UNIQUE,  content TEXT NOT NULL,  tags TEXT NOT NULL DEFAULT '',  author TEXT NOT NULL DEFAULT '',  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),  updated_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE TABLE IF NOT EXISTS agent_hints (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  role TEXT NOT NULL,  pattern TEXT NOT NULL,  hint TEXT NOT NULL,  consumed BIGINT NOT NULL DEFAULT 0,  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE TABLE IF NOT EXISTS collab_rules (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  text TEXT NOT NULL,  reason TEXT NOT NULL DEFAULT '',  proposed_by TEXT NOT NULL DEFAULT '',  status TEXT NOT NULL DEFAULT 'proposed',  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),  decided_at TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS collab_rules_meta (  key TEXT PRIMARY KEY,  value TEXT NOT NULL DEFAULT '');
-- kb_documents: canonical chunk rows. Embedding bytes are NOT stored here.
-- Vectors live in the pgvector extension tables (joined by document id).
-- chunk_strategy records which chunking policy produced this row.
-- chunk_context is a derived retrieval-aid field; it does not replace content.
CREATE TABLE IF NOT EXISTS kb_documents (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  project TEXT NOT NULL,  file_path TEXT NOT NULL,  file_hash TEXT NOT NULL,  chunk_index BIGINT NOT NULL,  heading_path TEXT NOT NULL DEFAULT '',  line_start BIGINT NOT NULL DEFAULT 0,  line_end BIGINT NOT NULL DEFAULT 0,  content TEXT NOT NULL,  token_count BIGINT NOT NULL DEFAULT 0,  updated_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')), prev_chunk_id BIGINT DEFAULT NULL, next_chunk_id BIGINT DEFAULT NULL);
CREATE TABLE IF NOT EXISTS kb_async_jobs (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  kind TEXT NOT NULL DEFAULT 'embed_raw',  document_id BIGINT NOT NULL REFERENCES kb_documents(id) ON DELETE CASCADE,  project TEXT NOT NULL DEFAULT '',  status TEXT NOT NULL DEFAULT 'pending',  attempts BIGINT NOT NULL DEFAULT 0,  last_error TEXT NOT NULL DEFAULT '',  claimed_by TEXT NOT NULL DEFAULT '',  claimed_at TEXT NOT NULL DEFAULT '',  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),  updated_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),  UNIQUE(kind, document_id));
CREATE TABLE IF NOT EXISTS memory_aliases (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  memory_id BIGINT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,  alias TEXT NOT NULL,  weight DOUBLE PRECISION NOT NULL DEFAULT 1.0,  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),  UNIQUE(memory_id, alias));
CREATE TABLE IF NOT EXISTS memory_entities (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  memory_id BIGINT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,  entity TEXT NOT NULL,  role TEXT NOT NULL DEFAULT 'mention',  weight DOUBLE PRECISION NOT NULL DEFAULT 1.0,  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),  UNIQUE(memory_id, entity, role));
CREATE TABLE IF NOT EXISTS memory_temporal_refs (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  memory_id BIGINT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,  ref_key TEXT NOT NULL,  granularity TEXT NOT NULL DEFAULT 'relative',  weight DOUBLE PRECISION NOT NULL DEFAULT 1.0,  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),  UNIQUE(memory_id, ref_key, granularity));
CREATE TABLE IF NOT EXISTS memory_event_frames (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  memory_id BIGINT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,  actor TEXT NOT NULL DEFAULT '',  action TEXT NOT NULL DEFAULT '',  object TEXT NOT NULL DEFAULT '',  location TEXT NOT NULL DEFAULT '',  event_time TEXT NOT NULL DEFAULT '',  evidence_kind TEXT NOT NULL DEFAULT 'derived',  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE TABLE IF NOT EXISTS memory_summaries (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  memory_id BIGINT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,  scope TEXT NOT NULL DEFAULT 'headline',  summary TEXT NOT NULL,  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),  UNIQUE(memory_id, scope));
CREATE TABLE IF NOT EXISTS memory_chunks (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  memory_id BIGINT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,  chunk_index BIGINT NOT NULL DEFAULT 0,  chunk_text TEXT NOT NULL,  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),  UNIQUE(memory_id, chunk_index));
CREATE TABLE IF NOT EXISTS memory_units (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  memory_id BIGINT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,  unit_type TEXT NOT NULL,  unit_key TEXT NOT NULL DEFAULT '',  unit_text TEXT NOT NULL,  weight DOUBLE PRECISION NOT NULL DEFAULT 1.0,  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')), memory_kind TEXT NOT NULL DEFAULT 'episodic', is_episode_card BIGINT NOT NULL DEFAULT 0,  UNIQUE(memory_id, unit_type, unit_key, unit_text));
CREATE TABLE IF NOT EXISTS memory_unit_edges (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  src_unit_id BIGINT NOT NULL REFERENCES memory_units(id) ON DELETE CASCADE,  dst_unit_id BIGINT NOT NULL REFERENCES memory_units(id) ON DELETE CASCADE,  edge_type TEXT NOT NULL DEFAULT 'related',  weight DOUBLE PRECISION NOT NULL DEFAULT 1.0);
CREATE TABLE IF NOT EXISTS memory_episodes (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  memory_id BIGINT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,  episode_key TEXT NOT NULL,  episode_text TEXT NOT NULL,  source_session TEXT NOT NULL DEFAULT '',  reference_time TEXT NOT NULL DEFAULT '',  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE TABLE IF NOT EXISTS memory_relations (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  memory_id BIGINT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,  episode_id BIGINT DEFAULT 0,  src_entity TEXT NOT NULL DEFAULT '',  relation TEXT NOT NULL DEFAULT '',  dst_entity TEXT NOT NULL DEFAULT '',  fact_text TEXT NOT NULL DEFAULT '',  valid_at TEXT NOT NULL DEFAULT '',  invalid_at TEXT NOT NULL DEFAULT '',  weight DOUBLE PRECISION NOT NULL DEFAULT 1.0,  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE TABLE IF NOT EXISTS memory_scopes (  memory_id BIGINT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,  scope_type TEXT NOT NULL,  scope_value TEXT NOT NULL,  PRIMARY KEY(memory_id, scope_type, scope_value));
CREATE TABLE IF NOT EXISTS entity_profiles (  entity_id TEXT NOT NULL PRIMARY KEY,  canonical_name TEXT NOT NULL,  observation_count BIGINT NOT NULL DEFAULT 0,  card_json TEXT NOT NULL DEFAULT '{}',  last_refreshed TEXT NOT NULL,  created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS memory_lineage (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  object_type TEXT NOT NULL,  object_id BIGINT NOT NULL,  source_kind TEXT NOT NULL,  source_ref TEXT NOT NULL DEFAULT '',  ingested_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),  confidence DOUBLE PRECISION NOT NULL DEFAULT 1.0);
CREATE TABLE IF NOT EXISTS memory_scenes (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  workspace_id TEXT NOT NULL DEFAULT '',  turn_count BIGINT NOT NULL DEFAULT 0,  noise_ratio DOUBLE PRECISION NOT NULL DEFAULT 0.0,  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),  updated_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE TABLE IF NOT EXISTS memory_scene_members (  scene_id BIGINT NOT NULL REFERENCES memory_scenes(id) ON DELETE CASCADE,  memory_id BIGINT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,  membership_strength DOUBLE PRECISION NOT NULL DEFAULT 1.0,  PRIMARY KEY(scene_id, memory_id));
CREATE TABLE IF NOT EXISTS memory_relation_schema (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  relation_id BIGINT NOT NULL,  subject_kind BIGINT NOT NULL DEFAULT 99,  object_kind  BIGINT NOT NULL DEFAULT 99);
CREATE TABLE IF NOT EXISTS memory_active_embedder (  id         BIGINT PRIMARY KEY CHECK (id = 1),  version    TEXT NOT NULL DEFAULT '',  updated_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE TABLE IF NOT EXISTS memory_reembed_progress (  id             BIGINT PRIMARY KEY CHECK (id = 1),  target_version TEXT    NOT NULL DEFAULT '',  last_id        BIGINT NOT NULL DEFAULT 0,  total          BIGINT NOT NULL DEFAULT 0,  done           BIGINT NOT NULL DEFAULT 0,  started_at     TEXT    NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),  finished_at    TEXT    DEFAULT NULL);
CREATE TABLE IF NOT EXISTS memory_coref_audit (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  memory_id BIGINT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,  session_id TEXT NOT NULL DEFAULT '',  outcome TEXT NOT NULL DEFAULT 'none',  entity TEXT NOT NULL DEFAULT '',  mode TEXT NOT NULL DEFAULT '',  confidence DOUBLE PRECISION NOT NULL DEFAULT 0.0,  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE TABLE IF NOT EXISTS curator_invalidation_events (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  source_kind TEXT NOT NULL DEFAULT '',  source_id TEXT NOT NULL DEFAULT '',  artifacts_stale INTEGER NOT NULL DEFAULT 0,  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE TABLE IF NOT EXISTS code_index_ops (  point_id BIGINT PRIMARY KEY,  project TEXT NOT NULL DEFAULT '',  node_key TEXT NOT NULL DEFAULT '',  file_path TEXT NOT NULL DEFAULT '',  status TEXT NOT NULL DEFAULT 'pending',  attempts BIGINT NOT NULL DEFAULT 0,  last_error TEXT NOT NULL DEFAULT '',  indexed_at TEXT,  updated_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE TABLE IF NOT EXISTS vector_index_ops (  point_id   BIGINT PRIMARY KEY,  collection TEXT    NOT NULL DEFAULT 'memory_units',  memory_id  BIGINT REFERENCES memories(id) ON DELETE CASCADE,  status     TEXT    NOT NULL DEFAULT 'pending',  attempts   BIGINT NOT NULL DEFAULT 0,  last_error TEXT    NOT NULL DEFAULT '',  indexed_at TEXT,  updated_at TEXT    NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE TABLE IF NOT EXISTS memory_promotion_approvals (  memory_id    BIGINT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,  target_tier  TEXT    NOT NULL,  approver     TEXT    NOT NULL DEFAULT 'operator',  note         TEXT    NOT NULL DEFAULT '',  approved_at  TEXT    NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),  PRIMARY KEY (memory_id, target_tier));
CREATE TABLE IF NOT EXISTS prospective_memories (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  trigger_text TEXT NOT NULL,  action_text TEXT NOT NULL,  anchor_entity TEXT NOT NULL DEFAULT '',  anchor_file TEXT NOT NULL DEFAULT '',  recurrence TEXT NOT NULL DEFAULT 'once',  state TEXT NOT NULL DEFAULT 'armed',  valid_until TEXT NOT NULL DEFAULT '',  source_session TEXT NOT NULL DEFAULT '',  trigger_count BIGINT NOT NULL DEFAULT 0,  last_triggered_at TEXT NOT NULL DEFAULT '',  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),  updated_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE TABLE IF NOT EXISTS epistemic_directives (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  question TEXT NOT NULL,  topic TEXT NOT NULL DEFAULT '',  anchor_entity TEXT NOT NULL DEFAULT '',  anchor_file TEXT NOT NULL DEFAULT '',  cause TEXT NOT NULL,  priority BIGINT NOT NULL DEFAULT 50,  state TEXT NOT NULL DEFAULT 'open',  memory_a_id BIGINT NOT NULL DEFAULT 0,  memory_b_id BIGINT NOT NULL DEFAULT 0,  resolution_memory_id BIGINT NOT NULL DEFAULT 0,  evidence TEXT NOT NULL DEFAULT '',  source_session TEXT NOT NULL DEFAULT '',  surfaced_count BIGINT NOT NULL DEFAULT 0,  last_surfaced_at TEXT NOT NULL DEFAULT '',  resolved_at TEXT NOT NULL DEFAULT '',  valid_until TEXT NOT NULL DEFAULT '',  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),  updated_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE TABLE IF NOT EXISTS failed_queries (  query_norm TEXT PRIMARY KEY,  failure_count BIGINT NOT NULL DEFAULT 0,  last_failed_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE TABLE IF NOT EXISTS working_profile_state (  field TEXT PRIMARY KEY,  value TEXT NOT NULL DEFAULT '',  sample_count BIGINT NOT NULL DEFAULT 0,  confidence DOUBLE PRECISION NOT NULL DEFAULT 0.0,  updated_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE TABLE IF NOT EXISTS working_profile_observations (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  field TEXT NOT NULL,  value TEXT NOT NULL,  confidence DOUBLE PRECISION NOT NULL DEFAULT 0.5,  source_session TEXT NOT NULL DEFAULT '',  observed_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE TABLE IF NOT EXISTS curiosity_items (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  gap_type TEXT NOT NULL,  target_entity TEXT NOT NULL DEFAULT '',  target_topic TEXT NOT NULL DEFAULT '',  evidence TEXT NOT NULL DEFAULT '',  importance DOUBLE PRECISION NOT NULL DEFAULT 0.0,  novelty DOUBLE PRECISION NOT NULL DEFAULT 0.0,  progress DOUBLE PRECISION NOT NULL DEFAULT 0.0,  routing_score DOUBLE PRECISION NOT NULL DEFAULT 0.0,  state TEXT NOT NULL DEFAULT 'open',  source_session TEXT NOT NULL DEFAULT '',  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),  updated_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE TABLE IF NOT EXISTS learning_signals (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  signal_type TEXT NOT NULL,  source TEXT NOT NULL DEFAULT 'explicit',  polarity TEXT NOT NULL DEFAULT '',  title TEXT NOT NULL DEFAULT '',  description TEXT NOT NULL DEFAULT '',  target_key TEXT NOT NULL DEFAULT '',  target_memory_id BIGINT NOT NULL DEFAULT 0,  correction_text TEXT NOT NULL DEFAULT '',  workflow_project TEXT NOT NULL DEFAULT '',  workflow_signal_type TEXT NOT NULL DEFAULT '',  evidence_refs TEXT NOT NULL DEFAULT '[]',  source_session TEXT NOT NULL DEFAULT '',  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE TABLE IF NOT EXISTS learning_proposals (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  signal_id BIGINT NOT NULL REFERENCES learning_signals(id) ON DELETE CASCADE,  sink TEXT NOT NULL,  state TEXT NOT NULL DEFAULT 'pending',  target_key TEXT NOT NULL DEFAULT '',  target_memory_id BIGINT NOT NULL DEFAULT 0,  action_json TEXT NOT NULL DEFAULT '{}',  evidence_refs TEXT NOT NULL DEFAULT '[]',  corroboration_count BIGINT NOT NULL DEFAULT 1,  expires_at TEXT NOT NULL DEFAULT '',  committed_at TEXT NOT NULL DEFAULT '',  archive_reason TEXT NOT NULL DEFAULT '',  created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),  updated_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE INDEX IF NOT EXISTS idx_kb_async_jobs_status ON kb_async_jobs(status, id);
CREATE TABLE IF NOT EXISTS kb_ingest_queue (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  project TEXT NOT NULL,  root_path TEXT NOT NULL,  workspace TEXT NOT NULL DEFAULT '',  status TEXT NOT NULL DEFAULT 'pending',  force INTEGER NOT NULL DEFAULT 0,  queued_at TEXT NOT NULL DEFAULT (pg_now_text()),  started_at TEXT DEFAULT NULL,  completed_at TEXT DEFAULT NULL,  files_indexed INTEGER NOT NULL DEFAULT 0,  chunks_added INTEGER NOT NULL DEFAULT 0,  embeddings_added INTEGER NOT NULL DEFAULT 0,  error_message TEXT DEFAULT NULL);
CREATE INDEX IF NOT EXISTS idx_kb_ingest_queue_status ON kb_ingest_queue(status);
CREATE UNIQUE INDEX IF NOT EXISTS idx_kb_ingest_queue_dedup ON kb_ingest_queue(project) WHERE status IN ('pending', 'running');
CREATE TABLE IF NOT EXISTS kb_file_index (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  project TEXT NOT NULL,  file_path TEXT NOT NULL,  file_hash TEXT NOT NULL,  ingested_at TEXT NOT NULL DEFAULT (pg_now_text()),  content TEXT DEFAULT NULL,  UNIQUE(project, file_path));
CREATE INDEX IF NOT EXISTS idx_kb_file_index_project ON kb_file_index(project);
CREATE INDEX IF NOT EXISTS idx_files_path ON files(path);
CREATE INDEX IF NOT EXISTS idx_terms_name ON terms(name);
CREATE INDEX IF NOT EXISTS idx_fi_name ON file_imports(name);
CREATE INDEX IF NOT EXISTS idx_fe_name ON file_exports(name);
CREATE INDEX IF NOT EXISTS idx_file_exports_file_id ON file_exports(file_id);
CREATE INDEX IF NOT EXISTS idx_file_imports_file_id ON file_imports(file_id);
CREATE INDEX IF NOT EXISTS idx_terms_file_id ON terms(file_id);
CREATE INDEX IF NOT EXISTS idx_code_calls_file_id ON code_calls(file_id);
CREATE INDEX IF NOT EXISTS idx_code_calls_callee ON code_calls(callee);
CREATE INDEX IF NOT EXISTS idx_ee_source ON entity_edges(source);
CREATE INDEX IF NOT EXISTS idx_ee_target ON entity_edges(target);
CREATE INDEX IF NOT EXISTS idx_mem_tier ON memories(tier);
CREATE INDEX IF NOT EXISTS idx_mem_kind ON memories(kind);
CREATE INDEX IF NOT EXISTS idx_mem_key ON memories(key);
CREATE INDEX IF NOT EXISTS idx_memories_sensitivity ON memories(sensitivity);
CREATE INDEX IF NOT EXISTS idx_mp_mem ON memory_provenance(memory_id);
CREATE INDEX IF NOT EXISTS idx_mc_unresolved ON memory_conflicts(resolved) WHERE resolved = 0;
CREATE INDEX IF NOT EXISTS idx_tasks_state ON tasks(state);
CREATE INDEX IF NOT EXISTS idx_tasks_parent ON tasks(parent_id);
CREATE INDEX IF NOT EXISTS idx_te_source ON task_edges(source_id);
CREATE INDEX IF NOT EXISTS idx_te_target ON task_edges(target_id);
CREATE INDEX IF NOT EXISTS idx_dl_task ON decision_log(task_id);
CREATE INDEX IF NOT EXISTS idx_agent_hints_lookup ON agent_hints(role, consumed);
CREATE INDEX IF NOT EXISTS idx_memory_workspaces_workspace ON memory_workspaces(workspace);
CREATE INDEX IF NOT EXISTS idx_memory_aliases_memory ON memory_aliases(memory_id);
CREATE INDEX IF NOT EXISTS idx_memory_aliases_alias ON memory_aliases(alias);
CREATE INDEX IF NOT EXISTS idx_memory_entities_entity ON memory_entities(entity);
CREATE INDEX IF NOT EXISTS idx_memory_entities_memory ON memory_entities(memory_id);
CREATE INDEX IF NOT EXISTS idx_memory_temporal_refs_ref ON memory_temporal_refs(ref_key);
CREATE INDEX IF NOT EXISTS idx_memory_temporal_refs_memory ON memory_temporal_refs(memory_id);
CREATE INDEX IF NOT EXISTS idx_memory_event_frames_actor ON memory_event_frames(actor);
CREATE INDEX IF NOT EXISTS idx_memory_event_frames_action ON memory_event_frames(action);
CREATE INDEX IF NOT EXISTS idx_memory_event_frames_event_time ON memory_event_frames(event_time);
CREATE INDEX IF NOT EXISTS idx_memory_event_frames_memory ON memory_event_frames(memory_id);
CREATE INDEX IF NOT EXISTS idx_memory_summaries_scope ON memory_summaries(scope);
CREATE INDEX IF NOT EXISTS idx_memory_chunks_memory ON memory_chunks(memory_id);
CREATE INDEX IF NOT EXISTS idx_memory_units_memory ON memory_units(memory_id);
CREATE INDEX IF NOT EXISTS idx_memory_units_type ON memory_units(unit_type);
CREATE INDEX IF NOT EXISTS idx_memory_units_key ON memory_units(unit_key);
CREATE INDEX IF NOT EXISTS idx_memory_unit_edges_src ON memory_unit_edges(src_unit_id);
CREATE INDEX IF NOT EXISTS idx_memory_unit_edges_dst ON memory_unit_edges(dst_unit_id);
CREATE INDEX IF NOT EXISTS idx_memory_unit_edges_type ON memory_unit_edges(edge_type);
CREATE INDEX IF NOT EXISTS idx_kb_documents_project ON kb_documents(project, file_path);
CREATE INDEX IF NOT EXISTS idx_memory_units_kind ON memory_units(memory_kind);
CREATE INDEX IF NOT EXISTS idx_memory_units_kind_key ON memory_units(memory_kind, unit_key);
CREATE INDEX IF NOT EXISTS idx_entity_profiles_refreshed  ON entity_profiles(last_refreshed);
CREATE INDEX IF NOT EXISTS idx_kb_docs_prev  ON kb_documents(prev_chunk_id) WHERE prev_chunk_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_kb_docs_next  ON kb_documents(next_chunk_id) WHERE next_chunk_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ml_object ON memory_lineage(object_type, object_id);
CREATE INDEX IF NOT EXISTS idx_msm_memory ON memory_scene_members(memory_id);
CREATE INDEX IF NOT EXISTS idx_mrs_rel ON memory_relation_schema(relation_id);
CREATE INDEX IF NOT EXISTS idx_mca_memory ON memory_coref_audit(memory_id);
CREATE INDEX IF NOT EXISTS idx_mca_session ON memory_coref_audit(session_id);
CREATE INDEX IF NOT EXISTS idx_vio_status    ON vector_index_ops(status);
CREATE INDEX IF NOT EXISTS idx_vio_memory_id ON vector_index_ops(memory_id);
CREATE INDEX IF NOT EXISTS idx_mpa_target ON memory_promotion_approvals(target_tier);
CREATE INDEX IF NOT EXISTS idx_prospective_state ON prospective_memories(state);
CREATE INDEX IF NOT EXISTS idx_prospective_state_valid  ON prospective_memories(state, valid_until);
CREATE INDEX IF NOT EXISTS idx_prospective_anchor_entity  ON prospective_memories(anchor_entity) WHERE anchor_entity != '';
CREATE INDEX IF NOT EXISTS idx_prospective_anchor_file  ON prospective_memories(anchor_file) WHERE anchor_file != '';
CREATE INDEX IF NOT EXISTS idx_memories_lifecycle_ttl  ON memories(lifecycle_state, ttl_at);
CREATE INDEX IF NOT EXISTS idx_memories_lifecycle  ON memories(lifecycle_state);
CREATE INDEX IF NOT EXISTS idx_directives_state  ON epistemic_directives(state);
CREATE INDEX IF NOT EXISTS idx_directives_state_priority  ON epistemic_directives(state, priority DESC);
CREATE INDEX IF NOT EXISTS idx_directives_anchor_entity  ON epistemic_directives(anchor_entity) WHERE anchor_entity != '';
CREATE INDEX IF NOT EXISTS idx_directives_anchor_file  ON epistemic_directives(anchor_file) WHERE anchor_file != '';
CREATE INDEX IF NOT EXISTS idx_directives_cause  ON epistemic_directives(cause);
CREATE UNIQUE INDEX IF NOT EXISTS idx_directives_dedup_contradiction  ON epistemic_directives(memory_a_id, memory_b_id)  WHERE cause = 'contradiction' AND memory_a_id != 0 AND memory_b_id != 0;
CREATE UNIQUE INDEX IF NOT EXISTS idx_directives_dedup_topic  ON epistemic_directives(cause, topic)  WHERE topic != '' AND cause IN ('retrieval_failure', 'missing_config');
CREATE INDEX IF NOT EXISTS idx_memories_cognified_kind  ON memories(cognified_memory_kind) WHERE cognified_memory_kind != '';
CREATE INDEX IF NOT EXISTS idx_working_profile_obs_field  ON working_profile_observations(field);
CREATE INDEX IF NOT EXISTS idx_working_profile_obs_field_value  ON working_profile_observations(field, value);
CREATE INDEX IF NOT EXISTS idx_curiosity_state  ON curiosity_items(state);
CREATE INDEX IF NOT EXISTS idx_curiosity_gap_type  ON curiosity_items(gap_type);
CREATE INDEX IF NOT EXISTS idx_curiosity_target  ON curiosity_items(target_entity, target_topic)  WHERE target_entity != '' OR target_topic != '';
CREATE UNIQUE INDEX IF NOT EXISTS idx_curiosity_dedup_missing_fact  ON curiosity_items(gap_type, target_topic)  WHERE gap_type = 'missing_fact' AND target_topic != '' AND state = 'open';
CREATE INDEX IF NOT EXISTS idx_learning_signals_type  ON learning_signals(signal_type, created_at);
CREATE INDEX IF NOT EXISTS idx_learning_proposals_state  ON learning_proposals(state, sink, created_at);
CREATE INDEX IF NOT EXISTS idx_learning_proposals_target  ON learning_proposals(sink, target_key, target_memory_id)  WHERE state = 'pending';
INSERT INTO tool_registry VALUES('bash','Run a shell command and capture stdout/stderr.','{"type":"object","properties":{"command":{"type":"string"},    "timeout_ms":{"type":"integer"}},"required":["command"]}','','write',0,1,'') ON CONFLICT DO NOTHING;
INSERT INTO tool_registry VALUES('read_file','Read a file from disk.','{"type":"object","properties":{"path":{"type":"string"},    "offset":{"type":"integer"},"limit":{"type":"integer"}},    "required":["path"]}','','read',1,1,'') ON CONFLICT DO NOTHING;
INSERT INTO tool_registry VALUES('write_file','Write a file to disk.','{"type":"object","properties":{"path":{"type":"string"},    "content":{"type":"string"}},"required":["path","content"]}','','write',0,1,'') ON CONFLICT DO NOTHING;
INSERT INTO tool_registry VALUES('list_files','List files in a directory.','{"type":"object","properties":{"path":{"type":"string"},    "pattern":{"type":"string"}},"required":["path"]}','','read',1,1,'') ON CONFLICT DO NOTHING;
INSERT INTO tool_registry VALUES('verify','Verify an expected condition.','{"type":"object","properties":{"check_type":{"type":"string"},    "target":{"type":"string"},"expected":{"type":"string"}},    "required":["check_type","target"]}','','read',1,1,'') ON CONFLICT DO NOTHING;
INSERT INTO tool_registry VALUES('git_log','Show recent git commits.','{"type":"object","properties":{"path":{"type":"string"},    "count":{"type":"integer"}},"required":["path"]}','','read',1,1,'') ON CONFLICT DO NOTHING;
INSERT INTO tool_registry VALUES('grep','Search files with a regex pattern.','{"type":"object","properties":{"path":{"type":"string"},    "pattern":{"type":"string"},"max_results":{"type":"integer"}},    "required":["path","pattern"]}','','read',1,1,'') ON CONFLICT DO NOTHING;
INSERT INTO tool_registry VALUES('git_diff','Show git diff output.','{"type":"object","properties":{"path":{"type":"string"},    "ref":{"type":"string"}},"required":["path"]}','','read',1,1,'') ON CONFLICT DO NOTHING;
INSERT INTO tool_registry VALUES('git_status','Show git working tree status.','{"type":"object","properties":{"path":{"type":"string"}},    "required":["path"]}','','read',1,1,'') ON CONFLICT DO NOTHING;
INSERT INTO tool_registry VALUES('env_get','Read a specific environment variable.','{"type":"object","properties":{"name":{"type":"string"}},    "required":["name"]}','','read',1,1,'') ON CONFLICT DO NOTHING;
INSERT INTO tool_registry VALUES('test','Check file properties.','{"type":"object","properties":{"path":{"type":"string"},    "check":{"type":"string"}},"required":["path"]}','','read',1,1,'') ON CONFLICT DO NOTHING;
INSERT INTO tool_registry VALUES('request_input','Request human input during delegated execution.','{"type":"object","properties":{"question":{"type":"string"}},    "required":["question"]}','','write',0,1,'') ON CONFLICT DO NOTHING;
INSERT INTO tool_registry VALUES('code_search','Search indexed code semantically or by symbol.','{"type":"object","properties":{"query":{"type":"string"},    "project":{"type":"string"},"max_results":{"type":"integer"}},    "required":["query"]}','','read',1,1,'') ON CONFLICT DO NOTHING;
INSERT INTO tool_registry VALUES('find_symbol','Look up the exact definition location of a C symbol, function, type, or macro in the indexed codebase.','{"type":"object","properties":{"identifier":{"type":"string"}},    "required":["identifier"]}','','read',1,1,'') ON CONFLICT DO NOTHING;
INSERT INTO tool_registry VALUES('search_memory','Search aimee knowledge base for stored facts, prior decisions, and project context.','{"type":"object","properties":{"query":{"type":"string"}},    "required":["query"]}','','read',1,1,'') ON CONFLICT DO NOTHING;
INSERT INTO kind_lifecycle VALUES('fact',3,0.900000000000000022,60,0.699999999999999955,30,1.0) ON CONFLICT DO NOTHING;
INSERT INTO kind_lifecycle VALUES('preference',2,0.800000000000000044,90,0.599999999999999977,30,1.5) ON CONFLICT DO NOTHING;
INSERT INTO kind_lifecycle VALUES('decision',3,0.900000000000000022,90,0.699999999999999955,45,1.5) ON CONFLICT DO NOTHING;
INSERT INTO kind_lifecycle VALUES('episode',5,0.900000000000000022,30,0.699999999999999955,14,0.5) ON CONFLICT DO NOTHING;
INSERT INTO kind_lifecycle VALUES('task',3,0.900000000000000022,14,0.699999999999999955,7,0.5) ON CONFLICT DO NOTHING;
INSERT INTO kind_lifecycle VALUES('scratch',5,0.949999999999999955,7,0.699999999999999955,3,0.25) ON CONFLICT DO NOTHING;
INSERT INTO kind_lifecycle VALUES('procedure',2,0.800000000000000044,180,0.5,90,3.0) ON CONFLICT DO NOTHING;
INSERT INTO kind_lifecycle VALUES('policy',1,0.699999999999999955,365,0.299999999999999988,180,5.0) ON CONFLICT DO NOTHING;
-- DB2 text-search projections. Views expose (rowid, source cols, fts_tsv) so
-- the DB2 rewriter can translate MATCH / bm25. memories_code_fts uses pg_trgm
-- (match_text + gin_trgm_ops) because trigram has no tsvector analogue. The
-- extension create is wrapped in a DO block that tolerates
-- insufficient_privilege so managed DB2 deployments without the extension
-- pre-enabled degrade to seq-scan rather than failing schema apply.
DO $trgm_ext$ BEGIN
   BEGIN
      CREATE EXTENSION IF NOT EXISTS pg_trgm;
   EXCEPTION WHEN OTHERS THEN
      RAISE NOTICE 'pg_trgm not enabled (%); memories_code_fts falls back to sequential scan', SQLERRM;
   END;
END $trgm_ext$;

ALTER TABLE memories
   ADD COLUMN IF NOT EXISTS provenance_category TEXT NOT NULL DEFAULT 'user_stated';

ALTER TABLE memories
   ADD COLUMN IF NOT EXISTS memories_fts_tsv tsvector GENERATED ALWAYS AS (
      to_tsvector('simple', coalesce(key, '') || ' ' || coalesce(content, ''))) STORED,
   ADD COLUMN IF NOT EXISTS memory_negation_fts_tsv tsvector GENERATED ALWAYS AS (
      to_tsvector('simple', coalesce(negation_tokens, ''))) STORED,
   ADD COLUMN IF NOT EXISTS memories_code_fts_text text GENERATED ALWAYS AS (
      coalesce(key, '') || ' ' || coalesce(content, '')) STORED;
CREATE INDEX IF NOT EXISTS memories_fts_gin ON memories USING GIN (memories_fts_tsv);
CREATE INDEX IF NOT EXISTS memory_negation_fts_gin ON memories USING GIN (memory_negation_fts_tsv);
DO $trgm_idx$ BEGIN
   BEGIN
      CREATE INDEX IF NOT EXISTS memories_code_fts_trgm_gin
         ON memories USING GIN (memories_code_fts_text gin_trgm_ops);
   EXCEPTION WHEN OTHERS THEN
      RAISE NOTICE 'memories_code_fts_trgm_gin skipped (%)', SQLERRM;
   END;
END $trgm_idx$;

-- ingest-lab: strategy metadata and enrichment fields (no embedding bytes in canonical rows)
ALTER TABLE kb_documents
   ADD COLUMN IF NOT EXISTS chunk_strategy TEXT NOT NULL DEFAULT 'heading',
   ADD COLUMN IF NOT EXISTS doc_kind TEXT NOT NULL DEFAULT '',
   ADD COLUMN IF NOT EXISTS chunk_context TEXT NOT NULL DEFAULT '';

ALTER TABLE kb_documents
   ADD COLUMN IF NOT EXISTS kb_fts_tsv tsvector GENERATED ALWAYS AS (
      to_tsvector('simple', coalesce(content, '') || ' ' || coalesce(heading_path, ''))) STORED;
CREATE INDEX IF NOT EXISTS kb_fts_gin ON kb_documents USING GIN (kb_fts_tsv);

ALTER TABLE memory_chunks
   ADD COLUMN IF NOT EXISTS memory_chunks_fts_tsv tsvector GENERATED ALWAYS AS (
      to_tsvector('simple', coalesce(chunk_text, ''))) STORED;
CREATE INDEX IF NOT EXISTS memory_chunks_fts_gin ON memory_chunks USING GIN (memory_chunks_fts_tsv);

ALTER TABLE memory_units
   ADD COLUMN IF NOT EXISTS memory_units_fts_tsv tsvector GENERATED ALWAYS AS (
      to_tsvector('simple', coalesce(unit_key, '') || ' ' || coalesce(unit_text, ''))) STORED;
CREATE INDEX IF NOT EXISTS memory_units_fts_gin ON memory_units USING GIN (memory_units_fts_tsv);

ALTER TABLE prospective_memories
   ADD COLUMN IF NOT EXISTS prospective_memories_fts_tsv tsvector GENERATED ALWAYS AS (
      to_tsvector('simple', coalesce(trigger_text, ''))) STORED;
CREATE INDEX IF NOT EXISTS prospective_memories_fts_gin ON prospective_memories USING GIN (prospective_memories_fts_tsv);

ALTER TABLE epistemic_directives
   ADD COLUMN IF NOT EXISTS epistemic_directives_fts_tsv tsvector GENERATED ALWAYS AS (
      to_tsvector('simple', coalesce(question, '') || ' ' || coalesce(topic, ''))) STORED;
CREATE INDEX IF NOT EXISTS epistemic_directives_fts_gin ON epistemic_directives USING GIN (epistemic_directives_fts_tsv);

ALTER TABLE file_contents
   ADD COLUMN IF NOT EXISTS code_fts_tsv tsvector GENERATED ALWAYS AS (
      to_tsvector('simple', coalesce(content, ''))) STORED;
CREATE INDEX IF NOT EXISTS code_fts_gin ON file_contents USING GIN (code_fts_tsv);
ALTER TABLE kb_file_index ADD COLUMN IF NOT EXISTS content TEXT DEFAULT NULL;

CREATE TABLE IF NOT EXISTS kb_code_unit_jobs (  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  project TEXT NOT NULL DEFAULT '',  file_path TEXT NOT NULL DEFAULT '',  symbol TEXT NOT NULL DEFAULT '',  kind TEXT NOT NULL DEFAULT 'function',  line INTEGER NOT NULL DEFAULT 0,  status TEXT NOT NULL DEFAULT 'pending',  attempts INTEGER NOT NULL DEFAULT 0,  last_error TEXT NOT NULL DEFAULT '',  claimed_by TEXT NOT NULL DEFAULT '',  claimed_at TEXT NOT NULL DEFAULT '',  created_at TEXT NOT NULL DEFAULT (pg_now_text()),  updated_at TEXT NOT NULL DEFAULT (pg_now_text()),  UNIQUE(project, file_path, symbol));
CREATE INDEX IF NOT EXISTS idx_kb_code_unit_jobs_status ON kb_code_unit_jobs(status, id);

CREATE OR REPLACE VIEW memories_fts AS
   SELECT id AS rowid, key, content, memories_fts_tsv AS fts_tsv FROM memories;
CREATE OR REPLACE VIEW memory_negation_fts AS
   SELECT id AS rowid, negation_tokens, memory_negation_fts_tsv AS fts_tsv FROM memories;
CREATE OR REPLACE VIEW memories_code_fts AS
   SELECT id AS rowid, key, content, memories_code_fts_text AS match_text FROM memories;
CREATE OR REPLACE VIEW kb_fts AS
   SELECT id AS rowid, content, heading_path, kb_fts_tsv AS fts_tsv FROM kb_documents;
CREATE OR REPLACE VIEW memory_chunks_fts AS
   SELECT id AS rowid, chunk_text, memory_chunks_fts_tsv AS fts_tsv FROM memory_chunks;
CREATE OR REPLACE VIEW memory_units_fts AS
   SELECT id AS rowid, unit_key, unit_text, memory_units_fts_tsv AS fts_tsv FROM memory_units;
CREATE OR REPLACE VIEW prospective_memories_fts AS
   SELECT id AS rowid, trigger_text, prospective_memories_fts_tsv AS fts_tsv FROM prospective_memories;
CREATE OR REPLACE VIEW epistemic_directives_fts AS
   SELECT id AS rowid, question, topic, epistemic_directives_fts_tsv AS fts_tsv FROM epistemic_directives;
CREATE OR REPLACE VIEW code_fts AS
   SELECT file_id AS rowid, content, code_fts_tsv AS fts_tsv FROM file_contents;

-- Approximate sketch persistence (Bloom, MinHash-LSH, Count-Min, HyperLogLog).
-- One row per (sketch_kind, scope_kind, scope_id, feature_family).
-- See docs/proposals/done/approximate-sketches-for-ingest-prefiltering.md
CREATE TABLE IF NOT EXISTS sketch_store (
    id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sketch_kind    TEXT NOT NULL,
    scope_kind     TEXT NOT NULL,
    scope_id       TEXT NOT NULL DEFAULT '',
    feature_family TEXT NOT NULL,
    state_bytes    BYTEA NOT NULL,
    item_count     BIGINT NOT NULL DEFAULT 0,
    params_json    JSONB NOT NULL DEFAULT '{}',
    created_at     TEXT NOT NULL,
    updated_at     TEXT NOT NULL,
    UNIQUE (sketch_kind, scope_kind, scope_id, feature_family)
);
CREATE TABLE IF NOT EXISTS kb_minhash_signatures (  project TEXT NOT NULL,  file_path TEXT NOT NULL,  file_hash TEXT NOT NULL DEFAULT '',  signature_bytes BYTEA NOT NULL,  updated_at TEXT NOT NULL DEFAULT (pg_now_text()),  PRIMARY KEY (project, file_path));
CREATE INDEX IF NOT EXISTS idx_kb_minhash_signatures_project ON kb_minhash_signatures(project);
CREATE TABLE IF NOT EXISTS kb_lsh_buckets (  project TEXT NOT NULL,  band INTEGER NOT NULL,  band_hash TEXT NOT NULL,  file_path TEXT NOT NULL,  updated_at TEXT NOT NULL DEFAULT (pg_now_text()),  PRIMARY KEY (project, band, band_hash, file_path));
CREATE INDEX IF NOT EXISTS idx_kb_lsh_buckets_lookup ON kb_lsh_buckets(project, band, band_hash);

-- Charter artifact tables: candidate and committed artifacts, citations,
-- links, and audit events.  Created exactly once across cross-source-learning-
-- substrate and deep-curator; all charter-instance proposals share them.
-- See docs/proposals/done/cross-source-learning-substrate.md
CREATE TABLE IF NOT EXISTS artifacts (
    id                 TEXT NOT NULL PRIMARY KEY,
    kind               TEXT NOT NULL,
    state              TEXT NOT NULL DEFAULT 'proposed',
    scope_kind         TEXT NOT NULL DEFAULT 'user',
    scope_id           TEXT NOT NULL DEFAULT '',
    operator_id        TEXT NOT NULL DEFAULT '',
    confidence         DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    attempt_count      INT NOT NULL DEFAULT 1,
    source_bundle_hash TEXT NOT NULL DEFAULT '',
    model_version      TEXT NOT NULL DEFAULT '',
    prompt_version     TEXT NOT NULL DEFAULT '',
    target_surface     TEXT NOT NULL DEFAULT '',
    created_at         TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),
    committed_at       TEXT NOT NULL DEFAULT '',
    retired_at         TEXT NOT NULL DEFAULT '',
    superseded_by      TEXT NOT NULL DEFAULT '',
    payload            JSONB NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_artifacts_kind_state ON artifacts (kind, state);
CREATE INDEX IF NOT EXISTS idx_artifacts_scope ON artifacts (scope_kind, scope_id);
CREATE INDEX IF NOT EXISTS idx_artifacts_retrieval_attr ON artifacts (kind, scope_id) WHERE kind = 'retrieval_attribution';
CREATE INDEX IF NOT EXISTS idx_artifacts_demotion_profile ON artifacts (kind, target_surface, scope_kind, scope_id) WHERE kind = 'demotion_profile';

-- evidence_index_ops / learning_synth_ops: embed-ops queues keyed on artifacts.
-- Must follow the artifacts table above — they carry a foreign key into it, so
-- a fresh-database single-pass schema apply fails if they precede it.
-- See docs/proposals/pending/cross-source-learning-pipeline.md
CREATE TABLE IF NOT EXISTS evidence_index_ops (  artifact_id TEXT PRIMARY KEY REFERENCES artifacts(id) ON DELETE CASCADE,  collection TEXT NOT NULL DEFAULT 'evidence',  status TEXT NOT NULL DEFAULT 'pending',  attempts BIGINT NOT NULL DEFAULT 0,  last_error TEXT NOT NULL DEFAULT '',  updated_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE INDEX IF NOT EXISTS idx_evidence_index_ops_status ON evidence_index_ops(status);
CREATE TABLE IF NOT EXISTS learning_synth_ops (  artifact_id TEXT PRIMARY KEY REFERENCES artifacts(id) ON DELETE CASCADE,  status TEXT NOT NULL DEFAULT 'pending',  attempts BIGINT NOT NULL DEFAULT 0,  last_error TEXT NOT NULL DEFAULT '',  updated_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')));
CREATE INDEX IF NOT EXISTS idx_learning_synth_ops_status ON learning_synth_ops(status);

CREATE TABLE IF NOT EXISTS artifact_citations (
    artifact_id  TEXT NOT NULL REFERENCES artifacts (id) ON DELETE CASCADE,
    source_kind  TEXT NOT NULL,
    source_id    TEXT NOT NULL,
    span_start   INT NOT NULL DEFAULT 0,
    span_end     INT NOT NULL DEFAULT 0,
    PRIMARY KEY (artifact_id, source_kind, source_id, span_start, span_end)
);

CREATE TABLE IF NOT EXISTS artifact_links (
    from_id  TEXT NOT NULL REFERENCES artifacts (id) ON DELETE CASCADE,
    to_id    TEXT NOT NULL REFERENCES artifacts (id) ON DELETE CASCADE,
    kind     TEXT NOT NULL,
    PRIMARY KEY (from_id, to_id, kind)
);

CREATE TABLE IF NOT EXISTS audit_events (
    id                  TEXT NOT NULL PRIMARY KEY,
    source_artifact_id  TEXT NOT NULL REFERENCES artifacts (id) ON DELETE CASCADE,
    target_surface      TEXT NOT NULL,
    target_id           TEXT NOT NULL,
    operator_id         TEXT NOT NULL DEFAULT '',
    scope_kind          TEXT NOT NULL DEFAULT '',
    scope_id            TEXT NOT NULL DEFAULT '',
    before_snapshot     JSONB,
    after_snapshot      JSONB,
    applied_at          TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),
    applied_confidence  DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    flagged_for_review  BOOLEAN NOT NULL DEFAULT FALSE,
    reviewed_at         TEXT NOT NULL DEFAULT '',
    verdict             TEXT NOT NULL DEFAULT '',
    verdict_tag         TEXT NOT NULL DEFAULT '',
    verdict_scope       TEXT NOT NULL DEFAULT '',
    counter_example     TEXT NOT NULL DEFAULT '',
    verdict_note        TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_audit_events_artifact ON audit_events (source_artifact_id);
CREATE INDEX IF NOT EXISTS idx_audit_events_surface ON audit_events (target_surface, applied_at);

CREATE TABLE IF NOT EXISTS feature_rows (
    subject_id          TEXT NOT NULL,
    subject_kind        TEXT NOT NULL,
    scope_kind          TEXT NOT NULL DEFAULT '',
    scope_id            TEXT NOT NULL DEFAULT '',
    feature_set_version TEXT NOT NULL,
    features            JSONB NOT NULL DEFAULT '{}',
    computed_at         TEXT NOT NULL,
    PRIMARY KEY (subject_id, subject_kind, feature_set_version)
);
CREATE INDEX IF NOT EXISTS idx_feature_rows_kind_ts ON feature_rows (subject_kind, computed_at);

CREATE TABLE IF NOT EXISTS report_enrichments (
    subject_type        TEXT NOT NULL,
    subject_id          TEXT NOT NULL,
    enrichment_kind     TEXT NOT NULL,
    source              TEXT NOT NULL DEFAULT '',
    schema_version      TEXT NOT NULL,
    payload_json        JSONB NOT NULL DEFAULT '{}',
    input_hash          TEXT NOT NULL DEFAULT '',
    computed_at         TEXT NOT NULL,
    expires_at          TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (subject_type, subject_id, enrichment_kind, source, schema_version)
);
CREATE INDEX IF NOT EXISTS idx_report_enrichments_subject
    ON report_enrichments (subject_type, subject_id);
CREATE INDEX IF NOT EXISTS idx_report_enrichments_kind_ts
    ON report_enrichments (enrichment_kind, computed_at);

-- Contextual bandit: per-decision log for propensity-weighted replay.
-- See docs/proposals/accepted/contextual-bandits-and-counterfactual-replay.md
CREATE TABLE IF NOT EXISTS bandit_decisions (
    id              TEXT NOT NULL PRIMARY KEY,
    decision_point  TEXT NOT NULL,
    arm_id          TEXT NOT NULL,
    context_hash    TEXT NOT NULL DEFAULT '',
    propensity      DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    reward          DOUBLE PRECISION,
    decided_at      TEXT NOT NULL,
    closed_at       TEXT NOT NULL DEFAULT '',
    is_exploration  BOOLEAN NOT NULL DEFAULT FALSE
);
-- Additive migration: prior deployments that pre-date is_exploration.
ALTER TABLE bandit_decisions ADD COLUMN IF NOT EXISTS is_exploration BOOLEAN NOT NULL DEFAULT FALSE;
CREATE INDEX IF NOT EXISTS idx_bandit_decisions_point ON bandit_decisions (decision_point, arm_id, decided_at);
CREATE INDEX IF NOT EXISTS idx_bandit_decisions_explore ON bandit_decisions (decision_point, decided_at, is_exploration);

-- Per-arm posterior statistics (materialized by the offline updater).
CREATE TABLE IF NOT EXISTS bandit_arm_stats (
    decision_point    TEXT NOT NULL,
    arm_id            TEXT NOT NULL,
    n_decisions       BIGINT NOT NULL DEFAULT 0,
    n_rewards         BIGINT NOT NULL DEFAULT 0,
    sum_reward        DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    sum_reward_sq     DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    posterior_alpha   DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    posterior_beta    DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    updated_at        TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),
    PRIMARY KEY (decision_point, arm_id)
);

-- Promoted (production-default) arm per decision point: the arm an operator has
-- locked in via `aimee optimize promote --apply`. Consumers use it as the default
-- when live bandit sampling is off; rollback_arm records the prior default.
CREATE TABLE IF NOT EXISTS bandit_promotions (
    decision_point  TEXT NOT NULL PRIMARY KEY,
    arm_id          TEXT NOT NULL,
    rollback_arm    TEXT NOT NULL DEFAULT '',
    promoted_at     TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'))
);

-- KB temporal confidence decay: access tracking + maintenance audit
ALTER TABLE artifacts ADD COLUMN IF NOT EXISTS last_accessed_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE artifacts ADD COLUMN IF NOT EXISTS last_decay_at TEXT DEFAULT NULL;
UPDATE artifacts SET last_accessed_at = COALESCE(NULLIF(committed_at,'')::timestamptz, created_at::timestamptz) WHERE last_accessed_at IS NULL;
CREATE TABLE IF NOT EXISTS kb_maintenance_runs (
    id           TEXT NOT NULL PRIMARY KEY,
    rows_decayed INTEGER NOT NULL DEFAULT 0,
    orphans_pruned INTEGER NOT NULL DEFAULT 0,
    elapsed_ms   BIGINT NOT NULL DEFAULT 0,
    lambda       DOUBLE PRECISION NOT NULL DEFAULT 0.005,
    confidence_floor DOUBLE PRECISION NOT NULL DEFAULT 0.10,
    dry_run      INTEGER NOT NULL DEFAULT 0,
    run_at       TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_kb_maintenance_runs_at ON kb_maintenance_runs (run_at DESC);

-- Cross-source learning review surface: reflection scheduling + review query index
ALTER TABLE artifacts ADD COLUMN IF NOT EXISTS reflected_at TEXT DEFAULT NULL;
CREATE INDEX IF NOT EXISTS idx_artifacts_review
    ON artifacts (state, target_surface, confidence DESC)
    WHERE state = 'proposed';

-- KB ingest API and corpus staging: doc upload, review queue, release lifecycle.
-- See docs/proposals/pending/aimee-kb-ingest-api-and-corpus-staging.md
CREATE TABLE IF NOT EXISTS docs (
    id               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content_hash     TEXT NOT NULL,
    filename         TEXT NOT NULL DEFAULT '',
    scope            TEXT NOT NULL DEFAULT 'global',
    converter        TEXT NOT NULL DEFAULT 'passthrough',
    converter_version TEXT NOT NULL DEFAULT '',
    normalized_text  TEXT NOT NULL DEFAULT '',
    state            TEXT NOT NULL DEFAULT 'staged',
    review_needed    BOOLEAN NOT NULL DEFAULT FALSE,
    review_reason    TEXT NOT NULL DEFAULT '',
    created_at       TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),
    updated_at       TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),
    UNIQUE (content_hash, converter, converter_version, scope)
);
CREATE INDEX IF NOT EXISTS idx_docs_state_review ON docs (state, review_needed);
CREATE INDEX IF NOT EXISTS idx_docs_content_hash ON docs (content_hash);
ALTER TABLE docs ADD COLUMN IF NOT EXISTS doc_type TEXT NOT NULL DEFAULT '';
ALTER TABLE docs ADD COLUMN IF NOT EXISTS doc_type_confidence DOUBLE PRECISION NOT NULL DEFAULT 0.0;
CREATE INDEX IF NOT EXISTS idx_docs_doc_type ON docs (doc_type);

CREATE TABLE IF NOT EXISTS document_sections (
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    doc_id       BIGINT NOT NULL REFERENCES docs(id) ON DELETE CASCADE,
    parent_id    BIGINT REFERENCES document_sections(id) ON DELETE CASCADE,
    ordinal      BIGINT NOT NULL DEFAULT 0,
    depth        BIGINT NOT NULL DEFAULT 0,
    heading      TEXT NOT NULL DEFAULT '',
    heading_path TEXT NOT NULL DEFAULT '',
    span_start   BIGINT NOT NULL DEFAULT 0,
    span_end     BIGINT NOT NULL DEFAULT 0,
    content_hash TEXT NOT NULL DEFAULT '',
    created_at   TEXT NOT NULL DEFAULT (pg_now_text()),
    UNIQUE (doc_id, heading_path, ordinal)
);
CREATE INDEX IF NOT EXISTS idx_document_sections_doc ON document_sections (doc_id, ordinal);
CREATE INDEX IF NOT EXISTS idx_document_sections_parent ON document_sections (parent_id);

CREATE TABLE IF NOT EXISTS document_references (
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    from_doc_id     BIGINT NOT NULL REFERENCES docs(id) ON DELETE CASCADE,
    from_section_id BIGINT REFERENCES document_sections(id) ON DELETE SET NULL,
    ref_type        TEXT NOT NULL DEFAULT 'mentions',
    raw_target      TEXT NOT NULL DEFAULT '',
    to_doc_id       BIGINT REFERENCES docs(id) ON DELETE SET NULL,
    resolution      TEXT NOT NULL DEFAULT 'unresolved',
    confidence      DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    created_at      TEXT NOT NULL DEFAULT (pg_now_text()),
    UNIQUE (from_doc_id, ref_type, raw_target)
);
CREATE INDEX IF NOT EXISTS idx_doc_refs_from ON document_references (from_doc_id);
CREATE INDEX IF NOT EXISTS idx_doc_refs_to ON document_references (to_doc_id) WHERE to_doc_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_doc_refs_resolution ON document_references (resolution);

CREATE TABLE IF NOT EXISTS corpus_processing_jobs (
    doc_id       BIGINT PRIMARY KEY REFERENCES docs(id) ON DELETE CASCADE,
    content_hash TEXT NOT NULL DEFAULT '',
    stage        TEXT NOT NULL DEFAULT 'ingested',
    stage_status TEXT NOT NULL DEFAULT 'pending',
    attempts     BIGINT NOT NULL DEFAULT 0,
    lease_owner  TEXT NOT NULL DEFAULT '',
    lease_until  TEXT NOT NULL DEFAULT '',
    last_error   TEXT NOT NULL DEFAULT '',
    created_at   TEXT NOT NULL DEFAULT (pg_now_text()),
    updated_at   TEXT NOT NULL DEFAULT (pg_now_text())
);
CREATE INDEX IF NOT EXISTS idx_corpus_jobs_status ON corpus_processing_jobs (stage_status, stage, doc_id);

CREATE TABLE IF NOT EXISTS corpus_stage_events (
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    doc_id     BIGINT NOT NULL REFERENCES docs(id) ON DELETE CASCADE,
    from_stage TEXT NOT NULL DEFAULT '',
    to_stage   TEXT NOT NULL DEFAULT '',
    outcome    TEXT NOT NULL DEFAULT '',
    detail     TEXT NOT NULL DEFAULT '',
    worker     TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT (pg_now_text())
);
CREATE INDEX IF NOT EXISTS idx_corpus_stage_events_doc ON corpus_stage_events (doc_id, id);

CREATE TABLE IF NOT EXISTS document_versions (
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    doc_key      TEXT NOT NULL,
    doc_id       BIGINT NOT NULL REFERENCES docs(id) ON DELETE CASCADE,
    content_hash TEXT NOT NULL DEFAULT '',
    version_no   BIGINT NOT NULL DEFAULT 1,
    source_mtime TEXT NOT NULL DEFAULT '',
    source_time  TEXT NOT NULL DEFAULT '',
    source_time_provenance TEXT NOT NULL DEFAULT 'unknown',
    is_current   BOOLEAN NOT NULL DEFAULT TRUE,
    superseded_at TEXT NOT NULL DEFAULT '',
    created_at   TEXT NOT NULL DEFAULT (pg_now_text()),
    UNIQUE (doc_key, content_hash)
);
CREATE INDEX IF NOT EXISTS idx_document_versions_current ON document_versions (doc_key, is_current);

CREATE TABLE IF NOT EXISTS doc_releases (
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name         TEXT NOT NULL UNIQUE,
    state        TEXT NOT NULL DEFAULT 'pending',
    promoted_at  TEXT NOT NULL DEFAULT '',
    retired_at   TEXT NOT NULL DEFAULT '',
    created_at   TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_doc_releases_state ON doc_releases (state);

CREATE TABLE IF NOT EXISTS release_docs (
    release_id  BIGINT NOT NULL REFERENCES doc_releases(id) ON DELETE CASCADE,
    doc_id      BIGINT NOT NULL REFERENCES docs(id) ON DELETE CASCADE,
    accepted_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),
    PRIMARY KEY (release_id, doc_id)
);
CREATE INDEX IF NOT EXISTS idx_release_docs_doc_id ON release_docs (doc_id);

-- pgvector embedding tables (memory_embeddings, kb_embeddings).
-- Wrapped in a DO block so schema apply degrades gracefully when pgvector is
-- not yet installed; operators will see a NOTICE and vector search returns no
-- results rather than crashing.
DO $pgvec_setup$ DECLARE v_ok BOOLEAN := FALSE; BEGIN
    BEGIN
        CREATE EXTENSION IF NOT EXISTS vector;
        v_ok := TRUE;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'pgvector not available (%), embedding tables skipped', SQLERRM;
    END;
    IF NOT v_ok THEN RETURN; END IF;

    EXECUTE $T$
        CREATE TABLE IF NOT EXISTS memory_embeddings (
            point_id      BIGINT PRIMARY KEY,
            embedding     vector(384),
            record_type   TEXT NOT NULL DEFAULT '',
            primary_scope TEXT NOT NULL DEFAULT '',
            workspace     TEXT NOT NULL DEFAULT '',
            project       TEXT NOT NULL DEFAULT '',
            kind          TEXT NOT NULL DEFAULT '',
            payload_json  TEXT NOT NULL DEFAULT ''
        )
    $T$;

    EXECUTE $T$
        CREATE TABLE IF NOT EXISTS kb_embeddings (
            point_id     BIGINT PRIMARY KEY,
            embedding    vector(384),
            project      TEXT NOT NULL DEFAULT '',
            payload_json TEXT NOT NULL DEFAULT ''
        )
    $T$;

    -- curator_entity_vectors: pgvector embeddings for deep-curator entity
    -- resolution (resolve_entities pass). Mirrors kb_embeddings with the
    -- additional scope_kind / scope_id / canonical_name columns the curator
    -- needs for filtering candidate entities, plus artifact_id so a matched
    -- point_id can be reverse-mapped to its source entity artifact (used by
    -- the resolve_entities judge band and fuzzy contradiction mining).
    EXECUTE $T$
        CREATE TABLE IF NOT EXISTS curator_entity_vectors (
            point_id       BIGINT PRIMARY KEY,
            embedding      vector(384),
            scope_kind     TEXT NOT NULL DEFAULT '',
            scope_id       TEXT NOT NULL DEFAULT '',
            canonical_name TEXT NOT NULL DEFAULT '',
            artifact_id    TEXT NOT NULL DEFAULT '',
            payload_json   TEXT NOT NULL DEFAULT ''
        )
    $T$;
    -- Back-fill the artifact_id column on databases created before it existed.
    EXECUTE $T$ ALTER TABLE curator_entity_vectors
                ADD COLUMN IF NOT EXISTS artifact_id TEXT NOT NULL DEFAULT '' $T$;

    -- curator_narrative_vectors: pgvector embeddings for deep-curator
    -- narrative store (one point per doc_summary / synthesis / open_question
    -- artifact) used for filter-first doc retrieval. Mirrors kb_embeddings
    -- with the additional artifact_id / kind / doc_id / status / priority
    -- columns the curator needs for filtering candidate documents.
    EXECUTE $T$
        CREATE TABLE IF NOT EXISTS curator_narrative_vectors (
            point_id     BIGINT PRIMARY KEY,
            embedding    vector(384),
            artifact_id  TEXT NOT NULL DEFAULT '',
            kind         TEXT NOT NULL DEFAULT '',
            doc_id       TEXT NOT NULL DEFAULT '',
            status       TEXT NOT NULL DEFAULT '',
            priority     TEXT NOT NULL DEFAULT '',
            payload_json TEXT NOT NULL DEFAULT ''
        )
    $T$;

    -- curator_claim_vectors: pgvector embeddings for deep-curator claims
    -- store (one point per resolved claim artifact) used by detect_contradictions
    -- to match on subject+attribute (subj_attr_vec) and anti-match on the
    -- claim's value (value_vec). Two named vector columns per row, with
    -- artifact_id / subject / attribute / value / claim_kind for filtering
    -- and provenance.
    EXECUTE $T$
        CREATE TABLE IF NOT EXISTS curator_claim_vectors (
            point_id      BIGINT PRIMARY KEY,
            subj_attr_vec vector(384),
            value_vec     vector(384),
            artifact_id   TEXT NOT NULL DEFAULT '',
            subject       TEXT NOT NULL DEFAULT '',
            attribute     TEXT NOT NULL DEFAULT '',
            value         TEXT NOT NULL DEFAULT '',
            claim_kind    TEXT NOT NULL DEFAULT '',
            payload_json  TEXT NOT NULL DEFAULT ''
        )
    $T$;

    -- curator_code_unit_vectors: pgvector embeddings for deep-curator
    -- per-definition semantic code store. One point per resolved code
    -- definition (function/struct/typedef/etc.) with three named vector
    -- columns: intent_vec (what the definition is trying to do),
    -- signature_vec (the parameter/return shape), and body_vec (the
    -- implementation semantics). artifact_id / file_path / def_kind /
    -- signature / body_hash / payload_json carry provenance and lookup
    -- keys for the search path.
    EXECUTE $T$
        CREATE TABLE IF NOT EXISTS curator_code_unit_vectors (
            point_id      BIGINT PRIMARY KEY,
            intent_vec    vector(384),
            signature_vec vector(384),
            body_vec      vector(384),
            artifact_id   TEXT NOT NULL DEFAULT '',
            file_path     TEXT NOT NULL DEFAULT '',
            def_kind      TEXT NOT NULL DEFAULT '',
            signature     TEXT NOT NULL DEFAULT '',
            body_hash     TEXT NOT NULL DEFAULT '',
            payload_json  TEXT NOT NULL DEFAULT ''
        )
    $T$;

    -- The embedding columns must carry a fixed dimension or the HNSW index
    -- below cannot be built (pgvector rejects an HNSW index on an
    -- undimensioned `vector` column), which leaves a fresh database with no
    -- usable vector index and /v1/health reporting pgvector degraded. All
    -- embedders in the stack emit 384 dims (MiniLM). This ALTER migrates
    -- databases created before the columns were dimensioned; it is a no-op
    -- once the columns are already vector(384).
    BEGIN
        EXECUTE $T$ ALTER TABLE memory_embeddings
                    ALTER COLUMN embedding TYPE vector(384) USING embedding::vector(384) $T$;
        EXECUTE $T$ ALTER TABLE kb_embeddings
                    ALTER COLUMN embedding TYPE vector(384) USING embedding::vector(384) $T$;
        EXECUTE $T$ ALTER TABLE curator_entity_vectors
                    ALTER COLUMN embedding TYPE vector(384) USING embedding::vector(384) $T$;
        EXECUTE $T$ ALTER TABLE curator_narrative_vectors
                    ALTER COLUMN embedding TYPE vector(384) USING embedding::vector(384) $T$;
        EXECUTE $T$ ALTER TABLE curator_claim_vectors
                    ALTER COLUMN subj_attr_vec TYPE vector(384) USING subj_attr_vec::vector(384) $T$;
        EXECUTE $T$ ALTER TABLE curator_claim_vectors
                    ALTER COLUMN value_vec TYPE vector(384) USING value_vec::vector(384) $T$;
        EXECUTE $T$ ALTER TABLE curator_code_unit_vectors
                    ALTER COLUMN intent_vec TYPE vector(384) USING intent_vec::vector(384) $T$;
        EXECUTE $T$ ALTER TABLE curator_code_unit_vectors
                    ALTER COLUMN signature_vec TYPE vector(384) USING signature_vec::vector(384) $T$;
        EXECUTE $T$ ALTER TABLE curator_code_unit_vectors
                    ALTER COLUMN body_vec TYPE vector(384) USING body_vec::vector(384) $T$;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'embedding column dimension migration skipped (%)', SQLERRM;
    END;

    EXECUTE $T$
        CREATE INDEX IF NOT EXISTS idx_memory_embeddings_record_type
            ON memory_embeddings (record_type)
    $T$;
    EXECUTE $T$
        CREATE INDEX IF NOT EXISTS idx_memory_embeddings_scope
            ON memory_embeddings (primary_scope, workspace, project)
    $T$;
    EXECUTE $T$
        CREATE INDEX IF NOT EXISTS idx_kb_embeddings_project
            ON kb_embeddings (project)
    $T$;
    EXECUTE $T$
        CREATE INDEX IF NOT EXISTS idx_curator_entity_vectors_scope
            ON curator_entity_vectors (scope_kind, scope_id)
    $T$;
    EXECUTE $T$
        CREATE INDEX IF NOT EXISTS idx_curator_narrative_vectors_kind
            ON curator_narrative_vectors (kind, status, priority)
    $T$;
    EXECUTE $T$
        CREATE INDEX IF NOT EXISTS idx_curator_claim_vectors_kind
            ON curator_claim_vectors (claim_kind)
    $T$;
    EXECUTE $T$
        CREATE INDEX IF NOT EXISTS idx_curator_code_unit_vectors_kind
            ON curator_code_unit_vectors (def_kind)
    $T$;

    BEGIN
        EXECUTE $T$
            CREATE INDEX IF NOT EXISTS idx_memory_embeddings_hnsw
                ON memory_embeddings USING hnsw (embedding vector_cosine_ops)
        $T$;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'memory_embeddings HNSW index skipped (%)', SQLERRM;
    END;
    BEGIN
        EXECUTE $T$
            CREATE INDEX IF NOT EXISTS idx_kb_embeddings_hnsw
                ON kb_embeddings USING hnsw (embedding vector_cosine_ops)
        $T$;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'kb_embeddings HNSW index skipped (%)', SQLERRM;
    END;
    BEGIN
        EXECUTE $T$
            CREATE INDEX IF NOT EXISTS idx_curator_entity_vectors_hnsw
                ON curator_entity_vectors USING hnsw (embedding vector_cosine_ops)
        $T$;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'curator_entity_vectors HNSW index skipped (%)', SQLERRM;
    END;
    BEGIN
        EXECUTE $T$
            CREATE INDEX IF NOT EXISTS idx_curator_narrative_vectors_hnsw
                ON curator_narrative_vectors USING hnsw (embedding vector_cosine_ops)
        $T$;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'curator_narrative_vectors HNSW index skipped (%)', SQLERRM;
    END;
    BEGIN
        EXECUTE $T$
            CREATE INDEX IF NOT EXISTS idx_curator_claim_vectors_subj_attr_hnsw
                ON curator_claim_vectors USING hnsw (subj_attr_vec vector_cosine_ops)
        $T$;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'curator_claim_vectors subj_attr HNSW index skipped (%)', SQLERRM;
    END;
    BEGIN
        EXECUTE $T$
            CREATE INDEX IF NOT EXISTS idx_curator_claim_vectors_value_hnsw
                ON curator_claim_vectors USING hnsw (value_vec vector_cosine_ops)
        $T$;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'curator_claim_vectors value HNSW index skipped (%)', SQLERRM;
    END;
    BEGIN
        EXECUTE $T$
            CREATE INDEX IF NOT EXISTS idx_curator_code_unit_vectors_intent_hnsw
                ON curator_code_unit_vectors USING hnsw (intent_vec vector_cosine_ops)
        $T$;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'curator_code_unit_vectors intent HNSW index skipped (%)', SQLERRM;
    END;
    BEGIN
        EXECUTE $T$
            CREATE INDEX IF NOT EXISTS idx_curator_code_unit_vectors_signature_hnsw
                ON curator_code_unit_vectors USING hnsw (signature_vec vector_cosine_ops)
        $T$;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'curator_code_unit_vectors signature HNSW index skipped (%)', SQLERRM;
    END;
    BEGIN
        EXECUTE $T$
            CREATE INDEX IF NOT EXISTS idx_curator_code_unit_vectors_body_hnsw
                ON curator_code_unit_vectors USING hnsw (body_vec vector_cosine_ops)
        $T$;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'curator_code_unit_vectors body HNSW index skipped (%)', SQLERRM;
    END;

    -- exemplar_vectors: pgvector embeddings for case artifact exemplar recall.
    -- See docs/proposals/accepted/graph-reasoning-case-based-recall-and-contradiction-logic.md
    BEGIN
        EXECUTE $T$
            CREATE TABLE IF NOT EXISTS exemplar_vectors (
                id          BIGSERIAL PRIMARY KEY,
                artifact_id TEXT      NOT NULL REFERENCES artifacts(id) ON DELETE CASCADE,
                collection  TEXT      NOT NULL DEFAULT 'case_exemplars',
                embedding   vector(384),
                created_at  TEXT      NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'))
            )
        $T$;
        EXECUTE $T$
            CREATE INDEX IF NOT EXISTS idx_exemplar_vectors_artifact_id
                ON exemplar_vectors (artifact_id)
        $T$;
        EXECUTE $T$
            CREATE INDEX IF NOT EXISTS idx_exemplar_vectors_collection
                ON exemplar_vectors (collection)
        $T$;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'exemplar_vectors table skipped (%)', SQLERRM;
    END;

    -- evidence_vectors: pgvector embeddings over the non-doc evidence layer
    -- (session/feedback/tool-outcome/guardrail rows) for the learning
    -- neighbourhood builder. The embed-ops queue is evidence_index_ops (plain).
    -- See docs/proposals/pending/cross-source-learning-pipeline.md
    BEGIN
        EXECUTE $T$
            CREATE TABLE IF NOT EXISTS evidence_vectors (
                id          BIGSERIAL PRIMARY KEY,
                artifact_id TEXT      NOT NULL REFERENCES artifacts(id) ON DELETE CASCADE,
                collection  TEXT      NOT NULL DEFAULT 'evidence',
                embedding   vector(384),
                created_at  TEXT      NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'))
            )
        $T$;
        EXECUTE $T$
            CREATE INDEX IF NOT EXISTS idx_evidence_vectors_artifact_id
                ON evidence_vectors (artifact_id)
        $T$;
        EXECUTE $T$
            CREATE INDEX IF NOT EXISTS idx_evidence_vectors_collection
                ON evidence_vectors (collection)
        $T$;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'evidence_vectors table skipped (%)', SQLERRM;
    END;
    -- Phase 5: code_embeddings — code-unit vector table for code vector recall.
    BEGIN
        EXECUTE $T$
            CREATE TABLE IF NOT EXISTS code_embeddings (
                point_id     BIGINT PRIMARY KEY,
                embedding    vector,
                project      TEXT NOT NULL DEFAULT '',
                node_key     TEXT NOT NULL DEFAULT '',
                file_path    TEXT NOT NULL DEFAULT '',
                symbol       TEXT NOT NULL DEFAULT '',
                record_type  TEXT NOT NULL DEFAULT 'code_unit',
                content_hash TEXT NOT NULL DEFAULT '',
                body_hash    TEXT NOT NULL DEFAULT '',
                source_hash  TEXT NOT NULL DEFAULT '',
                payload_json TEXT NOT NULL DEFAULT '',
                updated_at   TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'))
            )
        $T$;
        EXECUTE $T$
            ALTER TABLE code_embeddings ADD COLUMN IF NOT EXISTS body_hash TEXT NOT NULL DEFAULT ''
        $T$;
        EXECUTE $T$
            CREATE INDEX IF NOT EXISTS idx_code_embeddings_project
                ON code_embeddings(project)
        $T$;
        EXECUTE $T$
            CREATE INDEX IF NOT EXISTS idx_code_embeddings_node
                ON code_embeddings(project, node_key)
        $T$;
        EXECUTE $T$
            CREATE UNIQUE INDEX IF NOT EXISTS idx_code_embeddings_hash
                ON code_embeddings(project, node_key, content_hash)
        $T$;
        EXECUTE $T$
            CREATE INDEX IF NOT EXISTS idx_code_embeddings_body_hash
                ON code_embeddings(project, body_hash)
        $T$;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'code_embeddings table skipped (%)', SQLERRM;
    END;
    BEGIN
        EXECUTE $T$
            CREATE INDEX IF NOT EXISTS idx_code_embeddings_hnsw
                ON code_embeddings USING hnsw (embedding vector_cosine_ops)
        $T$;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'code_embeddings HNSW index skipped (%)', SQLERRM;
    END;
END $pgvec_setup$;

/* ---- graph reasoning: ruleset registry and case view ---- */
CREATE TABLE IF NOT EXISTS reasoning_rulesets (
    id           TEXT NOT NULL PRIMARY KEY,
    version      INT NOT NULL DEFAULT 1,
    name         TEXT NOT NULL DEFAULT '',
    content_hash TEXT NOT NULL DEFAULT '',
    active       BOOLEAN NOT NULL DEFAULT TRUE,
    rules        JSONB NOT NULL DEFAULT '[]',
    created_at   TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_reasoning_rulesets_active ON reasoning_rulesets (active, name);

CREATE OR REPLACE VIEW cases AS
    SELECT * FROM artifacts WHERE kind = 'case';

-- Phase 0: effectiveness-weighted code vector graph shadow-delta table.
-- Stores bounded top-K rank deltas for shadow-mode fused scoring vs baseline.
-- Retention capped at 10,000 rows or 14 days (whichever is smaller) by a
-- periodic maintenance job. delta_json contains compact deltas only: result
-- id/key, baseline rank, fused rank, score delta, and reason flags.
CREATE TABLE IF NOT EXISTS memory_recall_shadow_deltas (
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    query_hash   TEXT NOT NULL,
    project      TEXT NOT NULL DEFAULT '',
    mode         TEXT NOT NULL DEFAULT 'shadow',
    result_count BIGINT NOT NULL DEFAULT 0,
    delta_json   TEXT NOT NULL DEFAULT '{}',
    created_at   TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_mrsd_query_created
    ON memory_recall_shadow_deltas(query_hash, created_at);
CREATE INDEX IF NOT EXISTS idx_mrsd_project_created
    ON memory_recall_shadow_deltas(project, created_at);

-- Phase 1: entity edge uniqueness migration — new columns on entity_edges.
-- utility_touched_at: wall-clock timestamp of last utility_score change.
-- structural_weight:  trust weight from deterministic code-index extraction.
-- edge_origin:        provenance tag ('session', 'code_projection', etc.).
ALTER TABLE entity_edges ADD COLUMN IF NOT EXISTS utility_touched_at TEXT NOT NULL DEFAULT '';
ALTER TABLE entity_edges ADD COLUMN IF NOT EXISTS structural_weight INTEGER NOT NULL DEFAULT 0;
ALTER TABLE entity_edges ADD COLUMN IF NOT EXISTS edge_origin TEXT NOT NULL DEFAULT 'session';

-- Phase 2: canonical graph node dictionary and legacy alias bridge.
CREATE TABLE IF NOT EXISTS entity_nodes (
    node_key     TEXT PRIMARY KEY,
    node_kind    INTEGER NOT NULL DEFAULT 0,
    project      TEXT NOT NULL DEFAULT '',
    display_name TEXT NOT NULL DEFAULT '',
    full_key     TEXT NOT NULL DEFAULT '',
    file_path    TEXT NOT NULL DEFAULT '',
    symbol       TEXT NOT NULL DEFAULT '',
    node_origin  TEXT NOT NULL DEFAULT '',
    last_seen_generation_id BIGINT NOT NULL DEFAULT 0,
    created_at   TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),
    updated_at   TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_entity_nodes_project ON entity_nodes(project);
CREATE INDEX IF NOT EXISTS idx_entity_nodes_kind ON entity_nodes(node_kind);

CREATE TABLE IF NOT EXISTS entity_node_aliases (
    alias       TEXT NOT NULL,
    node_key    TEXT NOT NULL REFERENCES entity_nodes(node_key) ON DELETE CASCADE,
    alias_kind  TEXT NOT NULL DEFAULT '',
    project     TEXT NOT NULL DEFAULT '',
    last_seen_generation_id BIGINT NOT NULL DEFAULT 0,
    created_at  TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),
    PRIMARY KEY (alias, node_key)
);
CREATE INDEX IF NOT EXISTS idx_entity_node_aliases_alias
    ON entity_node_aliases(alias);
CREATE INDEX IF NOT EXISTS idx_entity_node_aliases_project_alias
    ON entity_node_aliases(project, alias);

-- Phase 3: code graph projection ledger.
-- code_projection_generations tracks one generation per project:
--   pending -> visible (on publish), pending -> aborted (on failure),
--   visible -> superseded (on next publish). At most one 'visible' per project.
CREATE TABLE IF NOT EXISTS code_projection_generations (
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    project     TEXT NOT NULL,
    state       TEXT NOT NULL DEFAULT 'pending'
                    CHECK (state IN ('pending','visible','superseded','aborted')),
    source_hash TEXT NOT NULL DEFAULT '',
    edge_count  BIGINT NOT NULL DEFAULT 0,
    node_count  BIGINT NOT NULL DEFAULT 0,
    started_at  TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),
    visible_at  TEXT NOT NULL DEFAULT '',
    aborted_at  TEXT NOT NULL DEFAULT '',
    error       TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_cpg_project_state
    ON code_projection_generations(project, state);
CREATE UNIQUE INDEX IF NOT EXISTS idx_cpg_one_visible_project
    ON code_projection_generations(project)
    WHERE state = 'visible';

-- Mutation bookkeeping: projected-edge membership per generation.
-- Not joined in hot recall path; used for publish, rollback, and cleanup.
CREATE TABLE IF NOT EXISTS code_projection_edges (
    generation_id BIGINT NOT NULL REFERENCES code_projection_generations(id)
        ON DELETE CASCADE,
    project       TEXT NOT NULL,
    source        TEXT NOT NULL,
    relation      TEXT NOT NULL,
    target        TEXT NOT NULL,
    source_hash   TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (generation_id, source, relation, target)
);
CREATE INDEX IF NOT EXISTS idx_cpe_project_triple
    ON code_projection_edges(project, source, relation, target);

-- Phase 3: projection_generation_id on entity_edges links each code-origin
-- edge to its owning generation so recall can filter by visible generation.
ALTER TABLE entity_edges
    ADD COLUMN IF NOT EXISTS projection_generation_id BIGINT NOT NULL DEFAULT 0;
ALTER TABLE entity_edges
    ADD COLUMN IF NOT EXISTS structural_updated_at TEXT NOT NULL DEFAULT '';

-- Phase 4: composite indexes for utility-aware two-hop CTE expansion.
CREATE INDEX IF NOT EXISTS idx_ee_source_relation ON entity_edges(source, relation);
CREATE INDEX IF NOT EXISTS idx_ee_target_relation ON entity_edges(target, relation);
CREATE INDEX IF NOT EXISTS idx_ee_origin_source ON entity_edges(edge_origin, source);
CREATE INDEX IF NOT EXISTS idx_ee_projection_generation ON entity_edges(projection_generation_id, source, relation);
